### ISSUE TITLE
Error message when entity not found needs improving

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1000]
For example:

https://dev.facebase.org/data/record/#5/isa:dataset/id=14086

This entity does not exist. I got there because the entity _did_ exist, then I deleted it from another client, and refreshed the record page. This is likely to happen as we begin to have more data editing by users.

The error message says

> Error:
> tuple not defined

Seems like that might even be a raw Javascript exception text, meaning we may not have properly caught this error and tripped over the equivalent of a null pointer/reference exception.

**Comment by hongsudt** [comment]
@jrchudy after the pull request is merged, please ask @robes to review..

**Comment by jrchudy** [comment]
The message text has been changed @robes.

**Comment by robes** [comment]
worked great for me
