### ISSUE TITLE
Sort control broken when FK references PK of same table

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1003]
On a table with a "self reference" (a FK that references its own PK), the sort control is broken on that column. The sort controls work for other columns still. See the "Derived From" column on the Imaging nested table on this record.

https://dev.facebase.org/data/record/#1/isa:sample/id=6

**Comment by RFSH** [comment]
@robes 
It seems like the "Derived Form" column has been removed from the table.
I created [this sample table](https://dev.isrd.isi.edu/chaise/recordset/#18723/reference_schema_2:table_w_self_fk) with a fk to itself (`col_1` is a foreign key to `id` column). The sorting is working for all the columns of this table.

**Comment by robes** [comment]
@RFSH I can't follow the link to the sample. That catalog no longer exists.

**Comment by RFSH** [comment]
@robes Please use [this link](https://dev.isrd.isi.edu/chaise/recordset/#19085/reference_schema_2:table_w_self_link) (fk_col is foreign key to the table).

**Comment by robes** [comment]
sample link works

**Comment by robes** [comment]
@RFSH this issue is back, or so it seems to me...

See:
https://dev.facebase.org/data/record/#5/isa:sample/id=6

**Comment by robes** [comment]
and another example on the dev isrd server.
https://dev.isrd.isi.edu/chaise/record/#1/isa:dataset/id=14084

**Comment by RFSH** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #364](https://github.com/informatics-isi-edu/ermrestjs/issues/364) via [**ZenHub**](https://www.zenhub.com/)
