### ISSUE TITLE
Add "remove current record from formset" feature to recordedit - edit mode

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1007]
We decided to use a stop sign symbol for this feature.. 

Once this is done, we should modify the creation process to use the same symbol instead of a trash can.

**Comment by amitjha21** [comment]
Add _exclusion_ feature in `recordedit` so that users can exclude all the rows from the *form* which they do not want to change. Use stop/minus sign for the logo. This logo would be used for creation as well.
