### ISSUE TITLE
config and set up google analytics for each app

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1008]
@crisaless probably has this done for the static pages. This issue is to put simple instruments on each app and check whether the current config applies.

@crisaless can you please give @howdyjessie access to the analytics accounts. We can start with the general isrd, if there is one, and facebase. 

@howdyjessie This requires a google account. So please send one to @crisaless 

---

- [x] Add GTM tag to FaceBase's Chaise apps on production
- [x] Configure blacklist of IP addresses/users
- [x] Create a view with the following metrics for static pages, all Chaise apps, and each Chaise app
    - Users
    - Unique Pageviews
    - Session duration
    - Bounce rate
    - Pages per session
    - Avg time per page
    - Referrer
- [x] Dynamically insert GTM in static and Chaise sites (FaceBase production)
- [ ] Reconcile authenticated users with webauthn cookie names and pipe it into GA
- [ ] Collect numbers on the tables that users are looking at. Differentiate between bogus/typo and the real ones, so you can group the bogus ones together..

**Comment by crisaless** [comment]
I've added jessie to the facebase 2 account. There wasn't one created for isrd yet so I made one - it's specific to dev.isrd.isi.edu - and added jessie as well.

**Comment by hongsudt** [comment]
I am closing this issue.. and will generate deployment specific issue to mimic what's done on facebase.
