### ISSUE TITLE
Refactor recordedit Testcases to not imitate ermrestjs logic

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1009]
There are some test cases that try to imitate the ermrestjs logic. For instance [`getVisibleColumns`](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/utils/page.utils.js#L277) function is trying to figure out the visible columns using the annotation.

I don't think we should have these sort of logics in chaise test cases. Instead, we should just test for a fixed and known result (instead of applying a logic).

**Comment by hongsudt** [comment]
@RFSH Can you identify specific test cases, so we can quickly discuss that with the test owners and have them removed?

**Comment by RFSH** [comment]
All the functions that are under [`EditInputs`](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/utils/page.utils.js#L230), are trying to get the result based on some logic and that should not be the case for unit tests. These function are just used in recordedit test suit.

| link                                                                                                      | function                   |
|-----------------------------------------------------------------------------------------------------------|----------------------------|
| [1](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L41)   | getDisplayname             |
| [2](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L54)   | getVisibleColumns          |
| [3](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L123)  | getVisibleColumns          |
| [4](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L72)   | getColumnsWithComment      |
| [5](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L90)   | getColumnsWithRequired     |
| [6](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js)       | getDisabledColumns         |
| [7](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L155)  | getLongTextDataTypeColumns |
| [8](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js)       | getTextDataTypeColumns     |
| [9](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L223)  | getBooleanDataTypeColumns  |
| [10](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L295) | getForeignKeyColumns       |
| [11](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L439) | getDateTypeColumns         |
| [12](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L553) | getTimestampTypeColumns    |
| [13](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L695) | getIntegerDataTypeColumns  |
| [14](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L864) | getFloatDataTypeColumns    |
| [15](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L721) | isKey                      |
| [16](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L728) | isDisabled                 |
| [17](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L206)       | isUrl                      |

Test cases that are related to sidebar in search app are using the same technique too.

**Comment by jrchudy** [comment]
I believe the `editInputs` and `sidebar` tests are testing functionality in the search app that don't rely on `ermrestJS`. This functionality is defined in a number of javascript files in `chaise` in the `scripts` folder under the `chaise` directory.

**Comment by RFSH** [comment]
As I mentioned in my previous comment, `editInputs` has been used widely in recordedit app, which is using `ermrestjs`.  My open PR has changed some of the heuristics and that's how I found this issue.

**Comment by hongsudt** [comment]
Let's discuss this tomorrow..

**Comment by hongsudt** [comment]
@chiragsanghvi can you update this issue of the action plan that we discussed related to these generic test cases?

**Comment by chiragsanghvi** [comment]
The pageUtils for chaise.page.js should not be used. Explicit columns with relevant criteria should now be a part of the config (recordedit.dev.json). The code shouldn't automatically determine columns using its logic. All expected situations should be a part of the json configuration.
