### ISSUE TITLE
timestamp column shows [object Object] when the input field is disabled

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1016]
https://dev.gpcrconsortium.org/chaise/recordedit/#1/assets:cpm/id=2@sort(last_modified_timestamp::desc::,id)

This feature used to work.. 

Please add a test case to detect that the values show up correctly regardless of whether it is enabled or disabled.

**Comment by howdyjessie** [comment]
PR #1022 has been reviewed and merged, closing this issue now.
