### ISSUE TITLE
Permalink generates wrong url in case sorting criteria is specified by users

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1018]
To replicate:
- go to this url
https://dev.gpcrconsortium.org/chaise/recordset/#1/assets:cpm/experiment_accession_id=GPCRUSC20170306EXP1@sort(last_modified_timestamp::desc::,id)
- sort based on device type
- the permalink generated is https://dev.gpcrconsortium.org/chaise/recordset/#1/assets:cpm/experiment_accession_id=GPCRUSC20170306EXP1@sort(assets_cpm_cpm_device_type_fkey::desc::,id)?limit=25
which leads to a 404 error message

Note: We need to improve on the error message. Users should never see 404.

**Comment by RFSH** [comment]
@hongsudt It's working properly now. I think the table changes occurred after you opened recordset, and before you open the permalink. So you could see the "device type" in recordset, but when you clicked on the permalink again the column has been removed from the visible columns.
