### ISSUE TITLE
submit an edit record doesn't direct user to the record page

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1019]
https://dev.gpcrconsortium.org/chaise/recordedit/#1/assets:cpm/uri=%2Fhatrac%2Fassets%2FUSC%2Fcpm%2F2017%2F01%2F78f585c2ff5e597f80c67e72e40275ea2644a0861d334b1087fec9261b6fbeef.csv@sort(last_modified_timestamp::desc::,id)

- Make modification to the record
- click submit, nothing happens but the record has already been modified
- click submit again, an error is thrown at the user
- If you check the record, it is clear that it has already been modified.

**Comment by jrchudy** [comment]
When I try to reproduce this bug I see the following error:
`ERROR: insert or update on table "cpm" violates foreign key constraint "cpm_last_update_user_guid_fkey" DETAIL: Key (last_update_user_guid)=(https://auth.globus.org/6ccebd18-ef90-11e5-8e41-cb8595f578a7) is not present in table "person".`

@hongsudt, is GPCR using some form of row level security that checks if a user is in the person's table to be able to edit or create entities?

**Comment by jrchudy** [comment]
This issue can no longer be reproduced. There are some other issues that are still present, but those are addressed in other github issues. Closing this issue.
