### ISSUE TITLE
clear all behavior

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#102]
I"m wondering if it might be visually more streamlined to continue to display the clear all chiclet even when there are not filters set.  It would seem to me that this would minimize the amount of jumping around that would occur when adding a filter.  What would happen is we would just remove the placeholder with instructions for using the sidebar with the actual search results once they are available, making for a smoother transition.

**Comment by robes** [comment]
+1 for less jumpy behavior


________________________________

**Comment by robes** [comment]
this hasn't been fixed but it seems okay, maybe due to other unrelated changes
