### ISSUE TITLE
Don't show transient error message on the search app

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1023]
Please don't show the transient error messages to the user. 

To replicate, go to https://data.gpcrconsortium.org/chaise/search/#1/assets:cpm
You will need to login first.

This issue is relevant to the webauthn issue here.. https://github.com/informatics-isi-edu/webauthn/issues/58

**Comment by svoinea** [comment]
The query parameter `cid=search` was added for all the`/ermrest` requests, inclusive for the `/ermrest/authn` ones.

The issue was fixed through the `webauthn issue` [58](https://github.com/informatics-isi-edu/webauthn/issues/58)

I'm closing the issue.

**Comment by karlcz** [comment]
Serban:

There shouldn't be any calls to /ermrest/authn anymore.  If you still have any in your app, please replace them with the equivalent /authn path.
