### ISSUE TITLE
No Records shown for table in recordset before results appear

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1027]
This happens in the case where the user navigates to a `recordset` page but aren't logged in yet. If they don't have a valid session, the table stays then until the user is redirected to the login form.

If they have a valid session, the table appears to flash with just an actions column and a `No Results` row before showing the content for the page.

**Comment by jrchudy** [comment]
With the new login flow, this issue is no longer repeatable. When there is not a session, the modal window (to open the login window) opens before the table begins to load the recordset view.

Assigning to @hongsudt and @karlcz to verify whether this is still repeatable.

**Comment by karlcz** [comment]
I see the login modal prompt now too.
