### ISSUE TITLE
409 conflict error -- recordedit for sec table

### ISSUE THREAD

**Issue by ankit081190** [informatics-isi-edu/chaise#1029]
On trying to submit the data using the following url
https://dev.gpcrconsortium.org/chaise/recordedit/#1/assets:sec/id=150@sort(last_modified_timestamp::desc::,id)

The below error is generated
Error 409 Conflict The request conflicts with the state of the server. Input row key ((14472, 1815, u'/hatrac/assets/USC/sec/2016/01/1cbbf813505fa95bfa7ff8fc12de9d4830170c30fdebf217dd4a69cd46af9ae0.cdf', 0.656604766845703, u'1cbbf813505fa95bfa7ff8fc12de9d4830170c30fdebf217dd4a69cd46af9ae0', 9.6, u'MWD1 B, Sig=280,4 Ref=off', u'https://auth.globus.org/c9b54e68-d274-11e5-8fa4-d7dde9f08df5', 13.1, u'serban', u'/hatrac/assets/USC/standards/sec/eb48a830cc520976da73a836890b4a141f24e3a1e56141651e71ef7036b04fe8.json', 0.288898999090082, u'GPCR USC IOBOX', u'/hatrac/assets/USC/standards/sec/a97d51f52136c13f021eed28857e105b6ac4bbe3be1c619a7076e3dcdc8aefe6.json', datetime.datetime(2016, 10, 27, 12, 12, 56, 661259, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=-420, name=None)), u'/hatrac/assets/USC/sec/2016/01/1cbbf813505fa95bfa7ff8fc12de9d4830170c30fdebf217dd4a69cd46af9ae0_meta.json', u'6620+NTX E2+3', datetime.datetime(2017, 3, 21, 11, 33, 46, 873307, tzinfo=psycopg2.tz.FixedOffsetTimezone(offset=-420, name=None)), 2, u'https://auth.globus.org/71ec6a84-a960-4ee8-a4b2-27127e1419dc', u'mAU', u'GPCR Process', u'Absorbance B', u'SIGNAL03.cdf', u'GPCRUSC20161027SEC41', u'USC', 150, None, u'12_6620NTX_E2-3_012216', u'/hatrac/assets/USC/sec/2016/01/1cbbf813505fa95bfa7ff8fc12de9d4830170c30fdebf217dd4a69cd46af9ae0.json', 1890)) does not match existing entity.

**Comment by jrchudy** [comment]
This issue is addressed in PR [#373](https://github.com/informatics-isi-edu/ermrestjs/pull/373) in `ermrestJS`.
