### ISSUE TITLE
Possible encoding issue with generated fragments

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#103]
See this example. From this page:

http://dev.facebase.org/data/record/#1/legacy:dataset/id=4691

Click on the "Mouse Mutation" value. The page then says "Not Found" which I assume might come from an encoding issue.

That link is this:

```
http://dev.facebase.org/data/record/#1/legacy:mouse_mutation/term=Tg%28KRT14-cre%2943Smr%3BTgfbr2%28tm1.2Hlm%29
```

**Comment by bennettl** [comment]
@robes  So in this scenario, it sends this GET request to the Ermrest API:

https://dev.facebase.org/ermrest/catalog/1/entity/mouse_mutation/term=Tg(KRT14-cre)43Smr%3BTgfbr2(tm1.2Hlm)

I'm guessing the "(" and ")" needs some sort of escaping?

**Comment by robes** [comment]
Yes, basically all user data values need to be URL escaped so that they don't interfere with URL or ERMrest parsing rules.

@svoinea can you suggest or point to example in the search app for how we encode all user data in our calls to ERMrest?

**Comment by karlcz** [comment]
Yes, all potentially user-generated values, including table names,
column names, and values MUST be URL-encoded in ERMrest URLs to
protect all reserved characters (as defined by RFC 3986).  Please
check with Serban and/or see the safe-encoding routines he is using in
the search app.

**Comment by svoinea** [comment]
Use the function fixedEncodeURIComponent() from ermrest.js. There are a couple of characters that the encodeURIComponent() function does not encode.

**Comment by bennettl** [comment]
@svoinea You're a hero. Fixed.

**Comment by robes** [comment]
confirmed on dev
