### ISSUE TITLE
Session as a Service

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1032]
Currently each app gets the Session before everything else. If this Session information ever changes, the apps won't update with that new info (user logs out on another page or the session times out etc.).

The Session needs to keep track of the current user's Session and poll on a consistent basis to find out if the Session info has changed at all. Each app should then only access the Session as necessary instead of trying to make sure it's fetched before reading data or submitting requests.

**Comment by hongsudt** [comment]
This is related to informatics-isi-edi/ermrestjs#370

**Comment by chiragsanghvi** [comment]
We need to move session handling from Chaise to ermrestjs. The `chaise.authen` module will not make any http calls to get the session. This functionality should be added to `authen.js` in ermrestjs repo.
