### ISSUE TITLE
copy should not copy generated columns

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1034]
These columns should be passed to the default list, so the default can be applied. 

* go to an existing experiment:  https://dev.gpcrconsortium.org/chaise/record/#1/experiments:experiment/id=40
* click copy
* when the new record is submitted, it seems like the values of generated columns (e.g. number of samples and number of images) also get updated. This is misleading as the new experiment shouldn't have any of these values. These generated columns should be using the default values.. 

Note: the rest of the columns will be overridden by the trigger, but it is still misleading to show the existing value. I can write a trigger to always initialize number of samples to 0, but this is probably the wrong approach. 

If it is easier, maybe we shouldn't be displaying the existing values of the generated column in the copy case.. We should show "automatically generated" instead. @karlcz @robes what do you think?

**Comment by robes** [comment]
Make sense to me
