### ISSUE TITLE
wierd 404 html error content displayed 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1035]
We see this on the sample table..  This error only happens in the editing case while it should have succeeded. Note that there is an invalidate url parameter in the url. 

![image](https://cloud.githubusercontent.com/assets/414732/24434631/9f4f1ae2-13e5-11e7-80d8-490340007831.png)

Here is the url extracted from the server log. The length of the url is 4243 which might exceed the url length limit. 

/ermrest/catalog/1/attributegroup/experiments:sample/id_o:=id,site_name_o:=site_name,accession_id_o:=accession_id,experiment_accession_id_o:=experiment_accession_id,sample_name_o:=sample_name,existing_biomass_o:=existing_biomass,ligand_name_o:=ligand_name,ligand_concentration%20%28uM%29_o:=ligand_concentration%20%28uM%29,protein_concentration%20%28mg%2FmL%29_o:=protein_concentration%20%28mg%2FmL%29,extraction_detergent_o:=extraction_detergent,extraction_detergent%20%28weight%2Fvolume%29_o:=extraction_detergent%20%28weight%2Fvolume%29,finishing_detergent_o:=finishing_detergent,finishing_detergent%20%28weight%2Fvolume%29_o:=finishing_detergent%20%28weight%2Fvolume%29,deglycosylation_enzyme_o:=deglycosylation_enzyme,protease_enzyme_o:=protease_enzyme,other_treatment_o:=other_treatment,membrane_preparation_sop_o:=membrane_preparation_sop,purification_sop_o:=purification_sop,analysis_sop_o:=analysis_sop,creator_guid_o:=creator_guid,creator_userid_o:=creator_userid,creator_name_o:=creator_name,creation_timestamp_o:=creation_timestamp,last_modified_timestamp_o:=last_modified_timestamp,construct_o:=construct,experiment_detail_o:=experiment_detail,biomass_volume%20%28mL%29_o:=biomass_volume%20%28mL%29,biomass_production_request_o:=biomass_production_request,biomass_production_parent_virus_o:=biomass_production_parent_virus,biomass_production_volume_o:=biomass_production_volume,biomass_production_moi_o:=biomass_production_moi,biomass_production_ligand_o:=biomass_production_ligand,biomass_production_ligand_concentration%20%28uM%29_o:=biomass_production_ligand_concentration%20%28uM%29,biomass_production_notes_o:=biomass_production_notes,biomass_production_status_o:=biomass_production_status,sec_configuration_o:=sec_configuration,sec_sample_container_o:=sec_sample_container,sec_well_location_o:=sec_well_location,sec_sample_name_o:=sec_sample_name,sec_method_name_o:=sec_method_name,sec_injection_source_o:=sec_injection_source,sec_injection_volume_o:=sec_injection_volume,sec_injection_vial_o:=sec_injection_vial,sec_sample_type_o:=sec_sample_type,sec_sample_volume_o:=sec_sample_volume,sec_autobalance_o:=sec_autobalance;id_n:=id,site_name_n:=site_name,accession_id_n:=accession_id,experiment_accession_id_n:=experiment_accession_id,sample_name_n:=sample_name,existing_biomass_n:=existing_biomass,ligand_name_n:=ligand_name,ligand_concentration%20%28uM%29_n:=ligand_concentration%20%28uM%29,protein_concentration%20%28mg%2FmL%29_n:=protein_concentration%20%28mg%2FmL%29,extraction_detergent_n:=extraction_detergent,extraction_detergent%20%28weight%2Fvolume%29_n:=extraction_detergent%20%28weight%2Fvolume%29,finishing_detergent_n:=finishing_detergent,finishing_detergent%20%28weight%2Fvolume%29_n:=finishing_detergent%20%28weight%2Fvolume%29,deglycosylation_enzyme_n:=deglycosylation_enzyme,protease_enzyme_n:=protease_enzyme,other_treatment_n:=other_treatment,membrane_preparation_sop_n:=membrane_preparation_sop,purification_sop_n:=purification_sop,analysis_sop_n:=analysis_sop,creator_guid_n:=creator_guid,creator_userid_n:=creator_userid,creator_name_n:=creator_name,creation_timestamp_n:=creation_timestamp,last_modified_timestamp_n:=last_modified_timestamp,construct_n:=construct,experiment_detail_n:=experiment_detail,biomass_volume%20%28mL%29_n:=biomass_volume%20%28mL%29,biomass_production_request_n:=biomass_production_request,biomass_production_parent_virus_n:=biomass_production_parent_virus,biomass_production_volume_n:=biomass_production_volume,biomass_production_moi_n:=biomass_production_moi,biomass_production_ligand_n:=biomass_production_ligand,biomass_production_ligand_concentration%20%28uM%29_n:=biomass_production_ligand_concentration%20%28uM%29,biomass_production_notes_n:=biomass_production_notes,biomass_production_status_n:=biomass_production_status,sec_configuration_n:=sec_configuration,sec_sample_container_n:=sec_sample_container,sec_well_location_n:=sec_well_location,sec_sample_name_n:=sec_sample_name,sec_method_name_n:=sec_method_name,sec_injection_source_n:=sec_injection_source,sec_injection_volume_n:=sec_injection_volume,sec_injection_vial_n:=sec_injection_vial,sec_sample_type_n:=sec_sample_type,sec_sample_volume_n:=sec_sample_volume,sec_autobalance_n:=sec_autobalance?cid=recordedit

**Comment by karlcz** [comment]
This looks like an Apache error message and we see it in the Apache logs but not the other place where ermrest logs events.

My guess would be we're hitting a maximum URL length limitation for Apache or its pattern-matching library and it decided not to route the URL to ermrest at all.

If so, this error will go away when recordedit reverts to setting fewer columns in the update request.

But, we should also fix the frontend to be more aware of error content-type and do more appropriate behaviors... ermrest will not produce HTML errors like this.
