### ISSUE TITLE
Timestamp entry is not initialized properly.. AM/PM toggle doesn't work

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1039]
If you go to a recordedit page in record creation mode that has a timestamp entry, and start editing fields, you get validation errors until you type a valid date and time digit set.  But, the AM toggle is broken.

If you click 'Now' to intiailize the entry box and then edit the digits, the AM/PM toggle works correctly.

So, I think it must be failing to properly initialize the controller when you start with a blank record?

example page:

https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Behavior

displays the error:

```
toggleMeridiem@https://synapse-dev.isrd.isi.edu/chaise/recordedit/form.controller.js?v=c3d6045a599d2bd8479fe7b37ab4c294:631:1
anonymous/fn@https://synapse-dev.isrd.isi.edu/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84 line 14432 > Function:2:541
expensiveCheckFn@https://synapse-dev.isrd.isi.edu/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:15485:18
ngEventHandler
```

even more detailed description of how to produce:
1. load the page
2. use mouse to enter the "Room Date" date field.
3. type 2017-01-02
4. use mouse to enter the "Room Date" time field.
5. type 120101 (it fills colons for you)
6. use mouse to leave the time field, e.g. clicked page background
7. click "AM" button on the "Room Date" field
8. get an "Error: Terminal Error" alert with merdiem is undefined

i'm doing this in a firefox private browser session w/ clean cache

**Comment by jrchudy** [comment]
This issue has been fixed. Reassigning to @karlcz for verification.

**Comment by karlcz** [comment]
ok I see that the terminal error is gone
