### ISSUE TITLE
change "link" to "add" on top of each related table

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1045]
~For the tooltip associated with the unlink, currently the tooltip only displays "unlink". We can add more information such as "Remove/disconnect this record from the main entity. The record will not be deleted."~

~@carlkesselman @robes @karlcz @ljpearlman Does this help? ~

Change `Link` to `Add` for related tables.

**Comment by jrchudy** [comment]
Issue #1060 was opened to track fixing the tooltip information.
