### ISSUE TITLE
Update related tables on focus if the content has changed

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1051]
Related tables on the record page should call `Reference.read` (or more appropriately `Reference.reread`) every time the page is focused. This `reread` function should take in the etag that was returned with the original read call for each of the related tables to verify if the content has changed or not. If the content has not changed, don't try to update the tables in the view.

We may need to explore what the browser does when it interprets a `304` response. If the browser sees this `304` response code, grabs the cached data, and returns a `200` response with the data, we need to change that. We want `chaise` and `ermrestJS` to manage that so we can properly update tables in the view when the data has actually changed.  

@karlcz please fill in or clarify any detail I may have missed.

**Comment by hongsudt** [comment]
@RFSH Please take a look at this issue as well when you work on the update.

**Comment by RFSH** [comment]
This is a old issue related to the flashing of tables when we were updating inline/related tables. This is not the correct behavior now, I am going to close this issue.
