### ISSUE TITLE
Load button on 3D Preview is not showing up in Safari.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#106]
If you go to a 3D image (say FB00000237) and go to the preview section, the load button in the viewer pane is not showing up.  It is there, as you get the hot spot and if you click the image does render.

**Comment by howdyjessie** [comment]
I'm stumped on this far. This might be an issue for slicedrop/@meihuisu. The load button shows up normally if you [directly visit the iframe's source url] (https://www.facebase.org/_viewer/xtk/view_on_load.html?url=https://www.facebase.org/hatrac/facebase/previews/fb1/FB00000177/CP084CCMB_transformed.nii.gz"%20src="https://www.facebase.org/_viewer/xtk/view_on_load.html?url=https://www.facebase.org/hatrac/facebase/previews/fb1/FB00000177/CP084CCMB_transformed.nii.gz), so I'm guessing the invisible button behavior has to do with how Safari renders the viewer in an iframe.

**Comment by robes** [comment]
@hongsudt this is still an active issue and we should schedule it to a sprint

**Comment by hongsudt** [comment]
@robes is this needed for facebase?

**Comment by robes** [comment]
yes

**Comment by meihuisu** [comment]
@howdyjessie, how do I get to that link you point to from facebase? what is the iframe that enclosing it
looks like.

**Comment by meihuisu** [comment]
This has nothing to do with the viewer-slicedrop if the image do shows up. It should be the 
iframe and safari problem or safari with $.holdReady()

**Comment by howdyjessie** [comment]
@meihuisu This is the FaceBase link that shows the embedded iframe: https://facebase.org/data/record/#1/legacy:dataset/id=4696

<img width="1440" alt="screen shot 2016-04-26 at 2 17 51 pm" src="https://cloud.githubusercontent.com/assets/4585431/14834518/b69feefe-0bb9-11e6-8a3e-d72cab8e649a.png">

**Comment by meihuisu** [comment]
if you hover on the invisible button(until you see a hand) and click right mouse 
button (without actually selecting it), the load button actually appears, it is
iframe/safari UI problem. you need to check the iframe tag, and button tag and maybe $.holdReady()
for safari, and on stackoverflow, people mentioned things about width of iframe-target, transparency of iframe-tag.

![screen shot 2016-04-26 at 5 05 43 pm](https://cloud.githubusercontent.com/assets/9042455/14837908/2c29225a-0bd1-11e6-80f2-7736121fa44a.png)

**Comment by hongsudt** [comment]
@howdyjessie I assume this is for you to fix now?

**Comment by howdyjessie** [comment]
@hongsudt Looks like it is :)

**Comment by hongsudt** [comment]
This app is going away. Will mark this as won't fix.
