### ISSUE TITLE
Tooltip for unlink needs info

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1060]
For the tooltip associated with the unlink action in the action column, currently the tooltip only displays "unlink". We need to add more information.
 -  ~~` "Disconnect <leaf_table_name>: <leaf_rowname> from this <main_table_name>."`~~ 
 
Issue #1591 tracks the above comment. Moved other comments below to the same issue.

**Comment by hongsudt** [comment]
@jrchudy is this done? I don't see any unchecked box.

**Comment by jrchudy** [comment]
Closing this issue since all comments for tracking this have been moved.
