### ISSUE TITLE
terminal error on logout

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1066]
I logged into a recordset page such as:

https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Subject

when I use the "Log Out" button at top right, a terminal error alert flashes before the page redirects.

If you enable whitelisting for cross-domain redirects in your browser, you can see the app stuck there while the browser is waiting for you to approve the redirect to the globus logout page.

**Comment by jrchudy** [comment]
I'm not able to reproduce the terminal error appearing before the page redirects to logout. After logging out though, if you follow the provided logout link: `.../chaise/logout`, you are met with an error dialog because of a missing provider. 

This is related to the `chaise.navbar` module.

**Comment by jrchudy** [comment]
Reassigning to @karlcz to verify whether this is still a problem or not.

**Comment by karlcz** [comment]
I am not seeing this error now either.
