### ISSUE TITLE
Flashing "Terminal Error" dialog after recordedit submit

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1068]
After editing an existing record, I'm seeing a flashing "Terminal Error" dialog. It flashes for a couple seconds and goes away before I can even click the view details. No errors in the console log.

I consistently get this when editing a record in the facebase `viz.mesh` table.  Such as this one.

https://dev.facebase.org/data/record/#5/viz:mesh/id=1

Or any listed under this one (linked to by the "Mesh" column of the nested table)

https://dev.facebase.org/data/record/#5/viz:model/id=1

**Comment by jrchudy** [comment]
Re-assigning this issue to @robes to verify it is fixed.

**Comment by robes** [comment]
seems to be working well now. thanks
