### ISSUE TITLE
URL rendering broken maybe due to space in it

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#107]
See the URL in the external references of this dataset:

http://dev.facebase.org/data/record/#1/legacy:dataset/id=4894

**Comment by karlcz** [comment]
those spaces are in the 'uri' column of the database and most
certainly are wrong as no uri can have space in it.

**Comment by robes** [comment]
Then let's fix the db. Over to Alejandro.

**Comment by bugacov** [comment]
yeah. there where 2 links w/ blanks for accessions FB00000263 and FB00000278. 
Should be fixed now. 
Alejandro.

**Comment by robes** [comment]
The original bug report is actually a data issue. In general this was fixed in the UI.
