### ISSUE TITLE
Terminal server error on record with no login 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1073]
A terminal server error is thrown on record page when a user is not login. RBK allows public access and this error should not be thrown. 

https://dev.rebuildingakidney.org/chaise/record/#2/Vocab:Species/Name=Mus%20musculus

@chiragsanghvi  Is this relevant to the new login flow?

**Comment by chiragsanghvi** [comment]
@hongsudt I fixed the unhandled issue in errors.js just now. 

The actual error on the above page is "Invalid filter undefined".

**Comment by jrchudy** [comment]
This issue can be seen at this link as well:
https://synapse-dev.isrd.isi.edu/~jchudy/chaise/record/#1/Synapse:Person/ID=Cza

**Comment by chiragsanghvi** [comment]
I just opened the page and checked it works. Maybe your cache needs to be clear.

**Comment by RFSH** [comment]
@chiragsanghvi you can see the error in here:
https://synapse-dev.isrd.isi.edu/chaise/record/#1/Synapse:Person/ID=Cza
@jrchudy already fixed it, that's why in the link that he provided you can not see the error message.
The problem is related to alternative tables. Which I will include in my PR.

**Comment by jrchudy** [comment]
@chiragsanghvi, I had actually played around a bit and fixed the problem in my dev environment and meant to paste a different link (one not pointing to my user directory).
