### ISSUE TITLE
HTML fragment not rendering correctly in detail page

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#108]
See this dataset:

http://dev.facebase.org/data/record/#1/legacy:dataset/id=4894

The html fragment that is included in the description attribute does not look right.

**Comment by bennettl** [comment]
@robes By executing the GET request

curl -k -H "Accept: application/json" http://vm-dev-030.misd.isi.edu/ermrest/catalog/1/entity/dataset/id=4894

I got back a JSON object, one of the keys "description" has the value

```"This dataset includes the results of ChIP-Seq analysis of p300 bound regions in E13.5 mouse palates. The results are also presented as tracks on the Genome Browser (see links in the External References section). <br />The data include the following information for each peak called: <blockquote> <ul> \t<li> \t\tranking.   Called peaks are ranked by maximum coverage, those with equal maximum coverage are then ranked by local p-value.</li> \t<li> \t\tthe location of the peak, shown as chromosome start and end positions (mouse genome build mm9)</li> \t<li> \t\tpeak length</li> \t<li> \t\tposition of the peak summit</li> \t<li> \t\ttags: the number of reads in peaks (# reads in region, not maximum read coverage depth)</li> \t<li> \t\tscore: -(log(pvalue))</li> \t<li> \t\tfold enrichment: enrichment in peak vs input sample</li> \t<li> \t\tFDR: false-discovery rate annotation based on post-peak calling filtering of peaks based on genome annotation</li> </ul> </blockquote> <br/>  To download the data, log in and click on the \"Download dataset\" button."```

**Comment by robes** [comment]
Thanks. (Next time I should just look into it myself!)
