### ISSUE TITLE
Entity attributes show up after nested entities

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1082]
The record app may show nested entities before showing the attributes.

**Comment by hongsudt** [comment]
@robes is this still an issue?

**Comment by robes** [comment]
yes, it is.

**Comment by jrchudy** [comment]
For clarification, do you mean that the related tables start loading into the DOM before the record itself displays in the DOM?

**Comment by jrchudy** [comment]
The code to fix this has been merged into master. Reassigning to @robes to verify it has been fixed.

**Comment by robes** [comment]
This is fixed yes.

I'm going to have to open another issue though because this fix now makes apparent that long wait time for the main entity attributes to appear. We should probably have a spinner displayed as a general practice while waiting for first display of something.

That said, I still consider this an improvement. thanks
