### ISSUE TITLE
chaise record page should enforce uniqueness of its entity reference

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1098]
This is a subtle issue. Notice these two links:

https://www.facebase.org/data/record/#1/vocabulary:anatomy/term=Head
 
https://www.facebase.org/data/record/#1/vocabulary:anatomy/iri=http%3A%2F%2Fpurl.org%2Fsig%2Font%2Ffma%2Ffma7154

They point to exactly the same base record, however, in the first one you will see a lot of related entities (which is actually a bug) while in the second you will not.

The problem is that when we form the URLs for the related references we are using the base query pattern `term=Head` which is _not unique_ and so we are linking on a record **set** not a single unique record.

This was exposed by a funny corner case where a user entered a chaise URL by hand -- something that I think we actually always wanted users to do.

My feeling is that the bug is _not_ the related record linking. The join is actually working correctly.

The bug is that we have not enforced uniqueness in chaise + ermrestjs.

I think the fix is
- [ ] ermrestjs should implement the skeleton API that I wrote for checking uniqueness (simple introspection will do it)
- [ ] chaise record app should use the ermrestjs API and throw an exception then the condition fails

This is the companion issue https://github.com/informatics-isi-edu/ermrestjs/issues/399

**Comment by karlcz** [comment]
An alternative if you want to allow unique-in-practice query terms would be to just change
the record fetch to use limit=2 and throw an error (or redirect to recordset) if a second
result is available?

**Comment by hongsudt** [comment]
I like a more flexible approach that @karlcz suggested.. This will allow user to continue as usual if there is no ambiguity.. And if there are duplicate, provide them a link to recordset..

**Comment by nitishksahu** [comment]
An implementation of how multiple records are going to be handled in record page is in place:

[A record page with more than 1 record](https://dev.isrd.isi.edu/~nitish/chaise/record/#1/vocabulary:anatomy/term=Head)

@robes @hongsudt @karlcz Any suggestions??

**Comment by nitishksahu** [comment]
The changes to address this issue have been merged with the master branch.

Instances of the issue in different deployment:

- [DEV Isrd](https://dev.isrd.isi.edu/chaise/record/#1/vocabulary:anatomy/term=Head)
- [RBK](https://dev.rebuildingakidney.org/chaise/record/#2/Protocol:Protocol_Author/Rank=1)
- [GPCR](https://dev.gpcrconsortium.org/chaise/record/#1/gpcr_browser:target_gui/shared=true@sort(title))

Assigning this to @robes to verify.

**Comment by hongsudt** [comment]
@nitishksahu  Please change the error text to 
"There are more than 1 record found for the filters provided.
Click OK to show all the matched records."

**Comment by nitishksahu** [comment]
The changes are done and merged to master, assigning this to @hongsudt to verify.
