### ISSUE TITLE
Record page does not update when a new record URL is pasted to browser

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#110]
If I am non one record (details) page and paste a URL to another record page into the browser window, the browser location bar updates but the page does not change. If I hit manual reload, the page then reloads with the correct content displayed.

For clarification, this is pasting the URL into the main browser content pane and I tested on Firefox. I'm not sure if pasting to the location bar itself will exhibit the same behavior as that is not an idiom I use...

**Comment by robes** [comment]
this is in the review column but it didn't work for me testing it on the dev host.

however... can I vote this "-1" ? ;-) I really think this is too obscure.

**Comment by karlcz** [comment]
I don't think it's an import UX feature but am concerned that it is a canary indicating something is not right with the location/bookmark event handling.  Consider this a repeatable test scenario...

**Comment by robes** [comment]
i think you're the best one to review this since i'm not sure i know how even.

**Comment by karlcz** [comment]
Confirmed to work on dev.misd
