### ISSUE TITLE
Investigate alternatives to angular.copy

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1102]
Angular.copy is doing a deep copy of `tuple.values` in the `recordedit` app. Should this just be a shallow copy? Should we write our own copy function for this?

**Comment by hongsudt** [comment]
This deep copy cause significant performance degradation on a table with many fks. Once this is done, please check the whether we still have an alert popup to stop running the script on rbk (catalog 2, table: RNASeq:Sample_Settings).

**Comment by jrchudy** [comment]
Re-assigning this issue to you @hongsudt to verify the performance is better for `recordedit`.

**Comment by hongsudt** [comment]
@svoinea can you please test this and see whether you still have problem on your browser on dev?

**Comment by svoinea** [comment]
I have tested it on `rbk-dev` and the delay is not present any more.
