### ISSUE TITLE
Detail page needs to support "display" and "hidden" annotations for tables and columns.

### ISSUE THREAD

**Issue by mikedarcy** [informatics-isi-edu/chaise#111]
These annotations were supported in the previous version of the detail page.  They somehow did not make the transition to the new implementation, but are a necessity for some deployments.

There should also be a default ordering for the table entities in the detail view.  The old version sorted alphabetically.  I think this is sufficient but with one caveat:  the sort should be performed on the annotated "display" value and not the entity name.

**Comment by carlkesselman** [comment]
Make sure that this is consistent with the new annotation spec.  May need to update the annotation spec.

**Comment by robes** [comment]
Just a note. We want to implement the new forms of these annotations as defined in the ERMrest guideline.

https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md

I have update a working copy of the GPCR database on vm-dev-030 catalog 6 to have hidden and display annotations on a few columns and tables.

**Comment by robes** [comment]
@mikedarcy: just want to clarify what you mean by the "default ordering for the table entities in the detail view"... Are you referring to the ordering of the nested tables? Those should be sorted in alphabetical (by display name if overridden) order?

**Comment by mikedarcy** [comment]
Yes, sorted alphabetically, with display name taking precedence.
