### ISSUE TITLE
Line separator missing in the recordedit page in the first column between the first and second record

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#1110]
That happens pretty often to me.
I'm attaching a screenshot for `rbk-dev`.
The used `URL` is: https://dev.rebuildingakidney.org/chaise/recordedit/#2/RNASeq:Sample_Settings/Sample_Accession_ID=RBKUSC20160727SAM1
![screenshot](https://cloud.githubusercontent.com/assets/1609577/25976270/b2acc292-3668-11e7-8dc7-e4dbe40adc93.png)

**Comment by hongsudt** [comment]
I am closing this issue since this is not deterministic..
