### ISSUE TITLE
timestamp creation throws an error despite proper values

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1115]
https://dev.gpcrconsortium.org/chaise/recordedit/#1/experiments:experiment

I got the following error when I entered "2016-02-01 10:00:00" :
Error 400 Bad Request The request is malformed. Bad JSON array input. ERROR: invalid input syntax for type timestamp with time zone: "{"date":null,"time":null,"meridiem":"AM"}" 

This problem did not happen in this commit: 3b6dd7f89b349e53f45a2424f1bc16df4139038a (which is on staging)

Please note: "2016-02-01 00:00:00" or "2016-02-01 00:00:01" also throws an error. In this case, it treats 00:00:00 as null and complains about incomplete data. 

While we are at it, can we make sure that the following cases are covered:
- allow users to enter only a date. If that's the case, set the default time to 00:00:00 
- allow users to enter just the hour; assume 00:00 minutes
- allow users to enter hour and minutes, assume 00:00 seconds
- If it is easier, we can just default the time component to 00:00:00.. 

Please make sure we have test cases for this as well..

**Comment by jrchudy** [comment]
Assigning to @hongsudt to verify that it has been fixed.

**Comment by hongsudt** [comment]
This is now fixed.
