### ISSUE TITLE
Don't show regex in the search box on recordset

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1117]
when you do a search in recordset, and then if you drill down to a page and then go back to the recordset, the search you entered get “regex”-ified looking rather technical.

Suggested solution (from the chat room): so you would need to change the fragment syntax to represent some higher-level search primitive that stores the original search term, and only expand to the full regex when sending to ermrest. A simple solution is to use a new operator like :search:  for the fragment..

**Comment by robes** [comment]
+1 for the simple solution.

**Comment by RFSH** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #455](https://github.com/informatics-isi-edu/ermrestjs/issues/455) via [**ZenHub**](https://www.zenhub.com/)
