### ISSUE TITLE
Relative path redirect in OAuth flow leads to 'not found' page

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1119]
Go through the login flow on a catalog like this:

```
https://dev.facebase.org/data/recordset/#2/hatracevents
```

Eventually leads to a final page in the oauth popup window that reads 'not found'.

The URL on that is clearly wrong.

```
https://dev.facebase.org/authn/chaise/login?referrerid=...
```

Josh indicates that Chaise has a bad relative URL in the code:

```
`var login_url = '../login?referrer='
```

**Comment by jrchudy** [comment]
This issue is related to issue #1130.

**Comment by nitishksahu** [comment]
I believe this issue is resolved with the code changes done for #1130

**Comment by nitishksahu** [comment]
@robes can we close this too?? this seems to be fixed now.

**Comment by robes** [comment]
yes, thanks
