### ISSUE TITLE
Support per-entity, on-demand loading of data in the detail view.

### ISSUE THREAD

**Issue by mikedarcy** [informatics-isi-edu/chaise#112]
For larger scale databases with numerous tables and more overall data, it is impractical to try to load all related tables and their respective rows into the detail page at once.  It causes significant a performance impact and more often than not the dreaded "Unresponsive Script" dialog box.

 By default, have all associated table entities collapsed by default unless annotated otherwise. Do not issue a query to the backend unless a user expands the table.

**Comment by carlkesselman** [comment]
Lets not worry about pagination right now unless this is very easy as they may become moot if we go with another table widget (i.e. Kendo).

**Comment by robes** [comment]
i reviewed this myself. walked through the code and saw a live demo of it. however we really need to test it against the bdds database. so i would like to reassign the review of this feature to mike.

**Comment by mikedarcy** [comment]
Working ok for me on the BDDS/PPMI data.
