### ISSUE TITLE
File upload hangs on large file

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1126]
I tried to upload a file on an existing record:

- https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Image/ID=ImgZfZdu20170516A1

1. chose a 2.4 GB file
2. clicked "Submit Data"
3. saw checksum progress bars run to completion
4. saw upload progress move about 10-20% at a good speed (90 MB/s)
5. saw UI freeze for nearly a minute
6. saw app stop with an "unexpected error" warning

Watching the server logs at the same time, the hatrac chunk PUT requests stopped arriving and the network went quiet when the UI froze.  Eventually, outstanding hatrac chunk PUT requests responded with 408 and 500 errors indicating timeout and failure to read the expected chunk content off the wire.

**Comment by hongsudt** [comment]
@karlcz is this still an issue?

**Comment by karlcz** [comment]
I think the new queue for file chunks fixes this.
