### ISSUE TITLE
default values are not displayed in recordedit

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1128]
check the difference between what's on [rbk production](https://www.rebuildingakidney.org/chaise/recordedit/#2/RNASeq:Sample_Settings) and [rbk dev](https://www.rebuildingakidney.org/chaise/recordedit/#2/RNASeq:Sample_Settings). It seems like recordedit no longer displays the default value.  

This bug is probably introduced during the recent changes to fix the timestamp issue? 

@jrchudy I forgot that the default value is used to mimic section header in recordedit. So for generated columns that have default values, we should display the default value (the way that is is used on rbk production above).

**Comment by jrchudy** [comment]
The corresponding PR has been merged into master.

Reassigning this issue to @hongsudt to verify that it has been fixed.

**Comment by hongsudt** [comment]
The defaults are working properly on rbk-dev.
