### ISSUE TITLE
Login confirmation page 'not found'

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1130]
When using the new modal login window for the oauth login flow, at the end you should see a login confirmation page, but instead the URL is wrong and therefore the page is 'not found'.

For example, this is the final URL when following the login on facebase (on the catalog/2 for derivalogs).

```
https://www.facebase.org/authn/chaise/login?referrerid=1495736269903
```

@jrchudy took a quick look in the chaise code and could confirm that we are using a relative page like `var loginURL = '../login.html'` (something like that).

Side note: I would be okay with changing the chaise install location from `./data` to the `./chaise` used by all other deployments but I don't think that would fix this issue.

I don't even understand what the correct URL should be, because `./chaise/login` is a login form.

**Comment by robes** [comment]
Why isn't this fixed already???? This is a simple bug to fix right?

We literally have our FaceBase program officer tripping over this bug. If its simple can't we fix this right away? Why keep pushing this down the stack?

**Comment by hongsudt** [comment]
Is this only seen in facebase or is this a common problem across deployments? 

The priority got dropped because @carlkesselman wants to move forward with faceting.

**Comment by hongsudt** [comment]
I logged in to the production site just fine, and got this error when tried to login on dev. I don't see the same problem on rbk or gpcr.

**Comment by robes** [comment]
As mentioned in my description, the problem is reproducible on facebase catalog/2, which is a catalog that requires authentication in order to read. Here is an example link.

https://www.facebase.org/data/recordset/#2/reports:download_data@sort(Timestamp::desc::,Event%20ID)

**Comment by robes** [comment]
The comment above about the `loginURL` actually `login_url` was a red herring. The real problem has to do with this line of code.

```
var url = serviceURL + '/authn/preauth?referrer=' + UriUtils.fixedEncodeURIComponent(window.location.href.substring(0,window.location.href.indexOf('chaise')) + "chaise/login?referrerid=" + referrerId);
```

And the fragility of generating this referrer by depending on the `chaise` base directory in this substring.

**Comment by hongsudt** [comment]
To solve this problem, we will probably need to detect the deployment path from the url and assume that the appname is the last component of the path and that’s all we are trying to remove (and the last component is of course between the last two /s not counting the fragment which is not part of the path)

**Comment by karlcz** [comment]
If I understand what you're reporting here, the problem is the redirect URI **should not** start with ".." because that level of relative addressing won't make any sense once you leave the Chaise page context and instead go to the `/authn/` API.  The redirect URI should be an absolute path `/.../login` to your actual login page.

**Comment by karlcz** [comment]
I think @hongsudt  is right that the correct solution is to find the current page path in Chaise and "pop" one element to get to the parent app hierarchy, then add the different login page suffix.

**Comment by robes** [comment]
Hongsuda wanted me to add that we should assume that our app names end with a trailing `/` because we strictly follow that practice. So an example path is `.../recordset/`. It never ends without the last `/`.

Also, our pathnames are usually _but not always_ followed by a fragment id, e.g., `#1/isa:dataset`.

So in order to pop off the app name one must:
- start with window.location.href
- trace backwards to just before the fragment `#...` _if_ it exists
- from there trace backwards to the _second to the last_ `/`
- then append the `+ 'login?referrerId=' + referrerId`

**Comment by nitishksahu** [comment]
The changes for this issue has been merged with master.

Assigning this to @robes to verify.

**Comment by robes** [comment]
Verified on dev.facebase.org. Worked for me. Thanks
