### ISSUE TITLE
file upload isn't setting filename, bytes, or md5

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1132]
Am I just missing an annotation somewhere? I created a minimal file upload example, and it uploaded the file and set the url column but didn't set the filename, byte count, or md5 values. After looking at it in a debugger (actually, looking at a different table in a debugger earlier), I think it's calculating the values but then deciding not to pass them to ermrest.

To reproduce this:

1. Log in on dev.rebuildingakidney.org (or run the following script on your own system and log in there).
2. Go to "https://dev.rebuildingakidney.org/chaise/recordset/#2/test:asset_test".
3. Click "+" to create a record.
4. Type something into the "asset_id" space and hit submit.
5. Edit the resulting record and upload a file.

The `url` field will be set (and any additional fields that you set by hand), but none of the others will be filled in. (In the record app, it will look like `url` isn't set, but you can see it in the database or in recordset or search).

```
set search_path = test;

drop table if exists asset_test;
create table asset_test (
   id serial primary key,
   asset_id text unique not null,
   url text,
   filename text,
   bytes integer,
   md5 text,
   sha256 text,
   comments text
);

delete from _ermrest.model_column_annotation where schema_name = 'test' and table_name = 'asset_test';
insert into _ermrest.model_column_annotation(schema_name, table_name, column_name, annotation_uri)
  values('test', 'asset_test', 'id', 'tag:isrd.isi.edu,2016:generated');

insert into _ermrest.model_column_annotation(schema_name, table_name, column_name, annotation_uri, annotation_value)
  values('test', 'asset_test', 'url', 'tag:isrd.isi.edu,2017:asset',
    '{ "url_pattern" : "/hatrac/resources/test/file{{{asset_id}}}",                                                                                    
        "filename_column" : "filename",                                                                                                                
        "byte_count_column" : "bytes",                                                                                                                 
        "md5" : "md5",                                                                                                                                 
        "sha256" : "sha256"                                                                                                                            
     }');
```

**Comment by ljpearlman** [comment]
It looks like this only happens in edit mode, not create mode.

**Comment by chiragsanghvi** [comment]
@hongsudt @jrchudy The issues seems to be with the update function [here](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/reference.js#L1237) in ermrest.js.

`this.columns` returns only the visible columns for update. Thus, it doesn't gets the other column and is unable to update them.

**Comment by jrchudy** [comment]
The above PR was merged. I can verify this works with a test that had written for `ermrestJS`.

Reassigning to @ljpearlman to verify the changes fixed the issue.
