### ISSUE TITLE
" [$rootScope:inprog] $apply already in progress" errors

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1138]
One of our users got this while using fileupload to upload a file. He says it wasn't a big file (it was a jpeg), but I'm not sure how not-big it was or how fast or slow his connection is. He gets the error consistently when he tries to upload today (he did manage to upload three files to the same table yesterday, though).
 
```
[$rootScope:inprog] $apply already in progress

http://errors.angularjs.org/1.5.5/$rootScope/inprog?p0=%24apply
https://www.rebuildingakidney.org/chaise/scripts/vendor/angular.js?v=ea03e809effc2b87cc7bd368e1740e84:17340:13
```

**Comment by chiragsanghvi** [comment]
@jrchudy  To avoid these errors just wrap the `$apply` calls in try catch.
I added the timeouts because sometimes they won't pick the new data.

**Comment by jrchudy** [comment]
PR #1140 addresses this issue. I added a `try/catch` block around each `$scope.$apply` in `upload.js`. The catch currently logs a warning to the users browser console. I will update this on Monday with logging to a folder on the server for each deployment so we can track how often this occurs and more appropriately handle this in the future if it continues to be a recurring problem.

**Comment by hongsudt** [comment]
This issue is still not solved! The user just reported the same error on RBK.

**Comment by jrchudy** [comment]
It appears that the user was using Internet Explorer 11. Odd that it didn't work in this version. Maybe there's another compatibility issue with IE that I'm not aware of with AngularJS.

Closing this issue based on the response we got in the email thread and after talking to @hongsudt.
