### ISSUE TITLE
Confirm edits with preview before commit

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1145]
This is kind of a wishlist feature. This came up as a user suggestion in the FB annual meeting.

When doing record edit, users would like to see a preview of what they are about to commit before they commit it.

**Comment by karlcz** [comment]
Any idea what the expected UX here would be?  Showing the whole final
form content again, or doing some kind of flagged "diff" to highlight
what changes the user is actually requesting?

**Comment by robes** [comment]
Just to document this response which was discussed this morning.

The user request was a subtle UX issue about reading a form being harder than reading it "the way it would look on the [record] page".

The idea I most liked from this morning was the idea of introducing a "Preview" mode *before* submitting the form that the user can toggle to see the page in more of a display mode (i.e., replacing edit controls with text dispaly, replacing markdown editor with the preview/generated text, etc.).

And as I mentioned, I would consider this low priority (in my opinion), unless we have an easy way to do this. Also, we are just releasing the recordedit app with the FB users, so we anticipate a lot more feedback. We might way until we learn more.

**Comment by robes** [comment]
I should add, I do personally like the "diff" to highlight the changes. The users I spoke to didn't request that, but I would believe it would be useful if we had that.

**Comment by jrchudy** [comment]
Added this to the wishlist wiki page, closing this issue.
