### ISSUE TITLE
Timestamp format error while trying to create a new Experiment or Sample on GPCR

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#1147]
https://dev.gpcrconsortium.org/chaise/recordedit/#1/experiments:experiment

Error 400 Bad Request The request is malformed. Bad JSON array input. ERROR: invalid input syntax for type timestamp with time zone: "{"date":null,"time":null,"meridiem":"AM"}" 

In the "Last Modified Timestamp" field it actually displays [object Object] instead of "Automatically Generated"

**Comment by jrchudy** [comment]
The changes to fix this issue have been merged into master.

Reassigning this to @bugacov to verify it has been fixed.

**Comment by bugacov** [comment]
I tested creating an experiment and sample on dev and this issue seems to be fixed. closing the issue.
