### ISSUE TITLE
Default Values in Recordedit

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1156]
The Default values need to be more robustly tested in the e2e tests at the initialization of the `recordedit` app. Include tests for each column type:
- **not** generated
  - [X] boolean
  - [X] date
  - [X] timestamp
  - [X] text
  - [X] markdown
  - [X] integer
  - [X] float
  - [X] f. key
- generated (disabled)
  - [X] boolean
  - [X] date
  - [X] timestamp
  - [X] text
  - [X] markdown
  - [X] integer
  - [X] float
  - [X] f. key

**Comment by karlcz** [comment]
foreign key is not a column type but an orthogonal choice to all of those column types...  also, please make any test for this general enough so that we can easily add more column types later, i.e. `json` and `jsonb` should be added as soon as we have that feature in chaise.

**Comment by jrchudy** [comment]
The changes for this issue are merged into master. Support for json columns is still in progress so those tests will be included with the chanegs to support `json` and `jsonb`. This is being tracked by issue #1041.
