### ISSUE TITLE
Foreign Key with Default Value

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1159]
The current implementation is a little crude as it is showing just the key value for the associated row in the foreign related table. There should be a request made to fetch that row and get a proper rowname to display in the field during record creation.

**Comment by hongsudt** [comment]
@RFSH the fk issue (allow access to the fk rows) that you are working on should address this issue as well, correct?

**Comment by RFSH** [comment]
@hongsudt No it won't. As Josh pointed out we need extra requests for each of the foreign keys.

**Comment by RFSH** [comment]
As part of #1400, we are now making extra requests for getting the actual foreignkey data and therefore we are showing the correct rownames (If the default values are invalid, we are going to completely ignore the default value).
