### ISSUE TITLE
Back arrow button target area too small on value picker.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#116]
This is going to make people crazy.  Need to be bigger, perhaps including text as well.

**Comment by crisaless** [comment]
Committed fix

**Comment by crisaless** [comment]
Ugh, just saw bug in Safari still. Back to the drawing board.

**Comment by crisaless** [comment]
Committed workaround for Safari. Once tested on the dev site this can be closed. I think we should wait for user feedback before considering adding text.
