### ISSUE TITLE
Editing a json column does not work

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1163]
Going to an existing record like

https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Synapse:FScope/ID=20170315_FScope2

with JSON content in a column does not work.  The editor shows `[object Object]` instead of the actual JSON content you would see in record app: `{"FISHSPY_GAMMA":2,"FISHSPY_CONTRAST":1.2}`

https://synapse-dev.isrd.isi.edu/chaise/record/#1/Synapse:FScope/ID=20170315_FScope2

**Comment by nitishksahu** [comment]
JSON column support changes have been merged to master with [PR#1177](https://github.com/informatics-isi-edu/chaise/pull/1177)

**Comment by nitishksahu** [comment]
Assigning this to @karlcz  to verify.

**Comment by karlcz** [comment]
I can confirm that this is working on my dev server tracking master branches
