### ISSUE TITLE
generated timestamp column with now() as default show "Invalid Date"  

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1174]
@karlcz How do we distinguish between a function vs literal values set for default?

For numeric, boolean, date, timestamp, we can probably validate the default value..  But what do we do with text columns?

**Comment by jrchudy** [comment]
The changes to fix this issue have been merged in `ermrestJS`. Reassigning this to @hongsudt for verification.

Below is the link that you originally saw the issue:
https://dev.gpcrconsortium.org/chaise/recordedit/#1/assets:fcs_source
