### ISSUE TITLE
Need "spinner" during load of record page

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1176]
As I commented on #1082 

> I'm going to have to open another issue though because this fix now makes apparent the long wait time for the main entity attributes to appear. We should probably have a spinner displayed as a general practice while waiting for first display of something.

**Comment by nitishksahu** [comment]
@robes , Can you please verify if it is still an issue?

Thanks!

**Comment by robes** [comment]
Works for me.
