### ISSUE TITLE
Add json and jsonb test cases to multi-col-types spec

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1182]
[multi-col-types.spec.js](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/default-config/recordedit/multi-col-types.spec.js) has test cases for different column types that chaise supports. We should add json and jsonb test cases to this test spec too.

**Comment by hongsudt** [comment]
@RFSH please review this and close it.

**Comment by hongsudt** [comment]
@nitishksahu @RFSH is this task done? If so, please close it.

**Comment by RFSH** [comment]
It is done as part of #1218, but the PR is still pending other changes. That's why we haven't closed this issue yet.

**Comment by nitishksahu** [comment]
The [PR](https://github.com/informatics-isi-edu/chaise/pull/1218) with these test cases have been merged to master, @RFSH can we close this issue now?
