### ISSUE TITLE
Fix the Makefile rules for e2e testing

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1189]
The main e2e test rule in Makefile is:

```
.PHONY: test
test: deps
    $(BIN)/protractor $(E2Enavbar) && $(BIN)/protractor $(E2EnavbarHeadTitle) && $(BIN)/protractor $(E2EDrecord) && $(BIN)/protractor $(E2EDrecordRelatedTable) && $(BIN)/protractor $(E2ErecordNoDeleteBtn) && $(BIN)/protractor $(E2EDrecordCopy) && $(BIN)/protractor $(E2EDrecordset) && $(BIN)/protractor $(E2ErecordsetAdd) && $(BIN)/protractor $(E2EDrecordsetEdit) && $(BIN)/protractor $(E2EDIrecordAdd) && $(BIN)/protractor $(E2EDIrecordDefaults) && $(BIN)/protractor $(E2EDIrecordMultiAdd) && $(BIN)/protractor $(E2EDIrecordEdit) && $(BIN)/protractor $(E2EDIrecordMultiEdit) && $(BIN)/protractor $(E2EDrecordEditCompositeKey) && $(BIN)/protractor $(E2ErecordEditNoDeleteBtn) && $(BIN)/protractor $(E2EDrecordEditSubmissionDisabled) && $(BIN)/protractor $(E2EDIrecordEditMultiColTypes) && $(BIN)/protractor $(E2EDrecordEditDomainFilter) && $(BIN)/protractor $(E2EmultiPermissionsVisibility) && $(BIN)/protractor $(E2EDviewer) && $(BIN)/protractor $(E2Esearch) && $(BIN)/protractor $(E2Efooter)
```

And then there are rules for individual units of tests such as this:

```
#Rule to run navbar tests
.PHONY: testnavbar
testnavbar: deps
    $(BIN)/protractor $(E2Enavbar) && $(BIN)/protractor $(E2EnavbarHeadTitle)
```

There are multiple problems here that make this potentially unreliable and inefficient:
- The master rule `test` should be a rollup of the individual test rules. As is, this is duplicative (copy and paste) with all of the problems that come with that.
- The rules do not specify any prerequisites. (I added the `deps` in my `fix-install` branch but otherwise they lacked even that).
- Without prerequisites, the rule fires even when it doesn't need to making it potentially inefficient.
- To work around this, we've created a bunch of rules to tests sub-units but this relies on a developer knowing precisely what code is impacted by a change they make, making it potentially unreliable.

With better written rules there would be no copy-and-paste duplication and only the tests that need to run would run when someone edits a file. When a developer changes a file `foo.js`, all of the dependent tests would fire and _only_ the dependent tests making the invocation of `make test` both a more reliable indicator of success (or failure) and making it more efficient.

**Comment by jrchudy** [comment]
If we were to change `make test` to have each make target (i.e. `make testrecord && make test navbar && ...`), if one of those specs fails, it stops running the rest after that for the rest of the target. 

Let me try to explain it a little more. Say `make testnavbar` has 2 specs, if I run `make test`, and `make testnavbar` starts running, but the first spec fails, the second spec will never run. Then make test will move on to the next target and runs those specs.

This isn't that big of a deal. It just doesn't let you run every single spec to see _all_ potential failures.

**Comment by robes** [comment]
@hongsudt This is another one of those makefile & related issues.
