### ISSUE TITLE
Generate Documentation for Chaise Errors

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1196]
We need to have a `doc.md` for the error service/factory that we have defined in chaise (`/common/errors.js`). This could be something similar to jdocs (where the documentation is inline in the code) that we then produce a document from at build time.

**Comment by amitjha21** [comment]
Created wiki here:
https://github.com/informatics-isi-edu/ermrestjs/wiki/General-Documentation-for-Error-Hierarchy

**Comment by amitjha21** [comment]
ERMrestJS error wiki:
https://github.com/informatics-isi-edu/ermrestjs/wiki/ERMrestJS-Error-Hierarchy
Chaise error wiki:
https://github.com/informatics-isi-edu/chaise/wiki/Chaise-Error-Hierarchy
