### ISSUE TITLE
Remove unused data types

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#12]
https://github.com/informatics-isi-edu/chaise/blob/3b3a88bb770fb21124d7a4c5b0bbd1e4556fa6ea/scripts/ermrest.js#L40-L44

Some of the types are not ever returned by ERMrest. We should prune those that are invalid from the lists and also remove any conditional and other code branches that depend on these types.

**Comment by robes** [comment]
this is probably finished?
