### ISSUE TITLE
Refactor Chaise and ERMrestjs Errors 

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1200]
We currently have a [factory for errors](https://github.com/informatics-isi-edu/chaise/blob/master/common/errors.js#L13) which is not being used. Instead the errors that are defined in [here](https://github.com/informatics-isi-edu/chaise/blob/master/common/errors.js#L96,L129) are the errors that we are using. We should clean this up. These are the list of tasks that I think we should do:

- [x] Add `name` attribute to ermrestjs error classes. This will be used in chaise as the title of error modal. For starting point, you can just return a more readable class name. For example `TimedOutError ` error can have `Timed Out Error` as its `name`.
- [x] Investigate whether it makes sense for [these](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/errors.js#L177,L229) error classes to be in ermrestjs. Should we move them to chaise? or leave them in ermrestjs? Two of them are duplicate and we have them in chaise too.
- [x] Refactor `Errors` and `ErrorService` factories in chaise. Move all the custom Errors into `Errors` factory.
- [x] Create a constant for error messages. Instead of reusing the `messageMap`.
- [x] Make sure all the errors are extending javascript `Error` object, and they have the same attributes.

    ```javascript
      // NOTE: 
      // this is just a sketch, you might need to change it accordingly.
      // You might need to add some other attributes based on the Error type.
      /**
      * @param {string} status the network error code
      * @param {string} message error message
      * @constructor
      */
      function CustomError(status, message) {
        this.status = status;
        this.message = (message === undefined ? errorMap.CustomError : message);
        this.name = SOME_VALUE;
      }

      CustomError.prototype = Object.create(Error.prototype);
      CustomError.prototype.constructor = CustomError;
    ```
- [x] Change [handleException](https://github.com/informatics-isi-edu/chaise/blob/master/common/errors.js#L134) accordingly. Instead of checking for code or message, they should check for object type (`error instanceof ExpectedError`).
- [x] Change the title of error modal to use the `name` attribute. Also remove the "Error: " form the message.

**Comment by amitjha21** [comment]
Slight modification of error message function which will be inside `Errors` factory:
``` javascript
   function multipleRecordError(status, name, message) {
            this.status = status;  //XXX e.g. 504
            this.type = type;      // multipleRecordError
            //errorNames is constant of error names; multipleDataErrName = "Multiple Records Found"
            this.name = (name === undefined ? errorNames.multipleDataErrName : name);                
           //errorMessages is constant of all error message
            this.message = (message === undefined ? errorMessages.multipleDataMessage : message);    
        }
        multipleRecordError.prototype = Object.create(Error.prototype);
        multipleRecordError.prototype.constructor = multipleRecordError;
```

I am hoping to keep this for both `chaise` and `ERMrestjs`.
Any thoughts?

**Comment by amitjha21** [comment]
Assigning to @RFSH  to review it.
Error handling is maintained both at `chaise` and `ermrestjs` repo. Error objects are created using [`Prototypes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/prototype) and subtype of 409 errors was created using inheritance.
_e.g._
   ```
 IntegrityConflictError.prototype = Object.create(ConflictError.prototype);
 IntegrityConflictError.prototype.constructor = IntegrityConflictError;
```
