### ISSUE TITLE
Footer flikers due to List element in html

### ISSUE THREAD

**Issue by amitjha21** [informatics-isi-edu/chaise#1204]
List (`ordered` or `unordered`) adds line height in the footer therefore increasing the page length. This causes footer directive to keep changing the location of the footer.

**Comment by jrchudy** [comment]
When starting at 100% zoom level and zooming out to 33%, the footer moves a little bit on the `recordset` page. It starts to move up with the page content. 

When looking at `record`, if you start zoomed out, the footer does flicker still while the content is loading.

**Comment by amitjha21** [comment]
Most of the sites have footers stick when zoomed out. I think we should have that way too. 
e.g.
github
![image](https://user-images.githubusercontent.com/9977014/28692483-9e37b8a4-72d5-11e7-9c2d-3cb59aab3b90.png)

**Comment by jrchudy** [comment]
@amitjha21 that seems to be the case when I was zooming out on the recordset page. That case seems reasonable. But the case where the footer was flickering while page content was loading on `record` worries me a little bit.

**Comment by amitjha21** [comment]
It is not reproducible. I tried `record` on Linux and Win machine. it worked (both on `chrome` and `FF`. 
Maybe I will try them in few Mac systems. 

**And just to highlight, flickering only happens when footer has `li` tag.**

**Comment by jrchudy** [comment]
Maybe that's the case I'm seeing. I still have my footer defined as:
`* Please check [Privacy Policy](/privacy-policy/){target='_blank'}`
