### ISSUE TITLE
Bad presentation of existing asset in file upload for recordedit

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1209]
I think the file upload widget needs a little more review and bug fixing related to presenting state of existing records.

First, we need to reach a consensus on expected behavior.  I think there are two choices:

1. The file upload widget should behave like other input fields and *ignore* any markdown_pattern presentation in the annotations, instead always showing a more raw value presentation.  In this case, the raw asset URL text should appear.
2. The file upload widget should deviate from other input fields and *obey* markdown_pattern presentation if it is defined for the corresponding context. In this case, the widget needs to observe the "is html" and related properties to put rendered markdown into the DOM.

Right now, it seems like it partially obeys the pattern but inserts it into the DOM incorrectly.  I see a text rendering of the HTML output of the markdown renderer.  I can see benefits of allowing markdown patterns here, e.g. a better UX might include embedded content display for some kinds of assets.

Also, when someone is revisiting this code, I think they should also confirm that the widget and chaise recordedit app state are safe in that they preserve existing asset metadata (url, hashes, etc) even if there is a markdown pattern affecting the presentation of that state.

Right now, the broken display doesn't install confidence, and I as a user was afraid that the corrupt looking widget presentation meant that I'd corrupt my ermrest record if I submitted the recordedit form.  Instead, I canceled and then went to change my annotations to exclude the column from visible columns, so I could be more confident that I wouldn't corrupt my existing asset URLs...

**Comment by RFSH** [comment]
This bug is happening because of [ermrestjs](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/reference.js#L3917) logic. If there's a `markdown_pattern`, regardless of context, we're using it. We can change it to always return the raw value in entry contexts (If we decid to stick with the first choice).

**Comment by RFSH** [comment]
The change in ermrestjs is merged (#459). Now ermrestjs will only return raw values for file assets in entry contexts.

**Comment by karlcz** [comment]
OK, I confirmed three different test scenarios on my test system
1. Edit an existing record to change some other field and the existing asset url remains stored
2. Copy an existing record and the existing asset url is copied and stored
3. Clear the upload control and the existing asset url is discarded
