### ISSUE TITLE
version file is not installed

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1210]
We have a script in chaise for generating its version including the versions of dependent software. The make file rule for this is not factored out well and more importantly the version is not installed anywhere except Travis where we don't even need it.

Also, the output `version.txt` should be cleaned up.

**Comment by robes** [comment]
@hongsudt This is one more makefile related issue

**Comment by chiragsanghvi** [comment]
This was fixed in this PR https://github.com/informatics-isi-edu/chaise/pull/1247. Now version is installed on all machines.
