### ISSUE TITLE
The composite key values are not assigned to the right slot

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1217]
https://dev.rebuildingakidney.org/chaise/recordedit/#2/RNASeq:scRNA_File

This table requires 1 composite fk which consists of 3 fields.. Choosing an entry leads and the app generates the corresponding error message. Note: I have another table that has 3 keys and it didn't have the same issues.. 

From the error below, the value for the Sample_Accession_ID and Single_Cell_Metrics_Accession_ID are swapped! 

Error 409 Conflict The request conflicts with the state of the server. Input data violates model. ERROR: insert or update on table "scRNA_File" violates foreign key constraint "scRNA_File_Study_Accession_ID_fkey" DETAIL: Key (Study_Accession_ID, Sample_Accession_ID, Single_Cell_Metrics_Accession_ID)=(RBKUSC20170719STU1, RBKUSC20170724SCM1, RBKUSC20170719SAM2) is not present in table "Single_Cell_Metrics".

**Comment by jrchudy** [comment]
Looks like the Sample Accession ID and Single Cell Metics Association ID got mixed up.

![image](https://user-images.githubusercontent.com/2932600/28548025-8da413e4-7086-11e7-8657-f2938c3fe71d.png)

**Comment by jrchudy** [comment]
The problem for this issue can be traced back to [ForeignKeyRef](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/core.js#L2734-L2774)'s constructor. In the constructor, `jsonFKR.foreign_key_columns` and `jsonFKR.referenced_columns` are both in the right order. But when those two column sets are copied to `foreignKeyCols` and `referencedCols`, the order is not properly preserved.

**Comment by RFSH** [comment]
@hongsudt This is fixed now. Can you please verify?

**Comment by hongsudt** [comment]
Yes. This is now working as expected.
