### ISSUE TITLE
disble login button after it is clicked

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1221]
When the button is clicked twice, a terminal error is generated. This happens to me quite often as my browser is a bit slow. We should prevent this problem.

**Comment by nitishksahu** [comment]
Disabling the login button can lead to some scenarios like:

- If the user clicks on login link but then decided not to log in and closes the login window popup then the `login` link remains disabled and the user is left with no other option but to refresh the page to enable the `login` link.

- Secondly, if the user somehow losses the pop-up window, and the pop-up window is now somewhere behind some other window, in that case as well the user had to refresh the page to get the login link enabled.

@hongsudt  @RFSH  @jrchudy any suggestions?

**Comment by nitishksahu** [comment]
This has been moved to `blocked` for now as we are expecting more inputs on this, we need to decide whether we want to disable the login link once clicked which could lead a situation where
if you click on the login button and didn't actually log in, you cannot login anymore until you reload the page.

**Comment by hongsudt** [comment]
I am closing this issue..
