### ISSUE TITLE
500 Error in Search Testcases 

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1222]
Search is returning 500 error in test cases. You can see the sample data that test case has created [here](https://dev.isrd.isi.edu/~ashafaei/chaise/search/#30554/product-search).

**Comment by hongsudt** [comment]
@svoinea please take a look at this problem.. We are not sure whether this is relevant to the new ermrest version..

**Comment by karlcz** [comment]
If this is reproducible the first step would be to capture the server error log which ought to include more error information from the ermrest service, i.e. a Python stack trace and exception information.

**Comment by karlcz** [comment]
Actually, the travis build already has the httpd server logs at the end.  This looks like an ermrest bug.  Please submit a bug report, including a small sample schema and request that can reproduce it independently of this whole test suite, i.e. just the necessary table and foreign key definitions used in the failing request.

**Comment by RFSH** [comment]
@karlcz 
Created [ermrest#160](https://github.com/informatics-isi-edu/ermrest/issues/160) with schema an request.

**Comment by hongsudt** [comment]
@RFSH are the search test cases still failing? If not, maybe we can close this issue?

**Comment by RFSH** [comment]
@hongsudt The test cases are passing now, I am closing this issue.
