### ISSUE TITLE
making "View" function more obvious

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#1227]
Users aren't 'getting' that they should click the "View" icon to see a details page. Two options:

- Make button more obvious: change one of the classes on the "a" tag from btn-default to btn-primary.

- In addition, could replace <span class="glyphicon glyphicon-eye-open"></span> with the text "View Details"

**Comment by amitjha21** [comment]
Added `btn-primary` class in the ellipses template with `View Details` as the tool-tip for demo.

### [Example](https://dev.rebuildingakidney.org/~amit/chaise/recordset/#2/RNASeq:Sample@sort(Last_Modified_Timestamp::desc::,Accession_ID))

![image](https://user-images.githubusercontent.com/9977014/29146997-321d4438-7d19-11e7-9c39-1f0b548cfbf3.png)

**Comment by hongsudt** [comment]
can you make all three buttons look the same.

**Comment by amitjha21** [comment]
Added `btn-primary` for all buttons.
![image](https://user-images.githubusercontent.com/9977014/29149624-36f06362-7d2a-11e7-8aae-efe389100037.png)

**Comment by amitjha21** [comment]
This has been merged into master. Assigning to @crisaless to verify and close it.

**Comment by crisaless** [comment]
looks good, thanks.
