### ISSUE TITLE
Minor display glitch: line separating selection from search result doesn't go all the way down to the footer.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#123]
![screen shot 2015-10-11 at 9 21 18 am](https://cloud.githubusercontent.com/assets/3597150/10417671/80355a40-6ff9-11e5-82e5-b9b8a72fac29.png)

**Comment by crisaless** [comment]
I've been wrestling with this for a while. For the next release, I am going to try to refactor the sidebar so it doesn't use 'position:fixed' (which is how it currently always stays visible even when you scroll down) 

For today, I can either do what I'm doing now, which is allow room at the bottom so it doesn't cover the footer - which doesn't scale when you change your scrolling, hence the gap - or let the sidebar overlay the footer. Another option is actually getting rid of the footer altogether.

**Comment by carlkesselman** [comment]
I would just leave it for now.

Carl

Sent from my iPhone

Dr. Carl Kesselman
Dean's Professor, Epstein Dept. Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Phone: +1 (310) 448-9338
Email: carl@isi.edu<mailto:carl@isi.edu>

On Oct 12, 2015, at 10:00 AM, Cris Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been wrestling with this for a while. For the next release, I am going to try to refactor the sidebar so it doesn't use 'position:fixed' (which is how it currently always stays visible even when you scroll down)

For today, I can either do what I'm doing now, which is allow room at the bottom so it doesn't cover the footer - which doesn't scale when you change your scrolling, hence the gap - or let the sidebar overlay the footer. Another option is actually getting rid of the footer altogether.

-

**Comment by robes** [comment]
@crisaless as this been fixed?

**Comment by crisaless** [comment]
this is a facebase-only issue because of that footer. My recent commit fixed this so go ahead and review on dev.facebase.org/data/search/ (you could only see the sidebar glitch once there were search results that push the footer down)
