### ISSUE TITLE
Adding a relation to an association table does not refresh the display in markdown display mode

### ISSUE THREAD

**Issue by nitishksahu** [informatics-isi-edu/chaise#1230]
When we add a relationship to an association table, the heading of the table (showing `n` results) gets updated but the related entities are not updated.

Steps to replicate: (in rbk)
- go to https://dev.rebuildingakidney.org/chaise/record/#2/Protocol:Protocol/ID=15
- Add a relationship in `Protocol Keyword`
- When we return back to the record page, we see the count heading updated but the new relationship added is not displayed until the page is refreshed

This issue is only there for non-tabular display, it is working fine for tabular display

**Comment by nitishksahu** [comment]
The changes for this issue has been merged with master, assigning this to @amitjha21 to verify and close

[Link](https://dev.rebuildingakidney.org/chaise/record/#2/Protocol:Protocol/ID=15)

**Comment by amitjha21** [comment]
The said feature works for *association table in markdown refresh*. However Same does not work for table with inbound foreign key association.

**Comment by amitjha21** [comment]
Closing this as #1244 has been opened to take care of inbound foreign key association.
