### ISSUE TITLE
Directive for Faceting

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1233]
Each Facet controller should have a list of applied filters and a controller for selecting new filters. This controller should show some useful aggregated information about available data. One of these controllers is going to be the list of distinct values with their count. This controller should have
- Searching capability
- Pagination
- Sorting capability.
- Ability to select a row (tuple).

These are the same capabilities that `recordset` directive (the directive in recordset page and also foreign key modal selector) has. This directive needs a Page object and Reference to function. But in the controller that I described for faceting, we don't have an actual table in the database and therefore we cannot create a Reference or Page object.

This issue is related to what kind of data structure the aggregate group APIs should return.

Following are different approaches that we can take to resolve this issue:

#### Chaise 

Ideally we should create a new directive that has no assumption about how the data is being generated and it's only calling the provided callbacks. This directive should have the following callbacks and parameters:

- columns (table headers): List of objects that have `name`, `displayname`, `sortable`, and `comment` attributes.
- row values: List of objects that have `isHTML` and `value` attributes.
- read (callback): The callback that will be called to update the displayed results. Should return a new set of row values.
- next (callback): Callback for getting the next page of results. Should return a new set of row values.
- previous (callback): Callback for getting the previous page of results. Should return a new set of row values.
- hasNext
- hasPrevious

As the first step, instead of changing the existing recordset directive we can just create a new directive and use it for this new case. Then we can refactor the existing code to use this newly created directive.

A big problem with this approach is that it's not just one directive that we have to recreate. recordset directive has a record-table directive inside, and record-table is using ellipses directive. To reduce the amount of nesseccary work, we can create the recordset directive without any hierarchy of directives. Later we can refactor this.

#### ERMrestjs

Now we need to discuss what should the aggregate group APIs return that eventually will be used by this new directive. We can take the `Reference.read` function as an example.
- `read` returns a `Page` object, which has `next`, `previous`, `hasNext`, and `hasPrevious` objects.
- The `next` and `previous` functions will return a new `Reference` which you can call `read` on it.

The good thing about this apporach of having a `Page` object is hiding the logic for getting the previous and next page from chaise. But in here, the pagination of aggregate group API result should not affect its `Reference` object. Therefore we cannot implement it using the same approach (or at least I am not sure how we can).

We can delegate the task of pagination to the chaise, then we don't need to keep the state of pagination of aggreagted result in the Reference object. For instance the `entityCount` API can have `sortOptions`, `previous`, `next`, and `search` as its parameters.

### 2. Create Pseudo-Table

If we can create a "fake" Page object, then the aggregate group APIs can just return a page which will eventually be used by current directives. And we won't need most of the changes described in the previous approach and we can reuse the existing logic and directives.

We don't know how we can create a "Pseudo-Table". We can create arbitary table objects in the ermrestjs, and pass it to the Reference. But we're not sure what APIs might break. Most of Reference APIs rely on the `Location` object or the uri to the table in ermrest API. If we create an arbitary table object, then if an API uses that uri (with the non-existing table name in it), it will throw an error.

This approachs needs more research. If eventually we want to support References based on non-existing tables (for example the result of joins), we should investigate this approach.

**Comment by RFSH** [comment]
I wrote this issue before the discussion in the meeting, so some of the points are invalid.

**Comment by hongsudt** [comment]
@RFSH @jrchudy please update the text above and also create a task list related to this issue..

**Comment by RFSH** [comment]
I am closing this issue since it's not relevant anymore. We're going to create a new "Page" like prototype in the ermrestjs, then we can reuse the current directive
