### ISSUE TITLE
Fix "Download CSV" tooltip

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1238]
Right now it misleads the user.

![image](https://user-images.githubusercontent.com/4202842/29292714-080a1e72-80fd-11e7-90aa-d1ec6c8129f9.png)

It says it will download only the "displayed" results but it actually downloads _all_ results based on the current filters of the recordset page (minus the limit). One would expect that the "displayed" results means the limit filter too.

My preferred fix for this would be to fix the tooltip text to read: "Click to download all results."

**Comment by nitishksahu** [comment]
The changes for this issue has been merged to master.
[Link](https://dev.isrd.isi.edu/~nitish/chaise/recordset/#1/isa:dataset@sort(release_date::desc::,id))

Assigning this to @robes to verify and close.

**Comment by robes** [comment]
Looks good. thanks
