### ISSUE TITLE
Main entities are loading after the related record.

### ISSUE THREAD

**Issue by amitjha21** [informatics-isi-edu/chaise#1242]
In `record` page entity records are loading after related tables with accordion. The issue sporadically occurs during initial page load.

**Comment by amitjha21** [comment]
This has been merged. Assigning @robes to verify and close it.
https://dev.isrd.isi.edu/chaise/record/#1/isa:dataset/id=269
https://dev.rebuildingakidney.org/chaise/record/#2/Protocol:Protocol/ID=22

**Comment by robes** [comment]
That link isn't working for me right now. But I've see it working correctly already in other deployments.
