### ISSUE TITLE
Referential integrity error in recordset app while deleting related table entry.

### ISSUE THREAD

**Issue by amitjha21** [informatics-isi-edu/chaise#1252]
1. Error while deleting records in `recordset`
> 409 Conflict
The request conflicts with the state of the server. update or delete on table "experiment_type" violates foreign key constraint "dataset_experiment_type_experiment_type_fkey" on table "dataset_experiment_type"
DETAIL:  Key (term)=(Confocal microscope images) is still referenced from table "dataset_experiment_type".

proper error handling in case of unauthorized/invalid deletion. 

2. Another change is required to remove an undeclared variable (_error_) in `ellipses.js`

**Comment by hongsudt** [comment]
This issue is the same as #716.. Will close this issue.
