### ISSUE TITLE
Truncated rendering of "automatically generated" label in recordedit

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1254]
In my test server, I am seeing some rendering/styling problems.  For example: 

- https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Image%20Pair%20Study

The `automatically generated` text looks clipped both on the left and the bottom on Firefox.

**Comment by karlcz** [comment]
![clipped](https://user-images.githubusercontent.com/1075148/30087657-bab4e984-9256-11e7-8808-83dd7f1ef0c1.png)

**Comment by RFSH** [comment]
It seems like this is not an issue anymore. We should close this.

**Comment by hongsudt** [comment]
This bug is not predictable.. I am going to mark this won't fix and close.
