### ISSUE TITLE
The default display of inline inbound fk should be a list

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1255]
Currently, a tabular format is displayed instead of a list of row names. Please fix asap. 
https://dev.rebuildingakidney.org/chaise/record/#2/RNASeq:Sample/Internal_ID=d18_batch4

Also when it is in a tabular format, the position of Add | View More should be on top of the table, not next to the table.

**Comment by amitjha21** [comment]
There is no accordion for tables that are appearing as part of the main entity; if `Add | View More` comes on top of the table it will create extra white space on the top. To utilize this space we had decided to add all action items next to the table.

**Comment by amitjha21** [comment]
1. Change action items position: Keep the items on top of the table. It is ok to have extra white spaces.
2. If no annotation is defined, default display should be bullets of row names. Row names should be available through `ermrestjs`.

**Comment by amitjha21** [comment]
If no annotation is defined then `ermrestjs` returns `table` type as default display type.

**Comment by amitjha21** [comment]
This is merged now. Assigning to @hongsudt to verify it.
