### ISSUE TITLE
More Options In Error Modal along with table displayname in the message

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1256]
Provide more options in the terminal error modal based on the app. For example in read only context we can have a retry/reload button. Currently we have just two options:

-  `ok` button which will change the page location to a url that is defined in chaise config or just the root.
- Dismiss button which will be available if `allowErrorDismissal` is available in the chaise config.

**Summary**

Three level of errors:
1. Chaise Specific
2. Ermrestjs Specific
3. Unknown(Terminal error) -- this should only be used for unexpected error cases.

* For 1 and 2 separate section in the `errors.js` will be created. 
  * For 1, OK and Reload will behave according to the app and table name that would be extracted from the reference. `Record` and `Recordedit` will be taking users to `Recordset` page (if the schema:table is valid). There will be a `Reload` button for `Recordedit` app.
  * For 2: the look and feel should be similar to 3, but the title should not be `Terminal Error` but something more meaningful to the users. There is also no need to have `show more detail`.
* For 3 there will be plain Site Admin error message with hard stop and OK going to Home Page. 

To get the table display name, reading reference.displayname.value before throwing errors across all apps. The error object thrown will have an attribute gotoTableDisplayname which contains this table name value.
If this attribute is defined along with redirectlink (i.e. link to recordset) then it will be case 1 as described above otherwise case 2 (with Home Page as goto Navigation display name and Link to home page for OK button).
A super class for all the errors has been created at `ermrestjs`. This `ERMresrError` class will be used at `chaise` to map all ermrest related errors.

Test cases:
`test/e2e/specs/all-features-confirmation/errors/errors.spec.js`
- All OK button behaviours
- Reload button in `recordedit`
- Collapsible `Show Error Details`
- Various error types check using modal and modal contents

**Comment by hongsudt** [comment]
I tried to think about cases where we wanted to provide an alternative. I can only come up with one (assuming that we know the context of when the error is thrown)... 
* if the terminal error is thrown from a record or recordedit page, provide an option to go to recordset of the same table. 

In other cases, we can provide an option for users to reload the page. But in some cases, that would lead back to the error again.

**Comment by amitjha21** [comment]
As per the discussion:
- For `record` app OK button should take users to the `recordset` page
- For `recordedit`, there should be two buttons. OK to take users to the `recordset` page and a Restart/Reload button to let user start over.

**Comment by amitjha21** [comment]
Error modal in `recordedit`. 

![image](https://user-images.githubusercontent.com/9977014/34171694-2bda07f8-e4a4-11e7-8566-7a89fe0036f1.png)

**Comment by hongsudt** [comment]
There are two terminal error cases that I want to improve the error messages: 
- Request timeout. We should append "The server is temporarily unavailable. Please try submitting your request later."
- In the case of record app without the filter/facet, it throws a generic terminal error. We should bring the "No filters have been specified" instead of embed that in the show error detail.

**Comment by amitjha21** [comment]
There are some terminal cases where URL would not be valid. In such scenarios, it is better to let existing behavior be in place (**`OK`** should take users to `Home`.). Some of such scenarios are:
- MalformedURIError
- InvalidFilterOperatorError
- InvalidFacetOperatorError

**Comment by amitjha21** [comment]
As per discussion:
Three level of erros:
- Chaise Specific
- Ermrestjs Specific
- Unknown(Terminal error)

For 1 and 2 separate listing will be created. For 1, OK and Reload will behave according to the app and table name that would be extracted from the reference. `Record` and `Recordedit` will be taking users to `Recordset` page. There will be a `Reload` button for `Recordedit` app.

For 3 there will be plain Site Admin error message with hard stop and OK going to Home Page.

**Comment by amitjha21** [comment]
To get the table display name, reading `reference.displayname.value` before throwing errors across all apps. The error object thrown will have an attribute `gotoTableDisplayname` which contains this table name value.
If this attribute is defined along with redirectlink (i.e. link to `recordset`) then it will be case 1 as described above otherwise case 2 (with  'Home Page' as goto Navigation display name and Link to home page fo `OK` button).

**Comment by amitjha21** [comment]
corresponding `ermrestjs` PR ermrestjs/pull/579

**Comment by amitjha21** [comment]
This has been merged into master. Assigning to @hongsudt to verify and close it.
