### ISSUE TITLE
inline inbound fk should display "No Result Found" if the table is empty

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1259]
Currently, nothing is displayed.

https://dev.rebuildingakidney.org/chaise/record/#2/Protocol:Protocol/ID=43

**Comment by hongsudt** [comment]
@robes @karlcz Do you remember the phrase that we want to replace "No Result Found"? "No data"?

**Comment by robes** [comment]
Sorry, I don't remember.

Given the specific context for related records, I might suggest "No Related Records" would make sense and be consistent with the link "Show/Hide ... Related Records".

**Comment by karlcz** [comment]
I thought the question was for "inline" pseudo columns.  I don't think a
user should be expected to understand that this is a related record when you are intentionally denormalizing it as a column.  So, I'd suggest something simpler that pretends it is a scalar, e.g.  "none" or "(none)".

**Comment by robes** [comment]
Oh, if this is for inline, then yes, I'd agree with either of those suggestions.

**Comment by amitjha21** [comment]
This is merged now. Assigning to @hongsudt to verify it.
