### ISSUE TITLE
Histogram support in Range picker

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1265]
The range picker needs to show a histogram for searching for each of integer, float, date, and timestamp.

**Comment by hongsudt** [comment]
For integer and date, we want the bin width to be a whole integer so when we label the bin, it is easy to understand... 

Let's assume that 
```
min: the current min
max: the current max
#bin: number of bins
Then 
bin width = round up ((max - min/#bin))
requested max = min + (bid width * #bin)
The new (min, requested max, #bin) will create a whole number bin size 
```

**Comment by hongsudt** [comment]
For auto-zoom, we will have to make that parametric too.. How about 60% zoom: 
```
median = floor(#bin/2)
#assume that we will zoom in 60%
range = #bin * 0.3
new min = min of bin (median - range) 
new max = max of bin (median + range)
```
