### ISSUE TITLE
Page loads without total count

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1271]
When the 'recordset' app loads, it loads without the total count of rows, i.e. "Displaying X of X records". This issue can also be seen in the "More options" modal popup.

**Comment by hongsudt** [comment]
It should be ok for the page to load with "Displaying X records" and then get updated to "Display X of Y records" later when Y is determined.

**Comment by jrchudy** [comment]
The issue is that it is never getting the Y value.

**Comment by RFSH** [comment]
This is done.
