### ISSUE TITLE
Chiclets should be bullet separated in tooltip

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1279]
The tooltip for each chiclet above the recordset table should be an unordered bulleted string. It should NOT appear as a list rather than a single string with values separated by bullets.

@RFSH mentioned that he fixed this already. So this issue is to verify that it is working properly.

**Comment by RFSH** [comment]
Yes, this is fixed and now in the `faceting` branch. It looks better now, but still needs some css tweaks which we can do for round two. Therefore, I am going to change the epic to round 2.
