### ISSUE TITLE
Update recordset after Create

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1286]
The create link on recordset with faceting should:
- [x] ~open recordedit in a new tab~ NOTE: this won't be done because the link won't be consistent with the other links in the bookmark bar
- [ ] use the on-focus event that reloads the content after the record is created and the recordset page is navigated back to and focused.
- [ ] make sure to use invalidate param

**Comment by jrchudy** [comment]
The create link opens in the same window so that it behaves the same way as `Edit`, `Permalink`, and `Download CSV`. Moving this to round 2 for the rest of the functionality.

**Comment by jrchudy** [comment]
Create on `recordset` now opens in a new tab instead. The rest of the functionality still needs to be implemented similar to what has been done for record app with updating the displayed data.

**Comment by RFSH** [comment]
Based on my understanding, this feature is completely implemented. When you click on "create" in the recordset app, we will open a new tab using the same "invalidate param" that is described in the issue. This will be used to signal recordset that it should update after going back to recordset page.
