### ISSUE TITLE
Infinite Spinner with 503 error

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1289]
Go to https://dev.facebase.org/~jchudy/chaise/recordset/#1/isa:dataset or on master after faceting is merged and follow these steps:
 1. expand organism, select 'Mouse'
 2. expand Mouse Gene, search 'msx', and select 'MSX1'
 3. expand phenotype
 4. spinner never disappears, notice 503 errors in console

**Comment by hongsudt** [comment]
@RFSH @karlcz and I discussed about the solution yesterday.. This is due to incorrect request.
