### ISSUE TITLE
Update the supported annotations in Chaise per the revised guidelines in ERMrest docs

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#129]
This primarily refers to the chaise/search page.

**Comment by robes** [comment]
We need to get to this one.

See ermrest doc:
https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md

Having these lined up with the new annotations is important to our active use cases that now have to set the old annotations and the news ones so that different pages in chaise will display consistently.

**Comment by robes** [comment]
@hongsudt this should be prioritized

**Comment by hongsudt** [comment]
We plan to deprecated this app with recordset app. So I am putting this in the wishlist and close the issue fo rnow.

**Comment by carlkesselman** [comment]
We should discuss branding.  Are we actually deprecating the name Chase in favor of the other names?

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 9, 2016, at 10:15 AM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:


We plan to deprecated this app with recordset app. So I am putting this in the wishlist and close the issue fo rnow.

**Comment by robes** [comment]
On 5/9/16, 10:20 AM, "Carl Kesselman" <notifications@github.com<mailto:notifications@github.com>> wrote:

We should discuss branding. Are we actually deprecating the name Chase in favor of the other names?

Chaise should still refer to the overall suite of UI components. Something like “search” is just one of its component.

**Comment by carlkesselman** [comment]
That is what I was thinking.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 9, 2016, at 2:09 PM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:



On 5/9/16, 10:20 AM, "Carl Kesselman" <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

We should discuss branding. Are we actually deprecating the name Chase in favor of the other names?

Chaise should still refer to the overall suite of UI components. Something like “search” is just one of its component.
