### ISSUE TITLE
Facets should expand with more content

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1290]
When a facet is opened with say 2 options, it's height is fixed. When faceting criteria is removed and more options are available for that facet, it should expand to accommodate those new options. Facets should never shrink though when new filters are selected.

**Comment by hongsudt** [comment]
@karlcz how strongly do you feel about having this feature? When you expand, it will shift the panel..

**Comment by karlcz** [comment]
On Sep 14, Hongsuda modulated:
> @karlcz how strongly do you feel about having this feature? When you
> expand, it will shift the panel..
> 

I think it is *broken* if the facet widget can show fewer than the
expected K values and a "Show more..." link.  If you're going through
the effort to prevent pathological cases like 0, 1, or 2 plus "Show
more..." why not just fix it completely?

I think letting it grow on demand is the safest/easiest solution. It
is still much less trashing than if things shrink again.

You could attempt to determine a maximum size before opening, but that
would still be fragile in the face of concurrent database edits, e.g.
by other clients.  So you can *always* be surprised by a newly
available value until you reach your limit K.

The other approach to avoiding thrashing, which we discussed in the
beginning, is to track the focused or last-focused facet widget
and keep that at the same scroll position, but allow stuff above and
below to resize.
