### ISSUE TITLE
Recordset (w/ facets) loading shows controls

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1294]
Some controls are displayed while the recordset+faceting page loads.
![facet-loading](https://user-images.githubusercontent.com/4202842/30496588-b889ae3c-9a04-11e7-927c-0a71a29c2006.jpeg)

**Comment by jrchudy** [comment]
This issue is related to issue #1278.

**Comment by jrchudy** [comment]
This issue has been fixed.
