### ISSUE TITLE
Fix footer position in apps

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1295]
The footer position needs to be part of the main container or at least relative to it so that it's placed at the body of that container.

**Comment by jrchudy** [comment]
Removing this from the epic. The footer has been temporarily set to be `fixed` at the bottom of the page (like the navbar is fixed to the top). This issue still needs to be addressed but it's much more time consuming than expected.

**Comment by hongsudt** [comment]
This change seems to break the browser print functionality. We need to fix this.

**Comment by jrchudy** [comment]
@hongsudt what do you mean by that? None of our apps are optimized for printing a web page using the browser. 

What I see is that the footer shows up at the bottom of each page in the "print preview" but there are far worse problems that can be seen. When looking at a `record` page, none of the related tables render properly in the print preview unless you drastically reduce the scale of the page. 

If there is concern with print preview not working properly, can you open a separate issue so we can discuss how to fix it or alternatives to using print preview? One thing I can think of is providing a "Download CSV" for a `record` page for instance.

**Comment by jrchudy** [comment]
To fix the footer position we need to address it in each app:
 - `recordset` - Move the footer to the bottom of the recordset content area so that it isn't part of the facet container.
 - `record`/`recordedit` - move footer to the bottom of "main-content" area so it sticks to the bottom of the document instead of the viewport
