### ISSUE TITLE
Recordset behaviour when the facet list is empty

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1296]
What should be the default behaviour?

If you go to the following link:
https://dev.facebase.org/~ashafaei/chaise/recordset/#1/isa:project@sort(id)

Since for faceting we're reusing the `filter` context name and in here the `filter` context is defined for the visible columns, the returned list of facets is empty. What should be the default behaviour of chaise in that case? just remove the faceting controls?

Should we use a different context in this case?

**Comment by jrchudy** [comment]
Issue #1299 was opened to address this issue. Closing this one.
