### ISSUE TITLE
Facet List Disappears After Clear All

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1297]
Go to the following link:

https://dev.facebase.org/~ashafaei/chaise/recordset/#1/isa:project/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JAEsIAjdafIpMEAGhAAcMUArHLAFwH1iA3HJB0IBzMBxQYuTVu26EoXAGYBrHAE8QAXQC+tUOg5k0FBFRr1pbTjwj9BIsRK5okODBDABbHEtUad9B7eWvRYABYohLhIlAAqbhiEAAQAEgB0SQBCOGL+2jpAA@sort(id)

Click on clear all, it will remove the facet column. (This is happening because of the current logic of merging permalink and annotations. And annotations in this case is empty)

**Comment by jrchudy** [comment]
This is the currently expected behavior. The facet list should show "No Filter Options" (as outlined by issue #1299) if it is emptied by the `clear all`.

**Comment by hongsudt** [comment]
@RFSH It seems like this is no longer the case, correct? If so, please close the issue.
