### ISSUE TITLE
Remove remnants of use case specific code and data

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#13]
https://github.com/informatics-isi-edu/chaise/blob/3b3a88bb770fb21124d7a4c5b0bbd1e4556fa6ea/scripts/ermrest.js#L40-L44

This block references a specific use case and data model. It should be removed and any other code that depends on it.

**Comment by robes** [comment]
is this fixed?

**Comment by howdyjessie** [comment]
I forgot; was the problem the usage of those psql* variable names or the data types listed in those lines? (And if it's the latter, how does one go about fixing that?)

**Comment by robes** [comment]
This looks fixed in master. I think Serban may have resolved it but may have missed closing this issue.

**Comment by robes** [comment]
can this be closed?
