### ISSUE TITLE
Record App Title

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1307]
The new style to push the title a.k.a., tuple display name up into the top gray section forces it to wrap a lot more than before.

1. it seems like we could give it more room before wrapping it.
2. the font is Huge. Probably bigger than necessary.
3. And bold. Also maybe not necessary.

**Comment by jrchudy** [comment]
Some more information for fixing this:
 - use different column sizes for different screen sizes (`col-xs`, `col-md`, `col-lg`)
 - content wraps around links and then flows below it

**Comment by hongsudt** [comment]
@jrchudy @RFSH Have we fixed this? If so, we should close the issue.

**Comment by jrchudy** [comment]
Yes this has been fixed. We addressed this by having the title text flow above the links. The links get pushed down to a new row when the title text is multiple rows.
