### ISSUE TITLE
Explore use of Kendo Grid widget in detail page

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#132]
We need an evaluation of the Kendo Grid widget for use in our detail pages, for the nested entities. Check out

http://demos.telerik.com/kendo-ui/grid/index

We're thinking we would hack this into a branch of Chaise and see what it can do for us.

**Comment by carlkesselman** [comment]
One specific thing we should be looking at here is the use of their virtual data connector to support paging through ERMrest.

**Comment by robes** [comment]
should reassign this to either @mikedarcy or @shinyichen
