### ISSUE TITLE
Recordset browser back button trap with faceting

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1321]
When visiting recordset w/ a bare schema:table name with faceting enabled, the location is rewritten as a new location with faceting in the URL.

This makes the page captive, as the browser back button tries to go back to the original URL and keep getting pushed back into the revised one.  The original change should have replaced the URL rather than push a new one, so back will go back to the referring page before the recordset app was entered.

**Comment by RFSH** [comment]
I changed the recordset behavior to instead of pushing to history, just replace it. The links works fine and if you navigate to other apps through links, back button will bring you to the latest version of recrodset app.

**Comment by karlcz** [comment]
I can confirm this is working as described.
