### ISSUE TITLE
Error: TypeError newTable._altForeignKey is undefined

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1324]
I see this on this record page for example:

https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/ID=ZfCza20170322A

it does not happen on every table.

**Comment by RFSH** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #508](https://github.com/informatics-isi-edu/ermrestjs/issues/508) via [**ZenHub**](https://www.zenhub.com/)
