### ISSUE TITLE
update names of two values under "Experiment Type"

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#133]
According to Paul Thomas, please rename the following:

* "Enhancer reporter data" to "Enhancer reporter gene assay"
* “Transcription factor binding site data” to “Chromatin modifier-associated region identification assay”

**Comment by bugacov** [comment]
I made these changes in dev and staging. Please review and I will roll them out to production also. 
alejandro.

**Comment by bugacov** [comment]
I now also propagated these changes to production. I'll move it to review and assign it to Cris

**Comment by crisaless** [comment]
Looks good!
