### ISSUE TITLE
Make All Buttons to use btn-inverted

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1330]
Then we need to add all the defined bootstrap btn classes for `btn-inverted`.

**Comment by jrchudy** [comment]
This has been done for all buttons in each chaise app. Added the following 2 css rules:
 - `.filter-label.label-primary.label-inverted` for our labels in the filter list
 - `.btn.btn-danger.btn-inverted` for our buttons that are red
