### ISSUE TITLE
Recordset Should Handle Faceting Errors Differently

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1332]
Recordset should treat errors that parser throws regarding invalid facets differently. We should show soft alerts. And upon catching the error it should read the unfiltered reference (to remove the facets and avoid the error).

**Comment by hongsudt** [comment]
@RFSH can you identify errors that are not terminal?  Here is a list that I can think of: 

- [ ] invalid sorting criteria

**Comment by RFSH** [comment]
Any part of error that can easily be ignored. These are what I can think of:

1. Invalid sort criteria

2. Invalid page criteria

3. Invalid facet

4. Invalid sort

This task includes changing ermrestjs to return appropriate errors too. For example for invalid sort criteria we don't have specific type of error.

There are some errors that we are throwing while we're parsing the url which still can be ignored, but I'm not sure how we can handle them. Since if error happens while parsing the url we won't have a reference to get the unfiltered version of it. For instance if the faceting blob cannot be turned into a JSON, we're throwing an error while parsing the url. But if one of the columns is invalid, we're throwing an error when we do the read. In both cases just removing the facet blob can solve the problem. We might have to change the way we're generating the error or let the chaise deal with those. Or we can ignore those cases.

**Comment by amitjha21** [comment]
As per discussion, messages will appear in Modal with OK button:

**Type** | **Message** | **Link formation**
------- | ------- | -------
Invalid sort criteria | Generated at `Ermrestjs` | Strip `sort` and `after, before` 
Invalid page criteria | Generated at `Ermrestjs` | Strip `after, before` 
Invalid facet | Generated at `Ermrestjs` | Strip `facet` and other conditions can co-exist
Invalid filter | Generated at `Ermrestjs` | Strip `filter` and other conditions can co-exist

These operations can be done at `ermrestjs` level.
For `record`  and `recordedit` apps, in case of no filters, it should go to `recordset`.

**Comment by amitjha21** [comment]
Few examples of error modal:
![image](https://user-images.githubusercontent.com/9977014/35466569-cd0b7930-02b9-11e8-8680-6802b4fe85f4.png)


![image](https://user-images.githubusercontent.com/9977014/35466588-fac9ec12-02b9-11e8-9645-766f7fef4f02.png)

**Comment by amitjha21** [comment]
This is merged into master. Assigning to @hongsudt and @RFSH  to verify and close it.
