### ISSUE TITLE
Make chaise attributes (e.g. user, date) available to Markdown 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1335]
Examples of these attributes are: 
- today: which consists of date, year, month, day.. This is so that we can use some of these properties in the Hatrac url pattern or to update some columns in the models.. 
- user info? 

We discussed about storing all these values under `chaise` object, so I could refer to this month with `{{{chaise.today.month}}}`

@karlcz @robes : please add missing detail..

**Comment by chiragsanghvi** [comment]
Date was added in ermrestjs. We are not adding user for now
