### ISSUE TITLE
enforce login in recordedit app

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1336]
* User login handling. If a user logs in pressing the login button, we need to re-fetch/introspect the catalog again and start the flow from beginning.
* If a user logs in because of a session timeout or not permitted error, we need to identify a way to handle rights for all the entities that were rendered before. For now we won't be handling this case.

I am not sure whether this should be in chaise or ermrestjs..

**Comment by chiragsanghvi** [comment]
User login handling. If a user logs in pressing the login button, we need to re-fetch/introspect the catalog again and start the flow from beginning.

This is already handled as the code refreshes the page when login button is pressed.

**Comment by hongsudt** [comment]
What about the second bullet?

**Comment by hongsudt** [comment]
We decided to leave the second bullet alone for now..
