### ISSUE TITLE
record app makes individual calls to each entry in related pure and binary assocation tables 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1337]
Here is the quick summary of @RFSH's investigation:
 
For checking 412, we used to pass the tuples object to the delete function, so the delete always needed the tuples object. For the association tables, since we're not actually deleteing from the same table, we needed to do another read to get the actual tuple that we want to delete. 

we can easily just remove that logic of getting the tuples and passing them to delete function.

**Comment by RFSH** [comment]
I pushed [a fix](https://github.com/informatics-isi-edu/chaise/commit/cc2c64aa0ece5f8b5b254ef2235489a66ecdd2cb) for this to master.
