### ISSUE TITLE
Error handling during 403 handler

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1338]
Please correct that title if I got this wrong. I don't know a better way to state the issue:

1. not logged in
2. go to a recordedit page (like this https://dev.facebase.org/data/recordedit/#1/isa:sample/id=432?invalidate=2744534207050970)
3. make a change
4. click submit
5. you should see a login dialog
6. click cancel
7. you should see an infinite spinner

**Comment by karlcz** [comment]
This seems like a bug if the recordedit page even lets you manipulate
content without being logged in.  It should have immediately detected
that you do not have enough rights and requested login before it even
presented any data-entry forms.

**Comment by hongsudt** [comment]
There is a new pull request that will prompt anonymous user for login when recordedit is loaded.. 
 @robes please review and close the issue.

**Comment by robes** [comment]
works well for me.
