### ISSUE TITLE
update document on how to run tests using saucelab

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1343]
The current protractor used for testing doesn't support the latest chrome version. 

While we are waiting for protractor to be fixed, we should fix the chrome version or run the tests using saucelab.

**Comment by chiragsanghvi** [comment]
Added documentation here https://github.com/informatics-isi-edu/chaise/wiki/E2E-tests-guide#running-tests-using-sauce-labs-locally
