### ISSUE TITLE
recordset not working on IE

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#1345]
I was using the URL:

```
https://dev.rebuildingakidney.org/chaise/recordset/#2/Immunofluorescence:Slide_Video
```

The page is not rendered. In the debug window, I can see multiple times errors like:

```
SCRIPT5007: Unable to get property 'toLowerCase' of undefined or null reference
errors.js (215,5)
SCRIPT5022: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.5.5/$rootScope/inprog?p0=%24digest
angular.js (17587,9)
```

The test was performed on `Windows 10` with `IE 11`.

**Comment by hongsudt** [comment]
@jrchudy did we fix this problem? If not, I will assign @chiragsanghvi to work on this.

**Comment by jrchudy** [comment]
@RFSH and I looked into it, but i don't think we fixed it..

**Comment by RFSH** [comment]
The problem was `Object.assign` not being defined in IE and we added a polyfill for it in ermrestjs. I used saucelabs manual testing to test the given URL in windows 10 IE11, and it's working now.
