### ISSUE TITLE
visible columns incorrectly displayed

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1346]
I ran into this situation when going to a record page -> 'view more' of a related record -> 'clear all' filters.

![image](https://user-images.githubusercontent.com/4202842/31953495-22f56e26-b898-11e7-8f3a-b1edadd2c8ab.png)

In this screenshot the columns to the right of 'iri' should not be display, and they are not displayed until clicking the 'clear all' button. Only 'term' and 'iri' should be visible. Also you'll notice that the columns to the right of 'iri' do not have a header.

I tested a different project deployment that is running a somewhat older version of chaise and it does not happen there. I suspect it is a bug since the introduction of faceting, even though faceting is not enabled on the above affected site.

@bugacov FYI

**Comment by robes** [comment]
This is probably an ermrestjs bug as I think about it more.

**Comment by RFSH** [comment]
I pushed [a fix](https://github.com/informatics-isi-edu/chaise/commit/c9cfa03bef4eabeda65f17f5184aac74fdd0189c) for this to master. The `unfiltered` function was not contextualizing reference and was returning an uncontextualized reference, which was causing this behaviour.

**Comment by robes** [comment]
thanks!
