### ISSUE TITLE
Broken numeric entry buttons in facet sidebar

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1348]
The current range widget has an upper and lower value entry widget.  This shows a number with little tiny up/down arrows.  If you click the arrow once, an `X` button overlays those arrows so you can clear the value and you cannot increment/decrement anymore.

I see this on firefox.

**Comment by jrchudy** [comment]
This has been fixed. FF changed the way this "attribute" was referenced when trying to hide the arrows using css. This is only a case when an input is `type=number`. Firefox does not have a simple way for hiding these controls for numeric inputs so we are now using css to change the input to `type=textfield` so these controls do not show up.

**Comment by jrchudy** [comment]
reassigning to @karlcz for verification.
