### ISSUE TITLE
record app should handle not-found case properly

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1352]
Currently, it throws a terminal error.. 

In this case, it should be "Record Not Found".. The detail message should tell user that the record indicated doesn't exist or no longer exist.  It should also give an option for the user to go to the recordset or the search page. 

I think there is a config that allows you to figure out whether to go to the search or recordset page. 

Is this correct, @jrchudy ?

**Comment by jrchudy** [comment]
> I think there is a config that allows you to figure out whether to go to the search or recordset page.

We have an annotation defined for this case:
https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2016-app-links

This is handled by the function, `appTagToUrl` in chaise, which is registered with `ermrestJS` at the beginning of each app. How this function is used is by contextualizing a reference into the context of the app you want to navigate to and then call `appLink` which will generate a proper url to that application.

So in this case, we should have something like:
`reference.contextualize.compact.appLink`

**Comment by jrchudy** [comment]
Another thing @hongsudt wanted me to check was what the "view more" link uses. It's actually using the appLink right now and should *NOT* be.

**Comment by amitjha21** [comment]
Here is a snap of the message box with error details. __Show Error Details__ will open a `span` with technical error details.
 
![image](https://user-images.githubusercontent.com/9977014/32304336-bcce27c4-bf2b-11e7-9b2b-873fee8d0336.png)


With details:
![image](https://user-images.githubusercontent.com/9977014/32304390-13178198-bf2c-11e7-83f2-ed611243534d.png)

**Comment by amitjha21** [comment]
Updated message box:
![image](https://user-images.githubusercontent.com/9977014/32400945-3c206bb0-c0c4-11e7-9b8d-a1c1b0933e7f.png)

**Comment by amitjha21** [comment]
This is merged. Assigning to @hongsudt for verifying and closing this issue.
