### ISSUE TITLE
New facet-mode for presence/not-null?

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1354]
We already have an entity mode versus scalar mode distinction for facets.

Some use-cases would benefit from a "presence" test where the projected facet column is tested `!column::null::`  (or `!column::null::;column!=null` for json/jsonb columns).

1. In my use cases, the column holds asset URLs and/or other stuff that is meaningless to the user. So I'd really want a presence-mode that just offers a streamlined UX for a checkbox w/o displaying any of the present values.
2. In other use cases, I think DBAs may want to offer the presence test as an additional checkbox beyond whatever choices/ranges/search UX is also offered.

I think we should try to find a single annotation feature and implementation mechanism that can cover both scenarios by mixing it with the other features.  I suspect we'd want to allow the DBA to control the labeling of the presence test checkbox so they can introduce an appropriate semantic label that complements their choice of facet name.

Perhaps this could be as simple as a new optional field in a facet object (sibling to `source` and `markdown_name` etc.) which looks something like:  `"presence":` _label_  ?

@hongsudt @ljpearlman @robes

**Comment by hongsudt** [comment]
We discussed this issue today and decided to introduce a not-null flag in the current facet syntax for dealing with not null checking. 

For UX simplicity, I am proposing to show a checkbox for `records with values` only in the compact/select (e.g. view more) mode. If the column or fk is not null, then this option should not be shown.

**Comment by RFSH** [comment]
`not_null` has been added as a new attribute to the facets. I will update the annotation and also the facet wiki page.
