### ISSUE TITLE
Filtering in facet definition?

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1355]
The `source` path syntax we are using in facet definitions was copied from the ERMrest dynamic ACL binding notation.  There are use cases for faceting which would benefit from including the filtering feature of that notation.

This would allow a DBA to introduce an extra constraint that limits the value choices presented to a user. It is analogous to the "domain filter" concept in the entity chooser UX.  The notation is already well-defined in ERMrest so we could just copy it over.

The interesting wrinkle is how it would mix with the presence test I suggested in #1354... I think it could be a useful combination but the resulting semantics of the facet would mean something like "present with matching content".  The DBA could use this to model more complex criteria as a boolean toggle for the search UX.

**Comment by hongsudt** [comment]
@RFSH let's discuss this with @karlcz tomorrow, to see whether it is relevant to the informatics-isi-edu/ermrestjs/#558

**Comment by RFSH** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #685](https://github.com/informatics-isi-edu/ermrestjs/issues/685) via [**ZenHub**](https://www.zenhub.com/)
