### ISSUE TITLE
Negation in faceting

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1356]
This needs a conversation before we can really define deliverable tasks.

Some use cases would seem on the surface to have a use for a negated facet filter. However, there are subtle differences in semantics and not a single well-defined negative filter. Users aren't always clear about these distinctions nor about communicating which one they actually need or expect.  A UX which doesn't clearly communicate the distinction could seem randomly broken even to a user who does know what they want.

Currently, our faceting sets existential conditions.  We should show a result only if "there exists a value in this facet which matches the condition".

There are several levels of negation possible for a simple facet condition like "column1 = value1":
1. There exists a facet value where "not column1 = value1"  (null not handled!)
2. There exists a facet value where "not column1 = value1 or column1 is null" (existentially quanitifed negative filter)
3. There does not exist a facet value where "column1 = value1" (universally quantified negative constraint)

The difference between 1 and 2 is due to the general null semantics in SQL, where comparisons ""X = Y" and "not X = Y" can both be false if any of the compared values is null.  This could happen for any column that is allowed to be null in the model.

The difference between 2 and 3 is apparent when a facet has a many-to-one relationship to the result entity. If there are several _children_ of a result, there may exist a child where "column1 = value1" and another child where "not column1 = value1". An existential test of either positive or negative choice will both match the result row. Only a universally quantified negative test would exclude the result row. This cannot be expressed with current ERMrest apis.

Furthermore, the impact of negation on a facet with multiple choices, ranges, or patterns is even more complex. A user could conceivably want to negate individual choices within the disjunction or negate the whole disjunction of choices.  These variants still have to consider the null handling and existential vs universal quantification mentioned above, and some cannot be implemented today with ERMrest.

Finally, a user could conceivably want to negate the entire conjunction of facet constraints. This cannot be expressed with ERMrest since we do not provide set subtraction.

**Comment by jrchudy** [comment]
Since we haven't had any discussion around this issue in here, in our stand up meetings or in slack, I'm going to close this issue and add it to the wishlist.
