### ISSUE TITLE
Reduce the number of assets (js, css, etc)

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1361]
If possible, to reduce the amount of download traffic required to bootstrap our apps.

**Comment by hongsudt** [comment]
From #1378, it seems like the number of assets is not the source of the performance issue. We will revisit this after we look into #1378.

**Comment by hongsudt** [comment]
#627 is relevant to this issue.

**Comment by jrchudy** [comment]
Since changing to SASS for the chaise styles, only 1 CSS file is being downloaded for all chaise apps.
