### ISSUE TITLE
ACL Handling

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1366]
We should do this for all the apps, it's currently done for recordedit.

**Comment by chiragsanghvi** [comment]
After discussion with @hongsudt and @karl we need to address following use cases.

1. **When a user visits a page as an anonymous user and logs in:**
   We should identify this situation by checking whether a session was present previously when the 
    user logged in. If not then reload the page.

2. **When a user visits a page and after some time, the user session has timed out and logs in as the same user:**
   In this case we should identify the change in user comparing the attributes of previously logged in user with current logged in user. If it same then we don't reload the page. As an enhancement we should fetch the schema again, and compare it with the previously fetched one for ACL changes. If any change is detected then reload the page else leave the page intact.

3. **When a user visits a page and after some time, the user session has timed out and logs in as a different user:**
   In this case we should identify the change in user by comparing id of the previously logged in user with current logged in user. If it same then we don't reload the page.

**Comment by RFSH** [comment]
@chiragsanghvi @hongsudt Should we create separate issues for these three cases or change the title? #1369 has fixed the first scenario, so if we want to create separate issues for other cases we should just close this issue.

**Comment by chiragsanghvi** [comment]
@RFSH  I think we should keep it in the same issue, so that we don't forget the context in future.

**Comment by hongsudt** [comment]
This issue mentions a list of cases where we need to determine what ACL to check and how Chaise app should response.

* Record app:
  * main entity columns
    * if not selectable but enumerable: Hide??   
  * related table
    * if not selectable but enumerable: ???
* Navbar
  * Hiding/showing links in navbar according to policy.

Please add any more cases to this issue if you find

**Comment by hongsudt** [comment]
I am closing #1334. We might want to check that issue to make sure everything is complete.
