### ISSUE TITLE
Asset URL Validation Missing

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1368]
We used to validate urls before creating upload jobs to show a better error message to users. For that we have a `areFilesValid` function defined in upload.js which was used in recordedit. But in the [Batch add association PR](https://github.com/informatics-isi-edu/chaise/pull/1251) that piece of code has accidentally been removed.

We should take that piece of code back and take another look at the PR to make sure that we haven't missed anything else.

**Comment by hongsudt** [comment]
@RFSH should I assign this to @amitjha21 ?

**Comment by RFSH** [comment]
I think @chiragsanghvi should review it first.
