### ISSUE TITLE
Value picker throws error on page followed by sort

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1370]
Go to

1. go to https://dev.facebase.org/data/recordset/#1/isa:clinical_assay
2. expand Syndromes
3. click "Show More"
4. in the picker, click next page ">"
5. then sort by the Syndrome column

Error:
> The request is malformed. The "after" page key of length 2 does not match the "sort" key of length 1.

Offending request:
`https://dev.facebase.org/ermrest/catalog/1/attributegroup/M:=isa:clinical_assay/value:=syndrome;count:=cnt(*)@sort(value)@after(34,Moebius syndrome)?limit=26&cid=recordset`

**Comment by RFSH** [comment]
This was an ermrestjs bug. In case of AttributeGroupReference (scalar picker), I wasn't removing the page settings after sorting. 
[The related commit in ermrestjs](https://github.com/informatics-isi-edu/ermrestjs/commit/f696c006c7bcc9d0fab145a1d25f24da21a11703).

**Comment by robes** [comment]
seems to work for me on dev facebase
