### ISSUE TITLE
text search on the facets control is not working for the columns having special characters

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#1371]
1. Go to https://cirm-dev.isrd.isi.edu/chaise/recordset/#1/Microscopy:Scan
2. Expand the  `Experiment ID` facet.
3. Enter a text in the search box (for example `JL`).
4. You get the error:
```
409 Conflict
The request conflicts with the state of the server. Requested column Experiment%20ID does not exist in table Scan.
```

The space from the `Experiment ID` is double URL encoded:
```
https://cirm-dev.isrd.isi.edu/ermrest/catalog/1/attributegroup/M:=Microscopy:Scan/Experiment%2520ID::ciregexp::JL/value:=Experiment%20ID;count:=cnt(*)@sort(count::desc::,value)
```

**Comment by RFSH** [comment]
As you mentioned in the description we were applying the URL encoding twice. I fixed ermrestjs and pushed it to master. Please let me know if it's still an issue or not.

**Comment by svoinea** [comment]
The problem is fixed now.
