### ISSUE TITLE
Refactor the UX for adding related entities

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1375]
I think we should refactor the UX for adding related entities.
1. Keep the "Add" link in the related entity section header, but
2. Do not display all the empty nested tables. Its not necessary.
3. Instead, at the top of the record page, in the menu section, add a menu for "Add related record"
    - For each related record, have a menu item
    - The user clicks on the menu item and is taken to the recordedit for that page
    - It should behave just like the current "Add" link does.

**Comment by hongsudt** [comment]
@robes now that we have ToC, is this issue still relevant? IF not, can I close it?

**Comment by hongsudt** [comment]
I think the TOC should alleviate this problem. I am closing this issue for now.
