### ISSUE TITLE
Performance in chaise

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1378]
Currently the apps are taking quite some time to load even on simple models. Linking the appropriate [division issue](https://github.com/informatics-isi-edu/division/issues/134).

It was mentioned that there was a very simple model in synapse (very few tables for introspection and assets for bootstrapping) to test this performance against, but I don't see it in the relevant issue.

**Comment by karlcz** [comment]
Sorry I didn't see this before.  The entire catalog/1 for synapse is a very simple model compared to many of the other deployments.

A table like https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Synapse:Person  doesn't have any embedded images or iframes to slow it down in compact context. 

The dashboard https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Classifier%20Status doesn't have any complex relationships at all.

**Comment by jrchudy** [comment]
It's been some time since this issue was opened. We have made some significant changes to record and recordset to introduce flow control so the app will bootstrap and load the main content faster.

Closing this issue.
