### ISSUE TITLE
Showing `nothing` in a term picker (to indicate NULL values?)

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1379]
![image](https://user-images.githubusercontent.com/4202842/32962445-4cabcf20-cb81-11e7-9619-a77639d6f663.png)

I'm assuming this means that this attribute is NULL. We really need to have some placeholder text. It makes no sense to show users just empty whitespace and think they will interpret that as a null.

So call it "--none--" or "--no entry--" or whatever.

**Comment by hongsudt** [comment]
@jrchudy @RFSH didn't we take care of this already? ?

**Comment by RFSH** [comment]
No. We just changed it in the faceting. We cannot change the display of values in here without effecting other apps. We should discuss about this.

**Comment by jrchudy** [comment]
To add what @hongsudt and I discussed last week:
Maybe we want to do this only in the case of sub contexts to the `compact` context. It doesn't make sense to apply this logic in `compact` (main recordset table) and we may not want to apply it for all `compact/brief` tables. But it may make sense to apply this logic in the case of `compact/select` where the user is going to want to know exactly what row and corresponding values they are attaching to an entity.

**Comment by RFSH** [comment]
All the faceting modal, foreignkey modal, and association modal pickers are using `compact/select`. Since we want this only for faceting in scalar mode, we cannot use context. For now I just added a new variable in the directive to use the logic of showing appropriate values for null/empty.

**Comment by RFSH** [comment]
This is fixed, We're showing the same "Empty" and "No Value" for faceting scalar pickers now.

**Comment by hongsudt** [comment]
@robes please review and close.
