### ISSUE TITLE
prototype related records section that shows a list of related tables 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1382]
* We should reuse the components that we have for recordset to create 2 independent panes on the record app---one for the table of content style that lists related tables, and one that shows the main content. 
* When I click on each related record, it should direct me to the relevant related record table in the main pane. It should automatically expand that table. 
* The TOC pane should be adjustable and collapsable. There should be a GUI control or a parameter to collapse TOC. 
* We might want to consider moving TOC to the right to visually distinguish the record app from recordset.

**Comment by hongsudt** [comment]
@robes @carlkesselman @ljpearlman I think this prototype should help with many of the UX issue in the case of multiple related tables.

**Comment by amitjha21** [comment]
I have added a demo link [here](https://dev.isrd.isi.edu/~amit/toc/record/#1/isa:dataset/id=269). Let me know about any changes.

**Comment by robes** [comment]
Looks promising. Couple thoughts:
- is the TOC heading using a standard font/size? It looks a little different but I can't tell exactly.
- the expand/collapse icon introduces a whitespace column/gap. It would be good to tighten that up.
- do we want the nested tables to be collapsed now by default? That said (or asked), I do like how when you follow a TOC link it not only scrolls to the position (as expected) but also opens the nested table.

**Comment by jrchudy** [comment]
Maybe there should be a "Top of Record" link?  (Top of Page?) Seems useful now that some users may navigate around the page quickly using the sidebar instead of scrolling.

**Comment by amitjha21** [comment]
The heading is using inherited font, however, size is different (with `h2` tag) to give it a header feel.
Default behavior for accordion panels are based on a `chaise.config` entry named `maxRelatedTablesOpen`. If a page has more related table entries than this value then all panels will be closed by default. For the demo, the `maxRelatedTablesOpen` is set at 15.

**Comment by amitjha21** [comment]
This has been merged into the `master`. Assigning to @hongsudt to verify and close it.
