### ISSUE TITLE
Sort icons not showing on IE11

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1391]
Reported by a user:

> ...wasn’t able to sort columns on a page like https://www.facebase.org/data/record/#1/isa:dataset/id=14096 when using IE11 but could when using Chrome.  I think I’ve figured out that the problem isn’t an inability to sort but rather that the sorting arrows don’t show up in IE11.  You can still sort by placing the cursor where the arrows should be.

**Comment by jrchudy** [comment]
From a relevant stackoverflow thread:
> It might be that their browser is set to block untrusted fonts, which I think may be a default for IE.

**Comment by jrchudy** [comment]
Another relevant page regarding font-awesome fonts not showing:
https://stackoverflow.com/questions/31291414/font-awesome-icon-is-not-appearing-in-ie-11-but-showing-in-other-browsers

**Comment by jrchudy** [comment]
When I start a manual testing session in SauceLabs, (which allows you to emulate any OS and browser) I see the sort icons in Win10 with IE11. 

@robes is this issue related to #1392 in the way that the user is accessing chaise (on a mac connecting through Windows Terminal Server)?

**Comment by robes** [comment]
@jrchudy No. This issue is independent of #1392.

Are the sort icons coming from a different set of icons than the rest? How does one 'trust' or not icons on IE 11?

**Comment by robes** [comment]
The user is on Windows 8.1 with IE 11.

**Comment by robes** [comment]
Here's a (totally random link returned by Google) link on checking if fonts download is enabled.

https://support.xmatters.com/hc/en-us/articles/207108186-Missing-icons-when-using-Internet-Explorer-11

**Comment by RFSH** [comment]
The sort icon is using the same font that other bootstrap icons (glyphicon) that we have (for example the view or edit icon) are using. So if it was a font problem, all the other icons should have the same problem.

**Comment by jrchudy** [comment]
That seems to be the general case but I found another related comment from a thread on stackoverflow:
https://stackoverflow.com/a/36016136

They mention these 2 headers:
`Pragma: no-cache`
`Cache-Control no-store`

> If the server is sending the header `Pragma: no-cache` and/or `Cache-Control no-store`, this will cause IE to fail to render the glyphs.


When looking at the requests for the glyphicons in the network panel, I see both of those headers defined.
```
GET /~jchudy/chaise/styles/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1
Host: dev.isrd.isi.edu
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Origin: https://dev.isrd.isi.edu
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Accept: */*
Referer: https://dev.isrd.isi.edu/~jchudy/chaise/styles/vendor/bootstrap.min.css?v=e3e8b38fed66211f84a6d5ddb8e0f876
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _ga=GA1.2.1821192269.1469123521; webauthn_track=79eb7ae2.551cbaf03163f; oauth2_auth_nonce=1510780286.2cBbDzTqZ8pgmxZ0VAqvApQf2pH6vRKarlgOevBD.; webauthn=qhkyKjZcgZiOMdEPXrDYUtuf
```

**Comment by hongsudt** [comment]
@Divyata-Singh Any clue?

**Comment by Divyata-Singh** [comment]
The sort icons work properly on both IE11 and edge on Windows 10.

**Comment by jrchudy** [comment]
I can verify this seems to be working as expected for IE 11 on windows 10. We changed the way icons show for sorting when we merged the mitigation PR in mid October. Closing this issue.
