### ISSUE TITLE
Presentation of "asset" columns needs to handle null filename column

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1393]
@karlcz commented on [Mon Nov 06 2017](https://github.com/informatics-isi-edu/ermrest/issues/176)

If you have a URL column annotated with the "asset" annotation and providing a mapping for the `filename_column` field, the presentation does not handle a case where a row has a non-NULL URL but a NULL filename column value.  No download link is offered.

This could easily happen if data were uploaded by a different client rather than the Chaise-embedded asset upload widget. The presentation should handle this case, perhaps by substituting the basename of the URL.

**Comment by karlcz** [comment]
I am not sure if this was moved incorrectly or if I originally created it in the wrong repo... but I just found it in the ermrest repo and moved it to Chaise since it is a presentation issue.  I am not sure how this feature is split between Chaise and ermrestjs.

**Comment by hongsudt** [comment]
@RFSH we have taken care of this issue, right? If so, can you assign @karlcz to review this, so we can close the issue.

**Comment by RFSH** [comment]
I thought I had fixed this before, but that wasn't the case. I just made the change and pushed it to master.

**Comment by karlcz** [comment]
I confirmed that a downloadable asset can now be configured w/o an upload url template being available.
