### ISSUE TITLE
wierd error flow

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1397]
On this page, https://dev.rebuildingakidney.org/chaise/record/#2/RNASeq:Sample/RID=13-FMFG
- click add file
- add an arbitrary file.. This will throw a terminal error since I have a bad trigger.  In the past, this is a soft error that allows me to go back and makes change to my recordedit.. 

Anyway, when I click ok, it directed me to another page which then throw another terimal error.. And when I click cancel, nothing happens. 

Is this expected?

**Comment by jrchudy** [comment]
Error in Chrome:
```
Maximum call stack size exceeded
https://dev.rebuildingakidney.org/ermrestjs/ermrest.js?v=be98d7755b86f8107acf7a6d6e423e09:3909:49
```

Error in FF:
```
too much recursion
https://dev.rebuildingakidney.org/ermrestjs/ermrest.js?v=be98d7755b86f8107acf7a6d6e423e09:3913:21
```

This is happening at [this line](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/utilities.js#L352-L369) in the code. Seems like the recursive function to replace `.` with `_` is recursing too much for the browser.

Note: I like FF is error message here, straight to the point.

**Comment by RFSH** [comment]
This is happening for the reason that @jrchudy mentioned. In the file upload we're attaching the whole hatrac object to the values that will be used for template (which is wrong), and in that object we have recursive references which is causing this error.

The assumption for the `renderTemplate` was that the given object will be a very simple JSON object, but in this case it's not and it's  javascript object. We should just remove the hatrac object in hatrac.js before passing in to the template functions.

(We should move this issue to ermerstjs)

**Comment by hongsudt** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #563](https://github.com/informatics-isi-edu/ermrestjs/issues/563) via [**ZenHub**](https://www.zenhub.com/)
