### ISSUE TITLE
recordedit is displaying the RID value for a foreign key

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#1403]
On `cirm-dev`, go to the page https://cirm-dev.isrd.isi.edu/chaise/recordedit/#1/Microscopy:Specimen

Select a value for the `Submitted By` field. The `RID` value will be displayed.

The `Specimen` table has defined:
```
"Specimen_Initials_fkey" FOREIGN KEY ("Initials") REFERENCES "User"("Full Name")
```
and the `User` table has defined:
```
    "User_pkey" PRIMARY KEY, btree ("Initials")
    "User_Full Name_key" UNIQUE CONSTRAINT, btree ("Full Name")
    "User_RID_key" UNIQUE CONSTRAINT, btree ("RID")
```
The annotations for the `Specimen:Initials` column are:
```
{
  "tag:misd.isi.edu,2015:display": {
    "name": "Submitted By"
  }, 
  "facetOrder": 1, 
  "tag:isrd.isi.edu,2016:immutable": null, 
  "description": {
    "display": "Submitted By"
  }
}
```

**Comment by RFSH** [comment]
This is working as expected. We changed the row-name heuristics to use "RID" instead of the shortest key. If you want to change the displayed value (row-name), you need to define your own row-name for the table.
To do so, you need to add the following annotation to your table:
```
"tag:isrd.isi.edu,2016:table-display": {
  "row_name": {
    "row_markdown_pattern": "DEFINE YOUR NAME HERE"
  }
}
```

**Comment by hongsudt** [comment]
@svoinea we decided to remove RID from the row_name heuristics and let's it kicks in later in the shortest key..

**Comment by RFSH** [comment]
@hongsudt Just changing the row_name heuristics in this case won't solve the problem. The shortestkey is still is going to be RID (since we changed the shortest key heuristics to use RID when it's available). Unless we change the shortestkey logic back to the original too.

**Comment by hongsudt** [comment]
@RFSH ping @svoinea to review this issue after your are done with RID.

**Comment by RFSH** [comment]
@hongsudt @svoinea The change has been merged with master.

**Comment by svoinea** [comment]
@RFSH I have defined for the `User` table, the annotation:
```
{
	"tag:isrd.isi.edu,2016:table-display": {
		"row_name": {
			"row_markdown_pattern": "Full Name"
		}
	}
}
```

On selecting an user, the `Initials` are displayed now, ignoring thus the value `Full Name` specified in the `row_markdown_pattern`.

Does that happen because the `UNIQUE CONSTRAINT ("Full Name")` has not also the `NOT NULL` constraint?

**Comment by RFSH** [comment]
I don't have access to that table so I'm not sure what exactly is happening. But if you have defined your `row_markdown_pattern`, that will be used unless the value that you defined results in an empty string.

Based on the behavior that you explained your `row_markdown_pattern` is either defined on a wrong table or the defined value is not resulting in a valid string (The annotation that you posted should be `"{{{Full Name}}}"`), because it's going to the heuristic of choosing the shortest key for display instead of using the defined `row_name`
