### ISSUE TITLE
recordedit is displaying the default value of the RID column

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#1404]
On `cirm-dev`, go to the https://cirm-dev.isrd.isi.edu/chaise/recordedit/#1/Microscopy:Collection page.

For the `RID` column the `_ermrest.urlb32_encode(nextval('_ermrest.rid_seq'::regclass))` value is displayed.

I think it should be displayed `Automatically generated` like for the other `ermrest` system columns.

**Comment by RFSH** [comment]
This is related to [ermrestjs#562](https://github.com/informatics-isi-edu/ermrestjs/issues/562) issue.

**Comment by svoinea** [comment]
Closing as it is a duplicate.
