### ISSUE TITLE
Record Not Found clicking OK goes to the wrong place

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1405]
"Record Not Found" error, upon clicking OK, it is supposed to go to recordset, but instead it goes to the home page. 

https://www.rebuildingakidney.org/chaise/recordedit/#2/RNASeq:Sample_Settings/RID=13-FMFM?invalidate=6387594911901047

Do we have a test case for this?

**Comment by amitjha21** [comment]
This has been merged. Assigning to @hongsudt  to verify and close it.
