### ISSUE TITLE
Add Pure And Binary Testcases for Inline

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1409]
We have a test case for inline display of a related entity, but we don't have any test cases for inline pure and binary association related entities. We should add a test case for this.

Edited body:

### [Schema document](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/data_setup/schema/product.json) changes:
 - [x] a new table needs to be added to the product schema document to act as an association between `Accommodation` and `File`
   - [This](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/data_setup/schema/recordset/faceting.json#L224-L284) is a good example of how an association table is defined. A pure and binary association table must have 2 foreign keys, and a key that is created from those two foreign key columns. This concept is essentially used to describe a many to many relationship between two tables.
   - In the following I wrote the table definition which you can directly use (Please don't copy the table definition blindly and try to familiarize yourself with the concept of association table). The  product schema also already has an association table called `accomodation_image`, this table is going to be very similar to that (minus the extra attributes).
    - data needs to be added [here](https://github.com/informatics-isi-edu/chaise/tree/master/test/e2e/data_setup/data/product) for that new association table. 
    - Note: The json document filename has to have the same name as the table in the schema
- [x] modify the [visible columns list](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/data_setup/schema/record/product.json#L363-L399), so that the new table shows up as an inline related table
     - You can take a look at the annotation document for details about how to define a pseduo-column. But based on the given schema you need to add this to the list: 
       ```json
         {
            "source": [ 
              {"inbound": ["product-record", "fk_accom_image_assoc_1"]},
              {"outbound": ["product-record", "fk_accom_image_assoc_2"]},
              "id"
           ]
         }
       ```

Schema document:
```json
"accommodation_image_assoc": {
  "comment": "Association Table between accomodatiion and image",
  "kind": "table",
  "table_name": "accommodation_image_assoc",
  "schema_name": "product-record",
  "keys": [{
	  "unique_columns": [
		"image_id",
		"accommodation_id"
	  ]
  }],
  "entityCount": 0,
  "foreign_keys": [
	{
	  "names" : [["product-record", "fk_accom_image_assoc_1"]],
	  "foreign_key_columns": [
		{
		  "table_name": "accommodation_image_assoc",
		  "schema_name": "product-record",
		  "column_name": "accommodation_id"
		}
	  ],
	  "referenced_columns": [
		{
		  "table_name": "accommodation",
		  "schema_name": "product-record",
		  "column_name": "id"
		}
	  ]
	},
	{
	  "names" : [["product-record", "fk_accom_image_assoc_2"]],
	  "foreign_key_columns": [
		{
		  "table_name": "accommodation_image_assoc",
		  "schema_name": "product-record",
		  "column_name": "image_id"
		}
	  ],
	  "referenced_columns": [
		{
		  "table_name": "file",
		  "schema_name": "product-record",
		  "column_name": "id"
		}
	  ]
	}
  ],
  "column_definitions": [
	{
	  "name": "accommodation_id",
	  "nullok": false,
	  "type": {
		"typename": "int4"
	  }
	},
	{
	  "name": "image_id",
	  "nullok": false,
	  "type": {
		"typename": "int4"
	  }
	}
  ],
  "annotations": {
	"comment": [
	  "image"
	],
	"description": {
	  "display": "Accommodation Images"
	},
	"tag:isrd.isi.edu,2016:visible-columns": {
	  "*": [["product-record", "fk_accom_image_assoc_1"], ["product-record", "fk_accom_image_assoc_2"]]
	}
  }
},
```

### [Spec](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/all-features-confirmation/record/presentation.spec.js) changes:
- [x] update the [columns](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/all-features-confirmation/record/presentation.spec.js#L34-L56) expected data to include the new column added to the visible columns list
- [x] add a new object to the [inline columns](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/all-features-confirmation/record/presentation.spec.js#L77-L118) expected data
    - doing so should automatically test the related table in [this loop](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/utils/record-helpers.js#L408-L414) and therefore [this function]()
    - these properties should be defined like this:
        ```
         canEdit: true,
         canCreate: true,
         isInline: true,
         isTableMode: true
         ```

**Comment by amitjha21** [comment]
This has been merged into master. Assigning to @hongsudt, @RFSH  to verify and close it.

**Comment by RFSH** [comment]
I found the following issue with the PR that is merged:

1. You're using browser.sleep which seems unnecesary.

2. I don't think the inbound table that you have added is actually pure and binary association. It's just a normal inbound related table.

3. You're not testing specific features of pure and binary association (clicking on add should open modal instead of going to recordedit, unlink button should be available instead of delete, etc.). 

4. Delete unnecessary comments.

Please fix these issues in another PR. I am going to change the pipeline of this issue to "this week".
