### ISSUE TITLE
Remove model assumptions in record page

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#141]
Various model assumptions are noted in code comments. We need to go through these and make it neutral to the model, base decision on introspection.

**Comment by robes** [comment]
I think we mainly noticed these model assumptions when it came to keys and how tables were joined together. For instance, assumptions about the name of a key being 'id' or of a foreign key being 'othertable_id'. If I remember correctly.

And then the other thing that Alejandro has recently noticed is that it doesn't support composite keys in the foreign key relationships.

TODOs:
- [ ] use the schema definition to determine keys and foreign key relationships
- [ ] don't forget composite keys used in FKRs

**Comment by bennettl** [comment]
Do you have examples of entities that have composite keys with the database on my vm? If not, would it be possible to upload them?

**Comment by robes** [comment]
Another sub-task for this issue:
- [ ] introspect the entire schemata rather than a single named schema

See:
https://github.com/informatics-isi-edu/chaise/blob/c36d938c67945f2c17d359215293dab5eaa2e94a/record/assets/javascripts/app.js#L870
