### ISSUE TITLE
create catagorical heatmap viz module

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1413]
Create a reusable catagorical heatmap visualization module that can be embeded in a static site or to be displayed in the context of recordset..

This plot assumes that the x and y are sortable, and the z value is a array of terms. For each cell, render the appropriate color(s) based on the z value. Take a look at the facebase page for an example. The app should be responsive. 

Assumptions:
* The possible options of z should be small.. Let's assume that there are no more than 5 terms. We should handle `others` to deal with arbitrary number of z in the future. 
* A configrable parameters
  - Catalog number, schema name, table name, and a list of facets. We can assume that the URI for recordset with faceting will be used.
  - x, y, and z columns. 

Solution sketch
```{javascript}
- get a list of top 25 for x
- get a list of top 25 for y
- get a list of top 5 for z 
- get a list of tuples group by x and y
- plot(plotObject)
```

**Comment by hongsudt** [comment]
relevant to #1108

**Comment by RFSH** [comment]
[This is the PR](https://github.com/informatics-isi-edu/chaise/pull/1104) that we removed matrix from the chaise repository. You should be able to use the same logic and change it based on new app patterns.  [This](https://www.facebase.org/mousematrix/) is the current static implementation of it in facebase. Although the matrix app that I have created is a bit different from this static site. I changed the code a bit to make it easier for myself to express it in angularjs.

*I am going to update this comment with more details*

**Comment by hongsudt** [comment]
Issue moved to [informatics-isi-edu/deriva-webapps #3](https://github.com/informatics-isi-edu/deriva-webapps/issues/3) via [**ZenHub**](https://www.zenhub.com/)
