### ISSUE TITLE
UX: consider moving the "View more" link to bottom of nested tables

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1417]
It might be more intuitive to put the "View more" link at the _bottom_ of the nested table. That way as a user, when you scroll down the record page while looking at a nested table, you reach the bottom, you have a clear indication that there is a possibility for more results. We could even make a false row with the "View more". Currently, when you scroll to the bottom (or past) any nested table you have no indicator that there is an action you could take to see more results, and you have to scroll back up the page to get to the nested table's view more link.

Here's a page that I think demonstrates the issue.

https://www.facebase.org/data/record/#1/isa:project/id=152

**Comment by hongsudt** [comment]
I actually disagree on this suggestion since the table length is not fixed and therefore users might not easily see the link. I saw many GUDMAP users take advantage of this easy to spot link, but I am open to suggestions..  @ljpearlman @karlcz @mikedarcy @bugacov what's your opinion?

**Comment by hongsudt** [comment]
This issue will be addressed as part of the new UI layout. So I am closing this issue now.
