### ISSUE TITLE
Add job name to test suits to identify and investigate test failures on Sauce portal.

### ISSUE THREAD

**Issue by amitjha21** [informatics-isi-edu/chaise#1419]
To easily identify and check which module has failed in Sauce we should add `name` in `capabilities`.
The default name is `Unnamed job` which is not quite helpful when trying to find out failures.

We can add something in this format to each `conf` file.:
**_TestSuiteString_timestamp_**

 Here is the difference : 

![image](https://user-images.githubusercontent.com/9977014/34634577-258d140a-f23a-11e7-8f76-0e2d5f74e0fe.png)

**Comment by jrchudy** [comment]
This is no longer relevant. Sauce now uses the filename as the job name if it is left undefined.
![image](https://user-images.githubusercontent.com/2932600/40451413-64c7b754-5e93-11e8-831a-736d84fdd9a3.png)
