### ISSUE TITLE
image gallery not floating correctly anymore

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#142]
For example, when I go to this record page:

https://www.facebase.org/data/record/#1/legacy:dataset/id=1585

The thumbnails are below the full size image even though they should float left. On my desktop, there are also some empty scrollbars showing there, though not on my laptop (same browser). FYI, screenshot is from my laptop so you won't see the empty scrollbars there.

There should be a width set on floated elements - but if it never had a width assigned and was working correctly before, I don't know why it broke.

<img width="1280" alt="image-gallery-bug" src="https://cloud.githubusercontent.com/assets/8965132/10530963/0193ccb0-7361-11e5-894d-e29439a9dff0.png">

**Comment by crisaless** [comment]
@robes and @carlkesselman  - I should have also mentioned that this is a blocker for https://github.com/informatics-isi-edu/facebase-project/issues/9 (howto video) since I want to feature the image gallery but don't want to show it as broken.

**Comment by robes** [comment]
@crisaless  do you know whether this is a regression in chaise (standalone) or only when embedded in the facebase site?

**Comment by crisaless** [comment]
Yes, I see it on serban's instance. Here's an example - can you verify that you're seeing it to?:
https://serban.facebase.org/chaise/record/#1/legacy:dataset/id=1585

**Comment by robes** [comment]
Yes, seems to be working for me on Safari. -- rob


________________________________

**Comment by crisaless** [comment]
on my laptop, the float doesn't work.

on my desktop, the float works today (hm, didn't yesterday) but the empty scrollbars still show. something funky's going on.

**Comment by karlcz** [comment]
On Firefox viewing:

https://serban.facebase.org/chaise/record/#1/legacy:dataset/id=1585

I see a gallery view with a responsive behavior for the main image
pane and the thumbnail pane.

The size of the main image seems to vary with browser window
width. The main image is about 50% of the central page div?

- With browser ~1000px wide, the thumbnails flow below and occupy nearly 100% of the central div.
- With browser ~2100px wide, the thumbnails reflow to the right of the main image and each occupies around 50% of the central div.
- With rbowser ~3800px wide, the main image is about 50% of the central div and the thumbnails are about 25% while 25% is whitespace.

**Comment by crisaless** [comment]
I checked again on my retina display desktop and get the thumbnails floating below the image even when my browser is 100% wide - which makes the content container 1170px.

I think it's because both the big image and thumbnail boxes are floated but there's only a width declared on the big image (50%). if I add a width of 50% to the thumbnail box, it floats up correctly. The thumbnails do wrap within that area even with overflow: scroll. Since that is showing the scrollbars strangely I would do away with the overflow rule altogether.

Here's a screen shot of before and after (making the edits with Chrome Dev tools in the browser):

*Before:*

![image-gallery-before 1](https://cloud.githubusercontent.com/assets/8965132/10949765/c93f41be-82f1-11e5-9599-ad6f4394d519.png)

*After:*
![image-gallery-after](https://cloud.githubusercontent.com/assets/8965132/10949777/dd3da390-82f1-11e5-881d-bf4c3e84f474.png)

**Comment by robes** [comment]
@crisaless : this seems to be facebase stylesheet specific.
![image-gallery](https://cloud.githubusercontent.com/assets/4202842/11280307/44f419e2-8eaa-11e5-8487-4c3c1b3c6afc.jpg)

**Comment by crisaless** [comment]
It's still happening on my laptop so I still thinks it's on the chaise side. It's a very easy fix though. And on my desktop, it floats but these weird scrollbars appear. Attached is how the page looks on my laptop. 
<img width="600" alt="image-gallery-chaise-laptop" src="https://cloud.githubusercontent.com/assets/8965132/11281069/1bf07e1c-8eb6-11e5-9d64-4a172972e6a1.png">

**Comment by robes** [comment]
so maybe this is being "responsive"?


________________________________

**Comment by crisaless** [comment]
except there's plenty of whitespace to the right so it looks weird to me. At the very least, those scrollbars shouldn't appear on the wider screen. Here's how the same record from dev.misd.isi.edu looks on my desktop.
![image-gallery-chaise-desktop](https://cloud.githubusercontent.com/assets/8965132/11281379/93371bce-8eb7-11e5-8c47-33e7eb9c04de.png)

**Comment by crisaless** [comment]
come to think of it, it's not very responsive as it is. The main page will be 50% of its column but when you narrow the page it gets much smaller than it should. I tested using bootstrap columns here and it behaves much better - image stays full width while the thumbnails wrap below it and are centered. I'd like to test that on dev

**Comment by crisaless** [comment]
there doesn't seem to be much interest in fixing on the chaise side - but I'm going to add a couple of custom css rules on the facebase side. Then I can at least finally get that video done (which sparked this issue in the first place : )

**Comment by robes** [comment]
@hongsudt we should prioritize this

**Comment by hongsudt** [comment]
@robes who should work on this?

**Comment by robes** [comment]
anyone could. i don't think it requires deep knowledge of record page so any front end dev could handle it.

**Comment by hongsudt** [comment]
@cris is this still an issue?

**Comment by crisaless** [comment]
yes, still an issue

**Comment by crisaless** [comment]
I just committed some minor CSS tweaks to fix this:

https://github.com/informatics-isi-edu/chaise/commit/ad049fd291d1d5716978deffbfe2ddee77a8e80e

**Comment by crisaless** [comment]
fix is up and working on latest FF, Chrome and Safari. still have to test on IE.

**Comment by crisaless** [comment]
this is leading me down a rabbit hole of finding the best way to test for IE. right now it actually looks like the latest records page doesn't even load for IE9 or IE11 (the two VMs I've set up so far). Investigating more - but this may turn into a whole effort to make fixes for IE

**Comment by crisaless** [comment]
Yup, big bug in chaise on IE11 where records page doesn't appear at all. https://github.com/informatics-isi-edu/chaise/issues/490

We recently decided to start supporting IE - so I'm keeping this open until the bug is fixed and I can see if the floating is working correctly.

**Comment by crisaless** [comment]
I noticed the issue for fixing IE records page has been relegated to Backlog. @hongsudt - do you want to keep this in review until it can be confirmed to work for IE? As it is, it works on other browsers.

**Comment by hongsudt** [comment]
what's the traffic ratio coming from IE9 and 11 browsers? Can we tell
people to facebase users to use other browsers?

**Comment by hongsudt** [comment]
@crisaless @chiragsanghvi just fixed this issue (missing endWith function on IE). Can you review?

**Comment by crisaless** [comment]
Confirmed that on dev.isrd.isi.edu/, the records page and image gallery float display correctly for IE11/Windows7, IE11/Win8.1, IE10/Win7, IE9/Win7

Just an FYI - it's broken on IE8/Win7 but so is the rest of chaise. We're supporting IE9 and higher, though so I don't think we need to worry about it.
