### ISSUE TITLE
Showing "No Value" for all rows of a table when table is a 'table alternate' view

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1420]
https://dev.facebase.org/data/record/#1/isa:dataset/RID=14290

See the "File" nested table at the end of the page, as shown here in the screen shot.

![image](https://user-images.githubusercontent.com/4202842/34750819-12fa129e-f55e-11e7-801f-13c2813d9191.png)

The ERMrest query for that nested table _does_ return tuples. You can see it in the developer tools network response. It can also be validated with cURL.

`curl 'https://dev.facebase.org/ermrest/catalog/1/attributegroup/M:=isa:file_compact/left(id)=(isa:file:id)/left(dataset)=(isa:dataset:accession)/accession=FB00000879/$M/F1:=left(id)=(isa:file:id)/$M/id;M:=array(M:*),F1:=array(F1:*)@sort(id)?limit=26'`

The only relevant changes are really the software stack (ie, chaise, ermrestjs, ermest) to the best of our knowledge. We have been working on ACLs, but that seems to be ruled out as a culprit here since ERMrest does return the tuples. There may have been some work on annotations within the catalog but not related to this table to our knowledge.

**Comment by RFSH** [comment]
Related to [ermrestjs#583](https://github.com/informatics-isi-edu/ermrestjs/issues/583).

There was a bug in `tuple.uniqueId` logic which was causing it to return null in case of alternative tables. I recently changed the ellipses directive to show just `No Value` if the uniqueId is null. The combination of these two result in the behavior that you are seeing.

**Comment by RFSH** [comment]
Fix for this bug has been merged with ermrestjs/master.

**Comment by hongsudt** [comment]
@robes can you review and close the issue?
