### ISSUE TITLE
Improve the ease of entry for binary assocation tables

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1422]
For pure and binary, we offer multi-select feature. 

To support the binary association case, the flow will be 
- First show a multi-select page. Instead of "Submit", we show "Next"
- Use this information to pre-fill the multi-record creation.  

I think, we need an ermrestjs method to determine whether it is a binary association. A binary association requires the uniqueness of two forieng keys. Please consult with @RFSH on ermrestjs API extension.

**Comment by jrchudy** [comment]
Two things need to be done for this issue:
 - the prefill url parameter needs to be extended to be used for a set of multiple records as well as multiple values we want to be prefilled per record.
   - This will look something like: 
```
localStorage: {
  prefill: {
    "formxyz": {
      prefill: [id1, id2, ...],
      expires: timestamp
    }, 
    "formxyz2": ...
  }
}
```
 - change prexisting prefill cases to this new format

**Comment by RFSH** [comment]
Closing this issue as the newly created #2416 has more updated information.
