### ISSUE TITLE
Secondary Action Errors should be dismissible

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1423]
For example, you are on a record page, you try to delete (unlink) an associated record (which could be as simple as a vocabulary 'tag' like resource). Upon failure, which can happen with dynamic ACLs that allowed the 'unlink' icon to be present, you can get a Forbidden error. The dialog will leave no option but to return to the home page and lose the rest of your state.

![image](https://user-images.githubusercontent.com/4202842/34856550-83fa1fa0-f6fa-11e7-95f9-5d6de84e771a.png)

**Comment by amitjha21** [comment]
This is meant only for `403 Forbidden` case; no other scenario where we might get `409 Conflict` while deleting items?

**Comment by RFSH** [comment]
I think it should always be dismissible, regardless of the error.

**Comment by robes** [comment]
Right.

**Comment by RFSH** [comment]
- I don't think we're throwing modal error pop-ups for submitting the record. They're only alerts that we show at the top of the page.
- Edit and Download buttons are just opening links. For download, it's not even chaise environment so we cannot control that. And for Edit, it will go to recordedit and then that app will throw the error.

Based on this, I think only delete and unlink are the paths that we might end up with a pop-up error that should be dismissible.

And for the implementation, what you most probably should do is adding extra logic in the `catch` function of these secondary actions. For delete/unlink of table view, you can find the functions in `ellipses.js`.
 In the `catch`, you can create a new type of error that wraps the error that is being thrown and only has extra attribute/flags that signal the "catch-all" (`handleException`) to show a dismissible error. I remember there was some logic in that function to make sure we're always showing just one error pop-up. So dismissing a error, will prevent other errors to show. Make sure to handle that case.
The only reason that I think you still need to call the handleException function is that you still need to show the appropriate error pop-up and we don't want to duplicate the logic. There might be better way of implementing this though.

**Comment by jrchudy** [comment]
As @RFSH stated, the only "secondary" actions that need to have this dismissible error popup are the `delete` and `unlink` actions. 

These actions are present in `record` app as the `delete` button in the top bookmark bar. And as the `delete`/`unlink` buttons in the related tables.
The `delete` action is also present in the `recordset` app as the `delete` button in the table.

**Comment by amitjha21** [comment]
This has been merged into master. Assigning to @robes to verify and close it.
