### ISSUE TITLE
Test Sorting then Paging In Recordset Directive

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1433]
We need e2e tests that verify clicking the column headers sort the data appropriately. Make sure to test sorting on pseudocolumns.

What needs to be done to setup the data:
 - [x] This should be added to the [recordset presentation spec](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js).
 - [x] This spec's [schema definition](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/data_setup/schema/recordset/product-recordset.json#L368-L390) needs to be updated so the `Category` pseudocolumn shows up in the list of visible columns in the recordset view
    - This is so sorting can be verified on a pseudocolumn as well as numeric and text.
    - The above link (`schema definition`) points to the visible-columns annotation that needs to be changed. The foreign key constraint name for the category column should be added to this array (`["product-recordset", "fk_category"]`)
 - [x] Update the specs [expected data](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js#L11-L86) and [test cases](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/all-features-confirmation/recordset/presentation.spec.js#L137-L161) to account for this new column being present
    - The expected data needs to adjusted to include the column header information in `testParams.accomodation_tuple.columns`
    - Each object in the data array (`testParams.accomodation_tuple.data`) should also be modified to include the category value for each row
    - The linked test case should be modified to include verifying the data in the DOM against each expected value added to the data array in the prior step
      - You can find the expected display value of the "Category" data by looking at the [schema document](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/data_setup/schema/recordset/product-recordset.json) and it's [corresponding seed data](https://github.com/informatics-isi-edu/chaise/tree/master/test/e2e/data_setup/data/product) (Most of the `product-*` schemas in the test suite share the same seed data). 

For testing the sorting then paging:
 - [x] a new `it()` should be defined
 - [x] the url should be `browser.params.url + "/recordset/#" + browser.params.catalogId + "/product-recordset:" + accommodationParams.table_name + "@sort(" + accommodationParams.sortby + ")?limit=5"` which translates to: `.../chaise/recordset/#<id>/product-recordset:accommodation@sort(no_of_rooms)?limit=5`
    - we want to use `limit=5` because there are only 6 rows for the current dataset and want to be able to page the data (maybe it makes more sense to use `limit=2` or `limit=3`
 - [x] test sorting for a few "regular" columns
    - sorting should be tested for the `Name of Accommodation`, `User Rating`, and `Operational Since` columns
    - verify that sorting both descending and ascending work properly for each column
    - verify paging forward shows the proper data
    - verify paging back shows the proper data
    - "proper data" means that the data should still be in the order based on the sort criteria
      - for a sanity check, you can verify that the url has the `@sort(<col-name>)` criteria in it still where `col-name` is the column header last clicked on for sorting
 - [x] test sorting for the pseudocolumn `Category` that was added earlier
    - do the same verifications for this column as above

From discussion in scrum on Thursday morning, we need to also test sorting for a foreign key column with multiple hops. 
If `->` implies an outbound foreign key, we need something like `main -> fk1 -> fk2` and verify that sorting is based on the values in `fk2`.
 - [x] the above mentioned [schema document](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/data_setup/schema/recordset/product-recordset.json) should be adjusted for this case as well.
   - A new column needs to be added to the [accommodation table](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/data_setup/schema/recordset/product-recordset.json#L3-L405) to act as the link to the new outbound foreign key.
   - A new table needs to be added to this document to act as the first "foreign key". A basic example:
      ```
      "<table-name>": {
        "comment": "domain",
        "kind": "table",
        "keys": [
          {
            "unique_columns": [
              "id"
            ]
          }, 
        ],
        "foreign_keys": [],
        "table_name": "<table-name>",
        "schema_name": "product-recordset",
        "column_definitions": [
          {
            "name": "id",
            "nullok": false,
            "type": {
              "typename": "int4"
            }
          },
          {
            "name": "fk2",
            "nullok": false,
            "type": {
              "typename": "text"
            }
          }
        ],
        "annotations": {}
      }
      ```
   - a foreign key definition needs to be added to the accommodation table [here](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/data_setup/schema/recordset/product-recordset.json#L16-L78) that connects the column you added to the new table (the referenced column should point to the new tables Id column.
      ```
      {
          "names": [["product-recordset", "fk_<some-name-you-want-to-give-it>"]],
          "foreign_key_columns": [
            {
              "table_name": "accommodation",
              "schema_name": "product-recordset",
              "column_name": "<column-you-added>"
            }
          ],
          "referenced_columns": [
            {
              "table_name": "<table-name>",
              "schema_name": "product-recordset",
              "column_name": "id"
            }
          ]
        }
       ```
   - now add a second table to act as the 2nd outbound foreign key off of the first outbound foreign key. That table definition should be very similar to the one you added before.
   - then add a foreign key definition (similar to above) to the first table you added so you can connect the fk1 table to the fk2 table.
 - [x] the [visible columns list](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/data_setup/schema/recordset/product-recordset.json#L368-L390) needs to be updated again to account for this new multi-hop pseudo column
   - in this case we can't just rely on the constraint name because we need to specify multiple "hops"
   - the source notation will have to be used. The first outbound name needs to be the constraint name (`names`) for the foreign key you added from the main table.
   - the second outbound name needs to be the constraint name from the foreign key definition you added to fk1 table (mentioned in the previous step)
     ```
     { "source": [
       {"outbound": [["product-recordset", "fk_<some-name-you-want-to-give-it>"]]}, 
       {"outbound": [["product-recordset", "fk_<some-name-you-want-to-give-it-2>"]]}, 
       "ID COLUMN"
     ]}
     ```
 - [x] test sorting for new multi-hop pseudocolumn you added
    - do the same verifications for this column as above

**Comment by hongsudt** [comment]
@RFSH is this still an issue?

**Comment by RFSH** [comment]
@hongsudt Yes, e2e test cases for these features are missing in chaise.
