### ISSUE TITLE
Multi-record edit confirm page does not scroll

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1435]
1. go to a recordedit form
2. enter 10+ records
3. submit
4. on success, you will be on a confirm page
5. if you have enough new records so that they fill up more than the first browser page, you cannot scroll to see all results

Test on FF

![records-confirm-cant-scrill](https://user-images.githubusercontent.com/4202842/35827879-7902a924-0a72-11e8-82e4-557b58a306f4.jpeg)

**Comment by jrchudy** [comment]
This has been fixed. Assigning to @robes for verification.
