### ISSUE TITLE
chaise config parameter to show unfiltered results

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#144]
even when no filter is selected

**Comment by karlcz** [comment]
I think this should also be the default behavior, so a site admin has to explicitly enable the confusing, empty results screen.

**Comment by karlcz** [comment]
I updated the issue description because it is about showing unfiltered results.  But, it will still have paging/limited number so it isn't showing "all" results...
@bugacov @hongsudt just a reminder we already have this issue in here from long ago (it came up in a standup again last week)

**Comment by svoinea** [comment]
Fixed in commit 729d28e1fd83768a46327a13f99f5a59a0227c20
The `showUnfilteredResults` option was added to the Chaise configuration file.
If present and equal `true`, data will be displayed in the search result table even if no filter was selected.

**Comment by svoinea** [comment]
Assigning @karlcz for review.

**Comment by karlcz** [comment]
I verified that it works, but I made on a comment on the commit.  I think the new function should be renamed before this is considered complete.

**Comment by svoinea** [comment]
Renamed `showUnfilteredResults` by `showupResults`. The `showResults` name was already used in a different context.
