### ISSUE TITLE
No Connection Error

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1440]
This is only reproducible on OSX/Safari combination (Tested on: 10.13.2 OSX /11.0.2 Safari).

1. Go to https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Behavior
2. Click on "View" button for any of the records.
3. You should see the error. Then if you visit any chaise page it will show the same "No Connection Error" unless you delete the cache.

This is what safari shows as the request being generated:

![](https://dev.isrd.isi.edu/~ashafaei/wiki-images/NoConnectionError.png)

It happens randomly on meta or schema request.

"No Connection Error" in ermrestjs means that we couldn't connect to the server and for whatever reason the request failed (timeout, error in the code, promise getting canceled manually). So this means there must be a problem in the client.

Searching the "The operation couldn’t be completed. Protocol error" error, I found that this error has been seen on iOS 11 and iOS 9 too. Couldn't find any solution for it but the suggest that this might be related to http2 settings and removing the http2 option solved the problem.

**Comment by hongsudt** [comment]
@RFSH @carlkesselman do we still see this problem?

**Comment by robes** [comment]
@RFSH this must be closable now?

**Comment by RFSH** [comment]
Yes. I am going to close this issue now.

---
This issue was not related to chaise/ermrestjs. Based on the discussion on slack:
> The problem was our rest api code adding a text body 'Resource not modified' to the response when it should have been an empty response.
