### ISSUE TITLE
Better error handling when 404 and maintain history after navigation

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1448]
-  **Use case: someone shares me a [permalink]**(https://beta.gudmap.org/chaise/record/#2/Protocol:Protocol/RID=R-ZGCY) that is required to login. Users click that link (usually as an anonymous users), then get a File not found error with the option to go to recordset.  
In this case, can we remind them that they might need to login and provide a login link to continue with the page? 

-  **Add history for app navigation.** 
E.g. if the Ok button on the error modal is clicked and page navigates to another app; history should be maintained to come back to the previous page.

**Comment by hongsudt** [comment]
This is the dynamic ACL case. Because the status column is not release, anonymous can't see it or even know it exists.

**Comment by amitjha21** [comment]
There could be three cases here:
- The record exists and user needs to login to see it: Should be given `Login` option in the error modal.
- The record does not exist in the backend
- The record exists but hidden for the user through ACL

**Comment by amitjha21** [comment]
I have added `Login` option in the error modal for `Record Not Found` error. 
https://dev.isrd.isi.edu/~amit/chaise/record/#1/isa:dataset/id=26934
Let me know if text changes are required.

*_Before login_*

![image](https://user-images.githubusercontent.com/9977014/37061613-da6fcd58-2148-11e8-8e99-07519ce7aeb2.png)

*_After login_*

![image](https://user-images.githubusercontent.com/9977014/37061759-499e1130-2149-11e8-81f0-bbddba53f9b4.png)

**Comment by amitjha21** [comment]
In case of `Record Not Found` here are messages for  two scenarios:

| Annonymous | LoggedIn |
------------------- | --------------
You do not have authorization to view this record. Please login to continue. <br/><br/>Click **here** to login. | No authorization to view this record / No matching record found for the given filter or facet.

Let me know all text message changes.

**Comment by amitjha21** [comment]
History feature to maintain unloading page in the stack is added. 
``` javascript
$window.history.pushState(null, null, $window.location.hash);  // maintain history for back/forward navigation
```

**Comment by amitjha21** [comment]
New Message drafts:

| Annonymous | LoggedIn |
----------- | ------------
No matching record found for the given filter or facet/You may not be authorized to view this record. Please login to continue. | The record does not exist or may be hidden. Please contact the system administrator. 


Let me know about all text message changes.

**Comment by amitjha21** [comment]
**As anonymous:**

![image](https://user-images.githubusercontent.com/9977014/37366055-998a5654-26bc-11e8-9e2a-00b3af497174.png)

**After loggin in**
![image](https://user-images.githubusercontent.com/9977014/37366530-e89791c0-26bd-11e8-8051-1f32dac3e8f2.png)

**Comment by jrchudy** [comment]
@amitjha21 make sure these error modals only display in the case of a record/entity not being found.  These 404 error cases (anonymous/logged in) should only apply to `record` app. `recordedit` should prompt the user to login first because creating/editing is allowed with a logged in user. If the user has logged in and then get a 404, the logged in error popup text you have defined should show.

In the case of all the apps ('record'/'recordedit'/`recordset`), if a 404 is returned for catalog, schema, or table, this same popup structure should be present (ask user to login if anonymous to verify that the catalog/schema/table was not hidden from anon users). The difference is that a separate message should be displayed that is specific to the whichever part of the path (catalog/schema/table) is nonexistent.

**Comment by amitjha21** [comment]
In case of `recordedit`, the existing flow takes care of prompting login modal before error pop-up.
In case of  table or schema missing it appears saying that
`Table dataset1 not found in schema. `

**Comment by jrchudy** [comment]
So in the case where either the catalog, schema, or table is missing, we should present this 404 login popup as well.

**Comment by amitjha21** [comment]
This has been merged. Assigning to @hongsudt to verify and close it.

**Comment by amitjha21** [comment]
The final text message in case record was not found:
**_When Anonymous:_**

![image](https://user-images.githubusercontent.com/9977014/37987084-18303d0c-31b2-11e8-8923-f37904d50ee3.png)

_**After Logged in:**_

![image](https://user-images.githubusercontent.com/9977014/37987137-35313a28-31b2-11e8-8f0f-1d95441a886c.png)
