### ISSUE TITLE
default chaise-wide page size

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1458]
Currently using annotations we can define `page_size` on table level and if it's not defined, chaise is using 25 by default.  We can define a chaise-config so deployments can change this default value.
We need to discuss this because it might be even useful to have `page_size` defined in the annotation on schema level.

**Comment by hongsudt** [comment]
@RFSH @jrchudy I think we already have this defined in our annotation and it should already be implemented.. Can you guys check?

**Comment by RFSH** [comment]
We have an annotation to define `page_size` for each table. This issue is about the case that this annotation is not defined. Currently if annotation is not defined, we're using 25 by default. We can make this number a chaise-config instead of a hardcoded value.

**Comment by hongsudt** [comment]
Can you check whether we already have this defined? I recalled having a
discussion with Serban about this config for search.

**Comment by RFSH** [comment]
There's a `searchPageSize` in chaise-config but only search-app is using it.

**Comment by hongsudt** [comment]
@robes @bugacov @ljpearlman This shouldn't be difficult.. But is it a high priority?

**Comment by hongsudt** [comment]
@RFSH does this annotation get inherit from the schema level?

**Comment by RFSH** [comment]
@hongsudt The current `page_size` is part of table-display annotation (which is table level). So no.

**Comment by RFSH** [comment]
We are planning to [introduce a table-defaults annotation](https://github.com/informatics-isi-edu/ermrestjs/issues/997) which would also allow us to define the `page_size` on schema or catalog.  So I'm going to close this issue.
