### ISSUE TITLE
don't show links back to the entity from nested entity rows (in record page)

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#146]
check with @mikedarcy for more details

**Comment by robes** [comment]
@mikedarcy @bugacov : is this fixed? i don't see the links back to the entity anymore in the nested tables on the dev.misd.isi.edu catalogs. or maybe we just hid them using the new hidden column annotation?

**Comment by robes** [comment]
I think I do see what's going on here. There are columns that are the 'id' back to the primary entity, and there are also those erroneous "link" columns. And then there are also "Undefined" columns.
![link](https://cloud.githubusercontent.com/assets/4202842/11280721/0a5b5d16-8eac-11e5-97b1-3ae3472d055f.jpg)

**Comment by bugacov** [comment]
Hi Rob,
In there now you see them as "undefined" because the actual "id" column has
been annotated as hidden. That's why you don't see the "id" column in the
table either. I think that's also a bug, since in the specs the
"referenced" column (in this case "id") should be excluded from the table.
Alejandro.

**Comment by robes** [comment]
@bugacov is this still an issue? and if it is, do you have an example we can look at? thanks

**Comment by bugacov** [comment]
I think this is still an issue. It seems to be fixed if the key column(s)
are annotated as hidden.
But if that annotation is not there then the extra columns still show up.

Take a look at

https://gpcr-dev.misd.isi.edu/chaise/record/#1/gpcr_browser:construct_gui/title=Construct%20HUMM-1002

and expand the "protein" nested table. construct_id is the foreign key. If
not annotated as hidden it show at the
beginning and also as that extra column at the end.

I think the correct behavior should be the the key value is never displayed
(w/o having to annotate it as hidden) in the nested
table. I remember that was one of Karl's requirements.
Alejandro.

**Comment by robes** [comment]
Has this been fixed already? I think it might have

**Comment by hongsudt** [comment]
duplicate with #345.
