### ISSUE TITLE
Unauthorized Assets

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1461]
In ermrestjs, if the asset column has a value, we will turn that into a download button, so when users click on it, the browser download feature gets triggered (instead of just returning a link).

This can cause problems in the case that the hatrac url is not valid or user does not have access to it. Different browsers are handling this differently.  For instance Firefox downloads the page but the downloaded HTML just says "not found". We might be able to improve the UX in this case.

A simple solution is avoiding the `download` attribute and just returning a link. But the better solution might be sending a request to the given url and find out if it's invalid/not found/unauthorized we can show different type of buttons to signal that to the users.

**Comment by RFSH** [comment]
We had a quick discussion about this. We could modify all the `download` links in chaise to do a`HEAD` request first to see whether user has access to the file or not. So the UX would be

1. User clicks on the download button.
2. Chaise shows a spinner inside the button.
3. Chaise sends a HEAD request to the download url.
  3.1. If the request was successful, Chaise will redirect the page to the url so it can be downloaded.
  3.2. Otherwise we will show a message to the users about the error.
4. Chaise will hide the spinner.

I tested `HEAD` request to assets in hatrac. It will throw 401 if user doesn't have access to the asset. I'm not sure about the other types of assets that are hosted in other websites.

**Comment by hongsudt** [comment]
https://www.rebuildingakidney.org/chaise/recordset/#2/RNASeq:File/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JHQBcAjdafEAJQDkBBAZRwEcQAaEAMQEsAbHAPo9+AgCoBPAA6CAZgGsc4kAF0AvhyoBJACIqOWABYpuuJJQCKAWgCaAVmsAGdiCt2AGgFkV65Omx4EUGIyNAoEanomVg5hQQBRAA9pDG4AWxwIIgEtbQF5RW8NHT0QQ2NTSgBGADZLbQ8AdVFnGrrGhpba+obrTra3Jw5W+rcAJj6RgBYJjzdqmbcADgW6BYBhBbiFgHFC30xcOBAAGRwAczAscSE+QRznCBQsiDReXjgiDDQcVTUgA@sort(Replicate_RID::desc::,File_Type,RID)

Here is the list of files that should required login that are not on hatrac. Please check whether HEAD command will throw 401 or 403.

**Comment by RFSH** [comment]
@hongsudt All of these `URI`s are under hatrac (`/hatrac/resources2/`). Their folder might be different from what you're using for "non-legacy" data, but still they are hosted on hatrac.

**Comment by jrchudy** [comment]
Changes for this issue have been merged into master for both `chaise` and `ermrestJS`, assigning to @hongsudt  for verification. Links to test the different places these buttons appear can be found in the [closed PR](https://github.com/informatics-isi-edu/chaise/pull/1785).

**Comment by jrchudy** [comment]
When a 401 error is returned, we should avoid showing the login dialog because it doesn't have enough information to point out what the state of the app is. An anonymous user may not understand why they are getting that error. The dialog should provide more information about why the user can't download the asset.

A new chaiseConfig property is going to be added that will point to further information about the asset download policy for that host/catalog. Tentatively calling this property `assetDownloadPolicyUrl`.

**Comment by jrchudy** [comment]
The corresponding changes that were discussed, (use a modified error dialog instead of a login dialog), were merged into master. Assigning this issue back to @hongsudt .
