### ISSUE TITLE
Support for filename_ext_filter in asset annotations

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1463]
This would be very useful in FaceBase. We have already seen many example of users disregarding our documentation and uploading .zip files where they should have only uploaded image (.nii or similar) files.

https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2017-asset

**Comment by jrchudy** [comment]
Support for this feature has been added to `chaise`. reassigning to @robes for verification.
