### ISSUE TITLE
pre-filtering selections not supported in 'edit' mode

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1464]
I.e., edit this record and change the 'biosample'. you should see 38 but you will see 1300+.

https://dev.facebase.org/data/recordedit/#1/isa:replicate/RID=68027

But if you were to go back to the "Experiment" record and 'add' a replicate, you will get only the pre-filtered 38 biosamples from that same selection.

**Comment by jrchudy** [comment]
@robes can you update dev.facebase.org to include `isrd-staff` or `isrd-testers` as part of the group that can create/edit/delete data.

I can't test this issue, but it looks like an issue that was submitted a few days later in `ermrestJS` is related to this and has been fixed. So I think this issue may not be relevant anymore but I can't verify that.

**Comment by robes** [comment]
It appears to be resolved. thanks
