### ISSUE TITLE
Use of highlight in selectable mouseover is not consistant.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#147]
When your mouse is over the back button in the selector, the text and button turns gray to indicate that you can select, and the mouse curser changes.

However, we don't see the same behavior when the mouse is over one of the check boxes.  I would think we would want this to shade gray as well to indicate that you can click, and to be consistant with other selector.

**Comment by hongsudt** [comment]
@crisaless do we still have this problem, if not, can we close it?

**Comment by crisaless** [comment]
It's fixed in dev but hasn't been released to staging/production yet.

**Comment by hongsudt** [comment]
@crisaless What dev? Is this a common across all projects?

**Comment by crisaless** [comment]
Right, at the time this was opened, it was just facebase - I've looked at other apps and it's working as expected.
