### ISSUE TITLE
Remove the "Delete Record" button/link from recordedit

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1472]
There's no reason for this button/link anymore.

It also is confusing and invites error. I personally find myself feeling really nervous to have the Delete button here, especially since its right next to the Submit button.

Also, I would suggest relabelling "Submit Data" as simply "Submit".

**Comment by jrchudy** [comment]
The button has been removed because of buggy behavior when in `multi-edit` mode.
