### ISSUE TITLE
Missing scroll bar after creating a long list of new items - synapse data management server

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1474]
NOTE: this issue was filed on a project-specific technology repo but I believe it describes a Chaise recordedit UX issue for multi-record creation.  The user is reporting that scrolling doesn't seem to be enabled for the successful results page that renders the response of the ermrest POST request.

@BDemps commented on [Mon Mar 19 2018](https://github.com/informatics-isi-edu/synspy/issues/60)

Whenever you submit many things at the same time (e.g., behavior studies, image pair studies, zebrafish subjects, etc.), the resulting list cannot be scrolled. In order to see everything, I have to zoom out. An example is attached.
<img width="819" alt="screen shot 2018-03-12 at 2 00 14 pm" src="https://user-images.githubusercontent.com/28578487/37309366-f63cfb6e-25fd-11e8-8fe3-76675b497e53.png">

**Comment by jrchudy** [comment]
This looks like a duplicate of issue #1435. That issue was fixed just over 2 weeks ago. 

I saw on [synapse-dev.isrd.isi.edu](https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Image), that this wasn't working. When uploading the master to my [user directory](https://synapse-dev.isrd.isi.edu/~jchudy/chaise/recordedit/#1/Zebrafish:Image), this appears to be fixed.

**Comment by BDemps** [comment]
Oh, ok, cool. I'll let you know if I see it again. Thank you! That's
probably about the time that I sent in the request.

On Mon, Mar 26, 2018 at 3:48 PM, Josh Chudy <notifications@github.com>
wrote:

> This looks like a duplicate of issue #1435
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_chaise_issues_1435&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=_G8KexqeFFtvU2WwEZvt4l1EY1o3oPtveH16HekN4fQ&s=gpxTomTs165apohof_PWM3EwTFZUTseMpyQXneX0m4g&e=>.
> That issue was fixed just over 2 weeks ago.
>
> I saw on synapse-dev.isrd.isi.edu
> <https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Image>,
> that this wasn't working. When uploading the master to my user directory
> <https://synapse-dev.isrd.isi.edu/%7Ejchudy/chaise/recordedit/#1/Zebrafish:Image>,
> this appears to be fixed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_informatics-2Disi-2Dedu_chaise_issues_1474-23issuecomment-2D376336576&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=_G8KexqeFFtvU2WwEZvt4l1EY1o3oPtveH16HekN4fQ&s=5-dVto-FQBZW2Vc_aiDkAAkAsN0ZZDl-Fhv443ciZUc&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AbQSt4M5Ysai2qWccbrhPxbfMJN5ZMZOks5tiXAzgaJpZM4S75qr&d=DwMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=Lssj6JKak_DaRnExGYcKnQ&m=_G8KexqeFFtvU2WwEZvt4l1EY1o3oPtveH16HekN4fQ&s=W9Qpsr5TuibaNnFvzqJpM6nZCFbwklPYfOY3jZn0HCQ&e=>
> .
>



-- 
William Dempsey, Ph.D.
Postdoctoral Scholar
Molecular and Computational Biology
Dana and David Dornsife College of Letters, Arts and Sciences
University of Southern California
wdempsey@usc.edu
Lab #: 213-821-1818

**Comment by karlcz** [comment]
The synapse-dev server had its updated disabled for some other testing but is now back running the latest front-end code.  You can see the revised behavior there by just creating a bunch of dummy records, since this is a test catalog and won't hurt any production data.

This fix won't be on the production server until we gather up a few related updates worthy of a new release...

**Comment by karlcz** [comment]
I confirmed that I see a scroll bar when creating many records and resizing my browser on the dev server.
