### ISSUE TITLE
Page hangs when clicking "delete" on one of the newly added replicate records in recordedit  

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#1478]
E.g. in a FB dev dataset, click to add experiment, then click "+" to create a new replicate record then click the "trashcan" icon to delete the last entry and you get a never ending Loading spinner

**Comment by jrchudy** [comment]
This doesn't actually "freeze" up the page. It just never hides the spinner once the "remove form" function has finalized and returned to it's calling site. A fix for this will be pushed to master for this shortly.
