### ISSUE TITLE
Flow Control In Record App

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1486]
Currently after getting data for the main entity, we send requests for all the inbound and related entities. This might result on too many requests generated at once. Instead we should change the behavior to have some sort of flow control.

We should only generate N (4 for now, we can adjust that) requests at the time. The requests should be generated from top to bottom. That is all the inbounds and then related entities. We should also show them from top to bottom. We are doing this in related entities, we should do the same for inbounds.

Other Concerns:

1. Eventually related and inbound entities might have aggregated pseudo-columns. So the request for getting the data for those, might be actually consistent of multiple requests. This can make the record page to generate exponentially more requests which requires flow-control.

2. Related/inline tables can have secondary actions (`delete`, `edit`, `sort`) that manipulate the displayed page of results.

**Comment by karlcz** [comment]
We should try to refactor/reuse the flow control from recordset so
that these things are consistent and share maintenance/enhancements...
