### ISSUE TITLE
Headings of nested tables sometimes not display entirely

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#149]
See attached screen shot.

**Comment by robes** [comment]
[b0rken-table-heaading.tiff | uploaded via ZenHub](https://files.zenhub.io/5638ff0240685bbb4db6fdfc)

**Comment by robes** [comment]
![b0rken-table-heaading](https://cloud.githubusercontent.com/assets/4202842/10917736/210e1a68-8217-11e5-8f0c-99d4860332ce.jpg)

**Comment by robes** [comment]
this is another one that should probably be put on hold until we evaluate kendo ui

**Comment by karlcz** [comment]
I think this is going to be another wontfix, right? @robes @hongsudt   if so, we should tag it and close it.

**Comment by hongsudt** [comment]
Yes.. I have to log this in the record app wiki first, and then I will
close it.

**Comment by hongsudt** [comment]
tag as wishlist and keep track of it on record 2 wiki page.
