### ISSUE TITLE
Cleanup App Dependencies in Makefile

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1494]
In `Makefile` we're listing all the dependencies that are required for each app, and also the common dependencies. But some of these seem redundant. We should be able to clean up these list and change the way we're creating the dependency list. 

We recently found that one of the apps are not working because of a common dependency not being included. If we clean up the lists and make it more readable we can avoid such incident from happening again.

**Comment by hongsudt** [comment]
I can't find the issue that @karlcz brought up related to tagging the deployment files with versions. So I am just going to add the scope of this one..  Feel free to update my comments.. 

The chaise/ermrestjs deployment code should rename the files to include the file checksum (e.g. ermrest_<checksum>.js) and get referenced properly in any scripts that depend on those files. To do this, we need to: 
- [ ] ....

@RFSH @jrchudy please fill in the detail..

**Comment by RFSH** [comment]
I edited the previous comments, I feel like we need more discussion or at least more information about how we can actually achieve this. I don't think it's feasible to add version number to all of the dependencies in chaise. That can easily go out of control. We should consider merging the dependencies during the build, and then adding version.

**Comment by jrchudy** [comment]
Regarding tagging deployment files with versions, this has been done for most of the chaise assets excluding the vendor files.
