### ISSUE TITLE
Only show 'Actions' when there is an action other than view

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1495]
When the user can only do one thing (view) and there is a PK column displayed, the Actions (plural) is unnecessary.

**Comment by hongsudt** [comment]
As many of our users are accustomed to the eye, I am not sure that all will agree to this change. 
@ljpearlman @karlcz @bugacov @mikedarcy what do you guys think? 

We can change the column header to "View" which will reduce the white space a bit and make the table look a bit nicer.

**Comment by hongsudt** [comment]
A quick thing that we can do is to change the column header from `Actions` to `View` when the user cannot delete or edit the table content.. This change should make the column more compact. 

I will leave taking out the action column completely to a bigger group discussion.

**Comment by jrchudy** [comment]
The "Actions" column header has been changed to show "View" when the user can only view the records in the table. This is based on whether the user can delete or update any entities for that table (reference). 

If there is row level security that adds extra permissions that dis-allow edit or delete that create a state that appears to be read-only, this will still show "Actions".
