### ISSUE TITLE
Provide schema level annotations

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#15]
I would like to be able to annotate a schema in the same catalog being used by chaise as "excluded" so that all tables under that schema are not being processed by chaise. In this way I can use tables in that "excluded" schema for receiving data updates and then run in-database transformations to populate the actual tables used by chaise.

**Comment by robes** [comment]
@svoinea @karlcz : this is done right?

**Comment by karlcz** [comment]
ERMrest has schema-level notations but I have no idea if Chaise is
using any to support the function requested here.

**Comment by svoinea** [comment]
Chaise is using currently the "comment" annotation_uri with the possible values of "exclude" or "default".
