### ISSUE TITLE
navbar standalone app

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1505]
We have this issue in FaceBase to have login/logout links on all our pages, of which we have several "static" (non-chaise) pages. Could we simply make a standalone app out of the existing chaise navbar? It would have to be done in a way that the app could be included on an arbitrary html page generated by jekyl (in other words don't assume that you can produce an index.html because we can't directly use or display that in this scenario).

Here's a reference to some notes from the facebase project including some comments on the subject from @RFSH as relayed by @crisaless.

https://github.com/informatics-isi-edu/facebase-www/issues/65

**Comment by hongsudt** [comment]
duplicate with #1697. Will close.
