### ISSUE TITLE
export feature

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1506]
Additional changes that still need to be addressed:
- [x] What happens if you navigate away from `recordset` while export is running?
  - tested this, nothing happens (the export never completes)
  - should we block the UI with a "downloader", notify the user before navigating, or nothing
- [x] minimum set of file types supported
  - for `BAG` type, `csv`, `json`, `fetch`, and `download`
  - for `FILE` type, `csv` and `json`
- [x] make sure iobox is returning the proper errors
  - instead of what seems to be errors wrapped in a 500 error
- [ ] handle iobox not installed
  - "Error: iobox service not available
  - handle other services not available (ermrest, webauthn, hatrac)
    - maybe in callbacks of requests to those servers, if 500 is returned, add extra info to the error (submessage)

Tests
- [x] ermrestJS needs to test the error case
- [x] chaise e2e tests need to be written

**Comment by RFSH** [comment]
The first iteration of export support has been merged with master. These are the things that I think are missing:

- Better Error handling. This requires changes in `ioboxd` since it's always returning 500 now.
- E2E test cases

**Comment by jrchudy** [comment]
Assigning this issue to @hongsudt to reprioritize for the rest of the work:
 - verify errors returned by export are what we expect
 - handle iobox no installed (and other services not installed)

**Comment by jrchudy** [comment]
Talking to @mikedarcy today about export, he pointed out to me that when export fails/errors, we are not preserving all of the information returned to `ermrestJS`. The `_responseToError()` function is swallowing up the `response.data` value when it creates the `Error` object.

**Comment by hongsudt** [comment]
@RFSH the original issue still has something unchecked.. Are those still need to be done? 
Also, I want to move on to the next improvement of export, should I generate a new issue?

**Comment by RFSH** [comment]
@hongsudt the last part is not done. We're not checking whether iobox is installed or not. We're going to send the request regardless. The returned error most probably is going to be meaningful (it would be a 404 error I think), but it's not a specific error in ermrestjs/chaise as the last bullet point is suggesting.

**Comment by RFSH** [comment]
The remaining part of this issue is what's documented as round 3 in [ermrestjs#730](https://github.com/informatics-isi-edu/ermrestjs/issues/730). Therefore I am going to close this.
