### ISSUE TITLE
Defining scrollable height should be generic across all apps

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1507]
In `recordset`, `record`, and `recordedit`, the height is being set differently in each app.

In the case of `recordset` and `recordedit`, the height is defined on the `main-container`. Because of this, `recordset` has to make a separate request to fetch the faceting elements and define the height on those inner elements for the scroll to work properly.

In the case of `record`, the height is defined on the `main-content`. In this case, the main area and the ToC panel don't need to have their heights set separately like recordset main area and faceting.

Not sure which approach is more ideal. This would take some DOM manipulation to see which gives more consistent behavior. I'm leaning towards the approach we have taken for the `record` app as it means less overall code and less potentially duplicated code.

**Comment by jrchudy** [comment]
This has been done for `record` and `recordset` in PR #1847 .

`Recoredit` still pending...

**Comment by RFSH** [comment]
This has been done in #1847 for all three apps. We changed the watcher to watch for the changes in the height of the fixed area in the page. In case of record, recordset, and recordedit the fixed area includes the `navbar` and `.top-panel`. In case of all the recordset popups the fixed area is the modal header and `.top-panel` of the recordset that is displayed in the modal.

Although this method still has its own downsides and we should investigate this further. We might be able to utilize [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) feature for a better and more performant solution.
