### ISSUE TITLE
tooltips on the column headers of recordset appear twice 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1510]
There is a delay between the two tooltips. One tooltip looks normal, the other one uses a bigger font and show up on the bottom of the column header. 

https://www.gudmap.org/chaise/recordset/#2/Protocol:Protocol@sort(RID)

**Comment by jrchudy** [comment]
This has been fixed and merged into master. Looks like this "bug" has been in our project for quite some time now..
