### ISSUE TITLE
Firefox tab crash in modal multi-picker

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1527]
On synapse-dev I can repeat this crazy failure:

1. Go to [this record page](https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Cohort%20Analysis/RID=10DG)
2. Open the "Add" modal on the second related entity section `Cohort`
3. Open the facet sidebar
4. Set the `Behavior (Learned?)` facet to `true` so it says "Displaying 4 of 21 Records"
5. Set 25 items per page
6. Use the "select all" button (also notice there is a big lag when this happens)
7. Click Submit

I get a "gah, your browser tab crashed" error from firefox, and reloading shows that nothing was added to the original record's related entities when this happens.

Eventually, if I was patient enough, it seems I got it to work once.  I suspect this must be a race condition that has to do with the big plotly iframes being loaded for each entry in the picker for this use case...

**Comment by jrchudy** [comment]
I can't reproduce this issue because all of those 21 entities are now related to the main entity. I can however see issues with click events not triggering because of the plotly frames still trying to load.

**Comment by karlcz** [comment]
Feel free to create another record in the Cohort Analysis table so you can start
with a blank set of related entities...

**Comment by jrchudy** [comment]
No matter how quickly I select the facet value for "Behavior (Learned?)", switch my page size to 25, click "All", and then submit, I can't reproduce this error (browser tab crashing). I tested this in Firefox on my macbook as well as in the lab.

**Comment by jrchudy** [comment]
When I go to the above linked page, none of the thumbnails load for me (under the "Plot" column of the Cohort related table). In the console I see a 403 for each file associated with the thumbnails. 

I may not be able to reproduce this browser "lock up" because the iframes finish loading much quicker for me and never lock up my browser.

**Comment by karlcz** [comment]
I wasn't able to reproduce this anymore.  Now, the GUI just gets laggy and then completes operations rather than crashing.  Maybe a firefox updated fixed their own fragility?
