### ISSUE TITLE
'Clear all filters' removes the current catalog and schema:table from the URL

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#153]
If you are searching a catalog other than the default, the URL needs to include the catalog num and the schema:table in the URL like:

`https://.../chaise/search#2/myschema:mytable`

When you apply predicates to the filter you get something like

`https://.../chaise/search#2/myschema:mytable?facets=(...)`

When you click the 'Clear all filters' button, it resets the URL to:

`https://.../chaise/search`

So that not only removes the facets it may inadvertently change catalogs too.

**Comment by svoinea** [comment]
Fixed in commit 296761ea8c66d45f5716a11d340258c31140ad70
