### ISSUE TITLE
better error message

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1536]
Currently when an anonymous user visit a page that requires login, this is what we throw:
```
Table Monthly_Submission_Dashboard not found in schema. Please login to continue.

Click OK to go to the Home Page.
```

Please change this to.. 
```
Table Monthly_Submission_Dashboard not found in schema. You may need to login to see the table. Please login to continue.
```

**Comment by hongsudt** [comment]
@jrchudy @RFSH can one of you do this when you have a chance.. I just need one more sentence added to make the error message easier to understand..

**Comment by RFSH** [comment]
All the errors regarding "schema/table/column not found" are coming from ermrestjs as 404. So chaise cannot know if it's the table that is missing or schema. The error message that you suggested is assuming that it's the table that doesn't exist. 

If you want it to be expressive, we have to change those error objects in ermrestjs first. If you want a temporary and fast solution we can use "You may need to login to see the model" or something similar.

**Comment by RFSH** [comment]
The extra message of "You may need to login to see the model or data" has been added to not-found  errors. Assigning to @hongsudt to verify.

**Comment by RFSH** [comment]
To test this you can go to a page with any arbitrary [schema name](https://dev.rebuildingakidney.org/chaise/recordset/#2/Antibodyaaa:Antibodies) or [table name](https://dev.rebuildingakidney.org/chaise/recordset/#2/Antibody:Antibodies12312321).
