### ISSUE TITLE
'All Attributes' won't close, if you switch 'Search within: ...' table

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#154]
To recreate, go to a chaise deployment that has 'Search within: ...' enabled.

1. click on **View all attributes**
2. change to a different catalog from the **Search within** option
3. try to close **ALL ATTRIBUTES**

It can be closed only by going back to the table that you were on when you opened the attributes menu.

**Comment by svoinea** [comment]
Fixed in commit 647c56b87250bc86343bff8903f0a376d98f563d
