### ISSUE TITLE
Wrong column_display context used in record app main body

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1540]
1. Go to: https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Image/RID=2N0
2. Scroll down to the field labeled 'Image File' which corresponds to the 'URL' column of this table.
3. See a custom markdown presentation instead of an asset column presentation
4. Go to https://synapse-dev.isrd.isi.edu/ermrest/catalog/1/schema/Zebrafish/table/Image/column/URL/annotation

Note, the annotation defines a markdown pattern for the `compact` context but not for the `*` context. It also provides an asset annotation.  For the record app, this should be displaying the asset presentation for the detailed context.

**Comment by RFSH** [comment]
Based on the annotation `"detailed": "compact"`, we are using whatever is defined for the `compact`  for `detailed` too. So it's working as expected.

**Comment by karlcz** [comment]
Hah, thanks.  I don't know how many times I looked at that and didn't notice that extra line...
