### ISSUE TITLE
When creating multiple replicates at a time, 400 error thrown

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1545]
@bugacov found a bug when trying to create multiple replicates at the same time (in staging but it's reproducible in dev).

This was found when adding a replicate through the 'add' link on top of related tables which created a prefill param and an invalidate param. I suspect the query params are unrelated.

https://dev.facebase.org/data/recordedit/#1/isa:replicate

The table definition includes the `RID` as a column in the table, so when the payload is generated for 2 or more records, each record has `RID: null`. I suspect this is causing an issue. Not sure if it's `chaise`, `emrestJS`, or `ermrest` throwing this error.

Edit:
After removing the RID column from the recordedit visible columns list, this error is still reproducible.

**Comment by karlcz** [comment]
Chaise should be treating the RID as generated and including it in the
?defaults parameter. Then, the server wouldn't even be looking at
any RID input data.
