### ISSUE TITLE
Refactor recordset/recordset.controller.js and recordset/index.html.in

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1566]
In the recordset app (not directive) html template, we have the controller attached to it but we are not using `controller as` syntax. 

We should refactor the recordset controller to attach the necessary things to "this" (the controller) so that we can use the `controller as` syntax to call functions and variables from the DOM rather than relying on scope. 

The main concern with this is that `controller as` creates a scope that is available for all child elements. Where using `$scope` works fine, it fails when we have an `ng-if` defined because that creates a new isolated scope (I believe this is the case but haven't tested it to make sure).

**Comment by RFSH** [comment]
With the recent changes to recordset app, its controller doesn't have that much logic. We could easily make this change anytime. I am going to close this issue and instead add a TODO to the code.
