### ISSUE TITLE
Recordset performance issue? 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1570]
Here are the links to the data commons demo: 
* https://nih-commons.derivacloud.org/chaise/recordset/#1/public:KC7%20Search%20Demo
* https://dev.isrd.isi.edu/chaise/recordset/#44989/public:GTEx_lung_cancer_demo_data_v2-clean@sort(key)

Notice that the table is very wide but not very big. It has no fks, etc.. However, the browser will hang if we choose 100 or 200 items per page. 

The workaround is to work on the visible columns. But maybe we can look at this page to give us some clue on our performance issue..

**Comment by hongsudt** [comment]
This issue is related to #1378

**Comment by RFSH** [comment]
In the following I try to summarize how the process of investigating this issue went down. I will reference [this](https://docs.google.com/spreadsheets/d/16R5u26OwsFulrY_vxFla_zSAFURBwGsNocK7uWFm6cc/edit#gid=0) document in my explanations. In there you can find more information about different experiments that I ran. The load times that are written there were based on the output that chrome developer tools would print out. They might not be accurate, but for the sake of comparison it was satisfactory.

In the default case (52 range facets, 26 choice facets, 84 columns, 25 rows), the page would take  around 11 seconds to load. In the first few experiments, I tried changing number of rows, columns, and facets. What I realized was that the number of facets in this scale (rows less than 25), was the biggest factor. Investigating more revealed that the main issue was the range facets and the fact that we're attaching all the heavy plotly elements to the DOM even when the facet is closed. Therefore I changed the range facet behavior to only attach the plotly when the facet is opened. This change reduced the load time by around 50%. 

After this, we tried experimenting with the number of rows and columns in a higher scale. What we found out is that in those scales (rows * columns > 5000) it's the main table rows that take a long time to render. Even in higher scales this delay would result in browser not responding for around 20 seconds. This showed that we might need to change the way that we're showing the main result table.

**Comment by RFSH** [comment]
I tried different methods for reducing the load time in the extreme cases, but none of the trivial methods worked. This requires more research on the methods that we can improve the performance for `ng-repeat`.

**Comment by jrchudy** [comment]
Closing this issue as well after closing #1378. 

It's been quite some time since this was opened and multiple changes have been made to recordset since then to improve performance and load content in a more logical order so users can interact with the page sooner.
