### ISSUE TITLE
Accordion content is hidden by default

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1583]
The accordion directive used for the related tables in `Record` app and the facet panels in `Recordset`, on page load the content contained within them is "hidden" rather than not "drawn". This causes all of the containing content to be loaded during page load.

Ideally we would not want to draw any of that content unless the accordion was open by default or until the user opens the accordion. In the least, maybe there's a way to defer the load of hidden content until after all other content.

**Comment by hongsudt** [comment]
@RFSH Have you completed this issue?
