### ISSUE TITLE
Custom synapse-viewer generates warnings in browser console

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1589]
I see messages like this in the browser console, seemingly associated with viewer-plotly.js  and I think
correlated to each instance of synapse-viewer in an iframe. 

see for example https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Cohort%20Analysis/RID=17AR

    addThreeD!!!!
    Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/

**Comment by RFSH** [comment]
The warning is coming from one of  "openseadragon" source files ([this line](https://github.com/informatics-isi-edu/openseadragon-viewer/blob/master/js/osd.viewer_multi.js#L817)). I am going to close this issue since it's not part of chaise.
