### ISSUE TITLE
UX issues for unlink PB associations modal

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1591]
The unlink PB modal has been [revisited](https://github.com/informatics-isi-edu/chaise/issues/1060) since this was created .
 - ~~rename "remove" in places to "unlink"~~
   - [x] extend "unlink" tooltip to be `"Disconnect <leaf_table_name>: <leaf_rowname> from this <main_table_name>"`
 - [x] when row is selected, place an "x" in the check box instead of a check mark
 - [x] no "add" button in "unlink" popup
 - [ ] fix wrapping when visible-foreign-keys header text/buttons overlap
 
 Other changes (moved from issue #1060 ): 
  - for "+ Add records" button 
    - [x] tooltip: `"Connect <leaf_table_name> records to this <main_table_name>."`
    - [x] popup title: `"Add <column_displayname> to <main_table_name>: <rowname>"`
    - [x] submit button tooltip: `"Connect the selected rows to <main_table_name>: <rowname>."`
  - for "- Remove records" button
    - [x] tooltip: `"Disconnect <leaf_table_name> records from this <main_table_name>."`
    - [x] popup title: `"Remove <column_displayname> from <main_table_name>: <rowname>"`
    - [x] submit button tooltip: `"Disconnect the selected rows from <main_table_name>: <rowname>."`

**Comment by hongsudt** [comment]
@jrchudy Can you split this into 2 issues: ones for the unlink page and one for the overall UX improvement (e.g. the one that affect all modals).

The first one we can just go ahead and push after it is done. The second one, we might want to ask for some more feedback.

**Comment by jrchudy** [comment]
We talked about all the "words" we use for unlink/delete and create on record page and how those terms should remain the same in each context to keep the UX consistent.

### Record Page
#### Unlinking records
In the case of unlink, we use different verbs throughout the process. The list includes "disconnect", "delete", "remove", "unlink". We also use 2 different nouns including "records" and "rows".
  - unlink icon in action column for related tables
    - tooltip: "Disconnect <association_table_name>: <leaf_rowname> from this <main_table_name>"
  - confirm delete dialog
    - title: "Confirm Delete"
    - text: "Are you sure you want to delete this?"
    - button: "Delete"
  - batch delete action bar button
    - text: "Remove records"
    - tooltip: "Disconnect <association_table_name> records from this <main_table_name>"
    - multi select modal 
      - title: "Remove <association_table_name> from <main_table_name>: <main_rowname>"
      - submit button
        - text: "Remove"
        - tooltip: "Disconnect the selected rows from <main_table_name>: <main_rowname>"
      - confirm delete dialog
        - title: "Confirm Delete"
        - text: "Are you sure you want to delete X rows?"
        - button: "Delete"
      - post delete modal
        - title: "Batch Unlink Summary"
        - text: "X rows successfully removed. Y rows could not be removed. Check the error details below to see more information."

#### Deleting records
  - delete button in top right
    - text: "Delete"
    - tooltip: "Click here to delete this record."
  - delete icon in action column for related tables
    - tooltip: "Delete"
  - confirm delete dialog
    - title: "Confirm Delete"
    - text: "Are you sure you want to delete this?"
    - button: "Delete"

#### Linking records
In the case of link, we use different verbs throughout the process. The list includes "add", "connect", "save". We also use 2 different nouns including "records" and "rows".
  - create action bar button (p&b association)
    - text: "Add records"
    - tooltip: "Connect <association_table_name> records to this <main_table_name>."
    - multi select modal
      - title: "Add <leaf_table_name> to <main_table_name>: <main_rowname>."
      - submit button
        - text: "Save"
        - tooltip: "Connect the selected rows to <main_table_name>: <main_rowname>."
#### Adding records
In the case of add, we use different verbs throughout the process. The list includes "add", "create", "connect", "save".
  - create button in top right
    - text: "Create"
    - tooltip: "Click here to create a record."
  - copy button in top right
    - text: "Copy"
    - tooltip: "Click here to create a copy of this record."
  - create action bar button (foreign key relationship)
    - text: "Add records"
    - tooltip: "Connect <foreign_key_table_name> records to this <main_table_name>."
    - recordedit create page
      - title: "Create new <foreign_key_table_name>"
      - submit button
        - text: "Save"
        - tooltip: "Save this record on the server"
        
### Recordset page
#### Deleting records (future work defined in issue #2148 )
  - delete button in top right
    - text: "Delete records"
    - tooltip: "Delete records from <table_name>."
    - multi select modal 
      - title: "Delete <main_table_name> records"
      - submit button
        - text: "Delete"
        - tooltip: "Delete the selected rows from <main_table_name>."
      - confirm delete dialog
        - title: "Confirm Delete"
        - text: "Are you sure you want to delete X rows?"
        - button: "Delete"
      - post delete modal (is this needed?)
        - title: "Batch Delete Summary"
        - text: "X rows successfully deleted. Y rows could not be deleted. Check the error details below to see more information."

#### Creating records
  - create button in top right        
    - text: "Create"
    - tooltip: "Create new <table_name>"
