### ISSUE TITLE
Long text field overflows box in card view.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#160]
If you have a long text field in card view, it should either trunkate or wrap in the card.  Right now it overflows the card.  See URL field in
https://dev.rebuildingakidney.org/chaise/search/#1/rbk:image?facets=(embedding_medium:term::eq::OCT)&layout=list&page=1

**Comment by robes** [comment]
@carlkesselman @karlcz @hongsudt should we just drop the card view?

**Comment by robes** [comment]
Let's consider dropping all but Table view. We ought to discuss with everyone who represents user groups and get a collective decision.

**Comment by hongsudt** [comment]
move this to wishlist and close the issue for now. 
https://github.com/informatics-isi-edu/chaise/wiki/Wishlist
