### ISSUE TITLE
Overall UX improvements for recordset modals and P&B add popups

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1603]
all modals:
 - [x] change "x" button to a "cancel" button
 - [x] cancel button should be grey still (not blue)

both add/unlink popups:
 - [x] ~tighten whitespace~
 - [x] ~rename "clear all" to "unselect all" for the selected rows filters~
 - [x] move submit/unlink button into modal header to the left of "cancel"
 - [x] add tooltips to these buttons
 - [ ] static tooltip for selected rows on the rows container (instead of each filter)
    - should it be a tooltip per selected row filter
    - or a tooltip on the row that contains all the selected filters

just add:
 - [x] links in disabled rows should have a different color (should still be clickable, just need to emphasize the row is "grayed" out)
 - [x] disabled rows should have a check mark in the checkbox
 - [ ] move "+" button to modal header (and change name to add)
    - moved the "+" button to be adjacent to the table and renamed it to "create"

**Comment by RFSH** [comment]
I am going to close this. We modified the UX of p&b add popup during the mitigation and I don't think the remaining tasks that are described here are relevant anymore.
