### ISSUE TITLE
Too much whitespace around boolean facets

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1608]
Notice the big whitespace gap between the facet title "Released" and first value "true".

![image](https://user-images.githubusercontent.com/4202842/43279465-dcf73860-90c2-11e8-96b2-3203df3cf4d3.png)

**Comment by hongsudt** [comment]
@RFSH can you work on this issue as well?

**Comment by RFSH** [comment]
The fix has been merged with master.
