### ISSUE TITLE
Error Modal "Ok" Button Behavior For Dismissible Errors

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1612]
Currently all the error modals have an "ok" button that by default will redirect users to another page (chaiseConfig.dataBrowser or homepage). This makes sense in most cases because we don't know the last stable page that users was in, and it's safer to redirect them to the top level page.

But in case of dismissible errors, the "ok" button can behave the same way as the "x" button. We should change the "ok" button in this case to just dismiss the modal. I think the only type of dismissible error that we currently have is the error that we're showing after deleting a record.

**Comment by hongsudt** [comment]
@RFSH @jrchudy Have we done this? Is this still an open issue?

**Comment by jrchudy** [comment]
We have not done this yet.

**Comment by RFSH** [comment]
This has been done as part of React migration.
