### ISSUE TITLE
Viewer app history support

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1625]
Viewer app needs to be able to handle a versioned catalog id (aka `/chaise/viewer/1@1234/...`).

**Comment by hongsudt** [comment]
@svoinea when you have a chance, can you verify whether the viewer app can support catalog version? e.g. if the catalog is passed through to subsequent ermrest calls, then we are good. Otherwise, we have to make that part of ermrest calls.

**Comment by svoinea** [comment]
If I'm looking at the right place, the viewer sets the `catalogID` in a `context` object by using the `parseURLFragment(location, context)` function.

To set the `catalogID` to the value of `1@1234`, it will expect the URL to be `/chaise/viewer/#1@1234/...`.

**Comment by hongsudt** [comment]
cool.. It sounds like the viewer app uses ermrestjs function..  Then that should be fine.


What about the pyramid generation? If the czi file get changed, will the pyramid file location be different?


________________________________

**Comment by svoinea** [comment]
The pyramid files are generated in the `/var/www/html/data/[year/]<checksum>` directory.

The location is independent of the catalog. It depends only on the `*.czi` checksum and optional on the `year`.

**Comment by hongsudt** [comment]
OK. It seems like the viewer app can deal with versions. I am closing this issue.
