### ISSUE TITLE
Logging in via globus get stuck trying to open the session resource

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#163]
Logging into a recent Chaise deployment using the `goauth` and `oauth2` provider solution gets stuck on the Seamonkey browser.  It keeps presenting a modal browser dialog to handle the disposition of the `/ermrest/authn/session` resource as if it were a download link.  Canceling results in seeing the raw text of the session resource (a JSON object) in the browser window.

I filed this under Chaise because it is apparent during a login sequence using the Chaise GUI, but I think it is more likely related to how the webauthn REST sequence is behaving...?

**Comment by ljpearlman** [comment]
This sounds like what would happen if the original /preauth call was made without a Referrer header (if there is a Referrer header in the call to preauth, then a successful login will redirect to that referrer; otherwise, it will just return the session info).

**Comment by karlcz** [comment]
Hmm, I started with the same https URL in both browsers, so I wonder
why the referrer header behavior would vary...

**Comment by ljpearlman** [comment]
If this works for you with other browsers, is it possible you've configured Seamonkey not to send Referrer headers (as a privacy setting, or something)?

**Comment by karlcz** [comment]
I've seen this error on other people's browsers sporadically while shoulder-surfing. I am starting to think it is a timing error or maybe related to accidental double-clicking of the authorize buttons on the globus auth page leading to weird failure modes.

**Comment by karlcz** [comment]
Setting this to current milestone since it seems to be an ongoing investigation.

**Comment by hongsudt** [comment]
@ljpearlman Is this still an issue?

**Comment by ljpearlman** [comment]
I don't know. @karlcz ?

**Comment by karlcz** [comment]
I haven't observed it recently myself.  I think multiple problems with login flow have been identified and addressed, including potentially many concurrent fetches for preauth resource due to aggressive 401 response handlers to ajax calls.  I suggest we close this as out of sync and submit new bugs if we find problems with our current integrations...
