### ISSUE TITLE
jQuery Version Issue

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1637]
After updating the jQuery version we're seeing odd behavior from our apps. When you go to any of the new apps, for a second or two, you can see all the unrendered templates that we have used. This is more visible in recordedit.

![image](https://dev.isrd.isi.edu/~ashafaei/wiki-images/chaise_issue_jquery_version.png)

**Comment by RFSH** [comment]
Following the discussion about the version of dependencies that we're using I spent a little time looking at our dependencies. The following are our js dependencies:

### Angular-ui Bootstrap
At first I though angular-ui is using bootstrapjs and therefore jQuery. But it seems like it doesn't require bootstrapjs/jQuery at all. Also angular-ui is feature-complete and the version that we have included is the latest. That dependency won't be updated and we don't need to worry about it.

### plotly.js
Doesn't rely on jQuery and can be ignored from this discussion.

### Bootstrap
bootstrap itself doesn't rely on jQuery and it's the js component that needs jQuery. We should make sure the jQuery version that we're using is compatible with our bootstrapjs version.

### Chaise Code And Test cases

Currently we're using jQuery selectors in all of our apps. The use of jQuery is minimal and it's mainly just the jQuery selector itself (and not any of its dependencies that might have been deprecated with the new version). So the jQuery update shouldn't affect any of them. Although the fact that we saw weird behavior from recordedit shows otherwise.

### AngularJS
AngularJS doesn't rely on jQuery but if it's present in the app, it will use it. Based on AngularJS documentation "jQuery 1.7 and newer might work correctly with AngularJS but we don't guarantee that.".  So if we really want to take care of "updating" our dependencies and realize that the newest version of jQuery won't actually work correctly with the new version of Angularjs, we might want to completely drop jQuery from our project.

**Comment by RFSH** [comment]
We had a discussion about this a while ago. We decided that we can do any of these three different possible options to resolve this. Since we didn't document it at a time and I wanted to make sure that is documented here, I'm going to add them here.


**Option 1:** Minimal required task to get the login/navbar apps going (so they can be integrated with deriva web apps):

- [ ] Remove jQuery dependency from login/navbar apps and all the directives that they are using.
- [ ] Remove jQuery from login and navbar app (chaise should stick to the current version that is using).
- [ ] Add `ng-jq` directive to login/navbar to make sure they are not using any jQuery.

**Option 2:** Upgrade Chaise jQuery

- [ ] Find jQuery version that is compatible with bootstrapjs
- [ ] Make sure non of chaise angularjs apps are using jQuery (add `ng-jq`)
- [ ] Make sure the jQuery usage in the code and test are compatible with the new version.

**Option 3 (preferred):** Remove jQuery from Chaise

- [ ] Make sure non of chaise angularjs apps are using jQuery (add `ng-jq`)
- [ ] Remove bootstrapjs and change any where in the code that is using it directly to use angular-ui
- [ ] Rewrite chaise code and tests to avoid using jQuery.

**Comment by RFSH** [comment]
### What We Have Done

The following are the few experiments that we have done to tackle this issue:

1. Upgrading jQuery and using the `ng-jq` in boolean-search:

@Divyata-Singh please complete this section.

2. Removing jQuery injection from login and navbar, trying the boolean-search:

@Divyata-Singh 


### Future Plan

Based on these experiments and what we learned from them, the following are the steps that we should follow:

- [ ] Remove jQuery usage from navbar/login apps and directives completely. To test this, you can use the standalone navbar/login apps. 
  - Create a simple static page that doesn't include jQuery by itself. 
  - Include the navbar/login app in your static page.
  - Remove the included jQuery from navbar.app.js/login.app.js
  - Make sure they work properly (By modifying the chaise code).
- [ ] Do some more experiments.
  - [ ] Make sure we can use jQuery selectors in protractor environment without including jQuery in the page.
  - [ ] Figure out why `ng-jq` didn't work. When we upgraded the jQuery, the forms where still broken even with the `ng-jq`. We should figure out what was the issue exactly? Was the `ng-jq` ignored or it was broken because of some other issues.
  - [ ] Upgrade the included jQuery in boolean-search and figure out why the un-rendered forms are displayed before the page completely loads.
  - [ ] Use CSS to hide the elements before load in boolean-search. This is just to make sure master branch is stable. We should tag the current code so we can get back to it later (if we decided to upgrade the jQuery).


The next step after these experiments could be either "upgrading jQuery" or "removing jQuery". This relies on the result of the experiments.

**Comment by vipul-21** [comment]
### Update
The jQuery usage from navbar/login apps has been removed [PR].(https://github.com/informatics-isi-edu/chaise/pull/1803). 
This [function](https://github.com/informatics-isi-edu/chaise/blob/e4cbb31d83bc8836b5543b903e8474769b663373/common/utils.js#L1151) has been removed from navbar and login as the navbar is assumed to be primarily at the top of the webpage. In general to test the usage of the same, the dropdown of `Require DOI?` on this [page](https://dev.rebuildingakidney.org/chaise/recordedit/#2/Common:Collection) will produce the behavior based on the size of the viewport.

**Comment by vipul-21** [comment]
### Old Code with the issue
The [old code](https://github.com/informatics-isi-edu/chaise/commit/b06d661c28ae51dbcb6ef5e1b7cc338687d7a9f5) which uses jquery3 has the  issue. To replicate it,
1) Checkout [this commit](https://github.com/informatics-isi-edu/chaise/commit/b06d661c28ae51dbcb6ef5e1b7cc338687d7a9f5) to get the chaise app.
2) Checkout [this commit](https://github.com/informatics-isi-edu/ermrestjs/commit/fac21690386b638a1d49694a0653deb48fc72e36) to get the compatible ermrestjs.
The reason for the issue is that jquery3.3.1 uses timeout function for the initial call to setup, whereas jquery1.11.1 does not. 
The following line of code in jquery3.3.1 was changed from :

> t?c():(w.Deferred.getStackHook&&(c.stackTrace=w.Deferred.getStackHook()),e.setTimeout(c))

to 
> t?c():(w.Deferred.getStackHook&&(c.stackTrace=w.Deferred.getStackHook()),c())

By doing so, the un-rendered forms are not seen.

### Usage of `ng-jq`:
Adding of tag `ng-jq` on the `html` tag forces the angular app to use jqLite instead of using the available jquery. 
This is verified by adding the `ng-jq` tag on `html` tag and the page is not loading as  with the following error:

> [jqLite:nosel] http://errors.angularjs.org/1.6.9/jqLite/nosel

This means that "Looking up elements via selectors is not supported by jqLite". [More information the issue.](https://github.com/angular-slider/angularjs-slider/issues/13)

**Comment by vipul-21** [comment]
As mentioned in the comment https://github.com/informatics-isi-edu/chaise/issues/1637#issuecomment-506554324 about updating the jquery to 3.4.1
There are couple of bugs found while doing the local testing which are mentioned in the [PR](https://github.com/informatics-isi-edu/chaise/pull/1808#issuecomment-509360664).

**Comment by hongsudt** [comment]
@RFSH @vipul-21 Are we done with this issue? If not, what are the remaining tasks to finish?

**Comment by RFSH** [comment]
The only remaining task was upgrading jQuery version of deriva-webbapps which seems to be done. I am going to close this issue.
