### ISSUE TITLE
Safari 9.0.2 won't render records page

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#164]
Looks like the recent release of Safari browse 9.0.2 is interfering with rendering of any records page. Should be able to reproduce by using that version browser and try to pull up any records page. All that appears is a blank page with just the header and footer (whether in FaceBase or vanilla chaise). 

Some possible resources:
apple's Safari 9.0.2 page: https://support.apple.com/en-us/HT205639
a third-party writeup about the release:
http://blog.appgrounds.com/content-blockers-track-browser-history/

**Comment by crisaless** [comment]
one other interesting thing is the new Safari breaks the use of http:// in the URL. Other browsers will change http to https but new Safari doesn't seem to.

**Comment by robes** [comment]
I just updated my system and am now running Safari Version 9.0.2 (11601.3.9). All the details pages are working for me. We need to find a local system that is having the problem.

**Comment by robes** [comment]
The redirect to the record page did not specify a trailing `/`. I.e., it was `/record` that got concatenated with the fragment identifier. When browsing to the resource the apache server will issue a permanent redirect to the `.../record/` resource. Some browsers will then strip away the `#...` fragment identifier and therefore will not have any parameters. We will fix the immediate issue by adding the trailing `/` by default. We should also improve our error reporting from the record page. There is already an issue for that.

**Comment by robes** [comment]
Fixed. Tested. and deployed to a production server.
