### ISSUE TITLE
Fix Custom Filter Display

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1651]
The custom filter is usually a long string without any whitespace. This was causing the tooltip to overflow. To temporary fix this, I have added whitespace after each `;` or `&` so the text can break. We need to fix this using custom styling for the tooltip.

[This](https://dev.rebuildingakidney.org/chaise/recordset/#2/Gene_Expression:Specimen/RID=N-H950;Stage_Ordinal=21;Stage_Ordinal=20;RID=N-GHRW@sort(Stage_Ordinal,RID)) is an example of a page with custom filter (any type of filter that is not understandable by faceting syntax will be like this). [This](https://github.com/informatics-isi-edu/chaise/blob/master/common/templates/recordset.html#L99) is where we are showing the Custom filter in chaise. As you can see I am calling the `transformCustomFilter` function. To see the old behavior remove this function and see how it overflows. We want to add some custom css rules to this tooltip to make sure it's not going to overflow.

We might also want to think about a better display for custom filter (turning `;` to `or`, etc.). This can be done later. It requires a clear documentation of how we want to transform the filter.

**Comment by hongsudt** [comment]
please review her work and close the issue.

**Comment by RFSH** [comment]
The css changes has fixed the overflow issue.
