### ISSUE TITLE
selectively offer null option in the facets

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1654]
Null constraints give the wrong results (e.g. not the results that normal users would expect). 

The only cases where null is ok to be in the facet are:
1. scalar column of the main entity
2. `M -> S1 -> S2 -> S3...` facet that consist of all outbound path
3. `M <- S1`  facet that has one-hop in-bound
4. `M <- S1 -> S2` : Depending on how we implement this, it might be safe to allow null option

Any path that is not listed above shouldn't allow null constraint. 

Also, since we can only do one left outer join (only one null constraint except the one in 1), once a null option is selected in group 2,3,or 4, we should disable the rest of the null that cannot be allowed. 
 
Note: 
For group 2, if we can distinguish between not-null outbound path (e.g. all fks are not null) v.s. not, then the not-null outbound path can be implemented with inner join, and therefore could co-exist with the one from 3 and 4.

**Comment by RFSH** [comment]
After reviewing this, we realized what's described in this issue is not completely true. I am going to close this issue and create another one in ermrestjs that will explain what needs to be done.
