### ISSUE TITLE
"Select All" Button In Multi-Select Modals

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1666]
Currently we're showing the multi-select modal in two different scenarios:

 - P&B add modal: Clicking on "Add" in related entities section for pure and binary association tables. This will allow users to create multiple rows for the pure and binary association table.

- Facet modal: Clicking on "Show details" (show more) in the choice picker facets. Users are expected to select filters that they want to be applied to the recordset page in this view.

In this mode, we're going to show two new buttons in the first cell of the table. "All" and "None". "All" will select the checkboxes for the rows that are in the current page. "None" will deselect all the checkboxes for the rows that are in the current page (If no checkbox is selected in the current page it won't have any effect). The behavior of "All" button seems to be confusing to the users. They might interpret it as any of the following.

- It will select all the matching rows with the current applied set of filters or facets. For example if they search for a value, they expect "All" to match all the records with this given search criteria. We currently cannot support this case. The output of the modal is a set of rows. In this case, we only know the search/filter/facet criteria but don't know the individual row of values.

- In case of facet modal, they might think that it will match _any_ values. To reduce the confusion in this case we might want to change the button names because we are providing users with such a feature. It's the checkbox that is below the search box.

**Comment by jrchudy** [comment]
The above suggested change has been made. The buttons now say `All on page` and `None on page`. I decided to use `on` instead of `in` based on what verb is used by google mail for their multi-select interface.

Assigning to @hongsudt  for review.
