### ISSUE TITLE
make navbar phone-friendly

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1675]
We should allow users to click to expand the sub-menu.

**Comment by jrchudy** [comment]
@hongsudt should the hover functionality be removed? or should we support both click and hover?

**Comment by jrchudy** [comment]
It was decided to only support click.

**Comment by jrchudy** [comment]
Assigning to @hongsudt  to verify this is working as expected.

**Comment by hongsudt** [comment]
Yes.. This is working as expected.
