### ISSUE TITLE
Clear control in all input types

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1680]
We want to have a control that allows the users to easily clear the value for all input types. Currently in `recordedit`, there is a clear control for date inputs, timestamp inputs, Asset selector inputs, and Foreign Key selector inputs. In the range inputs, we already have integer/float inputs and date/timestamp inputs with an `x` control to remove the values.

**Comment by hongsudt** [comment]
@jrchudy @RFSH  Should this be part of the style guide?

**Comment by RFSH** [comment]
This has been done as part of #1847.
