### ISSUE TITLE
integer filter is not presented correctly in facet panel

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1684]
If a filter of an integer type and with equality operation (e.g. GeneID=1234) is passed through the URL, even though the result set does incorporates that constraint, there is no indicator on the page that the filter is applied. 

This bug happens when the columns are not in the facet list, or if the facet mode is not range. 

We need a visual clue to present to the users all filters that have been applied in the result set. 

Here is the solution that @RFSH and I have discussed:
- If the facet is range, and the filter is choice, convert choice to range
- If the facet is choice, and the filter is range, create a new facet

**Comment by RFSH** [comment]
This is happening because ermrestjs doesn't look for the preselected filters when it's deciding what should be the appropriate UX mode. I'm going to change it to honor the filters in the url. ermrestjs will ignore the `ux_mode` that is defined on the annotation and honor the url.

**Comment by RFSH** [comment]
This has been fixed in the referenced PR (#740).
