### ISSUE TITLE
Better error message when the server is not available

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1692]
I got this error during the server upgrade on rbk. We should use a different error message e.g. server is not available, please try again later. I think it used to work that way. 

Internal Server Error
An unexpected error has occurred. Please report this problem to your system administrators.Click OK to go to the Home Page.

**Comment by jrchudy** [comment]
The difference was that you probably had a `500` error returned to you when you are expecting a `503` based on your debugging of why the error was thrown.

**Comment by hongsudt** [comment]
I think we decided that the error messages were appropriate.. So I am closing this issue.
