### ISSUE TITLE
export broken if you dismiss the login prompt

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1693]
from what I can tell. if you attempt to export (not logged in) and get the message that you must login, and then dismiss the login, then if you attempt to export (still not logged in) you get a “exporting…” dialog but there is no real attempt to export going on.

was attempted on a recordset app here:

https://dev.facebase.org/chaise/recordset/#1/isa:track_data/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JHQBcAjdafEASyTBABoQiMwsBrAfSjCLA4FswAByFUIAcw5gkSHPxIAbAJ4cAZmxxKQAXQC+jKjG2MsACxRVcSSgDEAggGEAogCE7AZSewAjAFoALDYAWk46+sjo2HgIoMRkaBQI1LQMTCzsXDx8GDhCCpY8OGoaWnr0sWik5DBJNHSMOXkFREU4AB5COBhU-DgQRMWaYYwASgCSACI6JuaWONZJAMz+AAwAbGF6QA@sort(RID)

**Comment by jrchudy** [comment]
@robes this has been fixed. Changes have been made to both `chaise` and `ermrestJS` to resolve this issue.

**Comment by RFSH** [comment]
@robes You're seeing a Terminal Error because ermrestjs is not updated on facebase-dev. It's working properly on other deployments that have both ermrestjs and chaise changes that Josh did to fix this issue.

**Comment by robes** [comment]
OK. I tested it out. Working great. thanks
