### ISSUE TITLE
Check Page.content In related entities

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1695]
If it results empty (template is wrong), it should be treated as if the table-display is missing (fall back to tabular display).

We might want to do the same for inline tables. Should we?

**Comment by hongsudt** [comment]
It is not just because the template is wrong, but also because the template is not applicable e.g. I can only apply treeview to mouse data only instead of all data.

**Comment by RFSH** [comment]
This has been merged with master. The new behavior regarding the nested tables are as follows:

inline table:

- If page.content is null (no matching rows), show None and a button to switch to tabular mode.
- If page.content is empty string (empty string, due to invalid or empty row_markdown_pattern result), show the tabular mode. Don't provide the switch button.
Otherwise show the page.content in markdown-container. Provide the switch button.

Related table:

- If page.content is valid and there are matching rows, show page.content in a markdown-container with the switch button.
- Otherwise show the tabular mode.

What has been changed is checking for empty result of page.content and also checking for null values in the related section. Previously, as long as a related table has the `row_markdow_pattern`, we were showing the markdown display even if it didn't have any matching rows.

Assigning to @hongsudt to verify the behavior.

**Comment by hongsudt** [comment]
This is now working as intended.
