### ISSUE TITLE
Batch-copy: change the confirmation modal

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1698]
In mutli-edit recordedit page (go to recordset and click on the edit button on top of the page), for each of the records we are providing a remove button. Using this button they can remove any of the forms from the view. Currently the modal that we are showing for confirmation of this action is confusing to the users. We're not actually deleting anything. The following are the new text that should be used for different parts of the modal:

- Title: "Confirm Form Removal"
- Content: 
```
<div style="margin-bottom: 10px">
Are you sure you want to remove this record from the form?
</div>
<div>
Note: Removing a record from this form, will not delete the record from database)
</div>
```
(you don't need to necessarily copy and paste it the way I wrote it. I just wanted to emphasis that we want two different lines with the given text and there should be 10px space between them).

- Button name: "Remove"

**Comment by hongsudt** [comment]
@RFSH can you review this and close it?

**Comment by RFSH** [comment]
The wordings are a bit changed (e.g, "form" v. "edit form") but it conveys the same message. I'm closing the issue.
