### ISSUE TITLE
Uploader widget progress bar gains and loses progress

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1701]
When uploading a file in chaise using hatrac, if the system storage is full (hatrac is out of space), the uploader UI appears to shift back and forth pretty often.

I believe this is an issue with the uploader widget in chaise that is incorrectly reporting data as uploaded when it's actually in a retry loop.

@karlcz  can you update this issue with a way to try to replicate this issue without actually maxing out the storage on the server?

Note: It doesn't look like github allows us to upload videos, there is a message pinned to the #isrd-chaise channel in slack that has a video showing this "bug".

**Comment by karlcz** [comment]
Without hacking on the hatrac service to generate spurious exceptions,
the next easiest would be to temporarily change ownership of the
hatrac storage directory so the web service cannot write to it, e.g.

   sudo chown -R root:root /var/www/hatrac

After testing is complete, you can restore it to the original
ownership again:

   sudo chown -R hatrac:apache /var/www/hatrac

**Comment by jrchudy** [comment]
This is no longer happening after we migrated the app to ReactJS. If there are other problem related to the progress bar in the upload modal, we can create a separate github issue to track them.
