### ISSUE TITLE
docs for templating have examples of double-{ instead of triple-{

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1703]
I believe the instructions are to always use triple-{ when specifying where to insert an attribute value in a template. The doc here still shows a double-{ which I assume is wrong. Look for `{{name}}` in a couple places in the example.

http://docs.derivacloud.org/users-guide/annotations/mustache-templating.html?highlight=encode#replacement-with-url-encoding-encode-name-encode

In fact, the example following the above referenced also have a `{{date}}` in the title and `{{name}}` in its example code.

**Comment by RFSH** [comment]
I updated the docs to fix the issues that you have mentioned. There's just one instance of double-{ in docs now just to explain that `{{value}}` will do HTML escaping.
