### ISSUE TITLE
history: support templating in navbarMenu

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1709]
Support templating in navbarMenu (e.g. we will not change the param name) especially `$catalog` object. 

If the URL is chaise URL, use the catalog from the URL. If not, use default catalog. 

If there is no default catalog specified, then treat it as if the navbar menu is not available.

**Comment by jrchudy** [comment]
The changes for this issue have been merged into master, reassigning to @hongsudt .

**Comment by hongsudt** [comment]
@jrchudy Can you figure out a version number on rbk for me to use for testing?

**Comment by jrchudy** [comment]
Looks like this data is snapshotted on February 20th:
https://dev.rebuildingakidney.org/chaise/record/#2@2R4-PHS4-ZTV2/Protocol:Protocol/RID=N-H9E2
