### ISSUE TITLE
Record: support rendering of a record without column header and table outline

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1710]
The goal is to present a record as a  normal HTML page.

To do this, we need to: 
- turn off column headers amd table outline
- collapse TOC by default
 
Attributes to be added to the table-display annotations: 
- `hide_column_headers` - controls whether column names and the lines between columns (technically between the <tr> rows in the DOM) are visible or not
- `collapse_toc_panel` - controls the open/closed state of the table of contents panel

Currently table-display annotation takes the following parameters: 
- "row_order": [ sortkey ... ]: 
- "page_size": _number_: The default number of rows to be shown on a page.
- "page_markdown_pattern"
- "row_markdown_pattern": rowpattern
- "separator_markdown": separator- "prefix_markdown": prefix
- "suffix_markdown": suffix
  
@karlcz @jrchudy @RFSH I would like to discuss this tomorrow

**Comment by jrchudy** [comment]
The changes for this issue have been merged, reassigning to @hongsudt .

**Comment by hongsudt** [comment]
I am closing this issue as Carl is using it now..
