### ISSUE TITLE
scroll to top of page on submission

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1713]
After submitting data in `recordedit`, the page should automatically be scrolled back up to the top so the user can see if an error alert is displayed.

**Comment by carlkesselman** [comment]
YES!!!


----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Feb 6, 2019, at 5:37 PM, Josh Chudy <notifications@github.com<mailto:notifications@github.com>> wrote:


After submitting data in recordedit, the page should automatically be scrolled back up to the top so the user can see if an error alert is displayed.

**Comment by jrchudy** [comment]
The changes for this have been merged into master.
