### ISSUE TITLE
Change default for resolverImplicitCatalog

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1718]
The `chaise-config` property, `resolverImplicitCatalog`, has 3 options currently. Their behavior is as follows:
 - catalog id
   - matches current catalog and resolver is setup for shorter links, resolver link is provided without catalog id (`/id/X` where `X` is the filter)
   - doesn't match, resolver link is provided with catalog id (`/id/N/X` where `N` is the catalog id and `X` is the filter)
 - `false`
   - always use resolver in catalog qualified form (`/id/N/X`)
 - not defined
   - don't use resolver at all

Proposed change:
- C: resolver on, /id/RID for /id/C/RID, /id/N/RID for others 
- false: resolver on, always use explicit /id/N/RID 
- null: disable use of resolver URLs 
- undefined/property absent from config: same as false

 - ~~catalog id:  behave the same as before~~
 - ~~`true` or not defined: always use resolver in catalog qualified form (`/id/N/X`)~~
 - ~~`false`: don't use resolver at all~~

**Comment by karlcz** [comment]
On Feb 12, Josh Chudy modulated:
> The chaise-config property, resolverImplicitConfig, has 3 options
...
> Proposed change:
> 
>   • catalog id
>       □ behave the same as before
>   • true or not defined
>       □ always use resolver in catalog qualified form (/id/N/X)
>   • false
>       □ don't use resolver at all
> 

I don't think this change makes sense with the original property
name.  We should either replace the property entirely with a different
definition or just carefully distinguish null and undefined:

- C: resolver on, /id/RID for /id/C/RID, /id/N/RID for others
- false: resolver on, always use explicit /id/N/RID
- null: disable use of resolver URLs
- undefined/property absent from config: same as false

**Comment by hongsudt** [comment]
I like @karlcz's solution as it doesn't break any backward compatibility.

**Comment by hongsudt** [comment]
@svoinea can you please help review the issue by testing this `resolverImplicitCatalog` chaise-config parameter? Chaise should react appropriately depending on the set value.

**Comment by svoinea** [comment]
I have tested it on `pbcconsortium.isrd.isi.edu`, and only the first case was working as expected by me:
```
resolverImplicitCatalog: 1
```
and `https://pbcconsortium.isrd.isi.edu/id/1-882P`, `https://pbcconsortium.isrd.isi.edu/id/1/1-882P` and `https://pbcconsortium.isrd.isi.edu/id/3/1-19RC` were OK.

I tried the other three cases:
```
resolverImplicitCatalog: false
```
```
resolverImplicitCatalog: null
```
and `resolverImplicitCatalog` missing, and all of them were honouring the  `https://pbcconsortium.isrd.isi.edu/id/1-882P`, which I expected it shouldn't.

`pbcconsortium.isrd.isi.edu` receives daily updates.

**Comment by karlcz** [comment]
@svoinea I don't understand your comment.  What do you mean that URLs were "OK" and what do you mean by, "all of them were honouring the <implicit catalog URL>"?

It sounds to me like you are talking about the behavior of the resolver. This setting `resolverImplicitCatalog` is for Chaise and of course will not not change the behavior of the resolver on the server in any way. It will only change the type of URL offered by Chaise in the share/bookmark GUI.

**Comment by svoinea** [comment]
By `OK`, I mean the URLs were converted to `https://pbcconsortium.isrd.isi.edu/chaise/record/#1/Beta_Cell:Dataset/RID=1-882P` or `https://pbcconsortium.isrd.isi.edu/chaise/record/#3/vocab:specimen_terms/RID=1-19RC`.

I have retested and confirm that the links that appears under the `Share` button are matching the description for all the four cases.

The issue can be closed from my point of view.
