### ISSUE TITLE
Include just the assets (css, js, etc) need for each page

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#172]
Right now we include a common %ASSETS% block in all of our html pages. So every page pulls in a lot more code than they need. The Makefile should be updated with dependency lists specific to each page.

**Comment by robes** [comment]
@hongsudt this is a very minor refactoring issue that we should schedule

**Comment by hongsudt** [comment]
@robes should we try to do this with the record2?

**Comment by chiragsanghvi** [comment]
This has already been addressed and completed.
