### ISSUE TITLE
Terminal error row[k] is null in recordedit

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1724]
To reproduce, go to:

https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Synaptic%20Pair%20Study/RID=19WJ

Attempt to set the only value available in the "Synaptic Region 1" modal picker and submit. I get a terminal error with the details saying only:

    row[k] is null

**Comment by jrchudy** [comment]
In the supplied use case it is iterating to the `Region 1 URL` (which has a value of `null` supplied) and it’s choking out our conditional check that “assumes” `row[k]` (the value of `Region 1 URL`) is defined. 

offending line of code:
https://github.com/informatics-isi-edu/chaise/blob/master/common/upload.js#L635

**Comment by jrchudy** [comment]
The configuration that caused this involved a combination of `nullok: true` on a disabled input field that was part of the visible columns list. There are no problems with that configuration, just a small change to the check to make sure it doesn't short circuit again.

**Comment by jrchudy** [comment]
@karlcz this has been fixed with [this commit](https://github.com/informatics-isi-edu/chaise/commit/49b9ca7563dab7b2c3655bf716545bc447fcc8a5) to master. Reassigning to you to verify it's fixed and to close this issue.

**Comment by karlcz** [comment]
Fix confirmed.
