### ISSUE TITLE
Improve Pre-fill When Creating New Related Entities

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1725]
When users click on "add" button for related entities, we navigate them to a recordedit page with pre-filled value for the foreign key relationship with the main table. We are currently only doing this pre-fill based on the foreign key value. We could improve this by pre-filling other foreignkeys as well. 

To better understand this, take a look at the following example:

- User navigates to the record page for `Study` table.

- `Study` has two keys.
  
  ```
  "keys": [
    {
      "unique_columns": ["RID"], 
      "names": [["s", "key1"]]
    },
    {
      "unique_columns": ["RID", "Data_Provider", "PI", "Consortium"],
      "names": [["s", "key2"]]
    }
  ]
  ```
- `Experiment` has two foreign keys to the `Study` table based on the defined keys and all the columns are not-null. 

- We are showing `Experiment` on the related section based on the `RID` foreign key.

- User clicks on "Add" button in `Experiment` table to create new rows in relation with the displayed row of `Study` table. Here, we expect two foreign keys to be pre-filled because `Study.RID` alone is determining the one-to-one relationship of this row to the rows that we want to create for `Experiment`.

This can be generalized as following:

- `T2` has multiple foreign keys to `T1` (`FK`, `FK1`, `FK2`, ...).
- `T2` is displayed in the related entity section of `T1` based on `FK` foreign key and what user sees in the record page is based on this relationship.
- Let's call the keys that all their columns are part of `FK`, "pre-fill keys". In the example above, `["s", "key1"]` is the only pre-fill key.
- When user clicks on the add button, in the opened recordedit page we should pre-fill all the foreign keys that all their columns are at least part of one of the pre-fill keys.

**Comment by karlcz** [comment]
As you said, the second foreign key column set must be a superset of the first foreign key columns in order for us to infer anything about its possible contents. Thus, the pre-fill for the first foreign key partially fills out the second foreign key.

Our conjecture is that the second foreign key must point to the same record and we can therefore copy over additional values to fill in the rest. We need to actually prove that by checking more conditions:

- The second foreign key points to a uniqueness constraint that is a superset of the uniqueness constraint used by the first foreign key.

Rationale: If the smaller set of columns is a unique key for the parent record, then that key plus additional columns MUST also be a unique key to the same parent record. There is no other possible configuration (other than NULLs) that can satisfy the schema constraints and allow the record to be written.

- The extra columns of the second foreign key have `nullok: false`.

In this case, the pre-fill values from the parent record are the only possible configuration. However, if any of the columns are `nullok: true`, then it would also be valid for the user to leave them blank and disable the second foreign key. There is nothing in the model to tell us which choice is the correct one, so it seems to me we would need an annotation to hint at which way to pre-fill...?

**Comment by RFSH** [comment]
The changes for this PR are now merged with master. Assigning to @hongsudt to review the PR.

**Comment by RFSH** [comment]
I am going to close this issue due to inactivity. If we found any problems we should create new issues.
