### ISSUE TITLE
navbar app pulls in chaise assets that cannot be found from the static site

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#1739]
the navbar assumes that all content is at the same level (since chaise is a one-page app). But on the static sites there are many instances of pages in different directories. 

When chaise pulls in other assets, the file paths start with a period which makes the links relative to the current location. 

This breaks the navbar on a page such as https://dev.gudmap.org/about/. 

When the navbar app tries to pull in  "./chaise/common/styles/app.css" for example, the resulting web path is: https://dev.gudmap.org/about/chaise/common/styles/app.css - which of course doesn't exist.

**Comment by jrchudy** [comment]
This is the expected behavior. Please see the [readme](https://github.com/informatics-isi-edu/chaise/blob/master/lib/navbar/navbar-app.md#dependencies). The linked section explains how to resolve this issue.

**Comment by crisaless** [comment]
I'm able to pull in those files correctly. But there are other assets that are pulled in after navbar is called and I can't change those paths.

**Comment by RFSH** [comment]
@crisaless Thanks for reporting the bug.  It should be fixed now. [This](https://github.com/informatics-isi-edu/chaise/commit/c94a9acf1f98c79f6e110b2cfa0edcaa40d9a5b2) is the commit that fixes it. Please let us know if that resolved the issue.
