### ISSUE TITLE
logging issues

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1740]
I am going to summarize the issues I found here, so that people might be able to refer to it when they look at their logs:  (as of 2019/03/13)
**Chaise**
- There are cid = 'record', but action is 'recordset/main'. This is caused by ... 
- There are cid = 'recordset', action='recordset/main/load' without table. These requests have incorrect action. They belong to the following events: 
  - pseudo-columns that ask for count e.g. `/ermrest/catalog/2/attributegroup/M:=RNASeq:Experiment/value:=Markers;count:=cnt(*)@sort(count::desc::,value)?limit=26`
  - the count used to show the facet list e.g. 
- viewer app only has logs that ask for schema
- no dcctx in webautn requests

**Webapps**
- heatmap has cid='null' and there is no detail in the log
- treeview/boolean-search need to add logging

**Log servers**
- Extract uinit from the r_path 

**Hatrac**
- incorrect content-type (see example below) 
    - @karlcz mentioned that this is because  log entries are buggy. They duplicate the same value in the `"type"` and `"range"` fields of the raw systemevents JSON blob. This may have been fixed in webauthn on 2018-10-26.  it was a bug in the common logging code implemented there and used in ermrest, hatrac, and exporter
```
708842289 | 2018-12-03 15:21:49 | HEAD     | /hatrac/resources/rnaseq/study/14-3PXT/experiment/14-3PY4/replicate/14-3PZ8/6007ec003038b604af54ed157d7a73f7.bam                                       | */0
708842156 | 2018-12-03 15:21:31 | POST     | /hatrac/resources/rnaseq/study/14-3PXT/experiment/14-3PY4/replicate/14-3PZA/6007ec003038b604af54ed157d7a73f7.bam;upload/IUB7WUCDNZ5TTUDQNZIYJN534U     | */140
```

**Others**
- There is no cid that are non-chaise
- There are many requests without u_track e.g. r_path=/internal/, webauthn path, etc. 
- No logging for navbar loading
- No logging for navbar links (not sure if possible)
- Should template be included in dcctx header in log?

**Comment by RFSH** [comment]
Chaise bugs have been fixed. Please refer to the [change log](https://github.com/informatics-isi-edu/chaise/blob/master/docs/user-docs/logging.md#041819) for more information about the changes.
