### ISSUE TITLE
history: share dialog should include live and versioned link

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1745]
@jrchudy commented on [Tue Feb 05 2019](https://github.com/informatics-isi-edu/ermrestjs/issues/758)

When the user is looking at a versioned `record` page, the share dialog should include a share link for the current versioned catalog and one for the live catalog.

**Comment by hongsudt** [comment]
@carlkesselman @robes @karlcz @ljpearlman Please review and close the issue if it is good.

**Comment by robes** [comment]
Its okay with me.
