### ISSUE TITLE
don't show table name when no search results are shown

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#175]
Currently we show a gray box with the text:

"
     TABLE NAME
Use the sidebar to the right to select search attributes.
"

Let's remove Table Name because it may cause confusion to see "Dataset" or "Image" displayed there. (But keep the box and the rest of the text)

**Comment by svoinea** [comment]
Done through the commit 0c0f2279e108d78061117734bca0ba596593a4ea.

**Comment by robes** [comment]
Github's markdown ruined the issue I entered above. What I intended this issue to say was to remove only the TABLE NAME but not the whole box itself. Can you please bring back the box but not display the table name in it?

**Comment by svoinea** [comment]
Done now through commit 08b1abc949d9de7ad1fcf7189477962034b4ce89.
