### ISSUE TITLE
improve citation annotation support with fkey traversal

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1750]
As I understand it, currently the citation annotation

http://docs.derivacloud.org/users-guide/annotations/annotation.html?highlight=citation#tag-2018-citation

only supports a "pattern" expansion for its values and to my knowledge the pattern expansion cannot be used to traverse inbound/outbound fkeys to get to the desired column.

For example, a collection to be cited is likely to have >1 author. To model that, I'd like to have an association table "Author" to associate "Collection" (to be cited) and "Person" (to be used as authors). Then I'd like to reference the first/last (or full) names from the Person table in the Collections citation annotation.

**Comment by hongsudt** [comment]
This is pending on the pseudo-column feature that @RFSH is working. I am moving this to blocked.

**Comment by robes** [comment]
@RFSH maybe this is done now?

**Comment by RFSH** [comment]
@robes Yes it is. Thank you for pointing it out.

You should be able to use normal one hop away outbounds without defining `wait_for` and the rest of pseudo-columns (including multi-hop all-outbound foteignkeys) using the `wait_for` list.

I am going to close this issue. If you found any issues with this feature please feel free to create new issues.
