### ISSUE TITLE
data picker doesn't let me set filter

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#176]
For example in the RBK dev host, I can click on a date attribute like "Submitted" and I can see the From and To dates. I can actually pick dates for each, but I have no way to set the filter.

**Comment by svoinea** [comment]
Each time you pick a date (different from the original one), the filter works and I can see the filtered results.
What seems not working is deleting that filter.

**Comment by howdyjessie** [comment]
I get the same behavior as Serban does as well.

**Comment by svoinea** [comment]
Fixed the bug for deleting a date filter in the commit 2c5bb798d3e42029aaf7a04f725a6b04a45e57de.
