### ISSUE TITLE
Log links with ?

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1760]
When a user uses a link that includes the `?` instead of the `#`, we want to log that information. We want to be able to see how many users come to our web app from indexed (and searchable) links.

**Comment by hongsudt** [comment]
We already agreed on the syntax.. Please document and close the issue.

**Comment by RFSH** [comment]
We're using `"cqp": 1` to indicate the link was using `?` instead of `#`. This is documented in [here](https://github.com/informatics-isi-edu/chaise/blob/master/docs/user-docs/logging.md#attributes)
