### ISSUE TITLE
Entity Facet doesn't show selection (when logged in)

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1761]
This issue occurs infrequently, but I was able to see it one time today. Login first and then close this browser tab to prevent any caching.
https://dev.gudmap.org/chaise/recordset/#2/RNASeq:Replicate

Make sure you are logged in before navigating to this page with facets:
https://dev.gudmap.org/chaise/recordset/#2/RNASeq:Replicate/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JHQBcAjdafEAJQDkBBAZRwEcQAaanABwBsBLLGCI4A+gy44sfALY4IIqgEkAIiIBmAaxwBPEAF0AvhyXL9HLAAsUAnEkoBGAGwBaAMwBRALIBxfQcNAA@sort(RMT::desc::,RCT::desc::,RID)

What happens is a term is selected in the `Specimen` facet, but it's out of view. You can see a filter present that shows that selection is made. 

This issue was first found on production, I pasted links to dev to be safe. I was able to reproduce on dev once, but more frequently on production.

**Comment by jrchudy** [comment]
Image of me replicating on dev:
![image](https://user-images.githubusercontent.com/2932600/56064954-58b76600-5d28-11e9-9bc7-8d3b08cb88b3.png)


Once the view is this way, you can search `RBK` and the option in the facet will be moved to the top of the list where it will remain even after the search box is cleared again.

**Comment by RFSH** [comment]
This has been resolved. Assigning to @jrchudy for verification.

**Comment by jrchudy** [comment]
I can't reproduce this issue anymore after loading from cache and turning off the cache. Closing this issue.
