### ISSUE TITLE
Create multiple forms performance

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1767]
Investigate the performance of `recordedit` app when in create mode and the user is using the "add X forms" dialog to add multiple forms at once. It was noted by a user that adding 50 forms was slow and that we should look into what could be causing this. 

At the very least, we can reduce the "upper limit" for # of forms added at once to limit the amount o "hang time" while waiting for all forms to render.

**Comment by jrchudy** [comment]
Compare how multiple forms are rendered in `edit` mode vs `create` mode, a difference between the two might have some clues into why one loads faster.

**Comment by jrchudy** [comment]
Recordedit load times:

<table>
  <tr>
    <th colspan=5>Gene_Expression:Specimen</th>
  </tr>
  <tr>
    <th></th>
    <th colspan=2>Create Mode</th>
    <th colspan=2>Edit Mode</th>
  </tr>
  <tr>
    <th># forms</th>
    <th>Cache Disabled</th>
    <th>Cache Enabled</th>
    <th>Cache Disabled</th>
    <th>Cache Enabled</th>
  </tr>
  <tr>
    <td>25</td>
    <td>5 seconds</td>
    <td>3 seconds</td>
    <td>13 seconds</td>
    <td>3 seconds</td>
  </tr>
  <tr>
    <td>50</td>
    <td>5 seconds</td>
    <td>4 seconds</td>
    <td>14 seconds</td>
    <td>5 seconds</td>
  </tr>
  <tr>
    <td>100</td>
    <td>7 seconds</td>
    <td>5 seconds</td>
    <td>18 seconds</td>
    <td>7 seconds</td>
  </tr>
  <tr>
    <td>200</td>
    <td>11 seconds</td>
    <td>10 seconds</td>
    <td>21 seconds</td>
    <td>13 seconds</td>
  </tr>
  <tr>
    <th colspan=5>Common:Collection</th>
  </tr>
    <td>25</td>
    <td>3 seconds</td>
    <td>3 seconds</td>
    <td>4 seconds</td>
    <td>3 seconds</td>
  </tr>
  </tr>
    <td>50</td>
    <td>4 seconds</td>
    <td>3 seconds</td>
    <td>4 seconds</td>
    <td>3 seconds</td>
  </tr>
  </tr>
    <td>100</td>
    <td>6 seconds</td>
    <td>5 seconds</td>
    <td>4 seconds</td>
    <td>3 seconds</td>
  </tr>
  </tr>
    <td>200</td>
    <td>10 seconds</td>
    <td>9 seconds</td>
    <td>4 seconds</td>
    <td>3 seconds</td>
  </tr>
</table>

**Comment by jrchudy** [comment]
While evaluating the code, there's one glaring difference between the process of going to create mode and adding 199 more forms to add content to and going to edit mode with 200 forms preselected (some filter combination and `?limit=200`.

The major difference is that in the case of edit, we fetch those 200 rows of data and don't need to do anything extra to transform that data and show it in the DOM. In the case of create, we see an ever increasing time as the number of forms being added increases. This is because for each new form we need to add to the DOM, we have to run a loop that copies 3 different objects and pushes them into each array that is used to track the state of the DOM and submission data. The offending lines for create mode are [L385-L395](https://github.com/informatics-isi-edu/chaise/blob/master/recordedit/form.controller.js#L385-L395).

```js
for (var i = 0; i < vm.numberRowsToAdd; i++) {
  var row = angular.copy(protoRow);
  // transform row values to avoid parsing issues with null values
  var transformedRow = transformRowValues(row);
  var submissionRow = angular.copy(vm.recordEditModel.submissionRows[index]);
  var foreignKeyData = angular.copy(vm.recordEditModel.foreignKeyData[index]);

  rowset.push(transformedRow);
  vm.recordEditModel.submissionRows.push(submissionRow);
  vm.recordEditModel.foreignKeyData.push(foreignKeyData);
}
```

**Comment by jrchudy** [comment]
![image](https://user-images.githubusercontent.com/2932600/60129747-8ff3bb80-974a-11e9-820e-442da846de5c.png)

**Comment by jrchudy** [comment]
![image](https://user-images.githubusercontent.com/2932600/60477799-351fff80-9c35-11e9-9b9e-3b30611b644f.png)
![image](https://user-images.githubusercontent.com/2932600/60477837-5b459f80-9c35-11e9-9b00-2ba5471503bf.png)

The above 2 charts compare adding X forms performance in create mode for a complicated schema with a lot of foreign key inputs (Gene_Expression:Specimen) vs a simple schema with all text columns.

In both Chrome (first graph) and FF (second graph), adding only text inputs does run faster than if we compare it to a more complicated schema. The above data in each graph is in the context of one browser.

The graph below, compares Chrome to FF for the create mode performance with all text columns.
![image](https://user-images.githubusercontent.com/2932600/60477991-ef176b80-9c35-11e9-95a2-66be14fbbee0.png)

**Comment by hongsudt** [comment]
@jrchudy we should move this to pending or close the issue..
