### ISSUE TITLE
Chaise search app hangs on forbidden response to GET schema

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#177]
If the user signs in but is not authorized to see the catalog, ERMrest returns a Forbidden error to the GET /ermrest/catalog/N/schema request and Chaise search hangs rather than displaying a forbidden error.

**Comment by svoinea** [comment]
Fixed in commit 347e656449d6b9178f6e7eefc4b2caf6f2084927.
An alert will be displayed for the HTTP errors.
