### ISSUE TITLE
Google dataset (hidden json-ld) support

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1771]
I'd like to use one of Google's enhanced SEO features on some of our record pages. This would require including a section that looks like this:

<script type="application/ld+json">
_some metadata_
</script>

somewhere in the body of the record page. So I'd like to have chaise support an annotation that would take a string, do markdown/handlebars rendering, and wrap it in the above `script` tags. This won't be visible to the normal end-user, so it doesn't matter where on the page this section appears.

**Comment by carlkesselman** [comment]
Given that the fields in this JSON-LD are well defined, I would hope that we could build out conventions to automatically generate much of the information, rather then have to spell it out explicitly in the annotation.  For example, title, author, description, date fields would I think all be straight forward.  Other information should be provided by somehow defining a mapping between columns (or column names) and the associated schema.org<http://schema.org> identifiers.  So I would rather have the ability to provide a schema.org<http://schema.org> mapping per column defined and then some code that would look for the appropriate columns and use that to construct the dataset description.


Carl


On May 3, 2019, at 1:45 PM, ljpearlman <notifications@github.com<mailto:notifications@github.com>> wrote:


I'd like to use one of Google's enhanced SEO features on some of our record pages. This would require including a section that looks like this:

<script type="application/ld+json"> _some metadata_ </script>

somewhere in the body of the record page. So I'd like to have chaise support an annotation that would take a string, do markdown/handlebars rendering, and wrap it in the above script tags. This won't be visible to the normal end-user, so it doesn't matter where on the page this section appears.

**Comment by ljpearlman** [comment]
I agree that this should be our end goal, but I'd like the flexibility of playing around with it a little (without having to have a bunch of chaise changes) before settling on the final heuristics for the json-ld contents.

**Comment by carlkesselman** [comment]
Ok, but we should all be aware that the overall path is to have semantic annotations to the columns so we can generate JSON descriptions of our tables. I guess in general we should be having columns with OIDs, then we can have local column name or external term as column name to describe what the contents of the column is.  Basically attach some json-ld that describe the column.

Carl


On May 3, 2019, at 2:00 PM, ljpearlman <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree that this should be our end goal, but I'd like the flexibility of playing around with it a little (without having to have a bunch of chaise changes) before settling on the final heuristics for the json-ld contents.

**Comment by hongsudt** [comment]
@ljpearlman  Can you do an experiment with a few collections (E.g. Saving chaise page as html) or the publication page and make modification there?  The publication page is a list of all publications.


________________________________

**Comment by RFSH** [comment]
I'm going to close this issue in favor of #1801 since it has more information.
