### ISSUE TITLE
Minimize duplication of code for the reuse of configuration module

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1774]
A configuration app is being attached to each angular app that we have that needs the navbar (the configuration fetches the server object and waits for `ermrestJS` to finish initializing which allows for templating in the navbar). Currently, the following is duplicated across almost every angular app in our project:
```js
angular.module('<namespace>.configure-<appname>', ['chaise.config'])

    .constant('appName', '<appname>')

    .run(['$rootScope', function ($rootScope) {
        // When the configuration module's run block emits the `configuration-done` event, attach the app to the DOM
        $rootScope.$on("configuration-done", function () {

            angular.element(document).ready(function(){
                angular.bootstrap(document.getElementById('<appname>'), ["<namespace>.<appname>"]);
            });
        });
    }]);
```

Updated with simpler configuration with content from the doc linked below.

**Comment by RFSH** [comment]
I created [this doc](https://github.com/informatics-isi-edu/chaise/blob/master/docs/dev-docs/config-app.md) to summarize what exactly needs to be changed in different webapps that rely on chaise-config. I'm not sure whether we can make this shorter without changing the current implementation.

**Comment by hongsudt** [comment]
@jrchudy Didn't we discuss about this prior to my trip to not use the chaise namespace?
