### ISSUE TITLE
Improve Multi-Picker Modal UX

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1776]
When users are selecting new rows for the "add pure and binary" feature, we're showing a multi-picker modal. The current UI is cluttered and confusing. The following are list of issues that I could think of:

- When the facet panel is open, since the focus of the page is not on selecting the main rows anymore, it might be confusing what is the main action of the page.
- The list of "selected rows" is almost identical to the list of "selected filters". There's no indication of which is which.
- We're showing multiple "spinner" and loading indicators.
- There are two vertical scroll bars. One for the table and one for the modal (so you can see the full list of facets and next/previous buttons).
- The facet panel height is not set properly. So it doesn't have any scrollbars and you have to scroll the whole modal to see the rest of facet list. This is causing scroll to facet to not work properly.

I'm not sure how we should go about improving this and after discussion with @hongsudt we decided that we should at least create an issue and document this.

**Comment by jrchudy** [comment]
The following 2 cases should be considered together:
> When the facet panel is open, since the focus of the page is not on selecting the main rows anymore, it might be confusing what is the main action of the page.

> The list of "selected rows" is almost identical to the list of "selected filters". There's no indication of which is which.

This has distracted me from the purpose I was opening a modal for. There have been times I have selected a filter instead of an option because the set is only size 4 and a similar filter was open by default. It was user error, but I can imagine some users would not realize how they goofed up thinking one selection was the other one.

**Comment by RFSH** [comment]
It's the same as  #1603  and #1815 issues, therefore we closed this.
