### ISSUE TITLE
Under Share on record page, change Historical to Versioned

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1777]
It seems like people do not understand what "Historical Link" mean.. @crisaless  and @carlkesselman suggested changing the wording from "Historical Link" to "Versioned Link".

**Comment by jrchudy** [comment]
[This commit](https://github.com/informatics-isi-edu/chaise/commit/d898554285faa7368340c8098e5dbc6895db421c) to master includes the changes for this. Reassigning for review.
