### ISSUE TITLE
url parameter to hide the navbar

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1790]
Sometimes we want to embed the chaise page in another page.. In this case, it doesn't make sense to display the navbar.. 

hideNavbar=true|false

@robes do you still need this feature?

**Comment by robes** [comment]
not sure. we might. we should probably discuss the whole anatomy/atlas navigation. b/c that was the motivation for this.

**Comment by jrchudy** [comment]
Outside of an iframe, we will continue to show the navbar by default. This parameter will be honored for the page that the user is currently looking at. If they navigate away, it will not carry along the query parameter.

Inside of an iframe, we will hide the navbar by default. This property will be honored if present and propagated to any links that are contained within the iframe (if the links are contained within a chaise app). Meaning that, `hideNavbar=false` can be defined, to always show the navbar in the iframe.

**Comment by jrchudy** [comment]
@hongsudt  this feature has been merged into master. More info about the query parameter can be found [here](https://github.com/informatics-isi-edu/chaise/blob/master/docs/user-docs/query-parameters.md).
