### ISSUE TITLE
The error message for duplicate key should contain a hint to create an entry

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#1795]
The user would like the error message to include a hint for using the `+` link to create a new entry in the referred table, and then to select that entry as a FK value.

See issue https://github.com/informatics-isi-edu/protein-database/issues/9

**Comment by hongsudt** [comment]
@svoinea The new UI now makes the + button explicit.. This should help address this problem. I am going to close this issue.. If this is still an issue in pdb, please reopen.
