### ISSUE TITLE
Add "requires javascript" message when javascript isn't enabled?

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1811]
This is kind of a niche issue, but since not everyone has javascript enabled globally, it might be good to display a message about chaise requiring javascript instead in that case. This seems to be pretty standard for other javascript-dependent applications. Currently chaise just looks like a blank screen in non-javascript-enabled browsers.

**Comment by RFSH** [comment]
This is done [in this commit](https://github.com/informatics-isi-edu/chaise/commit/29a1dfdb4d27934fa6b2bee5f35ff0ca79524ad1). We're going to show a error modal when Javascript is not available.
