### ISSUE TITLE
Error on related table Add

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1816]
When a user encounters an error when trying to associate 2 entities via the pure and binary association modal dialog, the modal disappears, and the user is left looking at the page wondering what is wrong. 

This is because the error is shown at the top of the page in an alert dialog. We should show a dismissible error modal dialog instead so the user will see the issue as soon as the multi-select modal dialog disappears. It should be dismissible so it doesn't affect the state of the page and the users can continue to work on the page.

We decided to handle [this error dialog](https://github.com/informatics-isi-edu/chaise/issues/1461) in the same way on record page so the user sees the error right away instead of adjusted where they are on the page.

**Comment by hongsudt** [comment]
lets fix this ux issue

**Comment by jrchudy** [comment]
When associating 2 entities via the add button in record app for a pure and binary association, this dismissible error dialog will be shown to the user instead of the alert dialog at the top of the page:
![image](https://user-images.githubusercontent.com/2932600/62580519-27c0eb00-b85b-11e9-845d-d895296634b5.png)

**Comment by hongsudt** [comment]
@RFSH @jrchudy is this fixed?

**Comment by jrchudy** [comment]
This issue has been fixed. PR #1833 resolved this. Reassigning to @hongsudt .
