### ISSUE TITLE
Remove unnecessary statistical queries

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#182]
Loading the search app runs many statistical queries just to bootstrap the facet search page. We stopped displaying things like count but we still do the queries. We also do not need the heuristic ordering of columns (i.e., those that go on "top" based on a small computation).

We need to remove as many of these as possible:
 - count's
 - min's
 - max's
 - etc

**Comment by robes** [comment]
This should be prioritized.

**Comment by svoinea** [comment]
Fixed in commit 68566ab014c041aec59b29f1fb4f3bfb676f6a95.
Whenever possible, multiple requests for the table columns were combined into a single request.
