### ISSUE TITLE
Calling the ErrorService directly makes the dialog box overlap Navbar

### ISSUE THREAD

**Issue by vipul-21** [informatics-isi-edu/chaise#1822]
After the update of jquery to 3.4.1, the exception thrown to the global exception handling was being handled by jquery making the error being handled by `window.onerror` instead of the angular exception handler(desired behavior). 
To get the desired behavior, `ErrorService.handleException` was called directly instead of `throw exception`. The resulting error modal was overlapping with the navbar, (refer image).
![Screen Shot 2019-07-08 at 5 30 47 PM (1)](https://user-images.githubusercontent.com/8600441/61236444-dfdff580-a6ec-11e9-8448-ecbb885c7925.png)
The desired behavior is:
![Screen Shot 2019-07-15 at 10 41 44 AM](https://user-images.githubusercontent.com/8600441/61236619-48c76d80-a6ed-11e9-8ade-5f43fc8ae8ae.png)
Note: The issue is not related to jQuery, it will happen even if we call `ErrorService.handleException` in with the previous versions of jQuery.
The issue is in the branch `updateJquery`. Currently the  `ErrorService.handleException` is only called in the `recordset.app.js`.

**Comment by jrchudy** [comment]
I thought you determined that this issue occurred for you regardless of what version of jQuery we are using?

**Comment by vipul-21** [comment]
Yes, it is not dependent on jQuery. Just wanted to give the picture, how we landed up to the issue. Updated the issue.

**Comment by hongsudt** [comment]
is this still an i ssue with the updates?

**Comment by jrchudy** [comment]
This bug is not related to jQuery. Seems to only be reproducible for @vipul-21 .

**Comment by jrchudy** [comment]
Closing this issue as not reproducible.
