### ISSUE TITLE
Hard references to www.facebase.org in Angular templates

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#183]
On other projects like gpcr-dev I can view HTML and see references to www.facebase.org which are probably supposed to be relative URLs for the current server.  The ones I noticed are related to the XTK viewer but there may be more.

**Comment by robes** [comment]
I wouldn't think these would be references to XTK viewer. I would think they may be the help link and another similar one from the chaise configuration. That's where I would suggest looking first:

`<base dir>/chaise/chaise-config.js`

**Comment by robes** [comment]
Okay... I see it. Should have just done a quick repo search. Yes, its the XTK viewer / preview stuff.

The offending lines of code are here:
https://github.com/informatics-isi-edu/chaise/blob/master/record/index.html.in#L107-L108

**Comment by karlcz** [comment]
grep for www.facebase.org in record/index.html.in

**Comment by robes** [comment]
The bit of remaining ugliness is that it expects the viewers to be found at the origin host under a specific path.

```
Embedded image viewer =>
origin + '/_viewer/xtk/view_on_load.html?url=' + PREVIEW_URL
```

```
Full size image viewer =>
origin + '/_viewer/xtk/view.html?url=' + PREVIEW_URL
```

This could be resolved through some annotation but I think we should step back a bit and decide where we want to go with this really, before putting more effort into it right now.

**Comment by robes** [comment]
The fix can be viewed here:
https://dev.misd.isi.edu/~schuler/chaise/record/#1/legacy:dataset/id=4409

**Comment by karlcz** [comment]
I still see my browser trying to access facebase.org (in my 3rd party request blocker) and I still see stuff like this with view source:

`<a href="https://www.facebase.org/_viewer/xtk/view.html?url={{ preview.preview }}" target="_blank" class="enlarge">Enlarge</a>`

I am looking at https://dev.misd.isi.edu/chaise/record/#1/legacy:dataset/id=263 for example.
