### ISSUE TITLE
Investigate Custom styles (min width)

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1839]
Custom styles that use min-width and max-width are sometimes not honored when applied to table headers and table cells. It appears that the contained content (markdown vs HTML) may be causing this inconsistency in how the styles are being applied (or ignored).

**Comment by jrchudy** [comment]
Some more info found while working on the style guide:

When a table column has `max-width: 100px;`, the max width is not honored sometimes. This is believed to happen when the content of the column (in the header or any of the cells below) is greater than 100px. This was found out when trying to set a max-width for the `Actions` column so that it won't get stretched by the responsiveness of the CSS.

**Comment by jrchudy** [comment]
I updated `docs/user-docs/custom-css.md` with information that was noted above about `max-width` as well as extra information for `min-width`.

**Comment by jrchudy** [comment]
Reopening and assigning this issue to @hongsudt to verify if these "notes" help to explain the min/max width issues she has been seeing.

**Comment by hongsudt** [comment]
@jrchudy If the min-width set is too small for the content, it is pretty much get ignored, correct? Whatever width that will fit the content will be used instead?  

> If the content is longer than the min-width, the width will be at minimum the value set for min-width and get wider to accomodate the content.

**Comment by jrchudy** [comment]
Yes that's correct. Min-width will be ignored if the content is longer than the min-width.
