### ISSUE TITLE
create style guide

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1841]
Create a chaise style guide that can be referenced as developers are working on chaise.

**Comment by RFSH** [comment]
A draft version of this has been created as part of #1847 but we need to update it based on the recent changes.

**Comment by jrchudy** [comment]
The version created during mitigation ca be found here:
https://dev.rebuildingakidney.org/chaise/docs/style-guide/style-guide.html

This might need to be updated and modified further. Closing this issue for now.
