### ISSUE TITLE
Client event logging

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1843]
- [x] Review the logging information in [docs/user-docs/logging.md](https://github.com/informatics-isi-edu/chaise/blob/master/docs/user-docs/logging.md#button-action-list). 
- [x] Change chaise/ermrestJS to make HEAD requests to the server to store that log info.

**Comment by hongsudt** [comment]
@RFSH since we went over your document structure, do we still need to keep this issue open?

**Comment by RFSH** [comment]
No, we don't. I am going to close the issues related to log changes.
