### ISSUE TITLE
clean up profileURL chaise-config property

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1845]
Currently if you define `profileURL`, it will not show the login dropdown anymore. Instead it will just show the link to the defined `profileURL`. The problem in this case is that the users won't be able to logout anymore.

We should either completely remove the `profileURL` property, or rewrite how it's used. We might want to move the `profileURL` to the dropdown menu. And then switch between opening a modal or link. This way the users also have the option to log out.

**Comment by jrchudy** [comment]
@ljpearlman  @robes @karlcz @carlkesselman  do we need to continue to support this chaise config property?

This is what we have as the description of the `profileURL` property:
> When a user is logged in, the navbar displays the user's username. Use this parameter to specify what the username in the navbar should link to (e.g. https://www.globus.org/app/account if your deployment uses Globus authentication). If profileURL is unspecified, the navbar will display the username as regular text.

**Comment by robes** [comment]
I’m not using it anywhere to my knowledge. -- rob

**Comment by RFSH** [comment]
We decided to remove this property in #2129 since the same behavior can be replicated with the newly added `loggedInMenu` property. Please refer to the PR for more information.
