### ISSUE TITLE
Default layout of Embedded table.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#185]
would it be possible/desirable to change the layout of long and thin embedded tables to default in transpose view?

**Comment by robes** [comment]
yes, we should do this.

**Comment by mikedarcy** [comment]
The way this heuristic is currently implemented doesn't sit too well with me.  It looks like the way that it is coded is that if the row count is simply above a certain threshold, it transposes.  This is not sufficient.  It should also require a column threshold that needs to exceed a certain limit as well.  As is stands, every table that is encountered over 5 rows is transposed, regardless of the column count.  That is not always what you want, especially if you have a reasonably small number of columns to fit in the page width.

**Comment by robes** [comment]
It should be easy to add a column count threshold on this feature. And we can make it default to normal (non-transposed) mode.
