### ISSUE TITLE
External Link

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1851]
Currently we're using `.external-link` class to show a modal upon clicking links. This is just to warn users that they are exiting the website. Also it is the DBA's responsibility to add this class to the links that they want. We should improve this. These are the proposed set of changes:

- ermrestjs should add this class automatically while it's rendering the markdown values by comparing the given link origin with the current origin. 
- There should be a chaise-config property that turns off the explained behavior in the previous item. DBAs should still be able to add the class manually (even if they define a chaise-config to turn it off), and chaise should show the modal.
- We should add a chaise-config property that allows us to define aliases for the origin (this will allow us to treat gudmap and rbk the same, and act as if they are the same origin).

**Comment by RFSH** [comment]
We should also add an extra class (`external-link-icon`), that will show an icon after the links. This should be added automatically all the time (doesn't have to honor the chaise-config that turns off the `external-link` addition). It should honor the chaise-config that defined aliases for origins.

While discussing this we realized that for external download links we might want to change the icon completely (instead of having both download icon and external link). One suggestion was the bootstrap `cloud-download` icon (https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_glyph_cloud-download&stacked=h).

**Comment by jrchudy** [comment]
This issue is related to #1040 .

**Comment by RFSH** [comment]
This has been done as part of #1847. The following is how we ended up implementing it:

- We're using the a chaise-config property called `internalHosts` to figure out if a link is external or not. We're always going to include the current host in that array (even if you don't include it).
- ermrestjs will automatically add `external-link-icon` to all the external link.
- The `disableExternalLinkModal` chaise-config property dictates whether we should add `external-link` class to external links (this class will change the behavior of links to open a modal first).

**Comment by RFSH** [comment]
We've merged the PR that does these changes to master. Assigning to @hongsudt for verification.

**Comment by hongsudt** [comment]
Confirmed the feature on this page: https://www.gudmap.org/chaise/record/#2/Common:Gene/RID=Q-3KXE
