### ISSUE TITLE
Punctuation enhancement for formatted display of data citations

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1853]
I think we are following this https://www.nature.com/documents/nr-data-availability-statements-data-citations.pdf

And it looks to me like you've got it right.

<img width="609" alt="Screen Shot 2019-09-20 at 5 16 54 PM" src="https://user-images.githubusercontent.com/4202842/65364981-80113980-dbca-11e9-8aa9-2a1f7353dd83.png">

Minor minor nit here. I think that (conditionally) adding a period after the author, title, and publication fields would enhance it. Conditional logic should be to the effect of: `if (field != null && !field.endsWith('.') { ...add a '.' ...}` so that we don't add an extra '.' if its already present in the field.

**Comment by hongsudt** [comment]
@robes We are not adding that to all the fields though right? Just the author and title? 
I looked into the punctuation in the past and didn't find it being used especially when there is no title. The example in the URL seems to apply the punctuation at the title field. 

 Hao, Z., AghaKouchak, A., Nakhjiri, N. & Farahmand, A. Global Integrated Drought Monitoring and Prediction System (GIDMaPS) Data sets. figshare http://dx.doi.org/10.6084/m9.figshare.853801 (2014)

**Comment by robes** [comment]
Right, just author and title. We have used this annotation in facebase and put punctuation into the author and title fields. That might be good enough for the time being. One thought is whether this is an issue unique to the citation formatting of whether this is something that could be more general and possibly solved at the handlebars level. Its really a conditional formatting based on the contents of a variable in the environment.

**Comment by robes** [comment]
Thanks. +1

On 2/26/24, 6:15 PM, "Hongsuda" ***@***.***> wrote:


Let's re-evaluate.

https://support.nature.com/en/support/solutions/articles/6000237618-correctly-citing-and-referencing-your-dataset-for-maximum-impact<https://urldefense.us/v2/url?u=https-3A__support.nature.com_en_support_solutions_articles_6000237618-2Dcorrectly-2Dciting-2Dand-2Dreferencing-2Dyour-2Ddataset-2Dfor-2Dmaximum-2Dimpact&d=DwMCaQ&c=qzHnJIRvjI6L-clJH8JwLQvf_Iq43fzikf6aoxZgMb8&r=0gYZbPLHj9UJxjxh12Y9VQ&m=TmPGP5tu1rIdVBv5uwqL4yZgXcUJM3CLj-GD5YBscQ69KWKdzm3m2_rrpizc4UzE&s=XVUJgbqI8YTMzmceAHWLSS8hGSnjLTsw4EqUaBRW3Eg&e=>

**Comment by jrchudy** [comment]
Another link to nature with more examples:
https://www.nature.com/sdata/publish/submission-guidelines

From these 2 sources that hongsuda linked:
 - authors
   - `,` between authors is a simple solution but not after the last one
   - `,` between authors with `&` between the last 2 instead of a comma
   - examples have a period after each value including the last one but I think that's because the "name" is abbreviated
 - title
   - "nature portfolio" has `.` after the title before the publisher
     - other link from nature follows this format with publisher _italicized_
   - "scientific data updates" uses _italics_ with no punctuation
     - might be because these examples only have a publisher with no title?
 - publisher
   - no italics in one case and italics in the other

**Comment by jrchudy** [comment]
We've decided to go with adding a period after the `author_pattern` and after the `title_pattern` as suggested. If there is already a period, we won't add one.
