### ISSUE TITLE
Safari-specific recordedit issues

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1854]
1. Try this in Safari:

1. Go to https://www.gudmap.org/chaise/record/#2/Gene_Expression:Specimen/RID=16-CT58
2. Log in.
3. Scroll down to "Specimen Expression" and click "Add"
4. Try to select an "Expression scored" value. At this point, you should see (and would see if you did this in Chrome) a popup with the first 24 of 6000+ options. Instead, in Safari, you'll get the error "400 Bad Request The request is malformed."
5. Dismiss the error popup and the "Choose Anatomy" popup.
6. Repeat step 4. This time the selection window will pop up without displaying an error, but there will be no rows of data (and again, there should be the first 25 of 6000+).

The same thing happens even if I wait a while between steps 3 and 4.

This all works correctly for me in Chrome. You can also see the same (broken Safari / working Chrome) behavior if you substitute dev.gudmap.org in the above URL.

2. I can't reproduce this, but @hongsudt and I watched a GUDMAP user, using Safari, try to bring up a selection on a recordedit page and have an empty page pop up (instead of the selection choices). I believe she was on https://www.gudmap.org/chaise/recordedit/#2/Gene_Expression:Specimen/RID=16-2BJ2@sort(RCT::desc::,Stage_Ordinal,RID)?pcid=record&ppid=285e1fr22ftw2lq72lx121bf trying to change Curation_Status.

**Comment by RFSH** [comment]
It seems like the `domain_filter_pattern` that is defined for one of the [`Gene_Expression:Specimen_Expression`](https://www.gudmap.org/ermrest/catalog/2/schema/Gene_Expression/table/Specimen_Expression/foreignkey) foreign keys is not properly url-encoded. 

I updated the annotation document regarding `domain_filter_pattern`.  the pattern that you define will be appended directly to the link without any extra encoding, so the output must be url-encoded.

The only reason that I can think of why this wasn't an issue in other browsers might be that other browsers were doing the encoding for you. 

Also dismissing the errors will put the app in an “error” state. The app will not behave as expected and no error will show up again.
The chaise-config to add dismiss button for errors was just meant to be used in dev servers and not production.

**Comment by jrchudy** [comment]
[This section](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/user-docs/annotation.md#tag-2016-foreign-key) of `annotation.md` has been updated with further information describing what the expected value of the attribute should be. 
 > The defined filter will be appended directly to the reference uri and therefore must be properly url encoded (chaise WILL NOT apply additional url encoding).

**Comment by jrchudy** [comment]
Looks like changes have been made to the annotation to properly URL encode the value. Assigning to @hongsudt  to verify the deocumentation makes sense and to close this issue.

**Comment by hongsudt** [comment]
The document looks good to me. I am closing the issue.
