### ISSUE TITLE
ToC mismatch

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1857]
The ToC (ie "Contents" right panel) displays a listing of related tables. What it should do is display a listing based on the visible foreign keys. The problem with the current display choice is that many of the related tables (on a deployment like facebase) are displayed "inline" in visible columns as pseudo-column and therefore should just be considered part of the "Main" category in the ToC.

**Comment by RFSH** [comment]
This has been addressed by the mitigation changes. Now inline related entities are listed under the "Summary" section.
