### ISSUE TITLE
Suggestion: On the record page, rethink the edit button for pure/binary association tables in the related-records section

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1863]
Related to #1862: Currently, if you have Table_A and Table_B linked by a pure/binary association table, then Table_A's record page will have a section that is:

- labelled Table_B
- with rows from Table_B
- and `view` buttons that take you to Table_B rows
- and `edit` buttons that take you to the association table
- and `unlink` buttons that remove the association

I think the fact that the `edit` button goes to a different table than everything else in that section is confusing, and my suggestion is to either get rid of it or make it open a recordedit window for the appropriate row in Table_B (similar to what would happen if Table_B had a direct foreign key to Table_A).

Admittedly, this means more work for the user in some cases. Swapping out a record on the far end (i.e., switch one Table_B record for another on the Table_A page) would take one or two more mouse clicks -- instead of [click edit button, select record, click submit, (maybe) return to the Table_A record page], the process would be click edit button, select record, click submit, click unlink button, confirm].

Changing the near-end (Table A) record or changing both ends would be more complicated. But I'm not sure anyone outside our group would think to do that -- you need to have a mental model that acknowledges the association table in order to even think about clicking on the edit button for those cases.

**Comment by RFSH** [comment]
@ljpearlman We changed the behavior of the edit button. It should now send users to the same row that the view button does. Can you please verify the change?
