### ISSUE TITLE
viewer/osd: Include annotation in the screenshot feature

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1867]
Currently, the svg content is excluded from the canvas.

**Comment by vipul-21** [comment]
This feature is provided in this [PR](https://github.com/informatics-isi-edu/openseadragon-viewer/pull/9).

**Current Version:**
 In this the openseadragon viewer is used to the get the scenes as canvas. Water mark and scale is added to that canvas. 
Problem with this is that we want the svg overlay to be in the screenshot. For that we need to update the canvas given by openseadragon and map the svg on the canvas with correct positioning like we're doing while rendering it.

**New Version:**
 To solve the above mentioned problem, we are using the library `html2canvas.js` which captures the html being rendered into a canvas. 
In this approach, we don't need to worry about the svg position on the scene as the screenshot is taken along with it. Hence, only the watermark is added to the bottom left of the canvas if required.

**Comment by hongsudt** [comment]
@rastogi-bhavya verify.. If this is done, please close.
