### ISSUE TITLE
Viewer app adjustments

### ISSUE THREAD

**Issue by vipul-21** [informatics-isi-edu/chaise#1873]
Based on the work done in the openseadragon-viewer, there are new things implemented on the viewer app in chaise.
- [x] Navbar should be configurable by the url parameter, `hideNavbar` like we have in treeview
- [x] Merging of the branch `annotation-list` with the master to follow the new styling guides of the chaise app.
- [x] Remove hardcoded hostname for svg and openseadragon-viewer app. It should be the same as the viewer app hostname.
- [x] (bug) On clicking the openseadragon viewer iframe on the viewer app, the navbar seems to hide but the functionality of the app remains intact.
- [ ] The left panel should be adjustable
- [ ] Loading the annotation in the left panel takes time. This makes the loading of the page looks odd as the left panel is shown after some time. Need to add a loader or something else so that this transition is smooth.
Styling changes on viewer app:
- [x] Annotation left bar should have the `hide panel` and `show panel` just like we had on the chiase app.
- [ ] The alignment of the viewer app is not correct on linux machines.
  - Summary of cross browser support: 
     - Windows:
      1) Firefox and chrome - Works fine
      2) IE and Edge not working - OSD(openseadragon-veiwer) not loading svg and styling is not correct.
     - MacOS:
      1) Chrome and safari works fine 
      2)  Firefox - OSD  only the annotations are visible not the whole image.
     - [ ]  Linux - Need to test on a linux machine

### Multiple scenes 
- [ ] Svg overlay should be able to work via url parameter
- [ ] Left panel should differentiate between different scenes and corresponding svg overlays. It should also compensate the search bar for the annotations(global for that scene url).

**Comment by RFSH** [comment]
With the recent changes to viewer app in the past year all the listed changes are done.
