### ISSUE TITLE
Boolean dropdowns clipped

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1880]
When a boolean dropdown menu is the last input field in a recordedit form, the dropdown gets clipped by the table containing the form.

https://dev.rebuildingakidney.org/chaise/recordedit/#2/Common:Principal_Investigator/RID=W-Q5P6

**Comment by jrchudy** [comment]
Corresponding PR has been fixed. Assigning this issue to @ljpearlman to verify it is now fixed.

**Comment by ljpearlman** [comment]
Looks good.
