### ISSUE TITLE
show_null behavior in record

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1893]
This issue is an extension of the discussion we had in standup and the subsequent comments I added to issue #1865. 

There are 4 states for the show_null attribute of the display annotation. No annotation attribute and the following:
> Supported JSON nshow patterns:
> - true (or ""): Show NULL values as an empty field.
> - " _marker_ " (a quoted string literal): For any string literal marker, display the marker text value in place of NULLs.
> - false: Completely eliminate the field if feasible in the presentation.

The following is pertaining to the case when the `show_null` attribute is not present. What should be displayed by default when the field is part of the visible columns list but there is no value to show to the user?  Each point below is the types of values that can occur for each column that can be displayed in the main section of `record` app:
  - regular column:
    - `null` => don't show column
    - `''` => show column with _nothing_ present
    - cases to consider:
      - JSON:
        - SQL `null`
          - `::null` is SQL null and can return JSON null in a query
        - JSON `{ null }`
      - Array type behavior:
        - consider array of each primitive type. Should be similar to the decision made to show aggregate arrays
  - composite display:
    - `null` => don't show column
      - if the value of any of the columns which are being used in the markdown_pattern are either null or empty, then the pattern will fall back on the show_nulls display annotation to return respective value (assuming no handlebars if/else guards were used)
    - template evaluates to `''` => show column with _nothing_ present
  - aggregate column types:
    - count:
      - ~~0+ => show value, can never not be a number~~
      - `null` when there's no data
      - else, count is 1+ with data
    - array:
      - `null` => show column ~~(maybe the template for output doesn't evaluate properly)~~ 
        - case when there's no data to aggregate over
      - ~~`[]` => show column (should we differentiate from the line above?)~~
        - can't happen
      - `[null, null]` => show column as `No Value, No Value`
      - `[""]` => show column as `Empty`
        - doesn't make sense to have `["", null]` be `, No Value` so `''` in an array should be displayed as `Empty`
    - min/max ~~(note: verify what is returned when no values exist, null or ''. also verify what happens with `null` value):~~
      - `null` => show column
      - ~~`null` value => show column with `No Value` or maybe show `null` as value~~
        - ~~when `null` is a valid value and is the max or min~~
        - won't be returned from a min/max request
        - if null is only value, `null` is returned as if there is no data
        - if values in set are `1` and `null`, 1 is both min and max
  - inline related table:
    - `[]` => 
      - no mutate permission, hide column
      - mutate permission, show column with `None` value in custom mode (based on button on page)

**Comment by jrchudy** [comment]
In the following example, the last visible column appears to "never load". This can be confusing since there is no indication that the page finished loading or that the content is "not defined" or "empty". The issue is that the markdown template is returning `''` (empty string) which is interpreted as a valid value currently by Chaise.

The above example can be seen here (image below if visible columns change):
https://www.gudmap.org/chaise/record/#2/Gene_Expression:Image/RID=16-2E46

![image](https://user-images.githubusercontent.com/2932600/107299091-8906e300-6a2b-11eb-8474-9b699fb395c1.png)

**Comment by RFSH** [comment]
As I mentioned in [here](https://github.com/informatics-isi-edu/chaise/issues/1865#issuecomment-1294063245), the issue related to aggregates that is described in the previous comment has been resolved by making sure we're honoring the show/hide empty sections. I'm not going to close this issue as it's talking about other types of columns that we're showing on the page.

**Comment by jrchudy** [comment]
This hasn't come up since the discussion above and after changing the case for aggregates. Closing this issue
