### ISSUE TITLE
Bookmark lost via GOAuth

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#190]
If you have a bookmark that ends up being redirected to GOauth, the filter parameters get lost and you get put into an search page with no facets selected.  Here is a link that will reproduce this error (you need to be in the GPCR group to access this site):

https://gpcr-dev.misd.isi.edu/chaise/search/#1/gpcr_browser:target_gui?facets=(target_gui:site::eq::USC)&layout=table&page=1

**Comment by svoinea** [comment]
The referrer is passed correctly.
It seems that webauthn is stripping the text following the '#', i.e. the bookmark.

**Comment by karlcz** [comment]
This may be impossible to fix since goauth involves whole page
redirects via the server while the bookmark is using a
fragment-identifier which does not get sent to the server, and thus
the server does not have the knowledge to redirect the client back to
that URL with fragment-identifier.

**Comment by carlkesselman** [comment]
Can we get a final determination on if this is as it should be, or a bug?  This is an issue for GPCR

**Comment by karlcz** [comment]
A fix for this will be pushed to chaise master branch very soon, then once that is deployed to a host the login during bookmark loading should start to work.

**Comment by svoinea** [comment]
The fix is in the commit 57f129f8a85cb0e71710749c5e67a1d8d3d897ff.

**Comment by bugacov** [comment]
In GPCR we are currently using the iframe branch.
What should I do to test it?
Alejandro.

**Comment by karlcz** [comment]
Presumably someone in charge of that branch needs to rebase to include
this patch from master and push the update to that branch.

**Comment by bugacov** [comment]
Sounds good!! Tomorrow I'll ask Jennifer if can rebase iframe to master.
Thanks!
Alejandro.

**Comment by bugacov** [comment]
Sounds good!! Tomorrow I'll ask Jennifer if can rebase iframe to master.
Alejandro.

**Comment by robes** [comment]
Wait. Shouldn't we just merge the iframe branch with master and start deploying that?

Rob Schuler

On Feb 9, 2016, at 6:30 PM, bugacov <notifications@github.com<mailto:notifications@github.com>> wrote:

Sounds good!! Tomorrow I'll ask Jennifer if can rebase iframe to master.
Alejandro.

On Tue, Feb 9, 2016 at 6:21 PM, karlcz <notifications@github.com<mailto:notifications@github.com>> wrote:

> Presumably someone in charge of that branch needs to rebase to include
> this patch from master and push the update to that branch.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/informatics-isi-edu/chaise/issues/190#issuecomment-182170705>
> .[image: Web Bug from
> https://github.com/notifications/beacon/AKDL2Vp88kYzh_bH_DQ1agC_owL50gAHks5pipYsgaJpZM4HN2MY.gif]
>

-

**Comment by bugacov** [comment]
The iframe implementation in gpcr  seem to work well, so if that's enough
as a measure then yes i dont see why not but i dont know the whole scope of
that branch.
Alejandro.
