### ISSUE TITLE
Multi-edit with implicit schema fails during submit

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1914]
If you go to a recordedit URL without an explicit schema name, the app mostly functions except for multi-record edit submission.

1. Go to a table without schema name, e.g. https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/AuthorList_Author
2. Select bulk edit button
3. Make some edits
4. Hit submit

An error banner is displayed  `Schema null does not exist`.  Doing the same flow for a single-record edit will succeed, so it seems to be multi-record specific code...

I wonder if the application should just normalize the URL during startup, finding the implicit schema and adding the missing schema name qualifier to the location bar and other app state?

**Comment by RFSH** [comment]
The `Reference.update` API in ermrestjs was using the wrong `Reference.location.schemaName` value which might be null. I [changed it to use the correct `Reference.table.schema.name` instead](https://github.com/informatics-isi-edu/ermrestjs/commit/86215f3d77565f7705dc918285aa548f153cef35). The edit should now work properly. The other parts of ermrestjs are using the correct API, so there wasn't any need for further changes.

 @karlcz can you please try this again and verify the fix?
