### ISSUE TITLE
Reduce running time of test cases in CI

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1921]
The e2e test cases when run in travis will often fail after 50 minutes (the timeout limit for builds). When the build does pass, it takes 45-50 minutes. The following is a list of the specs and their run times in a passing build on travis separated by config set:

#### all-features-confirmation 
| spec                     | runtime |
|-----------------|---------|
| navbar/no-logo.spec      | 6 sec     |
| record/create-btn.spec | 11 sec    |
| footer.spec         | 15 sec    |
| record/edit-btn.spec     | 10 sec    |
| record/delete-btn.spec | 16 sec   |
| errors.spec         | 24 sec   |
| recordedit/edit.spec             | 7 mins 56 sec |
| record/presentation.spec | 8 mins 27 sec |
| recordset/presentation.spec | 7 mins 12 sec |
| recordedit/add.spec | 15 mins 55 sec |

#### default-config
| spec                     | runtime |
|-----------------|---------|
| record/links.spec            | 18 sec   |
| composite-key.spec | 25 sec |
| domain-filter.spec | 2 mins 12 sec |
| immutable-inputs.spec | 1 min 31 sec |
| add-x-forms.spec | 2 mins 27 sec |
| remove-edit-form.spec | 14 sec |
| submission-disabled.spec | 13 sec |
| recordset/add.spec | 28 sec |
| multi-col-types.spec | 2 mins 52 sec |
| recordset/edit.spec | 26 sec |
| multi-edit.spec | 1 min 42 sec |

#### all-features
| spec                     | runtime |
|-----------------|---------|
| navbar/base-config.spec | 20 sec |
| record/permissions-visibility.spec | 59 sec |
| record/copy-btn.spec | 1 min 9 sec |
| recordedit/permissions-visibility.spec | 1 min 3 sec |
| recordset/permissions-visibility.spec | 35 sec |
| record/related-table.spec | 8 mins 43 sec |

#### delete-prohibited
| spec                     | runtime |
|-----------------|---------|
| record/no-delete-btn.spec | 13 sec |
| navbar/catalog-chaise-config | 11 sec |
| misc-facet.spec | 2 mins 16 sec |
| histogram-facet.spec | 3 mins 39 sec |
| ind-facet.spec | 10 mins 54 sec |

**Comment by RFSH** [comment]
While doing the changes in #1944 PR, I realized that despite showing terminal error, test cases might pass and continue without any issues. 

To fix this, we could modify how the expect works In protractor and always make sure we're not showing errors beforehand. But that's very inefficient and also errors might happen when we're not checking for any expectations. Another solution could be finding a way to signal our apps that it's running in protractor mode. Then, in that case, we can turn off the exception handler and let the javascript app completely break. If Javascript environment breaks, protractor shouldn't be able to run any javascript code on the website and therefore it should fail. 

This might not be directly related to the described issue in the previous comment, but it might be one of the causes of time-consuming test cases. It also requires looking more closely at how protractor behaves and our test cases, so it can be done in the same task.

**Comment by jrchudy** [comment]
To add to this issue, there is a test case that deterministically fails in `recordedit/add.spec.js`. The test case itself always passes but there is a terminal error being thrown on the 2nd iteration of the loop when modifying the float input for the 2nd record.

Linking the relevant `it` case. Comments will be added in the code: https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/utils/recordedit-helpers.js#L1346-L1388
