### ISSUE TITLE
Print style sheet needs update

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1922]
Example 1
----------
[record-app-print.pdf](https://github.com/informatics-isi-edu/chaise/files/4372534/record-app-print.pdf)

Example 2
-----------
[record-app-print-2.pdf](https://github.com/informatics-isi-edu/chaise/files/4372549/record-app-print-2.pdf)

Above are examples of the record app. Some issues that are visible:
- some buttons are visible
- "Sections" heading and "Hide panel" control are visible
- Title is wrapped oddly, probably due to "Sections" heading
- an iFrame is printed and should probably be hidden if at all possible
- example 2, there is only the title on the first page then blank before the second page shows more fields
- only a limited number of related records appear in either example
- the "Displaying all [X] records" is shown and should probably be hidden or styled less like a GUI control
- down arrow `V` to collapse/expand the related records should probably be hidden from a print

**Comment by DamCousik** [comment]
Fixed the following issues

1) some buttons are visible
2) "Sections" heading and "Hide panel" control is visible
3)The title is wrapped oddly, probably due to "Sections" heading
an iFrame is printed and should probably be hidden if at all possible
4) the "Displaying all [X] records" is shown and should probably be hidden or styled less like a GUI control
5) down-arrow V to collapse/expand the related records should probably be hidden from a print
6) Fixed the column spacing issue

Needs to be fixed
1) Page layout
2) Zoom factor

The code has been checked-in and tested.

**Comment by robes** [comment]
Good! This is improving. Unless you point me to look elsewhere I'm going to review what you are doing on the records you see listed under this set:

https://dev.facebase.org/chaise/recordset/#1/isa:data_access_request

So looking at this record in the print output (from Mac FireFix):
https://dev.facebase.org/chaise/record/#1/isa:data_access_request/RID=1-JHAR

Here are some things I can see that need fixing:
- the font of the title might be too large
- the first page is blank after the title, we should have all the columns follow right after the title without the excessive whitespace
- the related entities are not displayed, i.e., i do not see the "Dar Dataset" table.
- i still see buttons at top of page, i.e., "Show Empty Sections" etc
- the "(i)" icon for the tooltips should not be displayed

**Comment by DamCousik** [comment]
> Good! This is improving. Unless you point me to look elsewhere I'm going to review what you are doing on the records you see listed under this set:
> 
> https://dev.facebase.org/chaise/recordset/#1/isa:data_access_request
> 
> So looking at this record in the print output (from Mac FireFix):
> https://dev.facebase.org/chaise/record/#1/isa:data_access_request/RID=1-JHAR
> 
> Here are some things I can see that need fixing:
> 
> * the font of the title might be too large
> * the first page is blank after the title, we should have all the columns follow right after the title without the excessive whitespace
> * the related entities are not displayed, i.e., i do not see the "Dar Dataset" table.
> * i still see buttons at top of page, i.e., "Show Empty Sections" etc
> * the "(i)" icon for the tooltips should not be displayed

Hi Rob,
Could you please give me access to the links provided above as I am unable to access them?

**Comment by robes** [comment]
You should be able to see the listing of records at this link



https://dev.facebase.org/chaise/recordset/#1/isa:data_access_request@sort(RID)



and then you can look at any in there. Currently, there is 1.

**Comment by hongsudt** [comment]
Rob, Alajandro,

If you haven't already, is it possible to give isrd-tester read-write access to the facebase dev?

Thanks,
________________________________

**Comment by bugacov** [comment]
@hongsudt ... I gave curator level access to the testers group on FB dev.
