### ISSUE TITLE
409 on FK Read

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1927]
When a user has their permissions changed via a logout or a different user being the one with the active cookie, errors can occur in the foreign key popup modal. This can be seen in RBK when creating a specimen and trying to attach a parent specimen. This will through a 409 when no user is logged in but the page was loaded as a properly permissioned user.

**Comment by RFSH** [comment]
Closing this issue since #2149 includes this and has more information.
