### ISSUE TITLE
viewer app: channel controls are not working on Firefox

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#1928]
It seems like some default values are inconsistent e.g. on firefox it shows 0 instead of 100, and there is no slider to allow the adjustment. 

This bug is also on production; so it has probably been there for a while and not due to recent refactoring.

**Comment by hongsudt** [comment]
@rastogi-bhavya please verify.. If no longer an issue, please close.

**Comment by rastogi-bhavya** [comment]
@hongsudt which values are inconsistent? For those values what should be the default?

There are slider for adjustments. Checked for the below link.
https://dev.rebuildingakidney.org/chaise/viewer/#2/Gene_Expression:Image/id=16-2EC6?url=/iiif/2/https%3A%2F%2Fderiva-imaging.isi.edu%2Fimages%2F20160707-hKDCS19_133-JAM-0-30-000-3.tif/info.json&url=/~vipul/chaise-demo/data/20160707-hKDCS19-133-JAM-0-30-00_scene3_fixed.svg&channelName=TL%20Brightfield&meterScaleInPixels=455504&waterMark=GUDMAP.org
![Screen Shot 2020-07-06 at 9.32.32 AM.png](https://images.zenhubusercontent.com/5ebddb0b7e863dce4ee7e1ff/5f334064-cc6d-470f-ba0c-9775d0e6db33)

**Comment by rastogi-bhavya** [comment]
Need to check it for https://dev.gudmap.org/chaise/viewer/#2/Gene_Expression:Image/id=16-2GM0?waterMark=gudmap.org
check the behavior with Chrome

**Comment by RFSH** [comment]
@rastogi-bhavya What's the status of this issue?
