### ISSUE TITLE
buggy behavior related to file picker and clone

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1932]
One of our users reported a buggy behavior in recordedit that was caused as a combination of picking a file and using the clone feature. 

To recreate this bug,
- Go to a recordedit page that has foreignkey and file picker in create mode.
- Use the foreignkey picker and select a value.
- Use the file picker and select a file.
- Press the "clone" button.
- Use the file picker and select a file for the second form.
- Click the "select-all" button for any of the values. Upon clicking, the file picker values will change and user is not able to select new files anymore.

I am still not sure what the cause of this bug is and currently am investigating this and will update this issue with more information. My best guess is that when users click on "clone", we're not properly copying the value and that is causing a referential bug.

**Comment by hongsudt** [comment]
@ljpearlman @crisaless @robes @bugacov @svoinea So you guys are aware of this bug!

**Comment by RFSH** [comment]
### How to reproduce
I think I found the core of the problem. This bug is not a result of "clone" button and it's just a combination of opening foreign key picker and file picker. So

- Go to recordedit page in muti-edit mode that has foreignkey and file picker (make sure the file picker has data).
- Use a foreignkey picker.
- Click the "select-all" button for any of the columns apart from the file picker. The value of the file picker will be removed.

I didn't update the original issue because there might be some other issues related to "clone" specifically.


### Chaise background
To better understand this, let me first explain the following data structure/functions that chaise is using:

- `rows`: An array of "displayed" values. These are the values that users see in the UI. In most cases, each value is a simple string, but in the case of Files, it's an object that has multiple attributes that uploader uses (and we also display).

- `submissionRows`: An array of "submission" values. These values are hidden from users and are only meant to be used when chaise is talking with ermrestjs. This includes data submission and when users open a search popup (needed for`domain_filter_pattern` annotation).  For these two cases, before sending the data to ermrestjs recordedit is always calling `transformRowValues` to turn a `row` into `submissionRow`. 

-  `transformRowValues`: The function used for transforming `rows` into `submissionRows`. For instance, in this function, we're turning the string representation of a JSON column into actual JSON or turning the objects used for timestamp columns into the string representation. 

- `toggleSelectAll`: The function that is being called when you toggle any of the "select-all" menus. When users open this menu, recordedit needs to disable the existing inputs and turn them into simple text inputs (as opposed to showing uploader or dropdown UI). When this feature was implemented at first, recordedit was allowing multiple of these menus to be open at the same time. So the internal implementation is still working under that assumption. On toggle of each "select-all" menu, it will make sure the values of all the columns are correct based on their "select-all" menu state.  In the case of File inputs, recordedit is using `submissionRows` to facilitate this transition. If the menu is opened, it's holding the value of `rows` in `submissionRows` to make sure the object value is not lost. When the menu is closed,  if `submissionRows` has value, it will use that value instead of the displayed row.



### Why
Based on this, the following is how this bug occurs: 

- User opens a foreign key picker and selects a value:
    Before opening the foreign key picker, chaise calls the `populateSubmissionRow`, which in turn calls into `transformRowValues`.  In this function, there's a boolean check that if we're not calling it for submission, we're using an empty object (`{url: ""}`) for the value of asset columns. This causes the `submissionRows` value for the asset columns to turn into the empty object   **which I think is a bug and the check is unnecessary. Removing this check fixes this issue but it might cause other issues and require extra testing.**.

-  User opens a "select-all" menu for a column other than the file-picker:
   recordedit goes through the list of columns to make sure their value is correct. For asset columns, if the `submissionRows` has a value for the asset column it will use it. So, in this case, it will use the empty object which causes the file-picker value to be wiped out. **I  feel like we shouldn't have even used submissionRows here. Creating an extra object instead of abusing the submissionRows might have been the better option. Although this is not a bug and it will just improve the code.**


### Potential fix

As I mentioned the solution is fixing the `transformRowValues` object to properly handle the asset columns. Apart from making sure test cases are passing after this change, I need to make sure this is not causing any issues for the "clone" functionality. I'm not sure why, but for whatever reason, the "clone" function is calling the `transformRowValues` as well. That's why when you clone the value of asset inputs won't be copied (it's going through the same boolean check and since it's not for submission it's turning the value into an empty object). 

For "clone" we're using the `angular.copy` function and we're blindly copying all the values in the `rows` object. In the case of assets, `rows` has a `File`, and `hatracObject`. The `hatracObject` has `column` and `Reference` objects and that's why when you clone you can notice a delay and your browser freezes. And what's strange is that we're doing this heavy copy and then we're calling `transformRowValues` which will completely wipe all the copied objects. I think we should fix this part of the code as well.

**Comment by RFSH** [comment]
This bug has been fixed. From PR's description:

> Modified the select-all implementation regarding asset columns which fixed the #1932 issue. To make the implementation simpler, recordedit was using the simple disabled input for all the "select-all" forms, including assets. But this means that the rows value had to be a simple string and couldn't be the object that we store for assets. To solve this issue, recordedit was abusing submissionRows to hold the object. But this had an impact on other columns, and it was buggy. The code assumed that sumbissionRows is only populated after submit but that's not necessarily the case. For example, in the case of foreignkey pickers, we need submissionRows for the domain_filter_pattern support. Therefore we shouldn't have used submissionRows to hold these values. To fix this, I changed the input from a simple disabled to an actual upload directive that is disabled. A while ago we added disabled support to this directive, so I just had to make sure the boolean states are properly set. After this change, I could simply pass the rows to the upload directive and didn't need the submissionRows hack.

I also changed the code behind the  "clone" function and now it's much faster than it was before.

**Comment by RFSH** [comment]
@crisaless Can you please test this and verify that it's working properly now?

You can use any table as long as it has both foreign key and file pickers in the recordedit page.

**Comment by RFSH** [comment]
I am going to close this issue due to inactivity. If the issue still persist, we should create a new issue for it.
