### ISSUE TITLE
Typo in chaise docs

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1934]
http://docs.derivacloud.org/users-guide/annotations/annotation.html#tag-2019-chaise-config has the line `default values defined in chaise-config.md`, where `chaise-config.md` points to the  docs page for chaise-config.js. The text for that link should probably be "chaise-config.js" instead of "chaise-config.md".

**Comment by RFSH** [comment]
The document is trying to explain that at the bare minimum (if the property is missing from chaise-config.js and annotation), we will use the default values. And the default values are explained in the `chaise-config.md`.  So `chaise-config.md` is international but a bit misleading. I changed it to say "chaise configuration document"  instead.

https://github.com/informatics-isi-edu/ermrestjs/commit/ab1a59666dec3fe88aaa709c3ec22572afc5a716
