### ISSUE TITLE
Width of images may not be honored if squeezed by other wide content

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1939]
Take a look at this dataset as a test. You can modify as you like, its on a dev server.

https://dev.facebase.org/chaise/record/#1/isa:dataset/RID=1-G8FW

See the content in the Description but I believe this condition may happen even if in a compact table view.

**Comment by RFSH** [comment]
@robes We're cleaning up our issues and we came across this one. Is this still an issue? I cannot see the record.

**Comment by robes** [comment]
No sure, since that link is no longer valid. I would suggest closing the issue and I'll reopen if I encounter it again. Thanks
