### ISSUE TITLE
ermrestjs and chaise build assumptions

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1940]
While working on #1936, I wanted to deploy multiple ermrestjs and chaise versions, so I can test the different variants. But that wasn't possible because of the assumptions that chaise and ermrestjs are making about their relative path. To remove these assumptions, I was thinking about adding some environment variables. 

Before explaining these assumptions, let's take a look at the current list of environment variables that we have :

| variable                 | category | description                                   | default value             |
|--------------------------|----------|-----------------------------------------------|---------------------------|
| `ERMRESTJSDIR`           | build    | where to install ermrestjs                    | `/var/www/html/ermrestjs` |
| `CHAISEDIR`              | build    | where to install chaise                       | `/var/www/html/chaise`    |
| `REMOTE_CHAISE_DIR_PATH` | tests    | if defined, scp chaise-config to the location |                           |
| `CHAISE_BASE_URL`        | tests    | used in e2e tests in chaise                   |                           |
| `SHARDING`               | tests    | used in chaise test suit                      |                           |
| `ERMREST_URL`            | tests    | used in test suit (chaise and ermrestjs)      |                           |
| `AUTH_COOKIE`            | tests    | used in test suit (chaise and ermrestjs)      |                           |
| `RESTRICTED_AUTH_COOKIE` | tests    | used in ermrestjs test suit                   |                           |

 The following are the different places that ermrestjs and chaise are making assumptions about their paths:

-  Upon loading, when ermrestjs tries to dynamically fetch the dependencies using the `../../ermrestjs/` URL prefix. This works because chaise is always two levels deeper than ermrestjs when it's running this code (`/chaise/<app-name>` vs `/ermrestjs/`). This won't work if a static site is more than two levels deep.
    - Solution: We can add `ERMRESTJS_BASE_PATH` that uses the default value of `/ermrestjs/`. I chose this name because a while ago we added `chaiseBasePath` chaise-config property that is used to locate the templates in chaise.  

- Chaise creates the URLs with a `../` prefix for all the assets that are injected. This should be fine if the created URLs are only injected into chaise templates as all the current chaise apps are two levels deep (and therefore one level deeper from the assets fires). But if we introduce a new app that is not two levels deep, it won't work. Also if we decide to use makefile to create the list of assets that can be prefetched in navbar (or deriva web apps), this assumption won't work.
    - Solution: We can add `CHAISE_BASE_PATH` that defaults to `/chaise/`. With this, we can remove the `chaiseBasePath` from chaise-config properties.

- Chaise assumes that ermrestjs will be accessible using `../../ermrestjs/` URL prefix in runtime.
    - Solution: We can use the same `ERMRESTJS_BASE_PATH` here as well.

- Chaise assumes that the ermrestjs build folder is located under `../ermrestjs/build`.
    - Solution: The current variable in the makefile for this is called `ERMRESTJS_BLD_DIR `. We can use the same name and just make sure we're not always defining a new one. I don't think we can use the `ERMRESTJSDIR` here. We're using remote locations as the value of `ERMRESTJSDIR` attribute. I'm not sure how it's going to work in this context.

**Comment by jrchudy** [comment]
2 other environment variables that I have in my script are `WEBAPPSDIR` and `DOWNLOADS_PATH`. Looks like `WEBAPPSDIR` is used for the make command in `deriva-webapps`.

I don't think we use `DOWNLOADS_PATH` anymore (I can't find it in the ermrestjs, chaise, or the webapps). I think it was used for verifying that files got downloaded with proper filename and metadata that we decided not to test anymore?

**Comment by RFSH** [comment]
After discussing this we decided to introduce these four env variables:

```
WEB_URL_ROOT?=/
WEB_INSTALL_ROOT?=/var/www/html/
ERMRESTJS_REL_PATH?=ermrestjs/
CHAISE_REL_PATH?=chaise/
```
For example in my case, I should use these variables while building remotely:

```
export WEB_URL_ROOT=/~ashafaei/
export WEB_INSTALL_ROOT=ashafaei@dev.isrd.isi.edu:public_html/
export ERMRESTJS_REL_PATH=ermrestjs/
export CHAISE_REL_PATH=chaise/
```

Using these four we can create the `CHAISEDIR` and `ERMERSTJSDIR` that we currently have. It can also be used to create `ermrestjsBasePath` and `chaiseBasePath` that are used in js files of chaise and ermrestjs.
