### ISSUE TITLE
Default chaise-config values and documentation

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1943]
Some of the default chaise-config values seem to be different from what I think are the most commonly desired values. Specifically, showFaceting, editRecord, and deleteRecord should probably all default to true.

It's also not entirely clear to me from the documentation what some of the parameters are used for (and which were used by the old search app and are ignored by the current apps); specifically:

`catalog` -- this is distinct from `defaultCatalog`, and I'm not sure what it's used for
`feedbackURL`,  `helpURL`,  and ` logoutURL` - are these still in use?
`dataBrowser` - is that still in use? If so, the default needs to change
`maxColumns` - is this still in use?
`showUnfilteredResults` - either I'm misinterpreting the definition, the description is wrong, or it's no longer in use
`defaultCatalog` - I don't think the description is clear.
`signUpURL` - is this still in use?
`profileURL` - is this in use?

It also might be nice to indicate which apps each parameter is used for (some of them have that already, but others don't).

**Comment by jrchudy** [comment]
Still used by chaise:
 - logoutURL
 - dataBrowser
   - needs update to default to `recordset`. Still used for a default redirect in case window.error is encountered
 - defaultCatalog
   - needs update the language in the description
 - signUpURL
 - profileURL

The following properties are not used by chaise anymore:
 - catalog
 - feedbackURL
 - helpURL
   - still consumed by `scripts/tour.js` which was only used in search
 - maxColumns
   - still consumed by `scripts/utils.js` which was only used in search
 - showUnfilteredResults
   - still consumed by `scripts/controller/ermrestResultsController.js` which was only used in search

**Comment by jrchudy** [comment]
TODO: have a discussion about the "unused" properties and remove them after if that's what we decide.

**Comment by jrchudy** [comment]
The changes detailed above have been addressed. The list of properties no longer used by chaise have been removed from the documentation and marked as deprecated in `RELEASE.md`.

Reassigning to @ljpearlman to review the changes to the documentation.
