### ISSUE TITLE
Allow disabling or override of content disposition in hatrac uploader

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1949]
For the asset annotation, we need a way to configure "ignore client's local name for file". This is to address cases where the user community is using "private" local filename info and we do not want that leaking out into the metadata that will be exposed to consumers of public data.

At minimum, have an annotation field to disable the content-disposition/filename input to hatrac or to supply the same template-generated name used in the destination hatrac object name. (These are equivalent in practice, since hatrac defaults to using the object name as the content disposition during GET requests, if a custom one is not stored.)

I don't know if there is any need to allow override of the original filename column handling. It seems to me that this can remain as now, since the DBA can use ACLs to lock down access to it or skip it entirely by not providing a mapping. But, I don't use it much and so cannot be sure...  @robes @ljpearlman  ?

**Comment by jrchudy** [comment]
The proposed solution is to have a new field for the asset annotation called `filename_pattern`. `content_disposition_pattern` was considered but implies that the pattern would override the full `content-disposition` when it only replaces the `filename` used in the `content-disposition`. This name would cover the cases mentioned above:
 1. `filename_pattern` can be used to disable the `content-disposition` passed as a header when creating the upload job
    - `filename_pattern: false` can be set to ignore passing `content-disposition`
    - hatrac uses the object name which is dictated by the `url_pattern` property of asset annotation
    - last part of `url_pattern` (filename and suffix) becomes the object name
 2. `filename_pattern` if defined and valid will be used as the filename in the `content-disposition` allowing data modelers to control the `content-disposition` attached to files in hatrac
 3. If no `filename_pattern` is defined, the name of the file from the filesystem the file was uploaded from will be used (current behavior)
