### ISSUE TITLE
Issues with Print in record app

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1953]
When using our “record” app, we don’t provide a different template for users to print the information they are seeing. We rely on the browser to generate that template using `@media print` queries in CSS. This allows you to define different CSS rules for every element on the page when using the browser print function. You can see some of that written here already:
https://github.com/informatics-isi-edu/chaise/blob/master/common/styles/scss/_record-app.scss#L306-L338

Here's a page to begin with:
https://dev.rebuildingakidney.org/chaise/record/#2/Protocol:Protocol/RID=N-H99W
On this page, there is a lot of text information. When clicking print in the browser, some of this information is squished in the page provided and the rest of the info is not printed out. For me, I get the following screenshot that only tries to print 1 page when there are at least 2 pages of content to be printed. Another thing to look at here is that the left column takes up a lot of space in the print preview which can be addressed as well.

![image](https://user-images.githubusercontent.com/2932600/82269147-98864f00-9925-11ea-8394-4e660454dda7.png)

Here is the related issue that ultimately needs to be fixed, but these problems are on more pages than just the one I linked above. https://github.com/informatics-isi-edu/chaise/issues/1922

One thing to note is that the content can be displayed differently based on different zoom levels.

**Comment by RFSH** [comment]
One thing that I think is worth mentioning is that almost a year ago we redesigned the whole chaise page structure and the main reason that the print functionality is broken is exactly that. When we did the redesign, we didn't update the print media queries to use the new page structure. 
For example the first rule
```css
#main-content {
  height: auto !important;
  display: block;
}
```
should simply change from `#main-content` to `.bottom-panel-container`. This will solve the issue of scrolling in the print view. The other rules are most probably old and need to be updated as well. If you want to see the structure of old record page you can use [this link](https://github.com/informatics-isi-edu/chaise/blob/d57e4fc1d79417f45e75c6656c62b991c47a0aba/record/index.html.in)

We should make sure the rules that are currently used in the lines of code that @jrchudy pointed out are updated. And if there's a rule that is not needed anymore, it should be removed.

**Comment by DamCousik** [comment]
**The following has been completed:**

- [ ] Record action buttons 

- [ ] Screen Action buttons

- [ ] Side panel

- [ ] Vocab class presented as a bullet separated list

- [ ] Iframes hidden

- [ ] Whitespace reduced between the columns

- [ ] Iframes are hidden

- [ ] Table borders are restored in print preview

**Comment by RFSH** [comment]
@DamCousik Can you please post a link to rbk and facebase pages that you were working on, so we can test it too?

**Comment by DamCousik** [comment]
Pages worked on:

1) https://dev.rebuildingakidney.org/~cousik/chaise/record/#2/Gene_Expression:Specimen/RID=N-GXA4

2) https://dev.rebuildingakidney.org/~cousik/chaise/record/#2/Gene_Expression:Image/RID=N-FGK2

3) https://dev.facebase.org/~cousik/chaise/record/#1/isa:dataset/RID=TMJ

4) https://dev.facebase.org/~cousik/chaise/record/#1/isa:data_access_request/RID=1-MC4J

5) https://dev.facebase.org/~cousik/chaise/record/#1/isa:data_access_request/RID=1-KREY

**Comment by RFSH** [comment]
It seems like in some deployments we actually want to show iframes in the print view and in some we don't. To solve this issue, we decided to introduce a class that can be used to override the default print heuristics. So assuming that if we want to show iframes by default, we can define a special class in chaise that will signal hiding that element in the print view.

As far as implementation, in chaise, we should not make this class specific to iframes and it should be general. Assuming if we called it `hide-in-print` (we need to come up with better name), the implementation should be as simple as

```css
.hide-in-print {
  display: none !important;
}
```

To actually test this, you need to modify the annotations on deployments. In the meantime, you can just use inspect element feature of browsers and add the class directly yourself.

**Comment by DamCousik** [comment]
The progress so far:

- [ ] Record action buttons are hidden
- [ ] Removed justification for all text
- [ ]  Screen Action buttons are hidden
- [ ]  Removed the 'Displaying information' button
- [ ]  Side panel is hidden
- [ ]  Made the collapsible arrows smaller
- [ ]  Vocab class presented as a bullet separated list
- [ ]  Changed the font size for all the headers
- [ ]  Iframes hidden
- [ ]  Removed the Action/View column from the record header table
- [ ]  Whitespace reduced between the columns
- [ ]  Table borders are restored in print preview
- [ ]  Top arrow key hidden

Pending from this ticket:

- [ ] Add a class to custom style elements according to browser type and OS

Noticed that different browsers on different operating systems behave differently. Made a compiled observation of the behavior I noticed. (PFA document)

Have to work on the following which will be addressed as part of a different ticket:

- [ ] Iframe fixing
- [ ] Changing the header in the Print Preview
- [ ] Adding figcaption class for iframes and images

[ISI_BrowserPrint.pdf](https://github.com/informatics-isi-edu/chaise/files/4854582/ISI_BrowserPrint.pdf)
