### ISSUE TITLE
navbar app changes title of static sites

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1954]
All the apps that are using chaise (navbar, login, deriva web apps, internal chaise apps), are using`config.js` as part of their setup. This app will call `setupHead` function that we have in `utils.js` which will

- Change title
- Add polyfill functions
- Add canonical tags
- Set `wid` value on the `window` object.
- Override the behavior of links based on some class names (`.external-link` and `.asset-permission`.)

I don't think we should do all of these in external (navbar, login, deriva web apps) pages. The most obvious one that should not be done in external pages is "Change title". Currently in the static sites that navbar is included the title is completely ignored and will be changed to the given name in `chaise-config`.

We should evaluate the other changes and see whether it makes sense to apply them to external pages as well.

And for implementation of this, @jrchudy and I had a discussion. I think we should introduce a `settings` (or a better alternative name) constant value that is passed to `config.js`.  We should also move the current `appName` constant into this object.

**Comment by jrchudy** [comment]
Corresponding PR has been merged. Closing this issue.
