### ISSUE TITLE
Support for Dynamic ACL

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#1958]
It might be useful for `chaise` to handle dynamic ACL in a similar way like `ermrest`.

For example, an user (identified by the column `RCB`), belonging to a group (`https://www.globus.org/app/groups/...`) is allowed to see his own records, but should be allowed to update his own records only if one of its column (for example `status`) has a value specified through a set (for example `[DRAFT,DEPO]`).

Currently, `chaise` gives you access to the `edit` view, and `ermrest` rejects the update request if the user has no permission.

Ideally, `chaise` will prevent to submit an update request if the user has no permission.

**Comment by karlcz** [comment]
I updated an old ermrest issue informatics-isi-edu/ermrest#157  to reflect the API features probably required for this sort of Chaise feature.  @robes   @hongsudt

**Comment by robes** [comment]
@hongsudt this was actually entered by Serban but covers the scenario.

Priority: predicting the edit/delete rights on a per-row basis. For example, not seeing the "Delete" or "Edit" buttons on a record page. Not seeing the "edit" and "delete"/"unlink" controls within the recordset (or embedded recordset) apps.

**Comment by karlcz** [comment]
I've merged the first round of ermrest features which would enable better adaptaiton of the edit/delete and recordedit form activation fields.

See the revised ermrest API docs for details but here's the cheat sheet:

When you GET /ermrest/  you get a service advertisement in JSON format: 
```
{
   ...,
   "features": {
      "trs": true,
      "tcrs": true,
      ...
   }
}
```

when these fields are present and `true` you can try to use the new feature. Being absent means you are talking to an older server and SHOULD NOT attempt the feature as it will cause errors. If it is false you might be talking to a future server that has allowed the feature to be disabled, so also SHOULD NOT attempt it.

The new feature allows new syntax in the /attributegroup/ API list of column projections.  It looks like an aggregate function but requests a rights summary.

- `outalias:=trs(talias:RID)`
- `outalias:=tcrs(talias:RID)`

This adds an output column named by _outalias_ and provides a rights summary for the entity keyed by _talias_ and _RID_.  You should include this in the extra projection list (after the `;`), not in the group-key column list.

The first form is simpler and just provides row-level `update` and `delete` rights info.  This is faster and should be used in recordset listings to allow you to decide whether to show edit/delete controls for each row to this user.

The second form includes the row-level `update` and `delete` rights but also includes extra per-column `update` info. This is slower but appropriate for recordedit to allow you to decide whether to enable or disable an input field for this user.

**Comment by karlcz** [comment]
BTW the nmemonic for these would be "trs" = "table rights summary" and "tcrs" = "table+column rights summary"...

**Comment by RFSH** [comment]
The changes to support "Per-row record access" and "Per-row column access" has been added by #2081. I'm going to close this issue and we should create a new one for further support to accompany future ermrest changes regarding dynamic ACL support.
