### ISSUE TITLE
Rename submit button

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1959]
On RecordEdit, the submit button is called “Submit” but really in RecordEdit context, it's more like Saving than Submitting. So we should change it to "Save" instead.

We're also showing submit button for the following cases,

- add pure and binary popup: submitting the selected rows.
- facet popup: applying the selected filters to the page.

We should also change the add pure and binary popup to "Save", but leave the facet popup button the way it is.

**Comment by jrchudy** [comment]
Changes merged into master. Closing this issue.
