### ISSUE TITLE
navbar drop-down is not scrollable

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#1960]
When the `navbarMenu` has a lot of children, the menu items from the bottom are unreachable.

The `PDB` project has for example about `80` menu items.

**Comment by RFSH** [comment]
@svoinea Can you please post a link to one of Chaise pages? It's easier to look at it and see how the navbar behaves

**Comment by svoinea** [comment]
@RFSH Try this link https://pdb.isrd.isi.edu
You don't need to be logged in.
You will see two menus.
Having each a large number of items, I have grouped them to avoid as much as possible the lack of the vertical scroll bar.
Yesterday, during a meeting, when the image was zoomed in, we were unable to reach the bottom of the menu unless we reset the zoom.
I think another way to test it is to reduce the size of the browser window.

**Comment by RFSH** [comment]
We briefly discussed the desired behavior of navbar app. The same way that we're showing separate scrollbar for facet panel, each navbar dropdown menu can have their own scrollbars. Although, this means that we have to add scrollbars to each dropdown menu level, which might not be desirable. 
Another thing that we should make sure that we're properly handling, is the cases that one level can be displayed, but when you open the next level, it goes beyond the page limit. In those cases, we can modify the dropdown to open upward.

**Comment by jrchudy** [comment]
We discussed earlier that this can recreated on the PDB server by opening the dev console or shrinking the height of the browser window.

For recreating this on dev.rbk or dev.isrd, you will have to do the following:
 - create the file `chaise-config.js` in your chaise directory based on `chaise-config-sample.js`
 - copy the `navbarMenu` property from `chaiseConfig` on pdb.isrd.isi.edu/chaise/recordset/#1/PDB:entry
   - use the dev console and type `chaiseConfig` and find the property there
   - OR in dev console, go to `sources` tab and find `chaise-config.js` listed and copy the `navbarMenu` from there
 - use `make install-w-config` to install chaise AND `chaise-config.js` to your user folder on the server

**Comment by DamCousik** [comment]
I worked on this and noticed that once I set a fixed `max-height` to the ul element of the list and add an overflow, I am able to get the scrolling to work. However, since this is a 2-level dropdown menu, once the scrollbar is added, the second level of menu is not being displayed. 

I am currently working on checking if there is a better way to enable scrolling without physically displaying the scroll-bar.

**Comment by DamCousik** [comment]
Changes made to ensure menu items are scrollable. Further required changes include:

- Add spacing to make sure the scrollbar doesn't overlap the arrows
- Add color to the parent element so you can distinguish which submenu is open

**Comment by DamCousik** [comment]
Changes completed :

- [ ] Add spacing to make sure the scrollbar doesn't overlap the arrows

- [ ] Background color changed for the menu item

Changes to be done:

- [ ]  Remove / Reset background color when the user clicks outside the menu (on the browser)

This is not controlled by the code and is something that bootstrap controls. I tried changing the `on-toggle(open)` in the uib-dropdown settings but it was throwing errors. Please pick this up from here. The code has been pushed to the repository.
Link - https://angular-ui.github.io/bootstrap/

**Comment by jrchudy** [comment]
The changes to support this have been merged into master. This new feature to allow scrolling will work without any configuration change. Reassigning to @svoinea to test this.
