### ISSUE TITLE
Link to user profile

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#1964]
Currently the `profileURL` is a string literal, so we cannot use it to make a reference to a Chaise Record page.

For example, let's say we have defined a schema:table in our catalog called `user:profile` and lets say that this `profile` table has a unique, not-null, column in it called `username` which is the username returned by webauthn. Then in order to reference that specific user `profile` record I would need to form a URL like this:

`…chaise/record/user:profile?username={username}` where `{username}` is replaced with that username returned by webauthn.

I would like to see an enhancement such that we can define a `profileURL` based on a simple pattern that would allow us to make Chaise Record page references.

(**NOTE** I don't know what exactly Webauthn returns so I'm just guessing that its a `username` value but I suppose it could be a different type of identifier.)

**Comment by robes** [comment]
I'm guessing whatever the `user` object is in this template is the thing that holds the properties we'd need to populate the requested pattern.

https://github.com/informatics-isi-edu/chaise/blob/fb482f5d826a5ffb0818bf5637462f0410197208/common/templates/login.html#L4

**Comment by jrchudy** [comment]
This issue is related to the work described in #2118.

**Comment by RFSH** [comment]
We decided to remove this property in #2129 since the same behavior can be replicated with the newly added `loggedInMenu` property. Please refer to the PR for more information.
