### ISSUE TITLE
Search by RID

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1970]
Add a search box (or control that shows one when clicked) to navbar that allows the user to type in the `RID` of a record to navigate to that record page. The implementation should take the input `RID` and navigate to that page using the resolver.

**Comment by jrchudy** [comment]
How do we want to handle showing this input for the following:
- set to catalog id `1`
   - resolver on, /id/RID for /id/1/RID, /id/N/RID for others
- false
   - resolver on, always use explicit /id/N/RID
- null
   - resolver disabled
- undefined/property absent from config
   - resolver on, no shorthand

**Comment by jrchudy** [comment]
Chaise config option to control if search by RID should always be visible or not.

Log action for users using this feature.

**Comment by karlcz** [comment]
FYI, when you know the catalog number N, you can always use the /id/N/RID format with the resolver, even for the implicit catalog that is also resolved using /id/RID

**Comment by jrchudy** [comment]
- Change placeholder to `Go to RID`.
- colors:
  - Change background from white. maybe grey?
  - primary button color doesn't seem right?
- open in new tab
- magnifying glass might not work?
  - some icon with arrow pointing right
