### ISSUE TITLE
Bad request from usage of float4 column entry

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#1973]
There seem to be gaps in the validation and handling for the floating point column type data entry form.

1. Start a create record form such as using the "Copy" button on https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/RID=1-1V4R
2. Type a number with leading spaces e.g. '   5' without quotes
3. Backspace to remove the digits but not all the spaces
4. Hit submit

See Error 400 Bad Request The request is malformed. Bad JSON array input. ERROR: invalid input syntax for type real: "" .

It seems like part of the UI is stripping the spaces to create an empty string, but then sending a quoted string instead of resetting it to null as it should be for this column type.

**Comment by jrchudy** [comment]
@karlcz the above referenced commit to master fixes this issue. Reassigning this to you to test and close.

**Comment by RFSH** [comment]
Closing the issue due to inactivity.
