### ISSUE TITLE
Order of asset injection for navbar.app.js

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1975]
We decided on the following structure for including `navbar.app.js` in a static page:
```html
<head>
  <!-- other deployment specific dependencies -->


  <!-- Scripts to be included for navbar app -->
  <!-- TODO copy the chaise-dependencies.html content here -->
  <script src="/chaise/lib/navbar/navbar.app.js"></script>

</head>
```

This is fine for javascript files since generally they don't override each other. But in the case of CSS files, this can be an issue. CSS override works based on which one is defined last. We provide a mechanism to try to avoid this issue by allowing users to define the `customCSS` chaise config property. But this mechanism doesn't work for css files that are included because of other libraries.

The issue that is happening is that when a version of bootstrap is included for the static page, there's no way to have that bootstrap document take precedence unless it is fully copied into `customCSS`. When using navbar app, bootstrap is also included, but this is after all other user defined dependencies. This means the version from chaise will take precedence and override some of the rules.
```html
<script src="/chaise/lib/navbar/navbar.app.js">
<script type="text/javascript" src="/chaise/scripts/vendor/angular.js"></script>
    <!-- static asset -->
    <link rel="stylesheet" href="./css/components/normalize.css" type="text/css">
    <link rel="stylesheet" href="./css/components/bootstrap.min.css" type="text/css"> <!-- 4.7.0 -->
    <link rel="shortcut icon" type="image/png" href="./images/icons/CFDE-icon-1.png?v=2">
    <link rel="stylesheet" href="./css/fonts.css" type="text/css">
    <link rel="stylesheet" href="./css/style.css" type="text/css">
    <link rel="stylesheet" href="./css/index.css" type="text/css">

  <!-- chaise asset -->
  <script type="text/javascript" src="/chaise/dist/chaise.vendor.min.js"></script>
  <script type="text/javascript" src="/chaise/chaise-config.js"></script>
  <script type="text/javascript" src="/chaise/dist/chaise.min.js"></script>
  <script type="text/javascript" src="/ermrestjs/ermrest.min.js"></script>
  <link type="text/css" rel="stylesheet" href="/chaise/styles/vendor/bootstrap.min.css"> <!-- 3.3.7 -->
  <link type="text/css" rel="stylesheet" href="/chaise/styles/vendor/fontawesome.min.css">
  <link type="text/css" rel="stylesheet" href="/chaise/common/styles/app.css">
  <script type="text/javascript" src="/ermrestjs/ermrest.vendor.min.js?v=20200618050103"></script>

  <!-- customCSS chaise config -->
  <link rel="stylesheet" type="text/css" href="/css/custom.css">
```

We should come up with a way to allow users to include CSS libraries that would override our libraries.

**Comment by jrchudy** [comment]
As part of `navbar.app.js`, we are adding the chaise dependencies for navbar to the end of the script tag. Each one is being appended using `appendChild()`. 

One solution we could try to attach the assets right after `<script src="/chaise/lib/navbar/navbar.app.js">` so that the user defined version of bootstrap is added after the version we include. 

The other solution would be to have all of the user defined CSS styles combined into one document that is included using the `customCSS` chaise config property.

**Comment by RFSH** [comment]
@jrchudy I think we decided that the current approach works for now and therefore we don't need to make any changes to it. Is that correct?

 I think we should just close this issue (or move it to backlog) if we're not going to make any changes to the implementation anytime soon.

**Comment by jrchudy** [comment]
Yes, you are correct. We decided the current implementation is sufficient since we still provide a mechanism for making sure styles can be properly overridden.
