### ISSUE TITLE
Chaise config naming inconsistencies

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1979]
It was brought up that almost all of the chaise config properties use camel case starting with a lower case letter (`camelCase`). There are 2 properties that do not, `SystemColumnsDisplayCompact` and `SystemColumnsDisplayDetailed`.

**Comment by karlcz** [comment]
We certainly won't have different configuration parameters differing
only by case. Should we make chaise case-insensitive in its
interpretation of the config...?

**Comment by hongsudt** [comment]
case-insensitive makes sense.. We will proceed with camel case for documentation though.
________________________________

**Comment by RFSH** [comment]
#1943 is not directly related to this but can be done together. Both are related to chaise-config.

**Comment by jrchudy** [comment]
Both, `SystemColumnsDisplayCompact` and `SystemColumnsDisplayDetailed`, have been updated to use proper camel case in the code and documentation. 

Chaise config properties that are a part of `chaise-config.js` and the catalog chaise config annotation including `configRules` are case-insensitive.
