### ISSUE TITLE
Print view fix for iframes

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1981]
During printing, iframes were not displayed properly. The original CSS styles and layouts were stripped off in the print mode. The different markdowns (Image, Treeview, Video, etc) have to retain styles in the print feature. 

1) Treeview markdown in iframe in the print mode
     Issue : The lines showing the tree hierarchy was missing and all the raw links were displayed in print. Scrolling did not 
                 persist in print
    
     
<img width="1012" alt="Screen Shot 2020-07-21 at 9 37 28 PM" src="https://user-images.githubusercontent.com/65321179/88124152-76fe4980-cb9a-11ea-83b7-62a7be968d51.png">

2) YouTube video
     Issue : Video thumbnail missing in the print mode

<img width="1000" alt="Screen Shot 2020-07-21 at 9 40 34 PM" src="https://user-images.githubusercontent.com/65321179/88124348-ea07c000-cb9a-11ea-95c6-98517fdbdd2f.png">

3) Fix print issues for the `<video>` markdown pattern as well.

**Comment by RFSH** [comment]
We [discussed this in one of our meetings](https://github.com/informatics-isi-edu/chaise/issues/1953#issuecomment-641645841). The chosen class name shouldn't be specific to iframe. It should instead be a general name, that can be applied to any other elements as well.

**Comment by DamCousik** [comment]
Currently, there is no way to distinguish if the markdown that is being displayed by the iframe contains a youtube video or not. By parsing the iframe source, we can find out if the markdown is a YouTube video and then apply custom styling to hide the video frame during print.

**Comment by DamCousik** [comment]
Progress so far:

- [ ] Fixed the print for iframes with Treeview document to show the tree hierarchy during print. 

- [ ] Persisted scrolling during print

Yet to be done:

Applying the thumbnail to the YouTube video on print was complicated as the styles are applied via YouTube and we have limited access to it. Hence, the alternative was to display a note informing the user that the video is hidden during print and possibly provide the URL of the hidden video.

- [ ] Parsing the URL to check if there is an embedded YouTube video. If yes, then add a class to apply the above discussed custom styles.

- [ ]  Do the same for the `<video>` markdown pattern as well.

**Comment by RFSH** [comment]
For distinguishing whether an iframe contains a Youtube video or not, you need to modify both ermrestjs and chaise code. 

### Code change

### ermrestjs

You need to modify iframe parser to add an extra element and most probably a specific class to your iframe. The extra element will be visible only in print, and the specific class will help you with writing the rule to hide the iframe.

[This](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/utils/helpers.js#L1857) is where the iframe code attaches the `src` tag. You should set a boolean flag here that signals whether this is a youtube link. Then later in the code, the same way we're attaching `figcaption` and the `a` tag, you can attach an element with a specific class to the `html` element . You should add your specific class name somewhere in this code too.

### chaise

1. Add a rule to show the element added to iframe in print.
2. Add a rule to hide the iframes with the specific class name.

### Testing
After you're done with the code change and your manual testing, you need to modify the ermrestjs test cases.

#### How to run test cases
[In this comment](https://github.com/informatics-isi-edu/chaise/issues/1961) I explained what you need to do for running ermrestjs test cases. You can also find the same information on [the unit testing document page](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/dev-docs/unit-test.md).

#### Add test cases
For unit testing in ermrestjs we're using Jasmine 2.5. You don't need to know every detail of this package, and quickly reading [this simple document that they have](https://jasmine.github.io/2.5/introduction) should be enough. Although the test case that you need to add for this is very simple. The test spec that you're going to change is one of our first test specs and it's not completely following the same pattern as other specs. For this one you need to add the same three lines as [this](https://github.com/informatics-isi-edu/ermrestjs/blob/master/test/specs/print_utils/tests/01.print_utils.js#L142,L144) with different iframe pattern value and different expected value. Add them to the end of this `it` that I linked to.

After adding your test case, you can use [this method](https://github.com/informatics-isi-edu/ermrestjs/blob/master/docs/dev-docs/unit-test.md#test-single-spec-file) to run an specific spec. This will be quicker and easier to debug when you're developing test cases. But in the end, you should always run `make test` as well.
