### ISSUE TITLE
Weird corner case - URL and chicklet display disagree

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#1982]
The attached screenshot shows a recordset page in which there are no filters showing in the chicklet area, but the results are filtered (there are many world-readable entries in that table), and the browser's URL bar shows a filter.

I got there by visiting a RNASeq:Study record page, scrolling down to the Files area (which was empty), doing some other stuff for a while, and then coming back and clicking Explore. I was able to reproduce it by logging in, visiting a restricted Study file, manually invalidating my session, and then clicking Explore again.

You can sort of reproduce it by visiting https://dev.rebuildingakidney.org/chaise/recordset/#2/RNASeq:File/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JHQBcAjdafEAJQDkBBAZRwEcQAaEAMQEsAbHAPoMiaKAE8BVAJIARAQDMA1jjEgAugF8O0meo5YAFim64klAIwB2ALQA2ABoAWABzqNmoA@sort(Replicate_RID::desc::,File_Type,RID) -- you'll see the chicklet if you're logged in; you won't if you're not.

One other thing that might be relevant: the column being searched on is the Study RID; the additional information in the chicklet (the Study title) comes from a query of the Study table, and the result set of that query would be empty for an unauthenticated user. If that's the problem, then I think the best solution is to just show the RID alone in the chicklet when the Study query returns no results (either because of auth issues or because that record just doesn't exist).

<img width="1464" alt="Screen Shot 2020-07-21 at 4 21 22 PM" src="https://user-images.githubusercontent.com/8785501/88117158-3b01bf00-cb6f-11ea-8399-af60e84463e9.png">

**Comment by RFSH** [comment]
As you mentioned this is happening because the user cannot see that row in the study table. 

When you navigate to a page with facet, what's encoded in the facet is just the scalar value. In this case, it's the `RID` value. So we're doing an extra read to get the "row name" of that Study. But since the user cannot see that record, the response returns empty and ermrestjs is not properly handling this case. 

I agree that the best solution would be showing the underlying scalar value to the users.

**Comment by RFSH** [comment]
I pushed the following change to ermrestjs for this: https://github.com/informatics-isi-edu/ermrestjs/commit/d161d8c2d0056e2771110f62e645cb22090ba45d

I added a new test case and testing the changes on [my user directory works in rbk](https://dev.rebuildingakidney.org/~ashafaei/chaise/recordset/#2/RNASeq:File/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JHQBcAjdafEAJQDkBBAZRwEcQAaEAMQEsAbHAPoMiaKAE8BVAJIARAQDMA1jjEgAugF8O0meo5YAFim64klAIwB2ALQA2ABoAWABzqNmoA@sort(Replicate_RID::desc::,File_Type,RID)).

I think hourly updates are turned off in rbk, so I couldn't test the original link in the issue. @ljpearlman Can you please verify and close this issue?

**Comment by RFSH** [comment]
I am going to close this issue due to inactivity. We should create a new issue in case this bug is still not resolved.
