### ISSUE TITLE
Link for More Help on how to create/edit columns

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#1984]
It was brought up in the past that some users would like to have a link in the column name in recordedit to have more information about what should be input into the field. Or more information describing the foreign key that may be limited by a domain filter pattern.

2 suggestions for this:
 1. we could add a new annotation that users can define a url template or link that points to a help page
   OR
 2. we modify the comment and comment_display changes to work in recordedit and have modelers use inline comments for the functionality

**Comment by RFSH** [comment]
As part of #2393 we are going to allow inline comments on the recordedit page. So I'm going to close this issue.
