### ISSUE TITLE
Inconsistent id used in record page

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1986]
A while ago we changed the `makeSafeIdAttr` functionality to [properly modify the schema/table/column names that we're attaching to different models](https://github.com/informatics-isi-edu/chaise/blob/master/docs/user-docs/custom-css.md#character-replacement).

But it seems like we're not doing this consistently. For example, in [`record.html`](https://github.com/informatics-isi-edu/chaise/blob/master/common/templates/record.html#L2) we're not using this function for the row `id`. 

We should

- [x] make sure we're consistently using this function (`makeSafeIdAttr`) in all the places that we're creating id/class attributes.
- [ ] decide whether we want to use name or displayname. I saw different places in the code using different attributes.  
- [ ] Add `c_${name || displayname}` to the `<tr>` entity rows in the main section
  - currently similarly used in recordset table on the `<th>` element
  - this will be the new format and keep old values support backwards compatibility
- [ ] make sure test cases are stable based on changes to use `name` instead of `displayname`
- [ ] modify the custom-css styles that are used in different deployments to be aligned with the new change.
   - so new and old styles can coexist to prevent a regression in deployments that may have used `c_hash` with a source key also defined

**Comment by jrchudy** [comment]
We previously discussed this when talking about custom styles for different projects. More notably in the case of RBK/Gudmap. When we had that discussion, it was pointed out that the "displayname" may not be unique whereas the name should be. https://github.com/informatics-isi-edu/chaise/issues/1525#issuecomment-392986536

Related PR to make sure we don't break functionality of using name instead for custom styles:
https://github.com/informatics-isi-edu/rbk-www/pull/3/files

**Comment by jrchudy** [comment]
displayname:
 - What you see so it's easier to understand what to use in class
 - clear rule for replacing special characters. `-` replace space and other characters
 - less model awareness
 - might have HTML
   - i.e. <strong>Title</strong>

name:
 - case sensitive
 - more "aware" of the model
 - name will remain constant while displayname may be updated at any time
 - unique

Add `c_*` and other information to top section of record app. 

Apply this to recordedit as well.

**Comment by jrchudy** [comment]
ermrestJS decides `column.name` as:
 1. `sourcekey`
 2. default heuristic to generate hash based on path (current implementation)

chaise uses `column.name`

**Comment by jrchudy** [comment]
Update for playwright:
 - bullet 2 above
   - use name or displayname?  
     - `Accordion.Item` uses `#rt-heading-${displayname}`
     - `<tr>` in `RecordMainSection` uses `.entity-row-${displayname}`
       - also has `#row-${column.name}`
     - entity value `<td>` in `<tr>` of `RecordMainSection` uses `#entity-displayname`

**Comment by jrchudy** [comment]
PR #2526 fixes the issue mentioned in the first bullet above. 

Any further changes:
 - require more in depth discussion as to which of the options are "better"
 - changing any of the above id or classes might break backwards compatibility for deployments with custom CSS
   - includes prepending `c_`
 - source-key changes would not be a simple change
