### ISSUE TITLE
Evaluate the warning logic in share and cite popup

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#1990]
With the recent changes, I added the same share popup that we have in the record page to the viewer app. The popup will use the same logic that we have in record app to show a warning to users.

When users click on the share button, we're sending a catalog request to retrieve the latest `snaptime` that is reported on the catalog. If the `snaptime` is different from the one that we get from the initial catalog request of the page (that we fire on load), we're showing a warning with the following message

> The displayed content may be stale due to recent changes made by other users. You may wish to review the changes prior to sharing the \<live link\> below. Or, you may share the older content using the \<versioned link\>.

But this can be misleading. For example on the record page, the snaptime change might be because of a change that user did on the current page since we're not getting a new `snapshot` value after updating the page (due to create, edit, delete related entities). So I think we should improve this logic by at least updating the `snapshot` after each change. This is much more visible in viewer app since we want users to create/edit annotations and the warning will be displayed after the first change. We could apply the same improvement and update the `snapshot` after each change. 

I'm not sure whether we can easily derive the `snapshot` or somehow get it from the ermrest response. Or should we simply send an extra catalog request to get it.

**Comment by karlcz** [comment]
However, the fact that you made a request and updated snaptime does
not mean that these are the only changes represented in that new
snapshot. These are not sequence numbers so you cannot tell whether
there were additional snapshots in between your initial load and the
current state.

So, I think the warning is still applicable any time the snapshot is
different from the one you detected _before_ beginning to fetch content
that is rendered on the page.

**Comment by RFSH** [comment]
We had a discussion about this and these are what we concluded, 

- We should add the following to the warning: `Refresh the page to get the latest snapshot.`(just to provide more information to the users)

- Since in record app we're updating the whole page after a change (edit/create/delete), we can be sure what's displayed to the users after the change is the latest data. So we can update the snapshot of the page by sending a catalog request after updating the page. We will use this updated snapshot for the compression that we're doing to show the warning.

- In the viewer app, after edit/create, we're not updating the whole page. We're only updating the annotation that was modified. So updating the snapshot for the whole page doesn't make sense. Assume that you opened the page that has two annotations (`annot1` and `annot2`) and clicked on the `annot2` to edit it. While you were editing this annotation, someone changed the `annot1`. Now if you save the `annot2`, it's true that the displayed `annot2` is the latest version, but the displayed `annot1` is stale. To optimize this, we could keep track of the snapshot for each individual annotation. If you modify the annotation, we will fetch the snapshot and only use it for that annotation. This will ensure showing a proper warning to the users, but it might be confusing to the users since we're going to use different snapshot values for each one.

@karlcz Can you please see if these make sense to you? Do you think this optimization is useful or even correct?

**Comment by karlcz** [comment]
I don't think it makes sense to talk about different snaptimes for
each part of the viewer content.  Fundamentally, you want to know
whether navigating to the versioned citation link will reproduce the
same rendered view that the user is currently viewing.

For using snaptime, I think there's really only one logic that makes
sense: compare a current snaptime T to a fixed T0 that was observed
prior to any page content being retrieved.  If snaptimes differ, you
cannot be certain whether you have a reproducible view or some mixed
reproduced that cannot be reproduced again later (i.e. different
requests producing content from different intermediate snaptimes).  I
think you should just warn the user at that point.

But, if the viewer app inputs are well-defined enough, you could fetch
a new copy and compare all the "important" parts to detect a change.
I.e. URLs, metadata fields, and display parameters that contribute to
the rendered page.  Hatrac objects are immutable, so if you have the
same set of versioned annotation URLs at time 1 and time 2, you know
the content is identical, even if the snaptimes are different. You
don't need to compare annotation contents.

However, this requires some understanding about what is the complete
set of important data content is for a viewer page.  If the viewer app
provides a very open-ended view of the catalog content (as with
record/recordset), or if it depends on model annotations for
customization, then I think sticking to snaptime is still the wiser
thing to do.  It would be hard to accurately compute the complete
set of inputs without rebooting the whole app and repeating every bit
of introspection and data retrieval...
