### ISSUE TITLE
navbar app / chaise-config.js - extend chaise navigation to allow dropdown headers

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#1996]
Extend navigation so that you can enter a dropdown header. Header only - does not include a link. User inputs name and output uses an existing bootstrap class `dropdown-header` Output would look be like:

```<li class="dropdown-header">SAMPLE HEADER</li>```

Attaching two screenshots:
1. A screenshot that shows a demo version - using the bootstrap navbar component on the static site. Dropdown headers are in bolded teal:

<img width="1440" alt="demo-dropdown-headers-gudmap copy" src="https://user-images.githubusercontent.com/8965132/90291020-ca7b5480-de33-11ea-9172-00c8322b7de2.png">

2. A screenshot of hacking the current chaise navigation to insert the <li class="dropdown-header">HEADER</li> code. Can be styled per deployment using custom css:

<img width="1440" alt="hacked-chaise-version copy" src="https://user-images.githubusercontent.com/8965132/90290948-a91a6880-de33-11ea-8bd3-27e3d5a305a3.png">

Reason: This is for the GUDMAP redesigned site - which originally included a megamenu. Since we want consistent navigation between the chaise and static pages, and we need to show something in early September, I'm creating an alternative using the navbar app. But due to the many navigational items, I'd like to add the option of including non-linking headers to help "chunk" items on a dropdown menu.

**Comment by jrchudy** [comment]
Add a new property to `chaise-config.navbarMenu` items to allow for headers to be defined that don't have children or a link. The property to add is:
```js
  "children": [{
    "name": "Link",
    "header": true
}

**Comment by jrchudy** [comment]
Tentative design using the "primary color" we have defined for chaise (the deep blue that we color buttons with):
![image](https://user-images.githubusercontent.com/2932600/90824436-45d57e00-e2ec-11ea-8fa6-dfceb4091a21.png)

**Comment by crisaless** [comment]
Looks great! Is there a class associated with the header? I need to be able to customize per deployment branding

**Comment by jrchudy** [comment]
I'm using `dropdown-header` with the added class `chaise-dropdown-header`. Going to go over this tentative design with hongsuda in a little bit and hopefully merge this later today so you can work with it tomorrow and next week.

I'll give you and update when this is merged and tag everyone in the #isrd-chaise channel in slack.

**Comment by jrchudy** [comment]
@crisaless the connected PR has been merged into master. An example can be found in [chaise-config-sample.js](https://github.com/informatics-isi-edu/chaise/blob/master/chaise-config-sample.js#L80-L84) in the chaise repository.
