### ISSUE TITLE
Sort by on the search page should have ascending/descending option

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#200]
Right now it seems to sort only in ascending order.  It would be very useful to be able to sort in defending order too.

**Comment by svoinea** [comment]
The sort direction is present in the commit c2a5621fdd4bc921f9e0009455cff582efc9ca92.

**Comment by robes** [comment]
![sort-bug](https://cloud.githubusercontent.com/assets/4202842/13470672/1ea8b9b4-e062-11e5-9857-136cb2bc8e46.jpg)

**Comment by robes** [comment]
I get a repeatable bug:

- go to `dev.isrd.isi.edu`
- search on mouse gene `MSX1`
- sort on `Title`
- click descending
- click ascending

I wonder if this is just revealing an underlying issue about encoding of titles in urls, or if this is really a sort button bug. Either way need to figure this out.

**Comment by karlcz** [comment]
@svoinea and I think this and another recent testing bug are probably a configuration regression where the Apache `AllowEncodedSlashes` setting has been lost from the HTTPS site config.

This causes the `%2F` to be decoded into `/` by Apache before it gets to normal URL processing, thus mangling the client's properly formatted request.

**Comment by robes** [comment]
okay, so then  this issue appears done to me.
