### ISSUE TITLE
support boolean alternate text in the dropdown/edit

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#2010]
Currently, you can define a custom mapping for how to display `true/false` of a boolean valued column, but this does not apply during the edit/dropdown so it is somewhat incomplete.

**Comment by jrchudy** [comment]
@robes @hongsudt changes for this have been merged into master. The preformat annotation on boolean columns is now honored for display in recordedit app.

One example I'm aware of can be found here:
https://dev.rebuildingakidney.org/~jchudy/chaise/recordedit/#2/Common:Collection/

**Comment by hongsudt** [comment]
Rob, can you review and close this issue? Thanks.
________________________________

**Comment by robes** [comment]
looked good on the example we had. thanks all.
