### ISSUE TITLE
Record entry confirmation page looks broken or infinitely in-progress

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#2017]
This might be due to the usage of pseudo-columns. You can see what I mean in FaceBase by:

1. create a Dataset
2. add 2+ related Biosample records
3. see the confirmation screen

The issues as I see it are:
1. the "Experiments" pseudo-column will show up blank and an infinite spinner in the header
2. the "Species" through "Phenotype" pseudo-columns will all be blank even if you selected them

The model for Biosample has a many-many relationship with Experiment and a direct FKEY relationship with the other (Species etc) fields.

I would suggest that this screen be changed to one of the following:
1. ~~only show the basic confirmation message, e.g., "4/4 Biosample Records Created Successfully"~~
   - This was an issue brought up in the past and having the table of data was more beneficial
2. filter out the pseudo-columns and show the rest of the columns in the summary table
   - no harm in doing this for the time being, but it doesn't seem to be more helpful either

**Comment by robes** [comment]
<img width="1682" alt="Screen Shot 2020-10-02 at 1 53 57 PM" src="https://user-images.githubusercontent.com/4202842/94969278-451d3380-04b7-11eb-8a3f-08d435ca438a.png">

A screenshot of the confirmation screen related to the above steps to reproduce.

**Comment by RFSH** [comment]
This is related to #1804.

**Comment by jrchudy** [comment]
From above, we are going to go with option 2 that Rob pointed out for a better UX experience:
> filter out the pseudo-columns and show the rest of the columns in the summary table

**Comment by robes** [comment]
Sounds good :+1:

**Comment by jrchudy** [comment]
The changes to ermrestJS to filter out the pseduo-columns have been merged into master. Reassigning to @robes for review.

**Comment by robes** [comment]
This is better but not exactly as I had imagined. I was thinking to not even show those pseudo-columns at all (not just not show the values in them). I think this is an improvement but I have a feeling we'll revisit it in the future.
