### ISSUE TITLE
collapsed Menu button doesn't work

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#2025]
I just noticed that if you narrow the width of the browser in Chaise until the menu collapses, the Menu button does nothing when clicked.

Tested on Gudmap/RBK and FaceBase and on Chrome/Firefox/Safari.

More detailed explanation and reasons to fix it : )

When you narrow the browser to less than 768px, the navigation collapses - as designed per Bootstrap - to a Menu button. You should be able to click the button and the menu would appear below. But when I click, nothing happens and usually the word "Menu" disappears.

I did notice that when I go to a chaise page on my iphone - the browser window doesn't get narrower. Instead the page looks zoomed out so you still get a normal view of the navigation, though it's pretty small. So this isn't an issue for a mobile device - and the majority of our users aren't using cell phones.

But a user would definitely have a problem if they wanted to resize the browser window. On my laptop with resolution 1440px x 900px the breakpoint is at about half of my screen, which is a reasonable width someone might use if they want to compare two images side by side, for example.

I can imagine it would not be a simple fix to configure the mobile menu to work well with complex navbar configs like we're doing on staging.gudmap.org - but we do need some kind of workaround.

**Comment by RFSH** [comment]
@kpherwan To provide more context,

- You can test in on any page in rbk-dev or isrd-dev, for example go to [this page](https://dev.rebuildingakidney.org/chaise/recordset/#2/Protocol:Protocol@sort(RMT::desc::,RID)) and you can see the behavior. Just reduce the page width until the "menu" button shows up.
- Related code to navbar are:
  - [`navbar.js`](https://github.com/informatics-isi-edu/chaise/blob/master/common/navbar.js): Where the component is defined and all the js code related to it.
  - [`navbar.html`](https://github.com/informatics-isi-edu/chaise/blob/master/common/templates/navbar.html): Navbar's html template. Navbar is using [`navbarMenu.html`](https://github.com/informatics-isi-edu/chaise/blob/master/common/templates/navbarMenu.html) to implement navbar elements.
- Navbar is using [bootstrap 3's navbar](https://getbootstrap.com/docs/3.3/components/#navbar). And it seems like we didn't properly implement the responsive case. So you would have to most probably change the HTML or JS code to fix the implementation.

**Comment by kpherwan** [comment]
The changes to support this have been merged into master. RBK and Facebase should work as expected though Gudmap has a different way of implementation right now in production. @crisaless can you please review and confirm if changes look good.

**Comment by crisaless** [comment]
Works as expected in RBK and FaceBase. I believe I used css to disable the Menu for GUDMAP. I'll look into it.
