### ISSUE TITLE
Override heuristics for head title

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2035]
From [this comment](https://github.com/informatics-isi-edu/chaise/issues/1967#issuecomment-651242988) in the previous issue this was discussed:

## How to override heuristics

For the record page title, the following can be used:

```
"tag:isrd.isi.edu,2016:table-display": {
  "row_name/page_title": {
    "row_markdown_pattern": "<title>"
  }
}
```

But what about other apps? If we want to follow the same pattern and allow them to define title based on data content, we can use `page_markdown_pattern`, so

```
"tag:isrd.isi.edu,2016:table-display": {
  "row_name/page_title": {
    "page_markdown_pattern": "<here>"
  }
}
```

But how should we contextualize this? should we introduce `row_name/page_title/detailed`, `row_name/page_title/compact`, etc?

If we don't want a data-oriented solution, we could add a `page_title` attribute that is contextualized to display annotation too.

```
"tag:misd.isi.edu,2015:display": {
  "page_title": {
     "compact": "<title>",
     "entry/edit": "<another title>"
  }
}
```

So we use `table-display` for record and `display` annotation for other pages. I don't like this solution, but I cannot think of a better way.

**Comment by RFSH** [comment]
Moved to wish list.
