### ISSUE TITLE
Display buttons not showing up

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#204]
Occasionally, chaise will come up and the display selector icons will be wrong.  Mouse over displays the correct tips.  Fixed by a refresh.

![image](https://cloud.githubusercontent.com/assets/3597150/12963954/4d61b956-d002-11e5-9c1b-a2ce763c7efe.png)

**Comment by svoinea** [comment]
The single time I could see by chance a "similar" situation was when the dev VM was doing its hourly update.

**Comment by hongsudt** [comment]
@carlkesselman What browser (including version) did you use? 

I tried it on firefox an didn't have any problem. @svoinea can you test it on Safari and Chrome? If you still couldn't replicate the problem, I suggest we close this issue and roll-out whatever left to staging.

**Comment by carlkesselman** [comment]
Safari.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Mar 7, 2016, at 8:33 PM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:


@carlkesselman<https://github.com/carlkesselman> What browser (including version) did you use?

I tried it on firefox an didn't have any problem. @svoinea<https://github.com/svoinea> can you test it on Safari and Chrome? If you still couldn't replicate the problem, I suggest we close this issue and roll-out whatever left to staging.

**Comment by svoinea** [comment]
I have tested it on Safari and Chrome and there was no problem.
