### ISSUE TITLE
Text value overflowing into page margin

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#2041]
This is a really minor nit, but maybe also minor to fix.

Notice how the URL (literally the URL value in the "URL" column/field) in this screenshot overflows into the page margin. I wonder if its possible to make this wrap without spilling into margin.

<img width="1744" alt="Screen Shot 2021-01-08 at 12 06 54 PM" src="https://user-images.githubusercontent.com/4202842/104059508-535fa780-51aa-11eb-8ea5-4e362227d67d.png">

**Comment by jrchudy** [comment]
We can add `overflow-wrap: break-word;` style to our cells in the top section of record app (`<td>` elements). 

For a temporary solution specific to that record page, the following style can be added to the custom css document denoted by `customCSS` in the chaise-config:
```css
.r_s_isa.r_t_project #entity-URL {
  overflow-wrap: break-word;
}
```

**Comment by robes** [comment]
I think we should be doing that:


We can add overflow-wrap: break-word; style to our cells in the top section of record app (<td> elements).

**Comment by jrchudy** [comment]
The `overflow-wrap: break-word;` style was added to our cells in the top section of record app. Changes for this have been merged into master. reassigning to @robes to verify it has been fixed.
