### ISSUE TITLE
Adding padding to inline comments

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#2045]
There should be a little more white space above and to the right of the inline comments. (The padding on the right isn't strictly necessary but content that is so wide can be less user friendly).

Suggest the following css rule:

`span.inline-tooltip {
    padding: 10px 10px 0 0;
}`

**Comment by RFSH** [comment]
We decided to add `padding-bottom: 5px` to `.inline-tooltip`s that are displayed below the page title. We also decided to adjust the spacing in record page which will also affects the `.inline-tooltip`s.
