### ISSUE TITLE
Search-box markdown name overflow

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#2064]
Using a long `markdown_name` for a `search-box` source definition leads to an ugly text overflow.  Is there anything we can do to allow this sort of longer help string to be available?  Some kind of truncated (cursor?) scrollable div, or a new tooltip field?

**Comment by jrchudy** [comment]
![image](https://user-images.githubusercontent.com/2932600/110678216-e86f2480-818a-11eb-98bd-8889fe54ad93.png)

**Comment by jrchudy** [comment]
From conversation during standup we talked about adding an info icon. Think about how to customize this info button separate from our heuristics for the placeholder text. We talked about the following:
```
source-definitions: {
  sources: {
    source-1: {
      source: [...],
      entity: true,
      aggregate: "array_d"
    },
    search-box: {
      or: [...]
    }
  }
}

**Comment by karlcz** [comment]
did you paste the wrong thing?  I'd expect something like:

"source-definitions": {
  "sources": {
     ...
     "search-box": {
       "markdown_name": "shorter inline name",
       "comment": "A potentially long name to show on the tooltip with wrapping",
       "or": [...]
     }
  }
}

**Comment by jrchudy** [comment]
I think we are talking about the same thing Karl. The json objects are the same, just that you added a `markdown_name` as well. 

I think for `markdown_name` you are suggesting that be used for the placeholder? Then if it's not defined, we default to our previous heuristics.

**Comment by karlcz** [comment]
Sorry, I didn't see either field in what you pasted... not sure if
that happened on your end or somehow in how the notification got
rendered to me via email.

Anyway, yes, I'm saying keep the current name as placeholder and allow
the extra comment for tooltip documentation.

**Comment by RFSH** [comment]
The changes in https://github.com/informatics-isi-edu/chaise/commit/11130c75bf4a8f1f76f3fcb8c808ea9ed963428f commit makes sure the placeholder doesn't overflow, and behave the same as facet options (where we're showing a `...` if text is wider than its container, and the tooltip will show the original text). 

I also created a new issue for the proposed changes to the `search-box`. So I'm going to close this issue.
