### ISSUE TITLE
SSR functionality with angularJS

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2065]
From discussions we had in chaise standup, we explored how to handle Server Side Rendering (SSR) for the angularJS application. Even with a snapshotted template, angularJS has to still recompile the page causing snapshotted content to be duplicated or disappear. More information on the [angularJS compiler](https://docs.angularjs.org/guide/compiler) and the underlying [$compile service](https://docs.angularjs.org/api/ng/service/$compile) that each app/directive relies on for controller functionality.

We came to the conclusion that "restoring" functionality via jQuery seems like a viable solution for SSR rendering since most of the content on the page doesn't rely on server requests and heavy javascript functionality. 

### The following is how the functionality and work to restore that functionality can be broken done:

1. Functionality that works:
   -  [x] HTML links (`<a>` tag)
2. Functionality that can be restored:
   - [x] Navbar dropdown functionality
   - [x] Rid search
     - Will blindly send user to input value without error checking
   - [x] show/hide toc panel
   - [x] scrollTo event for toc links
   - [x] Explore button
     - Would require finagling to add a hidden div with data=ref.appLink
     - OR rewrite button as a link and have an onclick event to intercept request for logging
   - [x] Accordion heading
   - [x] Iframe content
   - [x] Share and cite
     - Prefetch the modal (or copy contents to DOM)
       - Preload the share popup
         - on page load, open the modal before saving it
         - when template is loaded, modal is hidden on load
   - [x] Show empty sections button
     - Show all sections on load
   - [x] Table/edit vs custom display modes for related content
     - load both sets of content into the dom on page load before taking snapshot
   - [x] Proper angularJS error handling
     - Anything that relies on loading more templates is all relatively pathed in the codebase so it’s not easy to fix this
   - [x] table controls - Sorting
       - reimplementing sort by parsing content out of the HTML is tedious to accomplish, hiding icons instead 
   - [ ] Alert warning user of "static" content
3. Functionality that CANNOT be restored:
   - [x] Resizeable ToC
     - minor detail that is much harder to accomplish without angular-resizable library
     - won't fix
   - [x] Other table controls
     - Dropdown
       - reducing page size from above maximum will require reimplementing paging, hiding dropdown 
       - won't fix
     - Paging
       - load all data and disallow reducing page size. means no paging necessary, hiding buttons
       - won't fix
   - [x] login/logout
     - redirect them to chaise to login/logout (done)
     - No create/edit/copy/delete buttons available at page top
     - No edit/delete available in RT action column
   - [x] Add record for related tables (requires login)
     - won't fix because of login flow
   - [x] Export dropdown and export links
     - The dropdown functionality can be restored but the actual javascript to run the export service won’t work without a lot of extra work
     - dropdown opens
     - default csv option works without redirect
     - BDBag default option redirects and prompts for login

**Comment by jrchudy** [comment]
- [ ] Fix whitespace at bottom of page.

**Comment by RFSH** [comment]
@jrchudy Is this issue needed?

**Comment by jrchudy** [comment]
Not it's not. I meant to close this once we verified the pages were added to production and were being crawled by google.

Closing this issue.
