### ISSUE TITLE
Ability to change the "Show All" to "Hide All" related records by default

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#2067]
On a per catalog basis (so probably an annotation at the catalog level like a new `chaise-config` annotation property):
- ability to set your catalog's default behavior to "Hide All" related records by defaut

**Comment by jrchudy** [comment]
option 1: 
true - hide all empty sections regardless permissions
false - show all empty sections regardless of permissions
null - use login/create heuristics
```
hideEmptyRelatedOnLoad: true || false || null 
```

option 2:
```
emptyRelatedTables: {
  hide: ["globus-group-id-1", "globus-group-id-2"],
  show: ["*"] // true
}
```

We discussed both options in chaise standup and decided on sticking with option 1.

**Comment by jrchudy** [comment]
Reassigning this issue to @robes to verify the changes working for your intended use case.

**Comment by RFSH** [comment]
I'm going to close this due to inactivity.

**Comment by robes** [comment]
Wait… I thought this was done. No?

Or at least that there was a chaise config property introduced to allow us to change our preferred default of show/hide all.

On 7/13/21, 12:44 PM, "Aref Shafaei" ***@***.******@***.***>> wrote:


I'm going to close this due to inactivity.
