### ISSUE TITLE
Authentication-related header buttons and icons need cleanup

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#207]
The behavior of the Chaise UI header bar around login, logout, and displaying the current user identity are very confusing.  The default Chaise installation should be usable for simple projects without site customization.

- There seems to be a meaningless circular icon and the stray word "Profile" which doesn't communicate anything useful.  I think these should just go away as there is no generic UI functionality to expose here.
- The user name for a logged in user seems to be a clickable link with a useless URL that just breaks the current single-page app state. This should be non-clickable until we arrive at some future milestone that exposes a user profile page or similar that could be linked in a default app.

**Comment by svoinea** [comment]
Removed the circular icon and the stray word "Profile" from the Chaise header.
The user name for a logged in user is now not clickable.

**Comment by karlcz** [comment]
I reviewed this on one of the project sites that has security enabled and it looks better.
