### ISSUE TITLE
mobile menu not working in navbar

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#2070]
When you narrow the browser to less than 768px, the navigation collapses - as designed per Bootstrap - to a Menu button. You should be able to click the button and the menu would appear below. But when I click, nothing happens and usually the word "Menu" disappears. 

I did notice that when I go to a chaise page on my iphone - the browser window doesn't get narrower. Instead the page looks zoomed out so you still get a normal view of the navigation, though it's pretty small. So this isn't an issue for a mobile device - and the majority of our users aren't using cell phones.

But a user would definitely have a problem if they wanted to resize the browser window. On my laptop the breakpoint is at about half of my screen, which is a reasonable width someone might use if they want to compare two images side by side, for example. 

I can imagine it would not be a simple fix to configure the mobile menu to work well with complex navbar configs like we're doing on staging.gudmap.org - but we do need some kind of workaround.

**Comment by karlcz** [comment]
Isn't this the same as #2025  ?

**Comment by crisaless** [comment]
Yes! thank you. I searched mobile thinking I would have used that term if I'd filed this before.
