### ISSUE TITLE
Allow facet by non-RID choices

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#2072]
For some use cases, it would be better to allow faceting to work by non-RID choices.  There are several parts to this:

- [ ] Allow the source definition to end with a non-RID column in entity mode and honor it, rather than changing to RID implicitly.
- [ ] Add some syntax to allow source definitions to end with a _compound_ key and honor it.
- [ ] Allow choices to be encoded via non-RID key material to match the source definition
- [ ] Saving a query validates if a "RID based facet" is detected. Error out if detected and disable save until query changed
   - might be CFDE specific

That last item is a concern.  You want to be able to detect a hazard such as a bookmarked facets blob encoding choices with key material that no longer matches the model or the catalog.

- If using a non-RID key with an inline definition, the chosen column(s) might no longer comprise a key in the table.
- If using a sourcekey rather than inline definition, the choices might be relative to a definition that has changed and no longer ends with the same column(s).
- For some deployments, we'd like an extra strict check that entity choices still exist in the domain table. It would be good to give the user a warning modal that choices (e.g. vocabulary) are no longer defined and so the query is likely to return different results than intended, similar to detecting other ill-defined facets and warning before dropping them..

**Comment by RFSH** [comment]
To make it easier to track the process of this issue, we've broken it up into the following three issues:

- https://github.com/informatics-isi-edu/ermrestjs/issues/874: Proper handling of related entities with non-RID source definitions
-  https://github.com/informatics-isi-edu/ermrestjs/issues/875: Allow source definitions to end with compound keys.
- #2077: Error handling for facet blobs.

I am going to close this issue in favor of the other ones.
