### ISSUE TITLE
CFDE: Saved Query - consume augmented facet blob and produce proper errors

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2077]
This is an extension to #2073, where users want to apply a saved query to recordset. There are two scenarios for this:

- User is in the same recordset page, clicks on "show saved queries" and selects one of the queries.
- User is in the "dashboard" or saved query table, and clicks on a link associated with one of the saved queries and navigates to a table with applied saved query.

As part of #2098, we have to make sure we're adding some extra attributes to the existing facet object that we have. These extra attributes will be used for validation/transformation. 

Assuming that the two given scenarios open a new instance of recordset, we would just need to change the logic of merging filters in facet blob with facet panel to consume the new object. The following is the current logic:

![Screen Shot 2021-08-04 at 10 25 50 AM](https://user-images.githubusercontent.com/2129750/128226390-77295a61-9025-4d5f-9934-6a42da585fa8.png)

Currently we're doing this for each `and` filter in the blob, but the "Error" cases will terminate the logic and show a generic error instead.

And now we just want to modify this logic, to do verification and transformation. So,

https://lucid.app/lucidchart/5e978d3e-d2f3-4f57-998a-b1ec978811d6/view
![Screen Shot 2021-08-04 at 10 42 59 AM](https://user-images.githubusercontent.com/2129750/128229046-6376fd23-0dcb-44da-abe5-bd7f255104fb.png)

Based on this, the following is the behavior:

- If there wasn't any issues in the facet blob just show the result to the users.
- If there was any issues in the blob:
  - We should show an error popup to summarize the issues in the url. 
  - <details>
    <summary>This is a rough draft of how the error should look like</summary>

    ```
    # Unsupported Filters
    Some (or all) externally supplied filter criteria cannot be implemented with the current catalog content. 
    This may be due to lack of permissions or changes made to the content since the criteria were initially saved.

    - Discarded facets: Anatomy, Disease
    - Facets with some discarded choices: Taxnomy

    You may need to login to see parts of the model or data. Please login to continue.
    Click <b>OK</b> to continue with the subset of filter criteria which are supported at this time.
    ---------
    Error details (collapsable):

    Discarded facets:

    - Anatomy (3 choices): 
      - UBERON:0000004
      - UBERON:0000032
      - UBERON:0000099
    - Disease (2 choices): 
      - DOID:0040012
      - DOID:0040099

    Partially discarded facets:

    - Taxonomy (2/5 choices): 
      - NCBI:txid9606
      - NCBI:txid96434
    -----------

                                                                                                     [ OK ]

    ```

    </details>
  - While showing the error, in the background, recordset should fetch data based on portion of facet blob that was valid and parsable.
  - Recordset should not modify the browser location and users should see the same error if they try to refresh.
  - Clicking on "OK" should update the url and get rid of the parts of the blob that had issues.

**Comment by RFSH** [comment]
The changes to support this has been merged into master.
