### ISSUE TITLE
Add a post-logout page to every Chaise app

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#208]
Even if we manage to break the auto-login cycle via Globus authentication providers, it still seems like a broken UX flow for the logout button to reload the app and immediately send the browser to a login flow.  Someone not paying close attention may find their browser stopped at various points in the login flow without enough mental context to remember why they are logging in.

Instead, after logout the user should be presented with some interstitial page that tells them their session has been ended and they must click a link on this page to return to the app. To account for sites that allow anonymous access, we might make this more dynamic and use cookies or some other state to record the logout event and choose a different UI behavior at the time of `401 Unauthorized` events depending on this state:

- Send stateless page loads to login flow as before
- Send post-logout page loads to the interstitial with a link to continue the login flow

This way, a public site could return straight to the anonymous viewing mode after logout, since login is not forced. But, a private site will pause at the interstitial rather than immediately restarting the login flow.

**Comment by svoinea** [comment]
Created an initial post-logout page.

**Comment by karlcz** [comment]
We probably also want to thread the new logout @ljpearlman is working on in the globus_auth branch to route back to this page or otherwise coordinate the two?  Should that extend this issue or be another companion issue...?

**Comment by hongsudt** [comment]
Related to #255.

**Comment by karlcz** [comment]
One thing I'm afraid we might have lost in all this... what is going to happen on idle session timeout?  It seems pretty absurd if it bounces through login and restarts a webauthn session based on existing globus session.  But is there anything else we can do...? @ljpearlman

**Comment by karlcz** [comment]
We observed a failure mode where the webauthn DELETE returns 404 and the chaise logout fails. We probably need to include post-logout advice with the 404 as well and still send the user to the Globus logout even if we don't have a current session for the user in webauthn.  Is this going to be possible @ljpearlman ?

**Comment by karlcz** [comment]
I think we decided to close this and address further improvements to logout flow in new issues
