### ISSUE TITLE
Record copy won't let me edit any fields

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#2088]
On the synapse-dev Image Region table, I hit a weird error trying to clone and modify a record.

If I try to copy an existing record, the form includes the fields with values from the source form.  Any attempt to revise the form eports "This field cannot be modified. To modify it, remove all records that have this field disabled (e.g. Record Number 1)".  This is on a single-record form for create record.

If I submit it, the field is populated with the copied source value and I can then edit it to change it.

**Comment by RFSH** [comment]
This is because of a bug that I introduced in my recent dynamic ACLs changes. The copy functionality is broken because of it.

I'll fix it and modify our copy test case to test for this case as well.

**Comment by RFSH** [comment]
@karlcz 
I pushed a fix for this to master. I manually tested this in rbk-dev and it's working properly now. I wasn't able to test the fix in synapse-dev since it is still using the old code and hasn't been updated with master.
