### ISSUE TITLE
Navbar issues

### ISSUE THREAD

**Issue by kpherwan** [informatics-isi-edu/chaise#2090]
- [ ] The text of the menu option wraps when width gets limited due to the scrollbar i.e. the browser doesn't accommodate width for the scrollbar but instead takes up width of the container/element.

<img width="518" alt="Screen Shot 2021-06-10 at 2 15 36 PM" src="https://user-images.githubusercontent.com/78573171/121604677-d1490880-c9ff-11eb-9a50-c1f10dda25ec.png">

Relevant URLs -

https://stackoverflow.com/questions/5605667/scrollbar-shifts-content

https://stackoverflow.com/questions/1417934/how-to-prevent-scrollbar-from-repositioning-web-page

- [x] In Safari exclusively, the submenu is not visible when the vertical scrollbar is enabled. My understanding is that Safari has some incompatibilities with position:fixed and scollbar. The submenu options are still clickable and inspectable but they are not visible!

Relevant URLs -

https://bugs.webkit.org/show_bug.cgi?id=160953

https://stackoverflow.com/questions/26704903/only-in-safari-positionfixed-child-cut-off-when-parent-is-positionfixed-and/59656203#59656203

**Comment by jrchudy** [comment]
This is fixed in safari with the migration to react. The other issue about text wrapping still occurs

**Comment by jrchudy** [comment]
Both issues still occur. 
 - Depending on the length of the text, the OS/browser will decide to place the scrollbar inside of the element or outside of the element on the right
   - This depends on their OS settings like on mac being able to show scrollbars "Based on using a mouse vs trackpad" which will hide most scrollbars until the element is hovered
   - we can't easily control this and is only a minor inconvenience
     - solution requires dynamic javascript to calculate element sizes and change CSS styles
 - the 2nd issue can be resolved by removing the z-index in safari browsers for the "parent" menu

**Comment by jrchudy** [comment]
The merged pull request fixes the 2nd bullet from the description above. The first issue will be marked as "won't fix". Closing this issue
