### ISSUE TITLE
Redirect at Cancel Login

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#2091]
Our home page on `PDB` forces you to login.
If the user clicks the `Cancel` button, the following screen is shown:
<img width="1235" alt="Screen Shot 2021-06-23 at 1 30 45 PM" src="https://user-images.githubusercontent.com/1609577/123164937-6f899500-d428-11eb-9126-422f44c938ac.png">

If the user clicks the `OK` button, he is redirected to the home page, which in this case forces again a login.

Is it any `chaise` configuration by which mean the user can remain on the screen shown in the picture w/o the popup window?

The navigation bar menu being  enabled,  the user can click on the `Documentation` link which is a page that does not require login.

The `Documentation` link can be clicked also currently, but it would be nice to get rid of the popup window.

**Comment by jrchudy** [comment]
@svoinea yesterday we pushed a change to chaise master to enable the navbar when the login dialog is shown.

We intend to modify the error dialog to have a more appropriate error when we know it came from a dismissed login dialog to communicate to the user that they need to login to continue.

**Comment by svoinea** [comment]
@jrchudy I tried https://data.pdb-dev.org/chaise/recordset/#1/PDB:entry and I don't see any differences.
The screen with `You need to be logged in to continue.` has still the navbar disabled, and when click on `Cancel`, you get the screen with the `Terminal Error` which has the navbar enabled (as it was before). 
The `pdb` server is doing daily updates.

**Comment by jrchudy** [comment]
When I made the change to chaise yesterday I referenced the class on the modal element and not the body element. The issue with that is the modal is a sibling to the container the navbar is in, so the rule wasn’t being applied. The rule should be working properly with the next update.

**Comment by svoinea** [comment]
@jrchudy I have checked and it is OK now.
