### ISSUE TITLE
Using tcrs on multiple rows causes timeout

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2092]
## Description

While implementing dynamic ACls support, we decided to always use `tcrs` to be able to support the following scenario:

> Given that data-modelers can modify column-level ACLs, there might be a case where user can update a particular row, but none of the visible columns are updatable. We decided treat this the same as if the whole row is disabled. So if users navigate to a recordedit page of this row, chaise will throw a forbidden error. And to be able to disable the "edit" button in record or recordset button, we would have to ask for `tcrs`.

But we found out that this can be disruptive and cause timeout in some deployments (currently this has been observed in cirm) and therefore we should modify the implementation.

## What we could do 

In short we should avoid using `tcrs` on a request that will return multiple rows. This includes compact views in all of our apps. 

Doing this in read-only modes are straight forward:
- If `detailed` context, use `tcrs`.
- If `compact` (and its sub-contexts), use `trs`.

Then if that special case happens, we would show the edit button and just throw an error when users go to recordedit page. Based on what Karl mentioned
> DBA should fix their policy if they don't like the UX I described.  They can coordinate row-level and column-level dynamic policies to go true/false together for every given group/role.  And worse case, I think it will just be as described: a pencil might be enabled to go to recordedit and then in recordedit you can determine that there are no form fields to activate and give a forbidden modal instead.

The hardest part is how we want to do this in recordedit. We have to somehow do `tcrs` but doing it in a multi-edit page might cause a timeout and therefore we should come up with an alternative. Also we don't have a signal that says the page is in single or multi. After sending the request, based on the response, recordedit shows a single edit page or a multi-edit one. Based on our discussions the followings are different ways that we could handle this:

1. Send a request with `tcrs` and if it timed out, try again with `trs`.

Implementing this would be very simple. But 
  - Causes too much overhead on server as we're not keeping track of this and every time user reloads the page the same two request would be sent to the server. 
  - By using `trs` we're completely dropping support for column-level ACLs on that table. 
  - It will lead to a misleading and confusing UX. Since the timeout is dependent on the number of rows and columns, users might see disabled columns in some cases and enabled ones in others. For example let's say user goes to a page with RID=1 and because of `tcrs` sees column `col` disabled. But going to a multi-edit page that shows the RID=1 and times out would show the `col` column enabled. 

So this is not really a realistic option for us.

2. Send the main request using `trs` and then for each of the rows that user can update, send individual requests with `tcrs`.

This doesn't have the UX issue of the other solution, and also doesn't bombard server with heavy requests as each individual request would be a lot faster. But requires a flow-control system in recordedit and since we're sending multiple requests, we would have to come up with a UX to let users know that the page is not completely loaded.

One solution is showing the current spinner only when the main request is pending. And then for the rows that are pending the `tcrs` request we could show a spinner and disallow user interaction. This way users can interact with the page while other parts of the page is loading. This can only work if the rows are independent, but that's not really the case. The select-all feature modifies the values of a column on all the rows. And also we have a logic to disable modification of a column based on ACLs of other rows (If one of the columns in a row cannot be edited, we are not allowing users to edit other rows as well since we're sending a batch PUT request). So doing this would require a lot of other changes.

The other simpler thing that we could do is showing the spinner while we're waiting for all the individual `tcrs` requests. This makes the implementation a lot simpler, but might cause a delay on the page. To signal to the users why the page is taking a longer than expected time, we could show some sort of a progress bar instead. 

**We need to decide if showing a spinner for all the requests is acceptable or not. If that's the case, the only complexity is adding a simple flow-control and then bootstrapping the recordedit app based on that.**

**Given that this would cause some degraded user experience (more load time), we might want to allow data-modelers to turn this feature off on some tables. So we might want to introduce a new annotation.**

**Comment by ljpearlman** [comment]
I was just about to create an issue about this -- it's causing timeouts (and postgres uses 99% of the cpu until the request times out) on the un-faceted view of the Specimen table on rbk-dev -- so we can't update chaise on the production rbk server until there's at least a way to turn this behavior off.

rbk-dev still isn't a suitable test environment for chaise, but the query generated for https://dev.gudmap.org/chaise/recordset/#2/Gene_Expression:Specimen@sort(RCT::desc::,Stage_Ordinal,RID)
times out when run on rbk-staging. Changing `tcrs:=tcrs` to `trs:=trs` prevented the timeout but still slowed the query considerably -- my unscientific test of running each query a couple times resulted in the plain query (with neither tcrs nor trs) taking 7-8 seconds and the trs query taking 27-29 seconds).

This is the tcrs version of the query:

https://staging.gudmap.org/ermrest/catalog/2/attributegroup/M:=Gene_Expression:Specimen/F16:=left(Embedding)=(Vocabulary:Embedding:Name)/$M/F15:=left(Phenotype)=(Vocab:Kidney_Phenotype:Name)/$M/F14:=left(Representative_Image)=(Gene_Expression:Image:RID)/$M/F13:=left(Wild_Type)=(Gene_Expression:Wild_Type:Name)/$M/F12:=left(Parent_Specimen)=(Gene_Expression:Specimen:RID)/$M/F11:=left(Sex)=(Vocabulary:Sex:Name)/$M/F10:=left(Stage_ID)=(Vocabulary:Developmental_Stage:ID)/$M/F9:=left(Cell_Line)=(Cell_Line:Cell_Line:Name)/$M/F8:=left(Fixation)=(Vocabulary:Fixation:Name)/$M/F7:=left(Provenance)=(Common:Provenance:Name)/$M/F6:=left(Consortium)=(Common:Consortium:Name)/$M/F5:=left(Principal_Investigator)=(Common:Principal_Investigator:Person)/$M/F4:=left(Curation_Status)=(Vocab:Status:Name)/$M/F3:=left(Preparation)=(Vocab:Preparation:Name)/$M/F2:=left(Assay_Type)=(Vocabulary:Assay_Type:Name)/$M/F1:=left(Species)=(Vocabulary:Species:Name)/$M/RCT,Stage_Ordinal,RID;M:=array_d(M:*),F16:=array_d(F16:*),F15:=array_d(F15:*),F14:=array_d(F14:*),F13:=array_d(F13:*),F12:=array_d(F12:*),F11:=array_d(F11:*),F10:=array_d(F10:*),F9:=array_d(F9:*),F8:=array_d(F8:*),F7:=array_d(F7:*),F6:=array_d(F6:*),F5:=array_d(F5:*),F4:=array_d(F4:*),F3:=array_d(F3:*),F2:=array_d(F2:*),F1:=array_d(F1:*),tcrs:=tcrs(M:RID)@sort(RCT::desc::,Stage_Ordinal,RID)?limit=26

This is the "plain" query:

https://staging.gudmap.org/ermrest/catalog/2/attributegroup/M:=Gene_Expression:Specimen/F16:=left(Representative_Image)=(Gene_Expression:Image:RID)/$M/F15:=left(Embedding)=(Vocabulary:Embedding:Name)/$M/F14:=left(Fixation)=(Vocabulary:Fixation:Name)/$M/F13:=left(Cell_Line)=(Cell_Line:Cell_Line:Name)/$M/F12:=left(Stage_ID)=(Vocabulary:Developmental_Stage:ID)/$M/F11:=left(Phenotype)=(Vocab:Kidney_Phenotype:Name)/$M/F10:=left(Wild_Type)=(Gene_Expression:Wild_Type:Name)/$M/F9:=left(Parent_Specimen)=(Gene_Expression:Specimen:RID)/$M/F8:=left(Provenance)=(Common:Provenance:Name)/$M/F7:=left(Sex)=(Vocabulary:Sex:Name)/$M/F6:=left(Consortium)=(Common:Consortium:Name)/$M/F5:=left(Principal_Investigator)=(Common:Principal_Investigator:Person)/$M/F4:=left(Curation_Status)=(Vocab:Status:Name)/$M/F3:=left(Preparation)=(Vocab:Preparation:Name)/$M/F2:=left(Assay_Type)=(Vocabulary:Assay_Type:Name)/$M/F1:=left(Species)=(Vocabulary:Species:Name)/$M/RCT,Stage_Ordinal,RID;M:=array_d(M:*),F16:=array_d(F16:*),F15:=array_d(F15:*),F14:=array_d(F14:*),F13:=array_d(F13:*),F12:=array_d(F12:*),F11:=array_d(F11:*),F10:=array_d(F10:*),F9:=array_d(F9:*),F8:=array_d(F8:*),F7:=array_d(F7:*),F6:=array_d(F6:*),F5:=array_d(F5:*),F4:=array_d(F4:*),F3:=array_d(F3:*),F2:=array_d(F2:*),F1:=array_d(F1:*)@sort(RCT::desc::,Stage_Ordinal,RID)?limit=26

And this is the "trs" query:
https://staging.gudmap.org/ermrest/catalog/2/attributegroup/M:=Gene_Expression:Specimen/F16:=left(Embedding)=(Vocabulary:Embedding:Name)/$M/F15:=left(Phenotype)=(Vocab:Kidney_Phenotype:Name)/$M/F14:=left(Representative_Image)=(Gene_Expression:Image:RID)/$M/F13:=left(Wild_Type)=(Gene_Expression:Wild_Type:Name)/$M/F12:=left(Parent_Specimen)=(Gene_Expression:Specimen:RID)/$M/F11:=left(Sex)=(Vocabulary:Sex:Name)/$M/F10:=left(Stage_ID)=(Vocabulary:Developmental_Stage:ID)/$M/F9:=left(Cell_Line)=(Cell_Line:Cell_Line:Name)/$M/F8:=left(Fixation)=(Vocabulary:Fixation:Name)/$M/F7:=left(Provenance)=(Common:Provenance:Name)/$M/F6:=left(Consortium)=(Common:Consortium:Name)/$M/F5:=left(Principal_Investigator)=(Common:Principal_Investigator:Person)/$M/F4:=left(Curation_Status)=(Vocab:Status:Name)/$M/F3:=left(Preparation)=(Vocab:Preparation:Name)/$M/F2:=left(Assay_Type)=(Vocabulary:Assay_Type:Name)/$M/F1:=left(Species)=(Vocabulary:Species:Name)/$M/RCT,Stage_Ordinal,RID;M:=array_d(M:*),F16:=array_d(F16:*),F15:=array_d(F15:*),F14:=array_d(F14:*),F13:=array_d(F13:*),F12:=array_d(F12:*),F11:=array_d(F11:*),F10:=array_d(F10:*),F9:=array_d(F9:*),F8:=array_d(F8:*),F7:=array_d(F7:*),F6:=array_d(F6:*),F5:=array_d(F5:*),F4:=array_d(F4:*),F3:=array_d(F3:*),F2:=array_d(F2:*),F1:=array_d(F1:*),trs:=trs(M:RID)@sort(RCT::desc::,Stage_Ordinal,RID)?limit=26

**Comment by RFSH** [comment]
Based on the discussions that we had, I should try to avoid using `trs` and `tcrs` as much as I can and only use `tcrs` where we want to show an edit form and need it. The degraded UX is fine and can be avoided by changing the ACL policies. Since the required changed to use `tcrs` is more complicated, we're going to remove usage of `tcrs` and only use `trs` when we have to. Therefore the immediate changes to resolve this issue are:

- [ ] Don't use `trs`/`tcrs` when the table has static permissions.
- [ ] If table has dynamic permission, use `trs` only for the requests that need to show edit/delete buttons or check edit permission (so only main requests of chaise apps, as well as related entity requests.)


The list of future improvements that we will work on later:
- [ ] Add a table-level annotation to signal chaise that we should use tcrs in recordedit
- [ ] If the flag is set, after sending the main trs  request in recordedit, send requests with tcrs for the rows that can be updated (to enable/disable columns).
- [ ] Gracefully drop the UX services based on timeout error on requests with trs and tcrs

**Comment by RFSH** [comment]
In the following I'll summarize the result of discussions that we had and our plan for the ACL support.


The following are how we get the ACL information:
- static ACLs: schema request
- dynamic table-level ACLs: `trs` as part of the request to fetch the rows
- dynamic column-level ACLs: `tcrs` as part of the request to fetch the rows

Based on this, we can break down the level of ACL support as the following:

1. Only support static ACLs (don’t ask for `trs` or `tcrs`)
2. Support dynamic table-level ACLs (only ask for `trs`)
3. Support dynamic table-level ACLs in read-only pages and column-level ACLs in recordedit (`trs` in read-only, `tcrs` in recordedit)
4. Support dynamic table-level and column-level ACL in all chaise apps (use `tcrs` everywhere)


By doing "3" Chaise fully supports ermrest ACLs and the only downside is the degraded UX in that specific case where users can update the row but non of the visible columns are updatable. In this case, users can click on "edit" button and navigate to recordedit page, but upon going to that page, chaise will throw an error and won't allow them to edit the data. Given this, we don't need to go with the approach "4" for now.

Later, to increase performance and flexibility of chaise we can introduce a chaise-config property (or a table-level annotation) to allow data-modelers to configure the level of ACL support that they want.
