### ISSUE TITLE
CFDE: Favorite terms and rows

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2099]
To support the favorites feature, we need to consider what places we want an indicator that a vocabulary term is favorited. Some of the potential places include:
#### requirement for August deadline (Epic 3)
  - in the facets on left of recordset app 
    - shown below in the attached image
      - show favorited options on load
      - on hover, show a star users can click to toggle whether the entity/term is a "favorite"
      - this will have no effect on the sort order (favorites won't show first)
    - should this translate to all facets in other recordset popups?
      - only in show more popup
  - In the CFDE system, each favorite is stored in a table named corresponding to the entity the favorite is for, for example:
     - favorite_anatomy
     - favorite_assay_type
     - favorite_data_type
  - configuration:
     - add a property (`user_favorites`) to the new `table-config` annotation ([detailed here](https://github.com/informatics-isi-edu/chaise/issues/2098)) on the leaf table to point to the favorite table
       - when defined, allow favoriting on entities for this leaf table
     - child object, `storage_table`, that is the same as the `savedQueryConfig.storageTable` which tells the UI where to save and fetch favorites from
       ```
       "tag:isrd.isi.edu,2021:table-config": {
          "user_favorites": {
            "storage_table": {
               catalog: "registry",
               schema: "CFDE",
               table: "favorite_anatomy"
            }
          }
       }
       ```
      - More properties to add to the table-config to remove hard coded options:
         - https://github.com/nih-cfde/cfde-deriva/issues/214#issuecomment-902260380

    
#### Stretch goal 1
  - when viewing the vocabulary table as a recordset
    - suggestion was to be another icon in the action column (clicking favorites/unfavorites)
    - `recordset/#1/schema:vocab_table` recordset page
    - show more popup
    - foreign key picker
    - add pure and binary
  - on individual record pages 
    - maybe a star indicator at top of page

#### Stretch goal 2
  - allow vocabulary term displaynames to include star that is "functional"? 

<img src="https://user-images.githubusercontent.com/2932600/126007874-debe8fcd-3b02-4e2c-906b-3345e8c9c997.png" height=550 width=500>

**Comment by RFSH** [comment]
Just for history purposes so we can track the changes, I'm going to mention the further changes that we did to fix some of the issues related to this feature:

- https://github.com/informatics-isi-edu/chaise/commit/1546ef15662f0f735aeb144e2c0e22a70873786d: Use the new `oncreate=skip` API and error handling changes related to that. Also added a spinner to favorites to disallow users from sending multiple requests.
- https://github.com/informatics-isi-edu/chaise/commit/0f1215b54db85b296ae37ab7f438614c3d7b1038: Fix a bug related to add pure and binary.
- https://github.com/informatics-isi-edu/chaise/commit/6420d299bdc726b3bc029493f94340b6814d80f0 and https://github.com/informatics-isi-edu/chaise/commit/042a7eb6704209b595d2564f8bb653f49aa21fcd: Making sure state of favorites is consistent between different facets as well as facet popup.
