### ISSUE TITLE
3rd party scripts not under vendor subdir

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#21]
Is there a reason for the bootstrap scripts not under the vendor directory but under the scripts dir? I would think they belong under scripts/vendor.

**Comment by robes** [comment]
also applies to scripts/respond.js and any other 3rd party scripts not under the scripts/vendor subdir.

**Comment by svoinea** [comment]
The bootstrap.* files were moved under the "vendor" directory.
