### ISSUE TITLE
Column annotation to display string in value structured as sets of columns with N characters 

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#210]
Example: 
(from https://gpcr-dev.misd.isi.edu/chaise/record/#1/gpcr_browser:construct_gui/title=IMPT-1003)

In GPCR we have a column "receptor protein sequence"  and the value is the following sequence  

ETPNTTEDYDTTTEFDYGDATPCQKVNERAFGAQLLPPLYSLVFVIGLVGNILVVLVLVQYKRLKNMTSIYLLNLAISDLLFLFTLPFWIDYKLKDDWVFGDAMCKILSGFYYTGLYSEIFFIILLTIDRYLAIVHAVFALRARTVTFGVITSIIIWALAILASMPGLYFSKTQWEFTHHTCSLHFPHESLREWKLFQALKLNLFGLVLPLLVMIICYTGIIKILLRRPNEKKSKAVRLIFVIMIIFFLFWTPYNLTILISVFQVFLFTHECEQSRHLDLAVQVTEVIAYTHCCVNPVIYAFVGERFRKYLRQLFHRRVAVHLVKWLPFLSVDRLERVSSTSPSTGEHELSAGF

We would like these string (sequence) to be displayed as chunks of 10 characters with a blank space in between. We don't want line breaks to fall within one of these chunks of 10. So we would like to see 

ETPNTTEDY  DTTTEFDYGD ATPCQKVNE RAFGAQLLP PLYSLVFVIG 
PLYSLVFVIG LVGNILVVLVL VQYKRLKNM TSIYLLNLAIS DLLFLFTLPF 
WIDYKLKDD  ..........

**Comment by karlcz** [comment]
Does there need to be a specific array-like structure of these blocks
or can they just reflow to variable-width tables as long as it breaks
on the space between blocks?

**Comment by bugacov** [comment]
​J​
ust reflow to variable-width tables as long as it breaks
on the space between blocks
​.

No call for specific structure at this point.​

**Comment by hongsudt** [comment]
reference informatics-isi-edu/gpcr-project#66

**Comment by hongsudt** [comment]
@robes Can we add this to 2016-02 milestone since GPCR needs this for its release?
