### ISSUE TITLE
More Saved Query Features

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2103]
The following is the functionality for saving queries that we said we will work on at a later time listed in issue #2080 as MVP.later:
- [ ] Schema and/or table property to turn on/off support for saved queries
    - might want to be able to disallow users from saving queries for vocabulary tables
- [ ] Other places to support saving queries
    - Pure and Binary add popups (record app)
    - Foreign key picker popups (recordedit)
    - "Show more" popup from clicking in facet (applies to record, recordset, and recordedit)
- [ ] control public vs private viewing
- [ ] When a saved query is applied, allow the back button from the browser to navigate back to the previous recordset page with the previous query

In recent discussions about saved query UI we talked about creating a more stateful recordset view scoped by the saved query. When a user clicks to apply a saved query, we want recordset to behave as if it's operating in an edit mode for the saved query.
 - [ ] Show the "name" of the saved query somewhere on the page (next to the title or inline with chiclets)
    - indicate the query has been modified since page loaded
       - warning icon
       - "*" to say it's dirty
 - [ ] the saved queries dropdown would have more options with:
    - "Save Query" - updates the saved query RS is scoped by
    - "Save Query as" - shows the create form to create a new saved query

**Comment by RFSH** [comment]
Moved to wish list.
