### ISSUE TITLE
Modify behavior of bullet lists in markdown container

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2105]
Currently there's a CSS rule that is hiding the bullet icon if there's just one element in the list. We added this for the cases that only a list is displayed to the users and showing the bullet list just makes the page more cluttered. But, in the cases where we have a header or other contents in the `markdown-container`, we should show the bullet list.

So the rule should be changed to "hide the bullet icon, only if it's the single child of a list that doesn't have any other siblings."

**Comment by kpherwan** [comment]
Closing it as changes have been implemented.
