### ISSUE TITLE
Date picker throws error when try to edit value in search boxes

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#213]
The date picker seems to work well if boundary dates are mouse picked from the presented choices but throws and error if try to keyboard enter a value in one of the date boundaries search boxes 

Example: 

1) go to 
https://dev.gpcrconsortium.org/chaise/search/#1/gpcr_browser:construct_gui?facets=(construct_gui:site::eq::USC)&layout=table&page=1

2) select the "date_registered" facet 

3) try to backspace on any of the search boxes

error 
Status: 409
ResponseText: 409 Conflict
The request conflicts with the state of the server. invalid input syntax for type date: "2016-01-"
LINE 8: ...te" = 'USC'::text)) AND ((t0."date_registered" >= '2016-01-'...
                                                             ^

TextStatus: error
ErrorThrown: Conflict
URL: https://staging.gpcrconsortium.org/ermrest/catalog/1/aggregate/A:=gpcr_browser:construct_gui/site=USC/date_registered::geq::2016-01-/$A/cnt:=cnt_d(title)

**Comment by svoinea** [comment]
Fixed in the master with commit 714e6461a1b2994d8981c1941b8685e6fab5645a by making readonly the input fields of the date picker.
In this way, the user can modify the dates only through the date widget.

**Comment by bugacov** [comment]
I confirm that the read only works and no longer throws error when trying to edit the field. But, is that the behavior we want? Wouldn't be a case in which the user wants to manually enter the value?

**Comment by hongsudt** [comment]
I think we should allow user to manually edit the date.. For example, the default on rbk is in 2014. If I want to set it to the current year, I would need to do too many clicks.

**Comment by hongsudt** [comment]
I am closing this issue for search. We will deal with this in recordset app.
