### ISSUE TITLE
Unsupported Filters error produces broken errors UX

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2136]
Unsupported Filters error allows users to still interact with the application but further errors are being ignored (and not displayed to the user). The unsupported filters error should be changed to be treated as "dismissible".

This came up with an improperly defined facet url and an invalid sort modifier also being applied.

**Comment by RFSH** [comment]
This behavior has been fixed in the React implementation. We're now showing the Unsupported filter first and after dismissing it, the sort error is displayed to the users.
