### ISSUE TITLE
Possible bug in filtering code

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#214]
It appears like Chaise may be making a redundant display request.  The following actions on facebase.org show the issue:

click “start from scratch” link on home page
Enter “Msx1” in “Search within attributes” field
Select “Mouse Gene” attribute
Click “MSX1” checkbox
The results table briefly shows 641 results and then shows 10 results.

**Comment by svoinea** [comment]
Without selecting any filter, Chaise gets all the 641 results, but hides them.
Once you select a filter:
- The results are unhidden 
- The request with the filter is sent to the server
- The new results are rendered.

Therefore, for a short while you have just seen the 641 old results (w/o any filter) that were hidden. Once the 10 new results (with a filter) are available, they replace the old ones.

**Comment by carlkesselman** [comment]
Does this make sense?  Why would you select all the results, hide them and then fetch filtered results?

Carl

Sent from my iPhone

On Feb 26, 2016, at 4:39 PM, svoinea <notifications@github.com<mailto:notifications@github.com>> wrote:


Without selecting any filter, Chaise gets all the 641 results, but hides them.
Once you select a filter:

  *   The results are unhidden
  *   The request with the filter is sent to the server
  *   The new results are rendered.

Therefore, for a short while you have just seen the 641 old results (w/o any filter) that were hidden. Once the 10 new results (with a filter) are available, they replace the old ones.

-

**Comment by svoinea** [comment]
In the original design, we were displaying the results when no filter was selected.
Anyway, when we clear all the filters, we have a similar situation. Even if we don't get all the results, we will hide the ones selected with the previous filter, and while selecting a new filter, the results table briefly will show the old results before showing the new results.

**Comment by hongsudt** [comment]
It seems like we won't be fixing this issue. Will close this for now and put it in wishlist.
