### ISSUE TITLE
Disable related entity add button when the main key is null

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2142]
Given that database allows foreignkey definition based on nullable columns, there might be a case where a related entity is based on a null column of the main table. In this case, Chaise won't be able to provide a proper "Add record" UX and if users attempt to add a new record they will see a raw "Conflict" error from ermrest.

Therefore we should detect this and disable the "add button". We might also want to provide extra information why the button is disabled.

**Comment by karlcz** [comment]
Just to make this really explicit...

For record app, a related entity section should disable the button if
the "parent" record page has null key material for the editable
association.  There is no reason to offer the UX because it cannot
work when the pre-filled values will be null.

For foreign key pickers, there should implicitly be a non-null filter
on the domain of available records which can be linked.

For compound fkey scenarios, consider key material null if ANY
component of the key is null.

**Comment by jrchudy** [comment]
### Pure & Binary add
We should disable the "Add record" button on record app for each related entity if the key information is null (**nullable**?). It seems like this should be based on the key information that the "path" uses and check if that column can be set to `null`, if it can, this button should be disabled. There should be a tooltip communicating why this input is disabled.

**What does this mean when a filter is applied in the path to remove `null` values?**


### Foreign Key inputs
For simple Foreign Keys, above it was mentioned that we should pre-filter the set. While this would work, it raises the question **"What if the filtered set returns 0 rows?"**. We could mitigate this "0 rows" case by pre-fetching the data before "enabling" the input but that might require "N" extra requests where N is the number of foreign key inputs. **If the set includes 10 total rows but 6 have null key information, would we "disable" the `add` button for that row in the foreign key picker?**

An alternative would be to do something similar as the pure and binary add case, and disable the foreign key input on load with a tooltip communicating why the input is disabled.


For compound Foreign Keys, the same decision for simple foreign keys applies. But in the case of compound FKs, if any column is null (nullable), then the disabled decision should be made.

**Comment by jrchudy** [comment]
Changes for this have been merged into master, closing this issue.
