### ISSUE TITLE
Review cid and pcid values

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2143]
A while ago we documented the list of cid values that are used throughout deriva in [here](https://docs.google.com/spreadsheets/d/1zoNTG0Vx4cedIKsHvGN1mZBTeFmDMWyQ1rfKR3ksSbU/edit#gid=0), but we never got back to review and take action based on it. 

Based on a brief conversation that we had, 
- We should make sure deriva webapps are using consistent cid and navbar pcids.
- Review whether we want to continue using `pcid=navbar` for non-chaise pages (static sites that are using navbar), or should we do `navbar/static` like this sheet suggets?
-  Do we want to add `chaise/` as a namespace to chaise app cid values?

We also realized that gudmap has `?pcid=navbar/static` in all the chaise links. The navbar app will use its own heuristics to add a proper `pcid` to all the chaise links, and therefore the `pcid` defined in the chaise-config will be ignored. So we should just remove this to avoid confusion.

**Comment by RFSH** [comment]
We should also make sure the guidelines are documented for chaise/ermrestjs.

**Comment by jrchudy** [comment]
`cid` and `pcid` are being used properly in each webapp except for `treeview`. More information can be found in the issue in deriva-webapps:
https://github.com/informatics-isi-edu/deriva-webapps/issues/84
