### ISSUE TITLE
Logging for Help app

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2147]
The help app doesn't do any logging currently outside of the catalog request made for the navbar. This doesn't communicate what "page" the help app has loaded. This app sets a query parameter (`page`) to decide what help page to load. 

It was also suggested that this logging should be a client action when a help page is selected. We talked about possibly using the `page` name as part of the action string or as a dcctx parameter.

**Comment by RFSH** [comment]
I just want to add this would also allow us to properly log `ppid` and `pcid` in this app as well. Given that the current app is not sending any request to ermrset, we couldn't properly log this information and with the addition of the client action this would be possible.

**Comment by RFSH** [comment]
Moved to wish list.
