### ISSUE TITLE
Add bulk delete functionality to recordset

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2148]
With #1535 we're going to bring back batch unlink feature which was reverted because of the issues that it had. While discussing it, we decided to also add a "Bulk Delete" button to recordset. It should be added to the right of the "Bulk Edit" button. 

The bulk delete should not rely on the current Reference url and should create a URL from scratch where it's filtering by the shortest key value of the displayed page of results. To do so, we most probably need to either add a new `delete` API or change the `Reference.delete` to accept a `page` (Originally [this PR](https://github.com/informatics-isi-edu/ermrestjs/pull/668) was created to modify the delete button to accept a `tuples` array but because of the issues that it had we reverted the changes).

**Comment by RFSH** [comment]
While discussing about delete function in ermrestjs, we realized that just relying on the reference's uri is dangerous, and we have to change the function to actually accept an array of tuples. Then this function can be used in both bulk and single delete.  By doing this, we're making sure the specific rows that are expected to deleted are passed instead of blindly calling delete on a Reference.

The function also have to make sure all the key column values are not-null.

**Comment by jrchudy** [comment]
It was also suggested that bulk delete could be triggered from recordedit app. The user might not be able to narrow the results of recordset down to only the set they want to delete.
