### ISSUE TITLE
caption not showing in iFrame using tag:misd.isi.edu,2015:url annotation

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#215]
It seems like the caption parameter is currently not being used in this annotation. 
In many cases we need the caption to  identify the data that's being shown in the iframe.

**Comment by hongsudt** [comment]
@robes is it possible for us to do this for GPCR by the end of Friday? This one has lower priority than the character sequence with a gap between 10 characters.

**Comment by robes** [comment]
what exactly does this mean? its not really clear where to show a caption with an iframe content.

**Comment by hongsudt** [comment]
@shinyichen is this a duplicate of #223? If so, then we can close this.

**Comment by shinyichen** [comment]
Yes looks like duplicate. Already pushed the code, waiting to @bugacov to review.

**Comment by robes** [comment]
since #223 has all the activity on it, we can close this duplicate
