### ISSUE TITLE
Suggest links to vocabularies when editing free text fields

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#216]
It is enevitable that users will start putting terms into free text fields.  We should do everything possible to prevent this, but rather put in links to controlled vocabulary instead.  Ideally, when a users is typing in to a text field, a spelling corrector type interface should make suggestions from the available vocabularies.  If a vocabulary term is used, we should attempt to provide sensible links from that term to filtered searches on appropriate objects.

**Comment by karlcz** [comment]
I would suggest that this only be adopted for markdown or similar rich text languages, i.e. *not* for actual raw text fields:

1. Part of the editing/data-entry/curation UX is to provide this guidance to compose better rich text values under human supervision
2. Later presentation can unambiguously handle the mix of text and URLs using a rich text renderer
3. Other mining/stripping could populate structured associations and indices between entities based on the embedded rich text content.

We need to avoid having adhoc, non-idempotent rounds of processing that will get out of sync and likely produce divergent results as datasets evolve.

**Comment by carlkesselman** [comment]
I'm ok with this.

**Comment by hongsudt** [comment]
I think this is no longer relevant. If it is still an issue, we can open one later.
