### ISSUE TITLE
Upload a file again but with new filename

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2164]
If a file is being uploaded to hatrac with a new filename, but the file already exists, the hatrac content disposition is not being updated to reflect the new filename. The filename is being set properly in ermrest in this case. 

Currently if chaise detects the file exists already, the job is marked complete and the next file is uploaded.

The content disposition in hatrac should be consistent with the filename information that we store in ermrest.

**Comment by RFSH** [comment]
#1949 is not directly related but is talking about how we handle filenames.

**Comment by jrchudy** [comment]
Changes were merged in ermrestJS as part of [PR #1009](https://github.com/informatics-isi-edu/ermrestjs/pull/1009).
