### ISSUE TITLE
catalog not found error when using a bookmark link while not being authenticated

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#218]
If I got to a page and use the permalink menu to copy the link location. 

e.g., https://staging.gpcrconsortium.org/chaise/record/#1/gpcr_browser:construct_gui/title=IMPT-100

Then open an incognito window and paste the link I get the following browser error 
Not Found
We're sorry, the catalogue id 1 does not exist. Please try again!

In the server logs I see 
==> /var/log/httpd/ssl_access_log <==
128.9.136.65 - - [01/Mar/2016:19:02:39 -0800] "GET /ermrest/catalog/1/schema HTTP/1.1" 401 70

If I then use the same link while authenticated then then it works ok

**Comment by shinyichen** [comment]
Is this already fixed? I got directed to the login page. @bugacov @hongsudt

**Comment by bugacov** [comment]
i think this has been fixed long ago.
