### ISSUE TITLE
Recordset > Faceting > range inputs > input switch

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2185]
Tasks:
- [x] 1. In the facet-range-picker component, create the skeleton for the from-to form:
  - don't worry about the different types (just do simple text) and focus on the layout of the form.
- [x] 2. properly display input for int (and variants of int)
- [x] 3. float (and variants of float)
- [x] 4. date
- [x] 5. timestamp (or timestamptz)
- [x] 6. implement the clear input functionality
- [x] 7. once the resizable filter code gets merged make sure that the from and to fields adjust according to width change as they on master.

Note:
- Submit button should just print out the inputs. We don't need to implement the submit button for now.
- For each column type,
  - Each individual input should have proper validation.
  - Validation for the from-to should be done (making sure from is bigger than to).
  - validation messages should be displayed at the bottom of the form.

Github branch : https://github.com/informatics-isi-edu/chaise/tree/input-switch

**Comment by anmol-singh-usc** [comment]
Doubts:
1. Should we use date picker for new date UI ?
2. Are there any limits for the min and max date ranges that we accept ?
3. What should be the input format for the timestamp - datetime or datetime-local ?


Relevant Info/Links:
1.

**Comment by anmol-singh-usc** [comment]
All the issues/considerations we looked at before adopting the 'datetime-local' input:

1. [datetime-local](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) - A string representing a date and time (in the local time zone)
2. [Support](https://caniuse.com/?search=datetime-local) for 'datetime-local' input type.
3. [how does the format work? is it always day-month-year? or can it be changed?](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#value)

**Comment by anmol-singh-usc** [comment]
Plan to use date and time inputs separately instead of datetime-local.

[Support](https://caniuse.com/?search=date):
Edge - Version 13 onwards (released Nov 2015)
Firefox - Version 57 onwards (released Nov 2017)
Chrome - Version 20 onwards (released May 2012)
Safari - Version 14.1 onwards (released April 2021)
