### ISSUE TITLE
tooltips to explain some of the attribute names

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#219]
Some attribute names in the data sets are not very clear. There should be a way to provide the definition/description of some attributes (where `attribute` is as defined in ERMrest, i.e. a column of a table). 

1. Generally, we should use the existing `comment` property of the column in the ERMrest schema to store the human-readable definition. The UI should find the comment field and display it appropriately as a tooltip or similar user help message when it is available (non-NULL).
  - This actually applies to many elements of the ERMrest schema besides columns. Should we generalize this whole issue?
  - Should we define the comment content to include plain text or markdown, so that advanced users could include basic formatting, links, etc?  Any plain text is also valid markdown.
2. This feature is requested by GPCR, but it should be useful for all projects.  The project-specific work would be to populate the comment field on the ERMrest catalog.

**Comment by hongsudt** [comment]
@robes this task seems to be well contained as well, if you want to assign this to students?

**Comment by robes** [comment]
right, this could be another good student task.

**Comment by hongsudt** [comment]
Do you have any student that could work on this? This feature will be used across all projects though, and might need close guidance from @robes.

**Comment by carlkesselman** [comment]
Anoop interviewed some and has someone he thinks is good.

Carl

Sent from my iPhone

On Mar 4, 2016, at 4:53 PM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have any student that could work on this? This feature will be used across all projects though, and might need close guidance from @robes<https://github.com/robes>.

-

**Comment by carlkesselman** [comment]
Here is Rajbharath's resume.   He was close second for the software
developer position.

**Comment by carlkesselman** [comment]
Thanks.

I would say that we look at him, and if he looks good, that we consider bringing onboard ASAP to do things like logging dashboard, tooltips (I have some more ideas about how we should to this), and other discrete tasks.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Mar 5, 2016, at 10:24 AM, Anoop Kumar <anoopk@isi.edu<mailto:anoopk@isi.edu>> wrote:

Here is Rajbharath's resume.   He was close second for the software developer position.

On Fri, Mar 4, 2016 at 5:41 PM, Carl Kesselman <carl@isi.edu<mailto:carl@isi.edu>> wrote:
Anoop interviewed some and has someone he thinks is good.

Carl

Sent from my iPhone

On Mar 4, 2016, at 4:53 PM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have any student that could work on this? This feature will be used across all projects though, and might need close guidance from @robes<https://github.com/robes>.

—
Reply to this email directly or view it on GitHub<https://github.com/informatics-isi-edu/chaise/issues/219#issuecomment-192540021>.

<Rajbharath_Rajendran.pdf>

**Comment by karlcz** [comment]
I've updated the issue summary.  Should we generalize this whole issue to having tooltips drive by the ERMrest schema comments?  Or should we keep it specific to column display for now?

**Comment by carlkesselman** [comment]
I think general is a good idea.

One think that I’ve been thinking of is that should we be considering column hames to be like a controlled vocabulary which has a description field as well as synonyms.  The same tooltip type behavior (and search behavior for that matter) you want on therms, you probably want for columns too.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Mar 7, 2016, at 2:25 PM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:


I've updated the issue summary. Should we generalize this whole issue to having tooltips drive by the ERMrest schema comments? Or should we keep it specific to column display for now?

**Comment by shinyichen** [comment]
Please clarify. Whatever is in the comment of the column definition is the tooltip?

**Comment by karlcz** [comment]
Yes, I think the comment of the column definition is the tooltip for instances of the column name in table, list, or facet views.

@robes, @hongsuda It could also serve as the default tooltip for values of that column, if there is not a better value-specific tooltip source available...?

**Comment by robes** [comment]
@shinyichen right
@karlcz i suppose we could consider that as long as it doesn't inadvertently introduce more confusion

**Comment by robes** [comment]
Can this get reviewed, I'm sure this was done a long time ago.

**Comment by hongsudt** [comment]
Right.. This is done in record app. I am closing the issue.
