### ISSUE TITLE
Column selector dropdown on search page is not consistant with the selector being used in metadata edit

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#220]
We should pick one selector widget and use throughout chaise.  Having different widgets in different places causes unnecessary inconsistency.  I personally prefer the one that is being used in RBK as it provides type ahead for fast selection

**Comment by robes** [comment]
Comment from Jessie:

>I’ve been using Angular UI’s ui-select tool with the Select2 theme.
>
>GitHub: https://github.com/angular-ui/ui-select
>Demo: http://plnkr.co/edit/a3KlK8dKH3wwiiksDSn2?p=preview
>
>The js and css files are already in the chaise/scripts/vendor and chaise/styles/vendor folders respectively.
>
>Mei, I’m not sure that your current project is an Angular app. If you’re not using Angular, you can use the jQuery version of Select2 here: https://select2.github.io/.

**Comment by svoinea** [comment]
Fixed for the search page in the commit c0692acd9e95a84dc06a191d72fd0061e83288c8.

**Comment by meihuisu** [comment]
switched to select2  jQuery version
