### ISSUE TITLE
Conflict Error on recordset row delete should NOT redirect home on click

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2200]
When trying to delete a row in recordset app that has a conflict error because other entities are still attached/related to it, the "ok" button in the error modal redirects to the home page. In this case, the modal is dismissible which is okay but we are "suggesting" to the user that they should navigate to the homepage when they might want to keep working with the current page (since the error is not because of a broken app).

The ok button should be changed to refresh/reload the current page. Update the text as well to be consistent with our other modal errors that suggest to "refresh/reload" on ok click.

NOTE: Check to see if this decision is affected by any chaise config properties.

**Comment by RFSH** [comment]
This behavior has been fixed in the React implementation.
