### ISSUE TITLE
Recordedit Add bulk delete

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2228]
An easier solution to design to support bulk delete in the current version of chaise is to add it as a button at the top of `recordedit` app. This way the user can filter recordset to the subset they want to delete, click `bulk edit`, and then further clean up the set before clicking `delete`. 

As mentioned in the other issue, the delete action should create a uri from the list of tuples based on the shortest keys to make sure only the set to be deleted is deleted. This requires a new function in ermrestJS similar to `deleteBatchAssociationTuples` that takes in a set of tuples and creates the uri. This function should also use the new `any=()` syntax while generating the uri. `deleteBatchAssociationTuples` should also be updated to use this new syntax.

Some notes from previous discussions:
 - button with text `delete`
   - tooltip: "Continue to delete the displayed set of rows"
 - validation for bulk delete needs to have proper unique, non-null primary keys used.
   - if it's a composite key, all parts have to be non-null
   - using the shortest key should solve this since almost all servers use RID but there are cases where that's not true
   - if null, show a terminal error modal that allows cancel/dismiss to clean up the set further
 - verify rows to be deleted in confirm delete dialog after the above validation
 - After delete, show a modal notification with how many were successfully deleted and not deleted. 
   - if the set of rows to be deleted is so large that multiple requests are made, the summary modal helps communicate that
   -  everything successful
     - ok - navigate to recordset with original facet filters, paging, limit, and sort
   - everything/partial failure
     - ok - navigate to recordset with original facet filters, paging, limit, and sort
     - close - (close modal and work with recordedit)
       - do we want to allow cancel and then clean up the forms automatically? 
       - let user try to clan up the forms and redelete?
       - in theory they could resubmit delete with the same exact set and the ones already deleted will be ignored since they don't exist
       - Look at the wording we used for the unlink for the cancel case

**Comment by RFSH** [comment]
While implementing this feature, we decided to make some changes to the described behavior above. Both batch unlink and delete are going to behave similarly:

  - After clicking on the unlink/delete button, the confirmation modal will mention the number of records that will be deleted:
    ```
    # unlink:
    Are you sure you want to unlink <number> records?

    # delete:
    Are you sure you want to delete all <number> of the displayed records?
    `` `
  - After the user confirms the action. Chaise will send all the tuples without any extra check to ermrestjs. In case of delete, ermrestjs will first filter the records and only attempts deleting of the records that user has proper permission to. The ignored records will be reported in the summary modal.
  - Depending on success/failure and the number of records, we will show different messages to the users:
      - One record, successful: 
        ```
        # unlink:
        The chosen record successfully unlinked.   
  
        # delete:
        The displayed record successfully deleted.
        ```
      - One record, failure: 
        ```
        # unlink:
        The chosen record could not be unlinked.   
  
        # delete:
        The displayed record could not be deleted.
        ```
      - Multiple record, all successful: 
        ```
        # unlink:
        All of the <number> chosen records successfully unlinked.   
  
        # delete:
        All of the <number> displayed records successfully deleted.
        ```
      - Multiple record record, all failure 
        ```
        # unlink:
        None of the chosen record could be unlinked.   
  
        # delete:
        None of the displayed record could be deleted.
        ```
      - Multiple record record, mix 
        ```
        <number> record(s) successfully {unlinked|deleted}. <number> record(s) could not be {unlinked|deleted}.   
        ```
 - In failure cases, the "show details" will provide more information to the users.
  - If all the records successfully deleted, the "ok" button will redirect users to recordset page. Otherwise, it will dismiss the modal and remove the deleted records from the form.
