### ISSUE TITLE
bug with homepage search on dev.facebase.org

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#2236]
User reported the homepage search did not work for her. After adding a search term and clicking Search, the results on the new tab didn't include the search term and just showed all datasets.

The Hub experimented with different browsers and got different behaviors without a specific pattern. Chrome and Firefox sometimes worked for different users and sometimes didn't. Clearing cache didn't seem to be a factor. 

However, Safari did consistently show the bug. Then today, I tried the homepage search on Safari and it actually opened up two tabs. one that showed the expected search results, and one that showed all datasets.

Expected behavior:

- Go to dev.facebase.org
- Enter "mouse mandible" in the homepage search.
- New tab opens with 15 results for "mouse mandible"

Buggy behavior:
- Go to dev.facebase.org
- Enter "mouse mandible" in the homepage search.
- Either one new tab opens with no search terms and showing all datasets OR
- two tabs open (in Safari) - one with 15 results for "mouse mandible" and one with no search terms and showing all datasets.

**Comment by RFSH** [comment]
Two different submit handlers are registered on the page, causing this bug. One is in [the `home-search.js`](https://dev.facebase.org/js/home-search.js) and the other in [the `script` tag at the bottom of the page](https://github.com/informatics-isi-edu/facebase-www/blob/master/www/_includes/footer_home.html#L77,L91). The code in the `script` tag looks like a leftover from the previous implementation and should be removed.
