### ISSUE TITLE
Allow explore button on record page to open in a new tab

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/chaise#2242]
It would be helpful if the `Explore` button on the record page opened in a new tab (similar to the `Add records` button). In the PDB project, it would allow for comparing the information on record page with that in the new tab and would also help to not lose track of the original record page.

**Comment by jrchudy** [comment]
This is currently possible using the "right click context menu" and clicking "open in a new tab/window". Leaving this issue open to explore a solution that can be applied by a data modeler that forces this behavior.
