### ISSUE TITLE
When done "unlinking a record" the modal requires an extra "Cancel" to dismiss

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#2257]
That modal should go away with the OK/Submit button click I think? I suppose you might go through multiple rounds of unlinking, but that seems more of a corner case. It feels odd to have to "Cancel" right after you just finished Submitting.

**Comment by jrchudy** [comment]
> I suppose you might go through multiple rounds of unlinking

When we originally implemented this feature, that was one reason to leave the modal open. A user could filter the set, make a handful of selections, and submit to unlink without being done with the task. The user might clear the filters and start with a new filter criteria to remove more. But as you said, this could be considered a corner case.

Another reason to keep the modal open after submitting a selection of rows was for the partial success/failure case. When rows would "fail to unlink", we thought leaving the modal open with those failed rows still selected would be better. To keep the partial success/failure case and complete success behavior consistent, we decided the modal should always remain open.

More information about the requirements from the original issue #1535

**Comment by robes** [comment]
Just thinking “cancel” might not be the clearest way to dismiss the form when you actually did stuff. Maybe “close” ? Not a real high priority but it does strike me as slightly confusing.
