### ISSUE TITLE
Unable to "clear" fields in bulk edit

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#2258]
When you bulk edit records, if you clear values, as your only change, and then save you will get:

> Warning No data was changed in the update request. Please check the form content and resubmit the data.
  Save

**Comment by jrchudy** [comment]
@robes Could you provide more information on how this was encountered? 

I have a schema I'm using for testing that includes 4 inputs (int, float, date, and timestamp) that I wasn't able to replicate this behavior. Maybe this error is tied to a specific input type?

This error is coming from `ermrestJS`, so either chaise isn't properly changing a value before passing it to `reference.update` or `ermrestJS` is interpreting the data incorrectly.

**Comment by robes** [comment]
Sure. This happened on the “isa:biosample” table in the facebase database. The original records involved in the bulk edit had their “genotype” columns assigned to a value. The genotype column is used in a foreign key reference. I used the bulk edit feature for the column to blank out the values across the entire set. Then hit save/submit.

**Comment by jrchudy** [comment]
This has been fixed on master (`recordedit` is angularJS, `record` and `recordset` are reactJS) and fixed on the branch `angularjs` since this bug prevents bulk clearing of data.

@robes reassigning this to you under review to verify it's working as you expect now.

**Comment by robes** [comment]
Worked for me!
