### ISSUE TITLE
Navigate to recordset after bulk create/edit

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2259]
The current implementation in angularJS for multi create/edit navigates to a less functional recordset view we call the "result view" which is part of the `recordedit` app. This acted as a confirmation of what records were successfully and unsuccessfully created/updated. This "result view" should be replaced with a confirmation dialog that shows over the `recordedit` forms communicating what was successful and what failed. There should be a way to navigate to a `recordset` page that shows only the set of created/updated records.

This is related to issue #2238.

<details>
<summary>Click here for the original message (the content are not accurate anymore).</summary>

The modal should show:
 - modal text should be different depending on whether all records are successful or we have a mix of both. All failures case will show the alert at top of `recordedit` since no data was changed in `ERMrest`
   - all records successful
      ```
      # create:
      All <number> records successfully created.   

      # edit: 
      All of the <number> displayed records successfully updated.
      ```
   - some successful, some failure
      ```
      <number> record(s) successfully {created|updated}. <number> record(s) could not be {created|updated}.   
      ```
     - In partial failure cases, the "show details" will provide more information to the users.
   - all records failed (**I don't think this will happen. The error alert will take priority since no data was updated in `ERMrest`**)

Navigating out of the modal:
 - in the cases of all success and partial success/failure, "ok" button will redirect users to the recordset page that shows the list of successfully created/updated records
   - The url to navigate to should enumerate the set of shortest keys so the user sees exactly the set that was created/updated
     - if this created url is too long, notify the user in the modal that a shorter url will be used that shows a subset or the created/edited content
   - Recordset will have the shortest key facet with all row keys selected
     - if the shortest key is a composite key, a custom facet will be created instead
     - all options will be selected in the facet so the length gets really long, **should we consider truncating the total number of options shown in a facet?**
       - user can still see the whole set by clicking `show more`
       - chiclet already truncates shown content with the full list included in the tooltip
 - in the case of all failure, instead of showing the modal, the error alert will show at the top of the page like any other failed create/update request with information from `ERMrest` and `ermrestJS` about the error

Improvements to limit url length issues:
 - in edit mode, if the user navigates to `recordedit` with the `limit` query parameter with some very large number that we know we can't handle, check what the url length would be if each shortest key is enumerated. Go through the set and remove rows to be edited until the length limit can handle it and notify the user of the size of the set that they are editing
    - Notify the user with an alert with Warning type
    - message: "You tried to edit a set of <number> records large enough that can't all be edited at once. Showing <number_can_edit> records that can be edited."

To consider in create mode:
 - general improvement: **should we figure out a safer upper bound than the current `201`**?
 - more exact improvement: **should we come up with heuristics about the length of each shortest key and limit the total number of forms allowed to be created?**

</details>

**Comment by hongsudt** [comment]
### all records are successfully created/editted
1. If the results can be captured within recordset page
- a popup summarizing the status
```
# create:
All <number> records successfully created.   

# edit: 
All of the <number> displayed records successfully updated.

Click OK to navigate to the created/edited results.

```
- Show the results through recordset or ResultSet. show recordset page with RIDs of those created/edited (make sure the page size is adjusted to fit all results in one page) 

- Optimization: 
  - limit the maximum allowed created/edited numbers, so that the recordset page can be shown. Do we have a max explicitly spelled out on the page now? 
  - Is there a way to guess the RID length?

2. If the results cannot be captured in recordset page
- User our current flow e.g. display the summary and result on the modal popup

### Partial success (due to chaise breaking it into multiple transactions)
- If the request need to be broken up in multiple calls, the result is unlikely going to fit in on URL. 
- Use resultset approach

### All failed
- Use current flow.. e.g. stay on recordedit page?

**Comment by RFSH** [comment]
All the changes described in the previous comment has been implemented in the new React version. The only thing that is left is a special context for the resultset view. I created an issue for it in #2296.
