### ISSUE TITLE
User Interface style guide: draft outline/elements

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#226]
We need to define a style guide that defines what are the acceptable ui controls, styles, icons, fonts, etc. across the entire UI. It should define the styles such that any application or component (no matter who developed them) will have the same look and feel. We should have a list of the ui controls (e.g., the drop downs, text boxes, etc that we use) and then use these consistently across all apps.

**Comment by hongsudt** [comment]
@crisaless What do you think about working on this in this milestone? 

Another way to start is to identify the inconsistency in the GUI elements (e.g. different drop-down list), pick the better design, and document that in the guide?

**Comment by crisaless** [comment]
yeah, let's go for this milestone. good idea, I've also been looking at other examples of this kind of guide. Should this be a markdown file under the division repo or in the division repo wiki?

**Comment by robes** [comment]
i would prefer a markdown file. it could go in division or in chaise itself. i would lean toward putting it in chaise.

**Comment by crisaless** [comment]
is this style guide only for chaise? or is it applicable to other user interfaces our division would make?

**Comment by carlkesselman** [comment]
I think we should have a consistent look and feel across all of our UX.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Mar 7, 2016, at 9:07 AM, Cris Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


is this style guide only for chaise? or is it applicable to other user interfaces our division would make?

**Comment by robes** [comment]
Its for all UIs.

**Comment by crisaless** [comment]
OK, then seems like this guide should be at the division level instead of just within chaise.

**Comment by robes** [comment]
But then its private and our students can’t read it or other outside contributors. I just think keep it in chaise. Let every other UI follow the “chaise UI guidelines”. My $0.02…

**Comment by crisaless** [comment]
Cool. Editing this so it's a 1 week chunk - then will create other issues for further development stages.

**Comment by crisaless** [comment]
Initial outline is up at:

chaise: doc/style-guide.md

Note that I've taken some cues from Google's material design style guide with adaptations for our use - it includes some components we may not be using yet but that may be useful in the future.

I can already see that as I delve deeper, this guide may inspire some changes in what we're doing - which we can either choose to retro-fit or just make changes moving forward. In any case, anything I put in here can be discussed.

I'm creating more 'chunked' tasks for future weeks, but the scope of this one is finished. I'll assign to Rob to review.

**Comment by crisaless** [comment]
new article by NNG Group specifically about writing interface style guides - will study this:
https://www.nngroup.com/articles/front-end-style-guides/

**Comment by robes** [comment]
maybe we should approach the style guide a little more tactical. for instance, we have decided to use bootstrap so that encodes much of these style decision. what we need to know now is, which bootstrap container should we use -- i.e., use container vs container-fluid. should tables use the default (bootstrap) table style or should they use table-striped or table-bordered etc? and for fonts etc, i think that bootstrap mostly determines the basic font, we might just need some decisions about special cases where we deviate from the default font and which one to use.

secondly, i would say we should define our style guide in terms of the css classes to use and for those that need to extend bootstrap, our style guide should basically be a reference to the classes in our own custom chaise.css (or whatever).

and thirdly, then we need to pick a set of non-bootstrap 3rd party ui components, such as which dropdown control to use (e.g., angular-ui-selector or whatever its called).
