### ISSUE TITLE
Recordset result count shows stale value during query reloads

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#2291]
When the user adjust filters and query results start reloading, the result set count at the top of the main pane continues to show the stale answer from the last result set. For slow-running queries with lots of psuedo column and facet updates, this is provides a confusing mix of old and new info.

The same event that starts the refresh cycle should "invalidate' the old count and make the UI go back to the state where it does not know the count, and only display it again once the revised count result comes back.

We need this in the CFDE branch but it should also be consistent in the newer react code.

**Comment by RFSH** [comment]
I applied the suggested change to both [`angularjs`](https://github.com/informatics-isi-edu/chaise/commit/1f4c63273e51f4a05932e6119b5ce84a372b8307) and [`master`](https://github.com/informatics-isi-edu/chaise/commit/072099ad17156a544e2eab3969177e53a96a7e9e) branches. Chaise will now hide the total count as soon as we have to update the page like you suggested.
