### ISSUE TITLE
Favorites request is not checking the url length

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#2295]
When a sufficiently large set of choices is "submitted" from the facet multi-picker, the recordset app can fail with:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
```

which we think is coming from some middleware/service container layer before it reaches the actual /ermrest/ service. In the deployment where we encountered this, we use AWS ELB application routing, which has not been the case with many prior deployments.

This is a pretty pathological test case, where upwards of 500 choices have been selected across several facets. But, since chaise has a mechanism meant to stop the user without breaking the app, we either need to hard-code a lower limit that is safe for this deployment method or make this limit configurable so that deployments can set appropriate limits.

**Comment by RFSH** [comment]
Just to add more context, this is how we came up with the existing 4000 character limit for url path: https://github.com/informatics-isi-edu/chaise/issues/1669

**Comment by karlcz** [comment]
I found this info about the AWS load balancer:

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-limits.html

it seems to suggest that request line (e.g. GET /path/...  HTTP/1.1)
is limited to 16KB, so I'm not sure why we're seeing a problem if
chaise is limiting it to only 4KB.

are you checking the limit for every request in recordset? i.e.
main request, facet control updates, count calls?

**Comment by RFSH** [comment]
The issue is the favorites request that we're sending for the facets. We're not doing any length checking in there. Also, the `any` syntax could be used to reduce the URL length.

Also, since in the AngularJS implementation, we're showing all the selected choices to the users, the favorites request is getting lengthier than any other requests on the page as we're iterating over each row to generate the URL.

**Comment by RFSH** [comment]
I pushed changes for the URL length issue to both [ermrestjs (`master`)](https://github.com/informatics-isi-edu/ermrestjs/pull/975) and [chaise (`angularjs`)](https://github.com/informatics-isi-edu/chaise/pull/2302).

The PR in chaise will ensure the favorites requests are honoring URL length and using any syntax. The ermrestjs one will ensure the same for the requests that we’re sending on load to validate the facets in the url. While the validation request wasn’t throwing any 404 or 401 errors to the users, it would just show the “Unsupported Facet Filters” errors when the request was large even if all the options were valid.
