### ISSUE TITLE
Boolean with the constraint "not null" is not working

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#2303]
We have the following definition:
```                                                  Table "PDB.Curation_Log"
     Column      |        Type        | Collation | Nullable |                            Default                            
-----------------+--------------------+-----------+----------+---------------------------------------------------------------
 Submitter_Allow | boolean            |           | not null | false
```
Trying to save a record with the `false` value, is generating the following error:
<img width="437" alt="Submitter_Allow" src="https://user-images.githubusercontent.com/1609577/233859829-568867f9-6817-4daa-966a-f781408d1601.png">
It happens on the `pdb-dev`.
The URL for the `recorset` is: https://dev.pdb-dev.org/chaise/recordset/#99/PDB:Curation_Log@sort(RID)
It seems that the `false` value is treated as a `NULL` value.

**Comment by RFSH** [comment]
@svoinea This is fixed now. As you mentioned, the React implementation was treating `false` value the same as `NULL`.
