### ISSUE TITLE
File upload errors not displayed

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2312]
From @robes in slack:
> We are beginning the hatrac migration of FaceBase. In doing so, we are putting hatrac in a read-only mode. Thus hatrac will respond with a 405 error on uploads. What we have noticed is that Chaise does not provide a UX for this error mode. The upload form just kind seems to disregard the upload without displaying an error message to the user.

This is indeed a bug that is not working after the migration to React. Marking this as a regression.

**Comment by jrchudy** [comment]
@robes this has been fixed in the PR I merged today. Feel free to test/close this issue when you get a chance.

**Comment by robes** [comment]
worked for me. thanks
