### ISSUE TITLE
Refactor collection of inputs (timestamp, array, range inputs)

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2331]
The current implementation of the timestamp-field and array-field (issue #1408 _in progress_ ) use a collection of inputs to allow users to fill in separate values (date and time OR multiple array elements). This collection of inputs are all added to the "global" react hook form context. For instance, with a timestamp field with column name `timestamp_col`, we have the following in react hook form's model:
```
{
  '0-timestamp_col': '<date>'+'<time>',
  '0-timestamp_col-date': '<date>',
  '0-timestamp_col-time': '<time>',
  ...
}
```

For every input timestamp input there are 3 inputs in the form model. In the case of array there is the "parent" and `N` more inputs where `N` is the number of elements in the array:
```
{
  '0-array_col': [<input0>, <input1>, ...],
  '0-array_col-0': <input0>,
  ...
  '0-array_col-N': <inputN>,
}
```

We want to change this so the react hook form model is NOT polluted with extra inputs that won't be sent to the database. A simple solution for this is to great a react hook form context for each timestamp-field and array-field. More info can be found here:
https://stackoverflow.com/questions/60276510/how-to-make-react-hook-form-work-with-multiple-forms-in-one-page

This change should also be done for range inputs.

**Comment by RFSH** [comment]
Moved to worksheet.
