### ISSUE TITLE
Need to refresh webpage in order to see latest updates in a table

### ISSUE THREAD

**Issue by monica81567** [informatics-isi-edu/chaise#2338]
In general, it happens for all tables.  A specific examples is when I was adding record to the software table. software.  Each time I did an add record, the table did not update unless I refreshed the browser.  It also happened when I changed selected software types using the pull-down menu.

![image](https://github.com/informatics-isi-edu/chaise/assets/103751282/843daab6-b1bf-4909-9be8-cd3e19a68340)

**Comment by RFSH** [comment]
After looking at this, I realized we are triggering the update, but we're not showing any indicators immediately. Also, the page was painfully slow to the point that you had to wait more than 1 minute for the whole page to update. 

I made some changes to how we're rerendering the page, which reduced the load time by about 60%. Also, we're now showing the spinner for each related table immediately. Apart from that, we're now showing an "Updating..." text at the bottom left of the page as long as there's any pending update request.

@monica81567 Can you please try again and let us know if you're still experiencing any issues?

**Comment by monica81567** [comment]
@RFSH I tested author list updates and I can see the spinner and the updates are now immediate.  Thanks so much!
