### ISSUE TITLE
Recordset page is not auto updating after new edits

### ISSUE THREAD

**Issue by brindakv** [informatics-isi-edu/chaise#2343]
Recordset page does not automatically update after records are edited using the recoredit page opened in a new tab from the recordset page. 

In the image below, `Last Communicated` column was updated in a new tab but the update is not reflected in the recordset page until the page is manually reloaded. 

![Screenshot 2023-07-25 at 5 49 18 PM](https://github.com/informatics-isi-edu/chaise/assets/15000874/4479211a-255d-4af8-8126-10ba039a2639)

https://dev.pdb-dev.org/chaise/recordset/#99/PDB:entry@sort(RCT::desc::,RID)

**Comment by RFSH** [comment]
We have not been able to reproduce this. Since the creation of this issue, we've improved the loading indicators (we're now showing them as soon as an update event is triggered instead of showing the spinner when the request is sent).

I'm going to close this issue due to inactivity.
