### ISSUE TITLE
value substitution in caption in 2015:url annotation  

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#235]
if annotation for col1 has "caption":"pattern1 {col1}"
and annotation for col2 has "caption":"pattern2 {col1}" 

then in the col2 annotation what gets substituted in {col1} is the whole "pattern1 {col1}" instead of the actual value for {col1} only.

**Comment by shinyichen** [comment]
This fix is on top of 'download' branch.
