### ISSUE TITLE
data analytics dashboard

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#237]
Create a simple dashboard page that pull data from google analystics.

We should set up a server-side authorization to display Google Analytics data to users without granting them access to your Google Analytics account. https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/

The following wiki link contains some of our brainstorming ideas: https://github.com/informatics-isi-edu/chaise/wiki/Analytics-Brainstorming. I would start with 
* Number of visits, number of unique visits
* Number of downloads
* The visit time

**Comment by hongsudt** [comment]
@RFSH Where are we on this?

**Comment by RFSH** [comment]
You can check out what I created so far in here: [http://analytics.arefsh.me/](http://analytics.arefsh.me/)
[RFSH/google-analytics](https://github.com/RFSH/google-analytics) is its respective repository.

I wrote a php function to authenticate users using a key that I got from google API. It is connected to my own google analytics account.

Sometime it doesn't load the charts properly, which currently I am trying to fix. Although doing a [hard refresh](https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers) solves the issue.
I didn't spend much on the interface, I am going to change the interface as the next step.

Please let me know if you have any questions or comments.

**Comment by hongsudt** [comment]
Will close this for now as we can utilize the default google analytic pages for data analysis.
