### ISSUE TITLE
No scrollbar in upload progress modal

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2374]
The upload progress modal doesn't show the `cancel` button when multiple files are uploaded at the same time and the content flows off the bottom of the screen. There is no way to scroll the page to get to the `cancel` button. We want to fix this so the cancel button can be clicked on. There are 2 solutions listed below.

In this image you can see the `cancel` button is not visible when the developer tools are opened to reduce the "height" of my browser viewport.
<img width="1103" alt="image" src="https://github.com/informatics-isi-edu/chaise/assets/2932600/4c98e3c0-64f3-4608-8404-b999db1fd417">

1. A simple solution is to make only the modal body scrollable by adding `overflow: auto;` to the `modal-body` element. This would be consistent with the scrollable area in recordset modal.

2. Another solution is to add a scrollbar to the whole modal so the modal will scroll up and down instead of just the modal-body.

This issue is also present in the share and cite modal popup on record app.

**Comment by RFSH** [comment]
For the profile popup we've solved this by adding [this](https://github.com/informatics-isi-edu/chaise/blob/master/src/assets/scss/_modal.scss#L207,L210). I think we should do the same for the popups that you mentioned.  The behavior is like the second solution that you mentioned.

**Comment by RFSH** [comment]
Changes in https://github.com/informatics-isi-edu/chaise/commit/7a2364deeb12bed02e1d9a07e541b86487d69c93 have fixed this.
