### ISSUE TITLE
Testing array input changes

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#2378]
To start testing the array input issue (#1408), follow the [instructions here](https://github.com/informatics-isi-edu/chaise/wiki/How-to-install-Chaise-ERMrestJS-from-you-local-machine#running-chaise-tests) for installing chaise and ermrestJS to set up the testing environment. [This document](https://github.com/informatics-isi-edu/chaise/blob/master/docs/dev-docs/e2e-test.md) that I pointed to before is the main doc for the e2e test cases.

Once you've set up the testing environment, try running `make testnavbar`. This will run the navbar test which don't rely on creating data. Once you can confirm this works as expected, continue to run both of the following specs, doing one at a time:
 - `make testrecordadd` - This command runs ALL the recordedit tests for `create` mode
 - `make testrecordedit` - This command runs ALL the recordedit tests for `edit` mode

Everything should pass except for test cases that relied on the old UI for array inputs since that was the functionality that is changed in your branch. After running each make command, `testrecordadd` and `testrecordedit, **summarize in this issue which tests are failing**. We can further discuss any new tests we want to add once we've identified the tests that need to be fixed.

**Comment by ladukaraniket** [comment]
# Cases failing in `recordadd` Suite
- **\`should show textarea input with correct value\`**  -  `test/e2e/utils/recordedit-helpers.js#L298`
- **\'should validate invalid array input.\'** - `test/e2e/utils/recordedit-helpers.js#L396`
- **\'should be able to set the correct value.\'** - `test/e2e/utils/recordedit-helpers.js#L447`
- **\'table must show correct results\'** - `test/e2e/utils/recordedit-helpers.js#L1716`
- **\'should render input type as file input\'** - `test/e2e/utils/recordedit-helpers.js#L1609`
- **\'table must show correct results.\'** - `test/e2e/utils/recordedit-helpers.js#L1716`
- **\'when all forms are selected, clicking on apply should apply change to all forms\'** - `test/e2e/specs/default-config/recordedit/multi-form-input.spec.js#L703`
- **\'when some forms are selected, clicking on apply should apply change to selected forms\'** - `test/e2e/specs/default-config/recordedit/multi-form-input.spec.js#L724`
- **\'change values in the forms without affecting the other forms\'** - `test/e2e/specs/default-config/recordedit/multi-form-input.spec.js#L765`
- **\'and redirect to a record page with the default values.\'** - `test/e2e/specs/default-config/recordedit/immutable-inputs.spec.js#L316`
- **\'when some forms are selected, clicking on clear should clear values in selected forms\'** - `test/e2e/specs/default-config/recordedit/multi-form-input.spec.js#L749`


# Cases failing in `recordedit` Suite
- to be updated soon
