### ISSUE TITLE
Use table view only in search results

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#238]
Currently Chase search page displays results in one of three layouts: list, card, and table.

I would like to explore the possibility of dropping all but the table layout in the search results. We could use feedback from everyone representing user projects:

@hongsudt 
@karlcz 
@bugacov 
@mikedarcy 
@ljpearlman
@carlkesselman (and carl)

We may also want some usability testing or polling by @crisaless 

Part of the justification is to focus our effort on making the table presentation much better and not having 3 layouts to maintain.

**Comment by crisaless** [comment]
agree we should definitely do some user testing - the issue would if they see a level of details that's useful to them, makes sense

**Comment by hongsudt** [comment]
We won't fix this in the search app. Will address this in recordset.
