### ISSUE TITLE
Include more columns as well as vocabulary tags in the search results table

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#239]
We have only a few columns displayed in the search results table. Not sure who or how those are decided. We ought to be able to include any/all of the columns for the tables being searched, we should also be able to include the vocabulary tags. We may need to review how we do this, and may want to use database views. (Maybe that's all there is to this, but we should confirm.)

Also, if we have numerous columns, the table should act sensibly. I.e., scroll left/right or something, and be able to hide/show columns.

**Comment by hongsudt** [comment]
Will roll this to recordset. Close this issue for now.
