### ISSUE TITLE
record app breaks when session expires

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#240]
On the record page, after the session expires, when I do a refresh or click on any link on that page it will return an error. It is difficult for users to know that this is due to session expiration. I saw this on staging.gpcrconsortium.org.

**Comment by hongsudt** [comment]
The search app also has the same problem.

**Comment by svoinea** [comment]
In the tests I have run on rbk-dev (where hourly updates are enabled), I can confirm that only the record page was showing a confused error message. I have fixed it in the commit 38f6e3301aee528b0454d54ec9dff3282ea60caa by issuing a /login request for the 401 Unauthorized error.

In the viewer, the bookmark does not contain the status for the selected tab (Annotations or Metadata), and therefore, refreshing the page ends always in the Annotations tab.

**Comment by hongsudt** [comment]
I still observed this problem on staging.gpcr..

**Comment by svoinea** [comment]
I have tested it yesterday with Alejandro and it works as expected, i.e. no error is reported when the session has expired and a refresh is clicked.
