### ISSUE TITLE
Allow user to access the export configuration

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2408]
Some users would like to grab the export configuration that ermrestjs/chaise generates and use it outside of chaise. Ideally, they should be able to get the config file.

## Details

After discussing this, we decided to add an extra option to the export menu called `Configurations`. This option will only be offered if there are any export templates that communicate with the export service (so, for example, if only the default `CSV` is offered, we're not going to show this submenu).

Clicking on this option would open a submenu that includes the export options that communicate with the export service. Clicking on each option will generate the appropriate config for users.

Since we only want this on some specific deployments, we will add a chaise-config property that should be used to enable this feature. To give more control over who can see this control, we will follow what we did with [`shareCiteAcls`](https://github.com/informatics-isi-edu/chaise/blob/master/docs/user-docs/chaise-config.md#shareciteacls) and introduce a new `exportConfigsSubmenuACLs`. So for example if you want all users to see and be able to use this submenu you would add

```
{
  "exportConfigsSubmenuACLs": {
    "show": ["*"].
    "enable": ["*"]
  }
}
```
If any of the `show` or `enable` are missing, we will use the `[]` default value, which means hiding/disabling for all.

**Comment by mikedarcy** [comment]
This is above and beyond what we need but thanks for the extra functionality. Sounds great to me. Thanks.
