### ISSUE TITLE
site tour fixes

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#241]
Some enhancements to the site tour:
- Add a first panel that welcomes you to the site tour for <app name>
- Create an <app name> configuration parameter - chaise deployments have different names for different projects
- Re-write some steps so it's more obvious that the tour is doing them instead of the user.

**Comment by hongsudt** [comment]
@crisaless this issue is so old. Are you still planning to do this or should we add "won't fix" and close it?
