### ISSUE TITLE
improve padding of record page tag buttons and text field sidebars

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#242]
The sidebars for text fields values (like Description) need some padding.

the tag 'buttons' on the records page need some CSS help - when the tags wrap, they are too close together vertically. But adding margin or padding at top makes all the buttons too low vertically. I think flexbox would help.

**Comment by hongsudt** [comment]
@crisaless are you stll planning on doing this or should we close this?

**Comment by crisaless** [comment]
yes - the padding issue really bugs me in particular so I'll try to knock that out today/tomorrow.

**Comment by crisaless** [comment]
Just committed a fix.

**Comment by crisaless** [comment]
I fixed the padding for the blue buttons a while back.

**Comment by hongsudt** [comment]
Please close the issue if it is done.
