### ISSUE TITLE
Make the "New" annotations button more obvious

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#245]
The "New" annotations button is a bit subtle. One simple improvement would be to make it with width of the sidebar. A more involved fix would be to move the button over to the rest of the image controls. For now, I'd consider just the simple fix and then get more user input.

**Comment by hongsudt** [comment]
@robes Since this is a quick fix, I am adding this to the current sprint..

**Comment by howdyjessie** [comment]
The New button now spans the width of the sidebar:

https://dev.rebuildingakidney.org/~jessie/chaise/viewer/#1/rbk:image/id=15
