### ISSUE TITLE
Support columns names with special characters on the recordedit app

### ISSUE THREAD

**Issue by RFSH** [informatics-isi-edu/chaise#2458]
React-hook-forms doesn't like using special characters for the input names. [This](https://react-hook-form.com/docs/useform/register#rules) is the only thing I could find in their documentation. But I don't know how much we can trust this. They mention not using names that start with a number, but that's the default behavior of the recordedit inputs, and it works properly.

At the very least, we know that `[].` characters should not be used as these will change the created output of react-hook-forms. For example, if you have an input called `a.b` and write the value `1` in it, the following is the output
```
{
  "a": {
    "b": 1
  }
}
```

While our code expects
```
{
  "a.b": 1
}
```

To solve this, we should most probably encode the column names and then decode them again before sending the data to ermrestjs. Or maybe add an API to ermrestjs that returns this encoded name and let chaise use that.

**Comment by jrchudy** [comment]
Two solutions that were discussed were:
 1. Write an encode/decode function for encoding special characters in the column name. Then use the encoded name as a `key` in the value map for react-hook-form
    - We would have to determine a list of allowed characters for this key in react-hook-form
      - their documentation says to avoid special characters so we should consider changing all of them
    - Requires encoding the column name during setup of each input for the form
    - decoding wouldn't be necessary since we get the values from the map by calling `formData[formNumber + '-' + col.name]`
      - we would just be encoding the column name again to make sure we fetch the same name from the map
 2. Use an unique identifier that is unique per column in the database
    - Each `column` has an RID value that is unique
      - access it using `column._baseCol.RID`
      - using RID instead of column name should already be encoded (includes numbers, letters, and `-` characters which are allowed in `react-hook-form`)
    - Set a value on the `columnModel` in chaise or column in ermrestJS using the `column._baseCol.RID`
      - or just use this outright even though `_baseCol` is intended to be a "private" function for ermrestJS only

**Comment by jrchudy** [comment]
We decided to change the `key` used in react hook form to use the `RID` of the column instead of the `name`. If the column is a pseudo column, it will use the `RID` of the foreign key instead

See linked PR for more details.
