### ISSUE TITLE
Automated tests for Image annotation viewer

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#246]
We need to develop a set of tests for the image annotation viewer. This should be a first cut of tests to cover the current functionality. I would suggest mocking the backend service (based on real ERMrest responses).

**Comment by hongsudt** [comment]
@robes I assume these tests are unit testing..

**Comment by jrchudy** [comment]
The basic structure of the unit tests are done in pull request #329 and assigned to @howdyjessie for review. Doing the same with this issue as it pertains to the code in that request.

I mistakenly shoved the test case changes onto my refactor branch so I am including a basic set of tests that cover pretty core functionality of the viewer app. I will expand on them in the future.

**Comment by howdyjessie** [comment]
The tests look good and have been merged into master; I'm closing this issue.
