### ISSUE TITLE
Current style of checkboxes in modal windows appear as if they are already checked.

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#2480]
We were watching a user enter a record in the ATLAS-D2K system and when she opened a modal window to make a selection, she was confused because it looked like all of the checkboxes were already checked off.

Now that we look at it, all of the checkboxes being a solid blue do appear that way to us as well.

Perhaps the style should be updated with a white background that is blue when checked.

**Comment by crisaless** [comment]
Here's a screenshot:
<img width="1512" alt="example-of-blue-checkboxes" src="https://github.com/informatics-isi-edu/chaise/assets/8965132/d34a0974-2df9-480a-b03d-9e92a0efeed2">

**Comment by jrchudy** [comment]
This was changed in [this commit](https://github.com/informatics-isi-edu/chaise/commit/245cb0024dbcc706a6326c43e77bef47ad6a0d16)
