### ISSUE TITLE
handle forbidden error gracefully

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#250]
This is currently what got shown when I attempted to access gpcr site without being authorized.
![screenshot from 2016-03-17 21-24-04](https://cloud.githubusercontent.com/assets/414732/13868518/011f2b2c-ec87-11e5-997e-738a7307209b.png)

**Comment by hongsudt** [comment]
@svoinea I still see this on the gpcr staging. @bugacov said he has the latest chaise code on that server.

**Comment by svoinea** [comment]
Updated the code such that the errors from the search page are displayed inside the page instead of a separated alert window.

Therefore, the spinner is not any more present while an error is detected.

**Comment by svoinea** [comment]
This is currently fixed on rbk-dev.

**Comment by hongsudt** [comment]
Will close this for now since I can't replicate the problem.
