### ISSUE TITLE
Long column names may get truncated or overrun the table heading cell boundaries

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#2518]
Example here. Several columns are truncates (11, 12, 13, etc) and the last "Status" column overruns the box.

<img width="1513" alt="Screenshot 2024-08-07 at 2 47 14 PM" src="https://github.com/user-attachments/assets/451b3878-e612-4ea3-8bfd-7d7d88c5e8a5">

**Comment by jrchudy** [comment]
Changes to fix this issue have been merged into master. Reassigning to @robes to test.

**Comment by robes** [comment]
Excellent! Looks great. Thanks
