### ISSUE TITLE
Need to be able to sort attribute values in a semantically meaningful way rather than lexical ordering

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#252]
The chaise/search app sorts the attribute values in a lexical order. For example, age stage would be ordered:

```
11 wks
12 wks
3 wks
4 wks
...
```

This is the wrong order. What you really want is: 3 wks, 4 wks... 11 wks, 12 wks...

Maybe there is a way to solve this in a general way by parsing numeric values and sorting based on their position in the string. However, another solution could be a sorting key in the vocabulary table. We will always need the latter because there will likely be term lists that we won't have a nice heuristic for.

Note: this is likely a general problem that will show up everywhere and not just in the chaise/search app.

**Comment by hongsudt** [comment]
@robes This problem has been solved on rbk-dev. @svoinea is your solution only applied to rbk specific column, or can it be generalize to support other use cases?

**Comment by svoinea** [comment]
The solution is applicable to any cases. You need an additional column with the ranked values, and through an annotation you specify the column to be sorted by it.

**Comment by hongsudt** [comment]
@svoinea  What's the annotation syntax for this? Can you give the rbk example?
@bugacov we can apply this to facebase.

**Comment by svoinea** [comment]
The ```annotation_uri``` is ```description``` with the key ```rank```.

Example of usage:

 table_name | schema_name |   column_name    | annotation_uri |             annotation_value              
------------+-------------+------------------+----------------+-------------------------------------------
  age_stage  | rbk         | term             | description    | {"rank": "weeks"}

In my case, the ```age_stage``` has the column ```term``` with values like ```7 weeks``` and ```10 weeks, 1 day```.
I added the ```weeks``` column with the values ```7``` and ```10.1```.
Due to the annotation, it will be sorted ```7 weeks```, ```10 weeks, 1 day```.

**Comment by hongsudt** [comment]
@bugacov Can we make use of this in facebase?  If not, please close the issue.

**Comment by robes** [comment]
i don't understand the solution. maybe @svoinea can review it with me.

**Comment by robes** [comment]
We actually want this implemented a different way. The sorting issue generally applies to vocabulary. We have an annotation describing vocabulary in the ermrest repo. We need to extend that specification with a sortby field which should reference a column. The column may or may not be a column used in the presentation of the vocabulary. That is, it may not be the code or label of a vocabulary entity. It may be a column which has the sole purpose of defining the order. The UI should check the annotation and then use that specified column to sort the values/rows of the vocabulary.

**Comment by karlcz** [comment]
I think this sortby annotation should apply more generally than to just vocabularies.  We should be able to define the natural sort for any table, and have it apply by default in search, recordset, and related-entity presentations of entity sets.

**Comment by karlcz** [comment]
Do we have consensus on this?  Should I draft the above annotation definition?  I have a use case where I'd want this table-specific sort applied to the related entity tables in the record app as well as to recordset.

**Comment by hongsudt** [comment]
Tag this as wishlist, and move it to recordset feature list on the wiki.
