### ISSUE TITLE
The search app sort also implicitly filters by the sort attribute

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#253]
For example, if you are searching on a table of images in the RBK implementation, and if you sort by `Number of Comments` it also filters out any rows that have `null` values.

This doesn't seem like the expected behavior. Should we treat `null` like the lowest value? I think that would be more intuitive.

Also by having sort also filter, it conflicts with the filters set in faceting.

**Comment by karlcz** [comment]
In ERMrest, sort is always NULLS LAST in the underlying SQL.  Are you
sure the NULLs have been filtered out and not just displaced to the
last page?

**Comment by robes** [comment]
Ah, that helps to know. So the bug is a little different then but still a bug. Steps:

1. go to the search page on www.rebuildingakidney.org
2. filter on Submitted By = Jill...
3. Sort by Number of Annotations

The display now is "Showing 1-4 of 125 results..." and you can click More to see more results.

I would expect that I would still see "...1-25 of 125 results..." but in sorted order. I don't think its very intuitive to make the other 25-N results disappear from the display. Obviously, it wasn't intuitive for me.

**Comment by svoinea** [comment]
The bug is fixed in the commit ad793a7ea17d49596677cb7dd361d12adc3ea435.

**Comment by hongsudt** [comment]
@robes This is no longer the case on rbk-dev. All null values have been converted to 0. Will close the issue.
