### ISSUE TITLE
add padding for slider attributes

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#256]
The slider value is rare in my experience, but just noticed it and the spacing is pretty squished. Should just be a matter of updating this rule in app.css (line 676) - v quick fix

.nav.filteritems li.attr-slider, .nav.filteritems li.attr-text, .nav.filteritems li.attr-date {
    padding: 15px 30px;
}

**Comment by hongsudt** [comment]
Since this hasn't been worked on for a few months. I will close this issue and mark it as won't fix.

**Comment by crisaless** [comment]
turns out it was a duplicate of #242 - which was fixed.
