### ISSUE TITLE
refactor getGoauth

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#258]
We need one source for the getGoauth function as a share util - currently it is copies-and-pasted about. But just as important we need to fix the semantics of this method and its name. It actually gets the webauthn preauth resource.

**Comment by hongsudt** [comment]
@svoinea @robes is this done with @svoinea 's revision of the authentication code?

**Comment by svoinea** [comment]
In the search app, this was already done (the `getGoauth` function does not exist - it was renamed to `login` which is doing the `/authn/preauth`).

The places where I see the `getGoauth` function are `dataEntry.app.js` and `viewer.app.js`.

The issue should be reassigned adequately.

**Comment by hongsudt** [comment]
assign to @howdyjessie

**Comment by hongsudt** [comment]
@howdyjessie mentioned that the getGoAuth in dataEntry and viewer app are separated from @svoinea getGoAuth. 

Since you implement the same functionality of his login, can you review this and close the issue?

**Comment by howdyjessie** [comment]
@hongsudt Sure thing!

**Comment by karlcz** [comment]
This relates to #298 as well.

**Comment by jrchudy** [comment]
This is only relevant to the viewer app now.
