### ISSUE TITLE
Remove RBK branding in the chaise/viewer app

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#259]
We have RBK branding leaking into the chaise/viewer. This needs to be removed.

https://github.com/informatics-isi-edu/chaise/blob/recordset/viewer/index.html.in#L4

**Comment by howdyjessie** [comment]
@robes I changed the title to just "Image Viewer"; will we need a dynamic title like "Image Viewer | [consortium name here]"?

**Comment by crisaless** [comment]
We have a config variable for the title tag for other index.html.in files (using chaise-config.js) so I can ask Serban to do the same for this file. So "Image Viewer" as a default is fine.

**Comment by robes** [comment]
Can you point Jessie to it?

**Comment by crisaless** [comment]
Serban used this in scripts/controller/ermrestInitController.js

	if (chaiseConfig['headTitle'] !== undefined) {
		document.getElementsByTagName("head")[0].getElementsByTagName("title")[0].innerHTML = chaiseConfig['headTitle'];
	}

And this in record/assets/javascripts/app.js

if (chaiseConfig['headTitle'] !== undefined) {
 		var title = document.createElement("title");
 		title.innerHTML = chaiseConfig['headTitle'];
 		document.getElementsByTagName("head")[0].appendChild(title);
 	}

**Comment by howdyjessie** [comment]
Awesome, well I've added the snippet in the Viewer and Data Entry apps.
