### ISSUE TITLE
Bad references to ermrestjs scripts

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#260]
https://github.com/informatics-isi-edu/chaise/blob/master/Makefile#L427-L447

First, the ermrestjs should be referenced from the dependencies lists not just injected in the make asset block loop.

Second, the links are wrong I'm sure. `../../../ermrestjs` is one level too deep. The deployments will always be at the same level such as:

```
/var/www/html/
               chaise/...
               ermrestjs/...
```

I'm sure this slipped in from a test environment setup but even there you should make your test environment match the deployment environment rather than alter the makefile.

**Comment by robes** [comment]
I think I fixed this

**Comment by howdyjessie** [comment]
I switched the data entry app to use `$(ERMREST_DEPS)` in its asset block. @jrchudy has done the same for the viewer app on his branch. When he pushes his refactor branch, we can review + close this issue.

**Comment by jrchudy** [comment]
This is changed in pull request #329 with the refactor code. @howdyjessie's changes for Data Entry are the same that I made for viewer. Closing this issue.
