### ISSUE TITLE
"Template-ize" index.html.in files

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#262]
In order to integrate with the FaceBase website, we use deployment-specific index.html.in files. It works well for search/index.html.in because the main code of that page is included in a template (%TEMPLATES%), which the FaceBase version uses. Then whenever that template is updated, it gets sucked into the FaceBase file.

This is not set up for records/index.html.in and I have to notice if the chaise version is changed and then manually update it - things get out of sync very easily.

So in general, index.html.in files should put the bulk of the code in a template block. I specifically need this for records/index.html.in but think it would be a good idea for others like viewer/index.html.in

**Comment by robes** [comment]
Can you tell me the block of html in the record/index.html.in that should be templatized? Should it be this entire block:

https://github.com/informatics-isi-edu/chaise/blob/master/record/index.html.in#L9-L262

**Comment by crisaless** [comment]
lines 22 through 261 should do it (from `<!-- SPINNER -->` to the last closing `<div> `tag)

**Comment by crisaless** [comment]
I've updated the facebase-www version so we'll see how it looks on dev after the next update

**Comment by hongsudt** [comment]
@crisaless can you please assign this to someone that can review the issue?

**Comment by robes** [comment]
i checked dev.facebase.org. details pages look fine.
