### ISSUE TITLE
Update chaise/viewer to use the new ermrestjs APIs

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#263]
The `chaise/viewer` is a chaise app that loads an image metadata record from ermrest, and then launches an embedded 2D image viewer (using the open seadragon library). The code is found here:

https://github.com/informatics-isi-edu/chaise/tree/master/viewer

The `chaise/viewer` was implemented with the current master version of the `ermrestjs` api. The api is currently being refactored -- see its `refactor` branch. We need to update the ermrestjs calls in the chaise/viewer to use the refactored apis. In some cases the semantics of the api have changed -- its not just a change of class or function signatures but in some cases functionality was remove or significantly revised.

This will require working off of the refactor branch of ermrestjs. The docs are still sparse but we do have a wiki page that gives a rough outline of the api here.

https://github.com/informatics-isi-edu/ermrestjs/wiki/ERMrest-Programmatic-API-Sketch

**Comment by jrchudy** [comment]
I created a pull request and assigned it to @howdyjessie for review. This is the corresponding issue.

**Comment by howdyjessie** [comment]
The PR has been reviewed and merged.
