### ISSUE TITLE
Consolidate `index.html.in` templates

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#266]
We only need one `index.html.in` template. We can inject assets and templates to produce each page based on `make` targets. We should factor out the title into a configurable setting and inject it into the page with angular, but that can be a separate issue.

**Comment by robes** [comment]
@hongsudt This is another one of those makefile & related issues.

**Comment by hongsudt** [comment]
I am moving this back to backlog..

**Comment by jrchudy** [comment]
Closing and moving this to wishlist.
