### ISSUE TITLE
Apply todos from code review to Viewer app

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#267]
Todos from the code review on March 29:
- [ ] Flatten file structure (no need to use folders if filenames are already clear)
- [ ] Use of $log vs console.log
- [ ] Put space between icons and text in buttons in a stylesheet
- [ ] Split up index.html into smaller templates via Makefile
- [ ] Split up viewer.app.js
- [ ] Remove hardcoded rbk link in viewer.spec.js
- [ ] Mock things properly in viewer.spec.js... possibly look at Shuai's code
- [ ] Where noted via TODO comment reminders, check for the assertion first instead of stuffing everything inside the `if` block
- [ ] In `viewer.app.js`, refactor the functions where you fetch entities from vocab tables
- [ ] Internationalize the `toTitleCase` filter
- [ ] Abstract away the code to authenticate the user via Globus

**Comment by hongsudt** [comment]
This is no longer relevant as the viewer app is now changing.
