### ISSUE TITLE
change the wording for the sorted dropdown suggested text

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#270]
instead of "select a filter", change it to "select an attribute".
![screenshot from 2016-04-04 16-50-32](https://cloud.githubusercontent.com/assets/414732/14267435/44044c54-fa85-11e5-8fc2-4fdc8c53df97.png)

**Comment by svoinea** [comment]
The issue is already fixed and might be viewed on rbk-dev.

**Comment by hongsudt** [comment]
this change is now on facebase-dev.
