### ISSUE TITLE
Add paging feature to the recordset app

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#271]

**Comment by hongsudt** [comment]
Where can we review this feature?  and please assign the reviewer that can review and close this issue.

**Comment by robes** [comment]
This seems to be working well, but did we want to update the permalink and the window location (replacing not adding to the window history) before considering this done? That was my impression from this morning's meeting.

**Comment by robes** [comment]
Oh, also I can imaging we will want some tweaks to the UX, but I suggest that once the above is resolved  we mark it done and then have a broader review of UX as a group. That's kind of a general comment that applies to other chaise components not just this one.

**Comment by robes** [comment]
the paging is working. just for anyone else reviewing this issue, we decided not to put the paging key into the bookmark because we don't have a (good) way of getting the count of the lower bound when dropped back into a recordset from such a bookmark.
