### ISSUE TITLE
Chaise search redirects to a page that shows a Login Object

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#276]
When navigating to `https://dev.rebuildingakidney.org/chaise/search`, if the user is logged in the user is redirected to a page that shows a JSON object of the user's session.

`{"attributes": [], "seconds_remaining": 1541, "since": "2016-04-06 17:07:50.130619-07:00", "expires": "2016-04-06 17:37:50.130619-07:00", "client": {"display_name": "jchudy", "id": "jchudy", "full_name": "Joshua Chudy", "email": "jchudy@isi.edu"}}`

The redirect URL is the following:
`https://dev.rebuildingakidney.org/ermrest/authn/session?state=b7fcfb385ef8c90abd1c592cc97c81aa7a440045c049e3c1f92209bb6d8360f2&code=ezqyWjcxyOM7iItmdYXGP9KCPWAZHw`

I believe this started happening after I clicked login on one of the chaise search pages and logged in with my globus account. I also cannot logout now because of this redirect. @karlcz suggested that this might actually be a webauthn bug and that @ljpearlman might know more about it.

**Comment by ljpearlman** [comment]
The commit I pushed tonight may help with this. Please let me know if you see this behavior again.

**Comment by hongsudt** [comment]
@jrchudy please check whether the problem persists..

**Comment by jrchudy** [comment]
This issue is no longer happening. Upon logging in to the application with my globus account it stays on the search page. I created another globus account for testing today and only had the `kidney-user` group associated with it, and did not see the issue either.
