### ISSUE TITLE
Error: link is null

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#277]
The record page is throwing an error "link is null".

Error can be reproduced here:
https://dev.facebase.org/data/record/#1/legacy:dataset/id=2765

It is line 601 of the app.js (that was deployed there).

```
    // if table has columns with url pattern, add to data as col_link
    this.patternInterpretationForTable = function(schemaName, tableName, references) {
        var urlInterp = schemaService.getColumnInterpretations(schemaName, tableName);
        var columns = Object.keys(references[0]);

        var originals = []; // keep original col values if has caption (so original value is used in other column caption)
        for (var col in urlInterp) {
            var uriPattern = urlInterp[col].uriPattern;
            var caption = urlInterp[col].captionPattern;

            if (uriPattern === "auto_link") { // link url is same as column value
                for (var row = 0; row < references.length; row++) {
                    references[row][col + '_link'] = references[row][col];
                }
            } else {

                for (var row = 0; row < references.length; row++) {

                    // replace each col used in the pattern
                    var link = uriPattern;
                    for (var c = 0; c < columns.length; c++) {
                        var col2 = columns[c];
                        // replace {col} with col value
                        var search = "{" + col2 + "}";
                        link = link.replace(new RegExp(search, 'g'), references[row][col2]);
                    }
                    references[row][col + '_link'] = link;
                }
            }
```

The offending line is `link = link.replace(...` it appears that `uriPattern` must be null from what I gather. There are a couple things that could be happening:

1- the use of the annotation might have been wrong and perhaps some project data needs fixing; but
2- never the less, the page should be hardened against the error.

**Comment by shinyichen** [comment]
This is because my code assumes the payload for `tag:misd.isi.edu,2015:url` is an array in order to support multiple presentations for a table (embed and download). However the documentation does say the payload could be null, empty object, object or array.
https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2015-url

**Comment by shinyichen** [comment]
@bugacov also you need to update the schema where 'pattern' is used in tag:misd.isi.edu,2015:url payload. It needs to be changed to 'url'.
