### ISSUE TITLE
A common error handling mechaism across Chaise apps

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#279]
Common errors: 
* invalid users (e.g. failed authentication). 
* session expires. In this case, direct the user to the login page. 
* network error 
* status 0 and no response text (#275). In this case, attempt a few retry and report an error if the failure is persistent. 

From@robes
We should look at how to address this at a couple levels or more.
* common error handling at the api level (ermrestjs)
* common error handling at the app level (common chaise functions)
* common error presentation, logging, etc. at the app level

**Comment by robes** [comment]
We should look at how to address this at a couple levels or more.

1. common error handling at the api level (ermrestjs)
2. common error handling at the app level (common chaise functions)
3. common error presentation, logging, etc. at the app level

**Comment by shinyichen** [comment]
I think this needs to be moved to ermrestjs, for my part.

**Comment by robes** [comment]
Added a wiki page with some thoughts on common error handling.
https://github.com/informatics-isi-edu/chaise/wiki/Towards-common-error-handling
