### ISSUE TITLE
user can't download data even if logged in

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#282]
This is a bug that pops up every now and then for Facebase: https://github.com/informatics-isi-edu/facebase-project/issues/104

We haven't figured out how to reproduce it and sometimes it resolves on its own.

* User is logged in
* User tries to download data file
* User gets Authentication error saying they need to be logged in to download data.

**Comment by svoinea** [comment]
Based on my tests, the error occurs when the hostname from the URL is just **facebase.org**.

It works as expected when the hostname is specified as www.facebase.org.

**Comment by crisaless** [comment]
This is being fixed in https://github.com/informatics-isi-edu/facebase-project/issues/105 via new .htaccess rules

**Comment by karlcz** [comment]
I think this issue was fixed and tested on facebase production now, so this issue can be closed?

**Comment by crisaless** [comment]
this bug is fixed. however, I just noticed a new bug. when you are not logged in and try to download, instead of getting the "Authentication Required" page, you get a generic Internal Server error:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

I'll close this issue but open a new one for this bug

**Comment by karlcz** [comment]
On which server are you seeing this internal server error?

**Comment by crisaless** [comment]
production
