### ISSUE TITLE
Allow search based on annotation type

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#288]
For example, when annotation type (e.g. "rectangle", "arrow","section of interest") is entered, only annotations associated with that type are displayed in the list

**Comment by hongsudt** [comment]
Issue moved to [informatics-isi-edu/rbk-project #139](https://github.com/informatics-isi-edu/rbk-project/issues/139) via [**ZenHub.io**](https://www.zenhub.io/)
