### ISSUE TITLE
Revise annotations

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#29]
We need to review and revise all annotations used by Chaise. These should follow the key/value pattern of "unique URN" : "value which may be json document". We should not reuse generic annotation keys. The annotation key should have some semantics.

1. first we need to define what are the annotations we need to support for our current use cases
2. draft a set of annotations
3. review with our internal stakeholders (i.e., other users of chaise/ermrest)
4. revise based on feedback from 3 above
5. then update the documentation and code

**Comment by karlcz** [comment]
I've started some drafts of this in two parts:
- [common ERMrest annotations](https://github.com/informatics-isi-edu/ermrest/user-doc/annotation.md)
- [data presentation heuristics](https://github.com/informatics-isi-edu/chaise/doc/heuristics.md)

**Comment by karlcz** [comment]
I am going to close this for now, and suggest that more specific issues be opened if specific annotation mechanisms need to be defined or revised.
