### ISSUE TITLE
Demystify onhashchange function

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#290]
We are using some variation of the following callback function for the onhashchange event throughout various apps.

https://github.com/informatics-isi-edu/chaise/blob/b8e1e35a1a55e58f4cc9ca72a0c496c98f5698eb/record/assets/javascripts/app.js#L6-L23

We do not fully understand it:
- like why the `goBack` function expression
- in this particular case, why is it wrapped in a timeout
- i personally, don't understand the `history.pushState` part of it either

Todo:
- [ ] First we need to understand what its doing and why. 
- [ ] Second, we need this to be a reusable in some shared utility js file
- [ ] Third, we need to factor out all uses of this to call the utility routine.

**Comment by karlcz** [comment]
By the way is this code the reason we see double-reloads on some apps?  It seems to me we would need to manage more state if we want to catch unexpected changes to the fragment ID (such as link navigation, history stack, etc.) but not also reload every time we intentionally change the fragment ID to reflect a new bookmarkable state...

It seems like we should store the last-rendered fragment ID somewhere and compare it as a guard on this event handler, or else unregister and reregister the handler around each change where we don't mean to have a reload.

**Comment by robes** [comment]
I could be the source of that double load. And, yes, I was thinking that too, that we should keep some state.

Also, based on this morning’s conversation, we should really revisit the location and history changes we are making in the apps. If we really just ‘replace’ the history (I think that’s the name of the call) instead of ‘assign’ (add to the history stack), then a lot this tracking should be simpler I think.

**Comment by jrchudy** [comment]
This is related to issue #581.
