### ISSUE TITLE
Support timestamp data type

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#291]
Rbk is forced to use date instead of timestamp since the date widget can't handle the timestamp string format. Maybe we can write a function to convert the timestamp into date format for the widget?

**Comment by svoinea** [comment]
Fixed in commit aa3adabee6b19057f9a9e90923c854bd35e0644b.

The timestamp values returned by ermrest are converted now to a date format before passing them to the widget.

**Comment by hongsudt** [comment]
@chiragsanghvi please review.
