### ISSUE TITLE
Recordset app login and logout

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/chaise#294]
This depends on ermrestjs login/logout
https://github.com/informatics-isi-edu/ermrestjs/issues/28

**Comment by karlcz** [comment]
Hopefully this work will yield a reusable page or nav-bar component we can reuse consistently in record, viewer, and other future apps...?  Also, I think this will overlap with the site-customization issues we've been trying to sort out in other existing apps.  We need a way for a deployed server to have Chaise and static site (i.e. Jekyll) configured with integrated branding.

**Comment by robes** [comment]
@karlcz: right, in fact, I was thinking we should factor out all of the `index.html.in` templates into a single template (see #266) and then we include common parts like login/logout so that they are always consistent across apps.

**Comment by robes** [comment]
The recordset app should also have the same header (and footer?) as the rest of the chaise apps.

**Comment by shinyichen** [comment]
Angularize login/logout and put them in common folder.

**Comment by robes** [comment]
Where should I got to see this in a working deployment? And where can I see the code? Also, is this task meant to cover Karl's comment asking for a reusable navbar component?

**Comment by shinyichen** [comment]
It is on the record-recordset branch. https://github.com/informatics-isi-edu/chaise/tree/record-recordset
I see this branch has been merged to the master. And yes it includes the reusable navbar component.

**Redirect to login at page loading**
https://github.com/informatics-isi-edu/chaise/blob/record-recordset/recordset/recordset.js#L481

**navbar and login/logout**
https://github.com/informatics-isi-edu/chaise/blob/record-recordset/recordset/recordset.js#L155

**Recordset html**
https://github.com/informatics-isi-edu/chaise/blob/record-recordset/recordset/recordset.html#L3

**Navbar templage**
https://github.com/informatics-isi-edu/chaise/blob/record-recordset/common/templates/navbar.html

**Navbar directive**
https://github.com/informatics-isi-edu/chaise/blob/record-recordset/common/views.js
