### ISSUE TITLE
record app: support navigatable foreign key natively

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#297]
When a column of currently displayed table is a key to another table, the record app should automatically create a url that is linked to another record page of the referenced table. 

The table annotation of the referenced table can be used to specify the title column to be used as a reference text in the display.  

See the diagram below: 
While displaying content of a construct, under the "target" column, a reference to the target record page of id=x should be displayed.
![img_20160420_155020](https://cloud.githubusercontent.com/assets/414732/14693132/28285672-0711-11e6-8382-de794fd8efda.jpg)

**Comment by robes** [comment]
@hongsudt: What behavior should we have when that foreign key is to a vocabulary or domain table? Do we want to drill down to see a record page for a vocabulary term. So far we have this behavior from the record page (take facebase for instance) from links to vocabulary. No one seems to get it when they go to those terms. It just confuses them. In those cases, we think that it makes more sense to go back to the search (or would be recordset) app and show records filtered by that term. In this case, when we are already on a recordset page, what should happen when the user clicks a link that is to a vocabulary term? Should it take them to the record page for vocabulary, or somehow modify the current filters, or something else?

**Comment by hongsudt** [comment]
That's really a good question. In the case of vocabulary, I think it should just display the title value as static text.  @robes I am not sure what you meant by the domain table, but supporting the case that provide a url to the search page using the title as a keyword search also makes sense. 

Is there a way to annotate the foreign key column to indicate which of the three options to use?

**Comment by karlcz** [comment]
I think we'll need a second level of heuristics (for default) and
annotations (for override) to recognize and navigate vocabularies and
association tables differently from plain referenced entities.  Let's
think about this holistically...

A problem with vocabularies is that you can think of terms as hubs in
a hub-and-spoke reference pattern. Without domain knowledge, I'm not
sure we'd know which other referencing table to search by term if you
click on a term.  It might not always be "stay on same referencing
table" but instead might have some navigation from an obscure table to
a more canonical table, or a context menu to choose which path to
search, or even a polymorphic search results page...?

**Comment by carlkesselman** [comment]
I agree that we need to treat vocabulaires specially.  It is essential that users interactions with terms/vocabuaries be as streamlined as possible.

I have no idea what you are trying to say in the second paragraph.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Apr 20, 2016, at 6:53 PM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:

I think we'll need a second level of heuristics (for default) and
annotations (for override) to recognize and navigate vocabularies and
association tables differently from plain referenced entities. Let's
think about this holistically...

A problem with vocabularies is that you can think of terms as hubs in
a hub-and-spoke reference pattern. Without domain knowledge, I'm not
sure we'd know which other referencing table to search by term if you
click on a term. It might not always be "stay on same referencing
table" but instead might have some navigation from an obscure table to
a more canonical table, or a context menu to choose which path to
search, or even a polymorphic search results page...?

**Comment by carlkesselman** [comment]
Let me add (perhaps we are in agreement), that I have long felt that we should be prescriptive about the structure of a vocabulary.  We should have standard (extensible) table structure, and we should be ok with having our tooling know about that structure.  For example, we are going to have to build UI elements for vocabulary selection that know about the structure of a term.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Apr 20, 2016, at 6:53 PM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:

I think we'll need a second level of heuristics (for default) and
annotations (for override) to recognize and navigate vocabularies and
association tables differently from plain referenced entities. Let's
think about this holistically...

A problem with vocabularies is that you can think of terms as hubs in
a hub-and-spoke reference pattern. Without domain knowledge, I'm not
sure we'd know which other referencing table to search by term if you
click on a term. It might not always be "stay on same referencing
table" but instead might have some navigation from an obscure table to
a more canonical table, or a context menu to choose which path to
search, or even a polymorphic search results page...?

**Comment by robes** [comment]
No disagreement with your comments. But they’re slightly tangential to this particular issue which is about how to navigate from recordset to XYZ other entity. Maybe we should start a wiki page in division to capture these cross cutting thoughts on vocabulary, as they cut across ermrest, chaise, general ux, and general data modeling.

**Comment by robes** [comment]
@shinyichen : i think this covers one of the issues we discussed. I would suggest breaking it up as follows:

1. create a link to a record simply based on the foreign key field and value
2. then add support for using the name or "title" as the text in the anchor tag (as described above)

**Comment by karlcz** [comment]
Should this issue be retargeted to record2 app?

**Comment by hongsudt** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #203](https://github.com/informatics-isi-edu/ermrestjs/issues/203) via [**ZenHub**](https://www.zenhub.com/)
