### ISSUE TITLE
Change over to standalone authn API outside ERMrest

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#298]
The `/ermrest/authn/` API will change to `/authn/` after other work in this epic is completed.
If the authn API path is made configurable in chaise_config.js, this work could be done in advance and we simply change the deployed config when ready...

**Comment by hongsudt** [comment]
@karlcz is this ready to be changed?

**Comment by karlcz** [comment]
@hongsudt   The `/authn/` API on dev-isrd is working now, so someone can start working on making Chaise talk to it instead of `/ermrest/authn/`...

**Comment by karlcz** [comment]
Can we schedule this small task soon?

**Comment by karlcz** [comment]
I think we should get this going in master soon and coordinate with transitioning of VMs to Fedora-based recipes so that the new VMs are using the new `/authn/` API, in anticipation of eventually using the other mod_webauthn features and disabling the legacy copy of webauthn nested as `/ermrest/authn/`

**Comment by hongsudt** [comment]
@karlcz  Is #822 a duplicate of this issue?

**Comment by karlcz** [comment]
yes, I think #822 is a duplicate

**Comment by karlcz** [comment]
Should #258 be handled at the same time?  Is this touching the same code?
