### ISSUE TITLE
Links to help and feedback pages should be configurable or generic

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#3]
The links to "Using the Data Browser | Send us your feedback" are hardcoded to one use case. These need to be either 
1. generic: we could host a generic help page on github in a docs section and a generic feedback form, or
2. configurable: probably passed in as a javascript variable in the html page which should then be configured for each deployment / use case of the UI.

**Comment by howdyjessie** [comment]
Can't really think of reasons why one way is outrightly better than the other. Is there deployment-specific content to display on the help & feedback forms? 

Or perhaps do we prefer to process the feedback forms in a unified manner/deployment-specific manner? (e.g. separate people process feedback for separate deployments)

**Comment by robes** [comment]
The current links reference pages (or forms) that are either ISI-specific of FaceBase-specific. What we want is to simply be able to change these links for a deployment. So maybe we need to have a variable defined in the app.html? or some other way of configuring what URL will get stuck into those links.

**Comment by howdyjessie** [comment]
Just pushed a (possible) fix to a branch. A variable deploymentName in ermrest.js allows users to set the specific ermrest deployment (e.g. FaceBase, GPCR), which is then used to set the correct URLs for the help and feedback links.
