### ISSUE TITLE
search app: search attribute shows attributes that do not have such keyword in them

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#300]
on rbk-dev, search "image". 2 options are shown---Image identifier and Annotation Description.

**Comment by hongsudt** [comment]
According to @karlcz We can't support attribute search for project with row-level security requirements. 

Then we should make a configurable parameter to turn the search on and off depending on the project.

**Comment by robes** [comment]
argh, this is a severe limitation then. we should discuss at some point.

**Comment by svoinea** [comment]
Implemented the additional **hideSearchTextFacet** configurable parameter. If present and **true**, the search box will be hidden.

**Comment by svoinea** [comment]
Can be tested on rbk-dev.

**Comment by hongsudt** [comment]
I asked @svoinea to take this out on rbk since we want to test the search index, etc.. We will need to test this on gpcr dev when the dev is setup.

**Comment by hongsudt** [comment]
@svoinea the other option is for me to test it on dev.isrd.. Does this make sense?

**Comment by svoinea** [comment]
I have added the option in chaise-config.js on isrd-dev. Once the test is done, I think we should remove it.

**Comment by hongsudt** [comment]
The search box is not present on dev.isrd. I am closing this issue. 
@svoinea you can turn it back on now.. Thanks.
