### ISSUE TITLE
search app: all attribute shows inconsistent number

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#302]
on rbk-dev, search attribute using last. It said 3 attribute(s) found. View all attributes lists 23, but when click on it, only 3 are shown.  I don't know the expected behavior of the number under view all, but is should either be 3 if 3 items are listed under it, or if 23 is correct, there should be 23 items under it.

**Comment by svoinea** [comment]
Done. Can be tested on rbk-dev.

**Comment by hongsudt** [comment]
@shinyichen since you have or will be testing this feature in the regression testing, can you review and close this issue?
