### ISSUE TITLE
search app: clicking an x on a number search range will not delete the search criteria 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#303]
on rbk-dev, select number of comments, set the serach range to 2-7. THis will reflect correctly on the search summary on top of the result list. Clicking x on that criteria only reset the range, but did not remove it from being displayed in the search list.

**Comment by hongsudt** [comment]
This problem seems to disappear on rbk-dev. @jrchudy did you fix this somehow?

**Comment by svoinea** [comment]
As rbk-dev is doing hourly updates, strange behaviour can happen when a test is performed concomitant with the update process.

**Comment by hongsudt** [comment]
@shinyichen can you please review this issue and close it if this problem disappears in regression testing?

**Comment by shinyichen** [comment]
This is the same thing I documented in the test cases. I still see the problem there.

**Comment by svoinea** [comment]
The hourly update on rbk-dev is broken, so the fix will be visible once the update process will be restored.

**Comment by svoinea** [comment]
Available now for test also on rbk-dev.
