### ISSUE TITLE
Refused to set unsafe header "User-agent"

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#305]
Chaise/Search generates a bunch of these errors, probably on every http call to ermrest. I assume this is a one line change somewhere. Let's prioritize fixing this.

**Comment by svoinea** [comment]
Fixed through commit 797413d6cfdc3a5c8ffbf8faae73b7748a0367ca.

**Comment by svoinea** [comment]
This can be tested on rbk-dev.

**Comment by robes** [comment]
thanks
