### ISSUE TITLE
Update login/logout to remove stale 'goauth' behaviors

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#306]
In preparation for the merge of the globus_auth PR into webauthn master, the Chaise code should stop having special cases for goauth and just follow the login/logout protocol defined in the doc/rest_api.md as it applies consistently to all three available providers (database, goauth, and globus_auth) in the new codebase. Check with @ljpearlman if clarification is needed.

**Comment by karlcz** [comment]
BTW, as I understand from @ljpearlman this change is needed to avoid breaking existing deployments that use goauth provider but get the new code update once we do the webauthn PR merge. There may be another workaround to adjust the configs on those deployments to avoid triggering these legacy code paths in Chaise, but extra effort and testing would be needed to get that right.

Beyond that regression risk, this is also dead code that shouldn't be carried forward in Chaise.

**Comment by svoinea** [comment]
For the search page, that was was done through the commit 460935e449c7af1fc0e497619aaf62ebca28f7a0.

The user sends now the GET '/ermrest/authn/preauth' request. The result will contain one of the following (as described at https://github.com/informatics-isi-edu/webauthn/blob/master/doc/rest_api.md):

- redirect_url. The user should be redirected to its value.
- login_form. An HTML form should be presented to the user for authentication.

For the login_form, the ermlogin.html page is presented where the user enters his/her credentials.
The '/ermrest/authn/session' POST request with the header 'application/x-www-form-urlencoded; charset=UTF-8' is then send for authentication.

**Comment by hongsudt** [comment]
@ljpearlman can you review @svoinea changes?
