### ISSUE TITLE
Link 3rd-party stylesheets and JavaScript files via CDN

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#31]
Instead of including the files with chaise, we should let a CDN host it for us to improve site speed, especially for popular tools on popular CDNs — like using Google's hosted jQuery.

**Comment by karlcz** [comment]
I would disagree with making our sites have an unnecessary run-time
dependency which we do not control nor sub-contract.

If we really have an optimization goal for a remote client where the
CDN-based cache helps dramatically, we would need to consider how to
apply the CDN benefit to all our real science assets as part of the
solution.  I don't think a few JS libraries or other static files are
worth targeting on their own.

But, if these static assets are a substantial part of the request
latency, we should consider how to solve that from our own hosted
copies. For example: minification, pre-compressed encodings, removing
gratuitous asset references, combining many small assets into a few
larger ones, or introducing asynchronous prefetching so the UX does
something useful prior to fetching everything.

**Comment by howdyjessie** [comment]
Hmm I didn't think about the dependency control thing :disappointed: 

Actually, I was looking at PageSpeed Insights to see how we could speed up Chaise, and [its suggestions](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fvm-dev-028.misd.isi.edu%2Fermrest-ui%2Fapp.html&tab=desktop) overlap with a lot of your suggestions as well. Perhaps we could use PageSpeed like a checklist?
