### ISSUE TITLE
Use defaults (catalog, schema, table) when not specified in URL

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#311]
- [ ] catalog default should come from the chaise-config.js
- [ ] schema should come from the annotations
- [ ] table should come from the annotations

**Comment by hongsudt** [comment]
This issue depends on #537

**Comment by jrchudy** [comment]
We decided to have schema and table be defined by the `defaultTables` chaise config parameter. This was written as a common module for every app that is going to use the new `Reference` object from ermrestJS. This was handled in PR #548. Closing this issue.
