### ISSUE TITLE
Support hidden annotation

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#312]
Hide columns based on the hidden annotation.

**Comment by robes** [comment]
When you work on this also make the update to the api and use it here.

https://github.com/informatics-isi-edu/ermrestjs/issues/39

**Comment by shinyichen** [comment]
A couple of tests for this schema
https://synapse-dev.isrd.isi.edu/ermrest/catalog/1/schema

https://synapse-dev.isrd.isi.edu/~jchen/chaise/recordset/#1/Zebrafish:Behavior
https://synapse-dev.isrd.isi.edu/~jchen/chaise/recordset/#1/Zebrafish:Image%20Segmentation
