### ISSUE TITLE
Support display names

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#313]
Support the display name annotation on schema, table and column names.

**Comment by shinyichen** [comment]
A couple of tests for this schema
https://synapse-dev.isrd.isi.edu/ermrest/catalog/1/schema

https://synapse-dev.isrd.isi.edu/~jchen/chaise/recordset/#1/Zebrafish:Behavior
https://synapse-dev.isrd.isi.edu/~jchen/chaise/recordset/#1/Zebrafish:Image%20Segmentation
