### ISSUE TITLE
Image Metadata Update displays wrong value

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#319]
In the Accession Number, I entered the value 23. After Save, it shows HuKidH+E11.6_19, i.e. the description value. When I click again Edit, it shows 23.

**Comment by jrchudy** [comment]
This issue occurred because if a value was set for accession number, we showed the description value instead of the accession number. A simple change to the html fixed this issue. Reassigning to @svoinea to verify it is working properly.

**Comment by svoinea** [comment]
Works as expected.
