### ISSUE TITLE
Allow user to choose different presentations for facet controls

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#32]
The code currently seems to largely map ermrest column types to presentation methods. However, some of the presentation models are equally valid for some types depending on use-case.

1. Conceptually, a slider can work for any ordered type including numbers, times, dates, datetimes, and even strings since they have lexicographic ordering.
2. A text-entry box can be useful for pretty much any type.
3. The pick-list is also valid for any small set of values.

In addition to the heuristic pick-list presentation, it would be helpful to allow a user to toggle different presentations at runtime or even save personal preference settings of some kind.

**Comment by mikedarcy** [comment]
I would also like to see boolean support in the form of Yes/No radio buttons.  This should be the default for boolean types in the discovered schema, and perhaps a configurable automatic option via annotation for integer types that range between 0 and 1 only.

**Comment by howdyjessie** [comment]
(Sorry, made a mistake in a commit message that references this issue number. Please ignore the reference from me.)

**Comment by robes** [comment]
moved to wishlist
