### ISSUE TITLE
The Age Stage drop down list should be ranked sorted 

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#321]

**Comment by karlcz** [comment]
is this issue redundant with work that was already done?  or does it reflect different work that still needs to be scheduled? @svoinea @hongsudt

**Comment by howdyjessie** [comment]
This is work that still needs to be done. I just looked at dev rbk and the Age Stage list is still displayed based on the order in the database.

**Comment by svoinea** [comment]
The bug should have been fixed now through the commit cf08b82f16061be8dfa342d08053d52b19ebddbf.
The `v_image.age_stage_weeks` column is displayed as `Age Stage`, i.e. same as `v_image.age_stage`. That is pretty confusing.
The summary table contains the `v_image.age_stage` column, while the `Age Stage` facets contains the values of the `v_image.age_stage_weeks` column. That is also confusing.
Finally, the `v_image.age_stage_weeks` column is sorted ranked by the `v_image.weeks` column. As there are different `v_image.age_stage` values that are mapped to the same `v_image.age_stage_weeks` value (for example `6 wks, 0 days` and `6 wks, 2 days` are mapped to `6 weeks`), it is possible that in the summary table, the `6 wks, 2 days` to appear before `6 wks, 0 days` one, while the sorting is performed ascending on the `Age Stage` facet.

**Comment by hongsudt** [comment]
This is no longer relevant.. Will close.
