### ISSUE TITLE
Referenced tables shows "No rows found"

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#325]
The test case says: "Showing all referenced tables unless table has 0 rows," but sometimes I'll expand a table and it'll say "No rows found."

For example, when looking at [this record page](https://staging.gpcrconsortium.org/chaise/record/#1/gpcr_browser:construct_gui/title=HUMM-1049) on GPCR staging, I expanded the Protein table and saw "No rows found."

**Comment by shinyichen** [comment]
Please see pull request #326

**Comment by howdyjessie** [comment]
Tested out #326 and it worked. The PR has been merged.
