### ISSUE TITLE
Provide statistical feedback on facets

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#33]
There are several kinds of statistic that could be rendered graphically in facet widgets to help users understand the data.

1. Distinct value distributions on sliders to help understand sparse ranges, e.g. dense areas where active values are clumped together vs. gaps where there is no further way to differentiate records with range filters.
2. Total value distributions which additionally show how popular certain values are. This could be used on sliders, pick-lists, or even date pickers.
3. For the above measures, there is a version that considers current filtering criteria and another that considers all records unfiltered. Some rendering methods might even display both statistics to highlight the difference between active and inactive records?
4. Some combination of curve plots, coloration, or heatmap rendering techniques could be used to present these statistics within the different presentation modes.  E.g. a 2D curve or bar-graph behind a slider; a per-element bar-graph or color mapping for pick list entries; a different color mapping for day boxes in date pickers; or even some kind of 2D curve within each day box for datetime pickers...

**Comment by karlcz** [comment]
We need to more carefully consider caching, precomputation, and aggregation of statistical results before attempting these sorts of features, since we are already seeing too many round-trips for chaise on typical databases.

**Comment by hongsudt** [comment]
put this in the chaise wishlist for now: https://github.com/informatics-isi-edu/chaise/wiki/Wishlist
