### ISSUE TITLE
GUI support for required field (e.g. NOT NULL) 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#330]
When the column's `nullok` status is true, the value is optional.  When the column's `nullok` status is false, a value is mandatory.

**Comment by karlcz** [comment]
This will depend on informatics-isi-edu/ermrest#70 exposing the constraint from the DB and also on ermrestjs exposing the information from ermrest...

**Comment by karlcz** [comment]
This will depend on informatics-isi-edu/ermrestjs#29

**Comment by howdyjessie** [comment]
Columns with a `nullok` of `false` now have (1) the `required` attribute on its input control; and (2) a red asterisk at the column name. Here's [a link](https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/legacy:dataset) to test.

**Comment by jrchudy** [comment]
The changes for this show up properly in the UI. Only the fields with `nullok` of `false` have the asterisk and fail the required validation.
