### ISSUE TITLE
Support vertical layout 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#332]

**Comment by howdyjessie** [comment]
I've transposed the form so that the table's columns are now arranged vertically: https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/legacy:dataset

@robes In the context of #334, does this issue also require adding in the logic for transposing between vertical and horizontal views?

**Comment by robes** [comment]
On 5/9/16, 7:13 PM, "Jessie Wong" <notifications@github.com<mailto:notifications@github.com>> wrote:

@robes<https://github.com/robes> In the context of #334<https://github.com/informatics-isi-edu/chaise/issues/334>, does this issue also require adding in the logic for transposing between vertical and horizontal views?

No. Not in the context of #334.

**Comment by howdyjessie** [comment]
Okay I assigned to @robes for review but if I could assign multiple people I'd also add @hongsudt and @jrchudy.

https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/legacy:dataset

**Comment by robes** [comment]
I would suggest a couple aesthetic changes:
- not using a visible table style
- reduce the spacing between the left column of labels and the right columns of data entry controls
- and/or consider right alignment of the left column of labels

+1 or -1 by @jrchudy and @hongsudt ?

**Comment by jrchudy** [comment]
I think the spacing in the left column should be reduced. But I'm thinking that's being done automatically to spread the table across the width of the display. Other than that, it looks good. I'm not sure how right alignment for the labels would look.

**Comment by hongsudt** [comment]
Yeah.. I tried changing the browser size and the spacing is adjusted automatically.  Left-justified is ok and is consistent with the record app.
* I assume the sharp sign (#) is the catalog. Can we not show that? 
* There should a table name (e.g. entity name) displayed e.g. Protein (new entry)
* The header row should be attributes and values
* I don't like displaying the raw type either.. Maybe we can use some small symbol to indicate number, text, boolean? 
* I assume the drop-down items are foreign keys and I should ignore them for now.

**Comment by howdyjessie** [comment]
Okay what I'm hearing is:
- Keep the visible tables but restrict the width of the table and table's column widths so that it looks more like Record app.
- Remove the # sign. (It was to indicate that that row is a row of numbers, but I can see how that's ambiguous.)

@hongsudt:
- The table name is currently displayed as "New [table name]" in the upper left corner. 
- What do you mean by "The header row should be attributes and values?"
- Yes the dropdowns are foreign keys.

**Comment by jrchudy** [comment]
I believe @hongsudt is suggesting that `#` and the subsequent column numbers for each row entry (`1, 2, 3, ....`) should be `Attributes` and `Values`.

**Comment by robes** [comment]
Actually, shouldn't the data entry vertical form look almost exactly like the record app? I think it should. That would mean, use the same table style, same page alignment, use the same fonts, font colors, etc. These should be as uniform as possible.

**Comment by robes** [comment]
I would just get rid of that first row with the `#` and `1` in it. I understand its for the multi-row editing but it might even be unnecessary in that context. Its enough to just see the multiple rows (or columns in the vertical layout).

**Comment by howdyjessie** [comment]
Okay here's a little more Record-like form: https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/legacy:dataset

Any other improvements/feedback?

**Comment by carlkesselman** [comment]
What should the sizing be of the first column.  When you add the rows (which are actually columns), they are a different width from the original.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 10, 2016, at 4:43 PM, Jessie Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay here's a little more Record-like form: https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/legacy:dataset<https://dev.isrd.isi.edu/%7Ejessie/chaise/data-entry/#1/legacy:dataset>

Any other improvements/feedback?

**Comment by robes** [comment]
@howdyjessie : this works for me. but can you remove the "Add a Record" button as that does not belong in the minimal data entry form. we should address carl's comment in the next round when we deal with the multi-record entry.

**Comment by howdyjessie** [comment]
@robes Sure thing, the Add a Record button has been removed.
@carlkesselman I'll make a note to add same-width columns for later!

https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/legacy:dataset

**Comment by hongsudt** [comment]
@robes, @howdyjessie I found alternating the row background between different rows useful though and would suggest that as a improvement.. But we can fine tune this later.
