### ISSUE TITLE
Set max # of copies

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#333]
Set a limit on how many rows the user can duplicate and append to the form to avoid the browser choking up in the case when a user selects a large number. This may require both a deployment-independent hard limit and a deployment-specific soft limit(?)

**Comment by karlcz** [comment]
I think we should just drop the notion of having a "number of duplicates" control and have a 1-click per duplicate control labeled "Add record".

**Comment by robes** [comment]
I think, per Karl's comment above, that this issue is no longer valid.
