### ISSUE TITLE
Type specific data entry

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#335]
Input fields need to be specific for the types of data entered into them. The supported types are:
- [x] text
  ~ Types: text (varchar() and char() are changed to text in backend)
- [x] integer
  ~ Types: int2, int4, int8
- [x] float
  ~ Types: numeric
- [x] date
  ~ Types: date
- [x] boolean
  ~ Types: boolean

**Comment by robes** [comment]
We should add `float` and `timestamp` to the list of basic types to be supported. Is that going to be a problem?

**Comment by carlkesselman** [comment]
does timestamp include dates?

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 10, 2016, at 5:23 PM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:


We should add float and timestamp to the list of basic types to be supported. Is that going to be a problem?

**Comment by robes** [comment]
There are different types for `date` and `timestamptz` and I think the presentation would be a little different for each. Doesn’t have to be that way but that’s what I’m thinking.

**Comment by jrchudy** [comment]
I don't think that will be an issue @robes.

**Comment by carlkesselman** [comment]
In that case, I would suggest we do both.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 10, 2016, at 5:33 PM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:

There are different types for `date` and `timestamptz` and I think the presentation would be a little different for each. Doesn’t have to be that way but that’s what I’m thinking.

**Comment by karlcz** [comment]
But to answer your question, a timestamptz is a point in absolute
time.  You typically display it as a date plus a time on that date, or
you could convert it to unix epoch seconds or similar.  It can include
fractional seconds too, i.e. floating point seconds value.

The "tz" means "with timezone", which just means we can unambigously
resolve it against UTC.  The other variant "without timezone" is to be
avoided since it really means "timezone unspecified"; those cannot be
interpreted as points in absolute time without assuming and applying
some localization context.

**Comment by hongsudt** [comment]
I rather prioritize adding more data type support (e.g. timestamp) after we
address other urgent issues such as required vs not-required, error
handling (what happens when there is a conflict), annotation, etc. We
decided that those are not needed for synapse use case.

**Comment by hongsudt** [comment]
@jrchudy I added float in the list above.

**Comment by jrchudy** [comment]
Input type fields are implemented for the above types except timestamp. Boolean is not filled in with values yet. 

I'm curious if this reliant on domain values that are passed from ermrest or that these values should be added in the UI. @karlcz might know.

Assigned to @howdyjessie for review. This can be reviewed [here](https://dev.isrd.isi.edu/~jchudy/chaise/data-entry/#1/public:form_test) at my directory or by pulling the code down from master. Mentioning @hongsuda and @robes so that they can look at it too.

**Comment by karlcz** [comment]
If you're asking whether boolean columns will have a foreign key
reference constraint to a boolean domain table, no they won't.  Just
add UI awareness of boolean type and use the same drop-down style...

**Comment by howdyjessie** [comment]
I'm assigning back to @jrchudy for a little more development.

**Comment by jrchudy** [comment]
Boolean dropdown is populated with proper values (`true`, `false`, and empty string `''`).

**Comment by howdyjessie** [comment]
The boolean dropdowns now show true, false, and empty string. Selecting empty string puts in a `null` in the database.
