### ISSUE TITLE
Client-side data validation

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#336]
Input data needs to be validated on the form before a request is made to ermrestJS.

**Comment by jrchudy** [comment]
Validations test for basic validations like fields being required and whether an input value is an integer and that it is within the min and max value size. Assigned to @howdyjessie for review. This can be reviewed here at my directory or by pulling the code down from master. Mentioning @hongsuda and @robes so that they can look at it too.

**Comment by robes** [comment]
The int sizes appear to get validated.
- But it didn't indicate an error when I put "abc" in the int, small int, big int fields. I do get an error on submit but it doesn't tell me which field is wrong, if I fill in all the other fields correctly.
- Same for the float field if I put in "abc"
- Boolean drop down is just empty. What should be in that?
- Should 'Char' be limited to single character? That's what I'd assume based on the type name.
- Should the Float field even use a numeric entry type? The up/down increment just increments by whole integers.

**Comment by karlcz** [comment]
I think the up/down is silly and bad UX for any kind of numeric input 
in our kind of research datasets.  Just validating text-entry would be
much better.

**Comment by robes** [comment]
+1

**Comment by howdyjessie** [comment]
I'm assigning back to @jrchudy for a little more development on getting those mins and maxes displayed in error messages.

**Comment by jrchudy** [comment]
Data validation shows messages that have more meaningful information for numeric input types.

**Comment by robes** [comment]
Can you assign to someone else for validation? I won’t be in a position to do it this week.

**Comment by jrchudy** [comment]
Will do.

**Comment by howdyjessie** [comment]
The form validates correctly now:
- All int fields validate with the correct number ranges and display the type-specific number range in error messages. The ints only accept numbers and "e". The numeric inputs no longer have the up and down steps to increment the inputs' values. 
- A field's error message goes away if the user enters a valid value. 
- Boolean dropdowns now display true, false, and empty string.

I've only found 1 remaining issue which is showing initial error messages (if any) before user clicks Submit. Right now the errors show only after Submit, but it's better UX for them to appear after the user has interacted with the control.

**Comment by jrchudy** [comment]
Some validations are run before the form is submitted, notably checking for integer, float, and a range of values for integers. Required validations are checked after the form is submitted.

Reassigning to @howdyjessie for final testing/review [here](https://dev.isrd.isi.edu/~jchudy/chaise/data-entry/#1/public:form_test).

**Comment by howdyjessie** [comment]
Works for me. The "non-required" error messages appear as soon as I enter an invalid value in the fields instead of waiting for submit.
