### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#339]
Make sure there is an error handling structure in place. Think about modularizing it as well as discuss with other developers to decide how to continue with error handling. @shinyichen has started to think about error handling for the recordset app. Consider discussing this with her to keep our practices consistent and potentially modularized.

**Comment by robes** [comment]
Per our conversation this morning, let's constrain the scope of this task to data entry specific error handling. Maybe just the basic obvious stuff?

**Comment by hongsudt** [comment]
Error handling cases should cover: 
- [ ] 409 conflict
  - [ ] violation of foreign key constraints including invalid vocabulary reference,   
  - [ ] unique key violation (e.g. the rows with same unique keys already exist)
  - [ ] data type violation (e.g. wrong type, out of range numbers, etc. )
  - [ ] unknown column names in defaults query parameter
  - [ ] unknown schema name or table name

**Comment by jrchudy** [comment]
Wiki page with Monday morning meeting info:
https://github.com/informatics-isi-edu/chaise/wiki/Towards-common-error-handling

**Comment by jrchudy** [comment]
Code for this issue is in pull request #374. How to test this is explained in the pull request.

**Comment by howdyjessie** [comment]
The PR #374 has been merged into `master`. This issue is now closed.
