### ISSUE TITLE
recordset gets stuck if fragment ID isn't complete

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#340]
The record app needs better error handling for incomplete fragment IDs:
- If you try to visit a URL like  `/chaise/recordset#N/tablename` the app gets stuck with spinner rather than looking to see if the tablename can be found in the schema unambiguously (which is what ERMrest does natively if you send it table names not qualified by a schema name).
- If you specify a non-existent schema and table it also gets stuck.

**Comment by karlcz** [comment]
The app now displays a yellow banner with an error instead of just freezing. However, in the case where no schema qualifier is supplied, it prints a funny message which I assume means that it decided the schema name was an empty string:

`Schema not found in catalog.`

compare to what I see with a bad schema name:

`Schema Foo not found in catalog.`

**Comment by hongsudt** [comment]
@shinyichen can you look at this problem?
