### ISSUE TITLE
Recordset should choose simplest key when forming links to records

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#343]
In synapse-dev the table `Zebrafish:Subject` has two unique keys.  One is a single-column key on the `Term` column while the other is a composite key on three columns `Issuer`, `Birth Date`, and `Sub-Sequence`.  Clicking on a row forms a record app link that uses the composite key rather than the single-column key, while I think it should prefer the key with the fewest elements.

**Comment by robes** [comment]
I believe I fixed this ... and it doesn't seem to have broken paging or sorting.

https://synapse-dev.isrd.isi.edu/~schuler/chaise/recordset/#1/Zebrafish:Subject

**Comment by karlcz** [comment]
confirmed that it now chooses the shorter key
