### ISSUE TITLE
Record app shouldn't change case on table names when already mixed case

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#344]
I have a model where I already set mixed (title) case in my table names in the schema.  The record app is displaying the table names to all UPPER CASE which I think is wrong.  If we're going to have a heuristic for automatic reformatting, I think it needs to be more conservative in deciding when the names need case changes.

**Comment by hongsudt** [comment]
Will not fix in the current record app, but move this to the new record app.

**Comment by hongsudt** [comment]
This is no longer relevant due to annotation on column name transformation.
