### ISSUE TITLE
Record2 app should hide related entity fields that are constrained by related entity query

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#345]
When display related entities, the record2 app should hide the column or columns that are constrained by the related entity query to always be equal to values from the parent record on the page.

As an example, `https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/Term=ZfDsy20151231A` has multiple related tables and they all have a `Subject` column that is a foreign key to the `Term` key of the subject being displayed. These are always going to have the same constant value in the related entity tables and waste valueable screen space.

**Comment by robes** [comment]
I think this risks over simplification. Those columns that form the "parent" FK from other related tables could include columns (subsets of the parent FK columns even) that form FKs to other tables.

**Comment by karlcz** [comment]
OK, let's phrase it another way. If the columns are being filtered by
the related-entities query to always refer to the parent table, then
they are redundant for display.  This filtering is a result of the
foreign key relationship but you can ignore that and just consider the
results... we know what filters we applied, and should not display
those filtered columns.

**Comment by hongsudt** [comment]
@karlcz I am moving this feature to the new record app. Let me know if you need this for synapse in the current record app.

**Comment by hongsudt** [comment]
More example, see #146.

**Comment by hongsudt** [comment]
I am closing this since it will be done by the ermrestjs Reference.related functionality.
