### ISSUE TITLE
Recordset doesn't handle url-encoded table names in fragment ID

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#347]
I try to visit `https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Brain%20Anatomy` and get stuck with a spinner and a javascript error like `Error: table is undefined`

**Comment by robes** [comment]
So what's happening is that when we get the `window.location.hash` it has encoded the space ` ` as `%20`, so the app looks for a table named `Brain%20Anatomy`.

**Comment by robes** [comment]
fix is committed to master. can be viewed here now:
`https://synapse-dev.isrd.isi.edu/~schuler/chaise/recordset/#1/Zebrafish:Brain%20Anatomy`

However,... the record app has the same bug. :-(

**Comment by karlcz** [comment]
confirmed `https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Brain%20Anatomy` now works
