### ISSUE TITLE
Record/recordset doesn't handle url-encoded names in fragment ID

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#349]
Similar to #347 

For example:
`https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Brain%20Anatomy/ID=lCere`

**Comment by shinyichen** [comment]
Is this the same issue as in #364 ?

**Comment by karlcz** [comment]
Yes I think I filed several specific bugs before I decided to write #364 to roll up all the test scenarios...

**Comment by karlcz** [comment]
It's actually a bunch of closely related bugs on both sides of the apps:  bad decoding of the fragment ID when loading the page with a pre-filled link, and bad encoding of page links in other apps.  Then this encoding and decoding fails in different ways on schema names, table names, column names, and column values...
