### ISSUE TITLE
Search in chicklet box...

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#35]
Users have expressed a desire to have a more obvious google search like first experience with interface.  Need to figure out how to make an obvious search box that blends smoothly with faceting.

**Comment by karlcz** [comment]
A simpler search box could also be part of a latency-hiding UX, e.g.
basic options can be ready to respond on a landing page before
the entire facet browser application state is loaded?

**Comment by robes** [comment]
do we still want this, or has this been obsoleted by removing the chiclet box and pinning the slide out by default?

**Comment by carlkesselman** [comment]
I think this has been obsoleted.

Carl


----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<applewebdata://4AF843A7-3D46-4AED-93B7-1BEF37ECE717/carl@isi.edu>
Web: http://www.isi.edu/~carl


On September 24, 2015 at 5:11:12 PM, robes (notifications@github.com<mailto:notifications@github.com>) wrote:

do we still want this, or has this been obsoleted by removing the chiclet box and pinning the slide out by default?

**Comment by robes** [comment]
moved to wishlist
