### ISSUE TITLE
Record2 app related entities tables

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#350]
This is something @robes and I have been discussing a bit and I'd like to see discussed more in the team. I think the current nested tables UX in the record app is pretty bad.  Between the flawed table headings (e.g. #149) and nested scrolling behaviors, it is very frustrating and ugly for records that have multiple nested result tables.

I think we should re-think this:
1. Have a configuration setting in chaise config and/or as annotation to set a maximum row count.
2. Have a heuristic and annotation to set sort order (this would also be useful on other apps to set default sort)
3. Fetch the sorted rows with limit of the maximum desired count plus 1 more as a sentinel
4. Display up to the maximum row count (not including sentinel even if it appears in result)
5. If sentinel appeared, include a "More results..." link to the same related entity data in the **recordset** app, where the user can then do any exploratory stuff on the related entities like sorting, paging, and eventually filtering as we expand the capabilities of that app.

I'm not sure if the link should go to the next page following the previously displayed rows or start over in that other app on the first page.

**Comment by carlkesselman** [comment]
First, I agree.  I find nested tables to be pretty bad.

Is this also the time we should be discussing having the nested tables being represented as a link back to a search page that that just has that nested table?  I think this has proven to be very useful in GPCR, and the users seem to like it (at least Mike does).

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 13, 2016, at 8:11 AM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:


This is something @robes<https://github.com/robes> and I have been discussing a bit and I'd like to see discussed more in the team. I think the current nested tables UX in the record app is pretty bad. Between the flawed table headings (e.g. #149<https://github.com/informatics-isi-edu/chaise/issues/149>) and nested scrolling behaviors, it is very frustrating and ugly for records that have multiple nested result tables.

I think we should re-think this:
1. Have a configuration setting in chaise config and/or as annotation to set a maximum row count.
2. Have a heuristic and annotation to set sort order (this would also be useful on other apps to set default sort)
3. Fetch the sorted rows with limit of the maximum desired count plus 1 more as a sentinel
4. Display up to the maximum row count (not including sentinel even if it appears in result)
5. If sentinel appeared, include a "More results..." link to the same related entity data in the recordset app, where the user can then do any exploratory stuff on the related entities like sorting, paging, and eventually filtering as we expand the capabilities of that app.

I'm not sure if the link should go to the next page following the previously displayed rows or start over in that other app on the first page.

**Comment by carlkesselman** [comment]
So a question, not knowing the implementation details.  Could the entity set app be used for displaying nested tables in the record page?

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 13, 2016, at 8:18 AM, Carl Kesselman <carl@exchange.isi.edu<mailto:carl@exchange.isi.edu>> wrote:

First, I agree.  I find nested tables to be pretty bad.

Is this also the time we should be discussing having the nested tables being represented as a link back to a search page that that just has that nested table?  I think this has proven to be very useful in GPCR, and the users seem to like it (at least Mike does).

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 13, 2016, at 8:11 AM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:


This is something @robes<https://github.com/robes> and I have been discussing a bit and I'd like to see discussed more in the team. I think the current nested tables UX in the record app is pretty bad. Between the flawed table headings (e.g. #149<https://github.com/informatics-isi-edu/chaise/issues/149>) and nested scrolling behaviors, it is very frustrating and ugly for records that have multiple nested result tables.

I think we should re-think this:
1. Have a configuration setting in chaise config and/or as annotation to set a maximum row count.
2. Have a heuristic and annotation to set sort order (this would also be useful on other apps to set default sort)
3. Fetch the sorted rows with limit of the maximum desired count plus 1 more as a sentinel
4. Display up to the maximum row count (not including sentinel even if it appears in result)
5. If sentinel appeared, include a "More results..." link to the same related entity data in the recordset app, where the user can then do any exploratory stuff on the related entities like sorting, paging, and eventually filtering as we expand the capabilities of that app.

I'm not sure if the link should go to the next page following the previously displayed rows or start over in that other app on the first page.

**Comment by karlcz** [comment]
I think we still want in-line display of simpler results, but I do agree that a deployment (or specific record source table) might want to set the maximum displayed rows to 0 and just end up with a link to see the related entities (if any exist).

As I understand it, we're not really at a point where we could factor out the recordset app and embed instances of it in the record page. But even if we could, I think we'd need a simplified UX without a bunch of controls decorating each in-line table.  No sort, no paging, no nested scroll or other iframe-like behaviors.  Those make for a very ugly presentation as you get more than a couple nested result sets for the same parent record.

**Comment by carlkesselman** [comment]
Its not clear to me you don’t want the controls.  If you are not displaying all of the elements of a nested table, then it seems to me you are going to either the table is small, and you can see everything you want, or you are going to want to look through the available rows, which implies either a link to the search page, or sort/search in the nested table.  I’m actually ok with just doing the link, but then this becomes very important in my mind.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 13, 2016, at 8:24 AM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:


I think we still want in-line display of simpler results, but I do agree that a deployment (or specific record source table) might want to set the maximum displayed rows to 0 and just end up with a link to see the related entities (if any exist).

As I understand it, we're not really at a point where we could factor out the recordset app and embed instances of it in the record page. But even if we could, I think we'd need a simplified UX without a bunch of controls decorating each in-line table. No sort, no paging, no nested scroll or other iframe-like behaviors. Those make for a very ugly presentation as you get more than a couple nested result sets for the same parent record.

**Comment by karlcz** [comment]
The final step of my first description on this issue is including a
link when there are more than the N rows available!

It sounds like we're all on the same page that this is necessary when
nested results are more than trivial, and that with this link we don't
need to clutter the in-line display for trivial results.

**Comment by robes** [comment]
The simpler option would be to display the first N rows of the nested table in a simplified table presentation (think of it as a tabular preview) without the controls that may clutter the page, as Karl has said. And then yes, there would be a link back to the recordset page for that nested table to search over the complete results set.

**Comment by karlcz** [comment]
I think my proposed configurable row count limit can already address
the case of just having a link w/o in-line tables (via a 0 count
limit).

So, I guess one variant to decide is whether the link is optional or
required:
1. "More results..." and only present when the set has been truncated;
2. Some other link name that would always be present, even if the entire, trivial result set was already displayed?

**Comment by carlkesselman** [comment]
For consistency purposes, I would propose we make it required.  Then the user never needs to guess.

I would not call it more results, as you are actually going to a page with different/more functionality.  I would expect “more” to imply paging.  Perhaps “Explore Table” or “Search Table"

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On May 13, 2016, at 8:50 AM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:

I think my proposed configurable row count limit can already address
the case of just having a link w/o in-line tables (via a 0 count
limit).

So, I guess one variant to decide is whether the link is optional or
required:
1. "More results..." and only present when the set has been truncated;
2. Some other link name that would always be present, even if the entire, trivial result set was already displayed?

**Comment by karlcz** [comment]
As for the naming of the link, I've been looking at other sites and often saw "view all" for a link that takes you to another result page.  Conversely, I often saw "show all" or "show more" when it was more like an accordian/inline expansion of more results.

**Comment by karlcz** [comment]
Updating the name of this issue and its tags to reflect that it discusses UX requirements for record2, since we're not going to fix it on record.

**Comment by jrchudy** [comment]
This has been implemented as part of the Epic #451. Closing this issue.
