### ISSUE TITLE
Hide columns in data-entry app

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#352]
The data-entry app should honor the `tag:misd.isi.edu,2015:hidden` annotation on columns as well as the draft `tag:isrd.isi.edu,2016:ignore` annotation which we are designing with the next MVP in mind...

1. The basic hidden one should apply to both the data-entry form and any resulting record display.
2. The new ignore annotation should allow us more precision to omit the field from the data-entry form while including it in the resulting record displays.

When we hide/ignore a column for data-entry, we should specify it in the `defaults` query parameter to tell the server that we wish it to fill in the column for us.

**Comment by howdyjessie** [comment]
I've created PR #378 for this issue. Description of changes and test info is on the PR.

**Comment by howdyjessie** [comment]
The PR has been reviewed and merged into `master`.
