### ISSUE TITLE
Simple foreign key support

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#355]
A _simple_ key is a key composed of a single column. For data entry purpose if we encounter a column that is a member of a _simple_ foreign key then we will support data entry by allowing the user to select a value from its "domain" where the domain is the set of values in the referenced _simple_ key (i.e., the distinct values for that key column in the referenced table).

In this case, the data entry form should present the user with our standard multi-select dropdown control, from which they may select a value. The column order of the table (as presented in the form) should be preserved.

**Comment by robes** [comment]
Note that #357 extends this issue with support for vocabulary tables. I've left that task out of the "Round Two" epic but if we make great progress we should consider pulling it in here.

**Comment by robes** [comment]
Another extension of this issue is #358, which adds support for a preferred display name. Again, would be great to get to this in the round two epic but I haven't put i in there.

**Comment by jrchudy** [comment]
The implementation for this works properly for simple foreign keys. It also appears to work for vocabulary tables as well. You can see it working for vocabularies in the [rbk image](https://dev.isrd.isi.edu/~jchudy/chaise/data-entry/#4/rbk:image/) table. And for both Owner names and Project IDs in the [legacy dataset](https://dev.isrd.isi.edu/~jchudy/chaise/data-entry/#1/legacy:dataset/) table.

**Comment by jrchudy** [comment]
It looks like this issue resolves #357 as well.

**Comment by robes** [comment]
Doesn't resolve #357.

But it works for me for what this initial FK support should do.
