### ISSUE TITLE
Vocabulary support, basic

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#357]
Following on from issue #355, the data entry app should support the (basic) display and selection of vocabulary terms. In this basic support, the multi-select control should have the user select from the referenced vocabulary table's `term` column per its annotation.

The data entry app should look at the vocabulary annotation to determine which column represents the term. The annotation is defined here:

https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2015-vocabulary

Note the "heuristics" section of the above document. For example, if the vocabulary annotation is empty (i.e., `null` or `{ }`) then the UI should look for a column called `term` as its term. It doesn't have to be explicitly specified when it uses the preferred column name.

We should probably update that annotation to say that it should be independent of case. That is, if there is a vocabulary table that has a `Term` column in it, that should be considered a match.

**Comment by jrchudy** [comment]
This issue is referenced in pull request #411. The code can be tested [here](https://synapse-dev.isrd.isi.edu/~jchudy/chaise/data-entry/#2/Zebrafish:Subject). The issuer dropdown is using the `full_name` column as the `term` defined in the annotations for this table. The `RNA Construct` column is using the `term` column as defined by one of the heuristics [here](https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2015-vocabulary).

**Comment by robes** [comment]
I went to the referenced link for testing. The presentation looked right, its displaying the term instead of the id. However, it fails on submit.


`Error 409 Conflict The request conflicts with the state of the server. Input data violates model. ERROR: insert or update on table "Subject" violates foreign key constraint "Subject_Issuer_fkey" DETAIL: Key (Issuer)=(Andrey Andreev) is not present in table "Person".`

This error message suggests that you are not only using the term for presentation but also for assignment. The assignment must still be a value taken from the key field of course, not the presentation (term) field.

**Comment by jrchudy** [comment]
Pull request #411 has the updated code for this issue. The code now follows along with the pseudocode that @robes and I came up with yesterday afternoon. This also includes basic exception handling.

Assigning to @robes and @howdyjessie for review. Code can be tested [here](https://synapse-dev.isrd.isi.edu/~jchudy/chaise/data-entry/#2/Zebrafish:Subject).

**Comment by robes** [comment]
It worked for me.

**Comment by robes** [comment]
@jrchudy I made a few comments in the PR. They are not huge but I think they should be addressed. Let me know when you update it. thanks
