### ISSUE TITLE
Foreign key support, with preferred field for display

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#358]
Another follow on to #355. We need to have a way of identifying or generating a _display name_ for a row. This is kind of similar to the concept we had of a row having a _title_ which we used to define by annotation in the older annotations. It should use the same general _pattern_ approach we have used in other annotations -- or a revised, improved form of that pattern.

~~Maybe @karlcz can help with this part.~~ Karl's suggestion for annotation controls is in #377 where we need to use the same feature when displaying foreign keys in other apps.

Then in the data entry app, we should enhance the basic foreign key support, so that in the multi-select dropdown control we display the _display name_ for the referenced table's rows.

**Comment by robes** [comment]
I updated the _display_ annotation with a new `row_name` field.

https://github.com/informatics-isi-edu/ermrest/blob/annotation-update/user-doc/annotation.md#2015-display

**Comment by hongsudt** [comment]
This issue should be taken care of by the current implementation. Will close.
