### ISSUE TITLE
Support composite sort keys in recordset bookmark

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#360]
If it is not too difficult, I think it would be useful to support composite sort keys in bookmarks. I.e.
1. On page init, if `@sort(...)` from bookmark has multiple columns, preserve them in data data retrieve
2. While paging through results, retain current sort even if multi-column.
3. If user clicks sort controls on table, it is OK to revert to single column sort. There doesn't need to be a way to begin a multi-column sort from the GUI for now.

This would be useful for bookmarks on project landing pages, where more interesting sort orders may be useful starting points for certain recurring workflows.

**Comment by shinyichen** [comment]
Sort with multiple column is already supported in recordset URL.
