### ISSUE TITLE
Enhance filter in recordset bookmarks

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#361]
- [ ] Support `::null::` operator
- [ ] Support `!` negation prefix

Each predicate has _column_, _operator_, and _value_ which may be empty as well as optional negation prefix `!`:
- `column::eq::value` or `!column::eq::value`
- `column::null::` or `!column::null::`
- `column::regexp::pattern` or `!column::regexp::pattern`

The full ERMrest filter language has two more features which might be more tricky to put in the fragment ID without disturbing other code in our Angular apps:
1. The `&` character also means AND but with different operator precedence
2. The `(` and `)` parentheses allow forced grouping of filters and logical operators to override operator precedence

**Comment by robes** [comment]
It does this. However it may not be complete. Like I do t think we supported OR, NULL, and maybe not regexp.

Rob Schuler

On May 16, 2016, at 2:37 PM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:


It would be very useful if the recordset app could parse filter predicates from the fragment ID of the URL and apply those filters to the data retrieval requests. This would allow task-specific bookmarks to be places on project landing pages as starting points for work, even if there is no GUI to edit the filter.

  *   /chaise/recordset/# N / schema : table
  *   /chaise/recordset/# N / schema : table @sort(...)
  *   /chaise/recordset/# N / schema : table / filter
  *   /chaise/recordset/# N / schema : table / filter @sort(...)

The filter itself can have multiple predicates and logical operators:

  *   p
  *   p1 / p2, i.e. p1 AND p2
  *   p1 ; p2, i.e. p1 OR p2
  *   p1 ; p2 / p3 ; p4, i.e. (p1 OR p2) AND (p3 OR p4)

Where each predicate has column, operator, and value which may be empty as well as optional negation prefix !:

  *   column::eq::value or !column::eq::value
  *   column::null:: or !column::null::
  *   column::regexp::pattern or !column::regexp::pattern

The full ERMrest filter language has two more features which might be more tricky to put in the fragment ID without disturbing other code in our Angular apps:
1. The & character also means AND but with different operator precedence
2. The ( and ) parentheses allow forced grouping of filters and logical operators to override operator precedence

-

**Comment by karlcz** [comment]
Hah, OK. Funny that I remembered `::eq::` when I wrote the issue but not when I tested manually and kept typing `=` instead...

Confirmed that it works with `::eq::` and `::regexp::` already

**Comment by karlcz** [comment]
However you are write, it doesn't seem to support ::null:: yet.

**Comment by robes** [comment]
Yeah, not surprised. I wrote this and just threw in what I remembered off the top of my head.

**Comment by shinyichen** [comment]
It looks that `!` and `::null::` are supported now.
