### ISSUE TITLE
Navigable links w/ complex content

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#364]
Rather than file a bunch of bugs, I want to give this overall task to be reviewed and fixed until it works...

Starting at the [synapse-dev landing page](https://synapse-dev.isrd.isi.edu/), you should be able to visit each link and further navigate the intra-chaise links presented by the app pages without encountering errors and broken/frozen apps.

- [x] Open any recordset page in the **Data-related Links** section and click a row to navigate to a record page. All should be navigating by the URL key column on those entities, but they fail due to bookmark encoding problems.
- [x] Open **PrcDsy20160101A protocols details page**, expand the Protocol Step related entities, and click on a row. Should show a record page, but fails due to bookmark encoding problems.
- [x] Open any recordset page in the **Vocabulary-related Links** section and click a row. Should show a record page, but fails due to bookmark encoding problems. The only one that works is the *People* page.

Once the above are fixed, please leave this issue open so we can test further and add more check items as we find them. It's hard to test now once you hit the first round of problems...

**Comment by robes** [comment]
I believe I checked every link off of Karl's landing page. I also went at least one more level deep from there. I.e., from recordset pages I went to the next level deep of a record page, and from record pages I went to the next level deep by drilling down from a nested table. In many cases I tried more than one link from the initial page I landed on.
