### ISSUE TITLE
Search app generates invalid result record links

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#365]
Visit the page https://synapse-dev.isrd.isi.edu/chaise/search/#1/Zebrafish:Subject?facets=(Subject:Issuer::eq::Dsy)&layout=table&page=1  and inspect the link URL in the data rows on the `Birth Date` column. The link shows `https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/Birth%2520Date=undefined&Issuer=Dsy&Sub-Sequence=A` which is incorrect for two reasons:
1. The column name should be encoded as `Birth%20Date` not as `Birth%2520Date` which looks like it was url-encoded twice in a row.
2. The date filter value should be `2015-12-31` not `undefined`

**Comment by svoinea** [comment]
Fixed through commit ceef0411e647bdb0201adab76626fa2272d9878b
The primary keys were double encoded in the record links.
Ready for review.

**Comment by karlcz** [comment]
Going to the same URL as in the bug description, latest master crashes with a blank page on the search app.

**Comment by svoinea** [comment]
I think the URL mentioned above is wrong (probably copied from the URL box).
It should be:
https://synapse-dev.isrd.isi.edu/chaise/search/#1/Zebrafish:Subject?facets=(Subject:Issuer::eq::Dsy)&layout=table&page=1

**Comment by karlcz** [comment]
OK, it's a little weird that the column with the link has now changed to just the Issuer, but the link does work unlike before.
