### ISSUE TITLE
Record app URL presentation ignored in main entity columns

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#367]
Visiting https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Movie/Subject=ZfDsy20151231A  shows the text caption `m4v` in the `Download` column as per the `url` annotation but does not present a link.  When showing the same data in the `Movie` related-entity section of https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/Term=ZfDsy20151231A the caption and link are presented properly.

The annotations controlling this are:
- `tag:misd.isi.edu,2015:display`
  - On column: `Zebrafish`, `Movie`, `URL`
  - Payload: `{"name": "Download"}`
- `tag:misd.isi.edu,2015:url`
  - On column: `Zebrafish`, `Movie`, `URL`
  - Payload: `{"url": "{URL}", "presentation": "download", "caption": "{File Type}"}`

So it is processing both annotations to have the altered column display name `Download` and the caption text coming from the template `{File Type}` but it isn't producing the actual link from the `{URL}` template.

**Comment by shinyichen** [comment]
Has the schema changed? There is no Movie table in the schema.

**Comment by robes** [comment]
Updated examples:

https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Image%20Segmentation/URL=%2Fhatrac%2FPrcDsy20160101A%2F2015%2F12%2FZfDsy20151231A%2Fseg0-lPal-debug.tiff

https://synapse-dev.isrd.isi.edu/chaise/record/#1/Synapse:Protocol%20Step/ID=PrcDsy20160101A-seg0
