### ISSUE TITLE
Handling NULLs in composite keys

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#368]
By most relational die-hards, including the designers of PostgreSQL, a composite key like (`a`, `b`, NULL) is considered an incomplete key as they interpret NULL as "unknown" rather than as its own value.  They would expect you to use a different, non-NULL value to represent "none", e.g. (`a`, `b`, `none`).

When a composite key has any NULLs in it:
1. A uniqueness constraint is not enforced on the incomplete key, so you can encounter multiple rows with the "same" incomplete key combination (`a`, `b`, NULL).
2. A foreign key constraint is not enforced on the incomplete references, so you can have arbitrary values like (`x`, `z`, NULL) where `x` and `z` would not be found in the referenced table no matter which value you were to substitute for the NULL.

I don't think we expect to diverge from SQL or Postgres too much here, so I suggest that when we are producing navigable links via foreign key, we should probably disable the link feature when we encounter incomplete references, i.e. references with one or more NULLs in them. Providing navigation by partial match would probably encourage the wrong understanding of how the ERM works.

In our actual projects, we should probably try to be more disciplined and introduce non-NULL constraints on our keys and references, and introduce different tombstone values to represent "none" rather than "unknown".  But, we still want Chaise to do appropriate things when it encounters less rigorous models...

**Comment by hongsudt** [comment]
@jrchudy check whether we have already handled this case?

**Comment by RFSH** [comment]
Isn't the attributegroup api handling it? Whenever one of the columns of composite key is null, it is returning null as the value of foreign key.

**Comment by karlcz** [comment]
A null value cannot participate in a valid key nor foreign key whether
a simple scalar value or as any part of a composite value.  This is a
part of SQL and PostgreSQL semantics, not specific to ERMrest or
Chaise.

The null value represents "unknown" or "incomplete" data and bypasses
the uniqueness constraints of the DB. More than one row could be
present with the same null state, meaning null cannot be used to
identify a row uniquely.

**Comment by hongsudt** [comment]
Ermrestjs seems to handle this case already.. Let's open another issue if we find a bug related to this.
