### ISSUE TITLE
Record app omits column with NULL value

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#370]
In https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Behavior/ID=1 there should be a column "Learned?" displaying with `N/A` for a NULL boolean value.  This will be necessary for future hooks to edit metadata, where a record will start with a NULL and a user will update to set true or false.

When the same table is displayed as a related-entity, the NULL is displayed properly: https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/Term=ZfDsy20151231A

**Comment by hongsudt** [comment]
@karlcz do we need to fix this for synapse or it can be waited until record2?

**Comment by karlcz** [comment]
I think we can try to live with it until record2

**Comment by hongsudt** [comment]
A duplicate of #474.
