### ISSUE TITLE
Record app related entities query fails with ambiguous links

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#371]
On my test catalog https://synapse-dev.isrd.isi.edu/chaise/record/#2/Synapse:Protocol_Step/ID=PrcDsy20160101A-behave fails to load due to an ambiguous link between this table and Zebrafish:Behavior

The underlying ERMrest query which fails is https://synapse-dev.isrd.isi.edu/ermrest/catalog/2/aggregate/Synapse:Protocol_Step/ID=PrcDsy20160101A-behave/Zebrafish:Behavior/row_count:=cnt(*) because there are two different foreign keys in the Behavior table that both reference Protocol_Step.

We should do one of two things when there are ambiguous links:
1. Ignore that linked table, rather than failing the whole page load
2. Include a separate related entities table for each available link, using the unambiguous link syntax in the ERMrest requests.  This is preferred, but more complex.

The unambiguous version of the query above would be these two different links:
- https://synapse-dev.isrd.isi.edu/ermrest/catalog/2/aggregate/Synapse:Protocol_Step/ID=PrcDsy20160101A-behave/(Zebrafish:Behavior:Image_Step)/row_count:=cnt(*)
- https://synapse-dev.isrd.isi.edu/ermrest/catalog/2/aggregate/Synapse:Protocol_Step/ID=PrcDsy20160101A-behave/(Zebrafish:Behavior:Analysis_Step)/row_count:=cnt(*)

i.e. one explicitly linking by each foreign key link that is available in the model.

**Comment by robes** [comment]
I tested this with the recent fix you added to ermrest and this page now works:
https://github.com/informatics-isi-edu/ermrest/issues/80

Personally, I think this is a good enough solution for now.

**Comment by karlcz** [comment]
Actually I had removed the ambiguous links from the schema to make it work.  I put it back and now the page loads but displays confusing/duplicate info for the two links.  The problem is that the related entity query for each link should set a different column constraint for each, and in this dataset only one of those queries should have the result shown twice now.  The other query should be empty result.

I.e. visit https://synapse-dev.isrd.isi.edu/chaise/record/#2/Synapse:Protocol_Step/ID=PrcDsy20160101A-behave and see two related-entity tables both titles `BEHAVIOR (1)`.  In reality, one should be querying on `Analysis_Step=PrcDsy20160101A-behave` and show a result, while the other should query on `Image_Step=PrcDsy20160101A-behave` and show no results.

Furthermore, this is where the proposed annotation `tag:misd.isi.edu,2015:binary-relationship` and its hueristics would be important.  The title for the two instances of the `Behavior` table could be determined specifically for each FKR rather than just using the same table name twice.

**Comment by karlcz** [comment]
@robes @shinyichen Could we patch the record app to be more consistent on this issue of ambiguous links?  I think either approach would work for now and would prefer that we fix it if not too difficult:

1. Change current code to express more specific entity linkage, since it seems the code is iterating over each link in the model (as it displays one query result per link).
2. Change current code to merge all links to same table into one result table if it is going to continue to use an ambiguous table-link pattern.

Right now it is very confusing as it does half of each...

**Comment by karlcz** [comment]
I guess we can convert this issue into requirements input to the replacement app?  @robes @hongsudt

**Comment by hongsudt** [comment]
tag as wishlist, and keep track of this in record2 wiki page.
