### ISSUE TITLE
Use compliant URL escaping function

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#372]
When we URL escape any model element names or data values, we must use a safe URL encoding function that handles arbitrary UTF-8 data as per RFC 3986:

1. Pass non-reserved characters verbatim: `A`-`Z` `a`-`z` `0`-`9` `-` `_` `.` `~`
2. Encode reserved characters: `!` `*` `'` `(` `)` `;` `:` `@` `&` `=` `+` `$` `,` `/` `?` `%` `[` `]`

Our data should already be encoded in UTF-8 and the UTF-8 string should be broken into 8-bit octets and each octet encoded as per the above rule. Any other octet than the above ascii characters is encoded as `%xx` with the hex digits representing its 8-bit value.

**NOTE**: most of the available url-escaping functions in Javascript are **broken** and non-conformant to this specification. You must test and verify that the above holds true for whatever routine you select.  See Chaise search app for some previous attempts at getting this right.  It is subtle and very important.

I'm tagging this for record and recordset because I've observed problems with these. All apps should be reviewed and testing should include data containing **ALL** of the above reserved and non-reserved characters as well as some non-ascii characters.  In ERMrest tests, we use someupside-down Unicode like `ɐɯǝɥɔs`, `ǝlqɐʇ`, and `ǝɯɐu` to validate UTF-8 passthrough.

**Comment by svoinea** [comment]
The `fixedEncodeURIComponent` function from ermrest.js is a candidate for it:
```
function fixedEncodeURIComponent (str) {
	return encodeURIComponent(str).replace(/[!'()*]/g, function(c) {
		return '%' + c.charCodeAt(0).toString(16).toUpperCase();
	});
}
```
At least, it passed the requirements 1 and 2.

`encodeURIComponent` is already a JavaScript function which encodes everything, but the characters from the regular expression mentioned in the `replace` argument.

**Comment by howdyjessie** [comment]
As discussed in this morning's standup, whatever function we end up using for this, it should be wrapped in an Angular filter inside `common/filters.js`.

**Comment by robes** [comment]
@karlcz Do you agree with @svoinea comment above? In particular, to your initial comment are you suggesting that the standard function `encodeURIComponent` which is supported by all browsers (which could have variable quality of implementations) is unusable?

MDN reference is here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**Comment by robes** [comment]
@howdyjessie regarding your comment to use an angular filter. I am not sure that will work... doesn't the encoding have to process the URL component-by-component. e.g., if you had to encode the url `http://example.org/A/B/name=cde/fgh/C` where `name=cde/fgh` is a single component not to be split at the intermediate `/` but rather needs to be encoded. Doesn't a filter just take the whole string and at that point not have the semantics of which `/`s should be encoded and which shouldn't?

**Comment by karlcz** [comment]
Our long-term experience has been that the "standard" functions in browsers are buggy and do not follow the *standard* for URL escaping. Historic bugs seem to be enshrined as the expected results of these JS routines.

If we now have a rigorous test case, perhaps it would be entertaining to run a bake-off of different browser functions to show which characters fail to encode properly...

**Comment by karlcz** [comment]
@robes Right, and similarly the URL needs to be parsed into components
before the components get decoded, when interpreting the href, e.g. during
bootstrapping of a page from a bookmark.

**Comment by howdyjessie** [comment]
@robes @karlcz Yeah Angular filters isn't the right approach here. A plain JavaScript function in `common` will suffice.
