### ISSUE TITLE
Preferred display name (row-name) for linked entities

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#377]
Use common annotation and logic shared with #358 to determine a preferred way of referring to entities in a foreign domain table. Replace foreign key values with this preferred entity name when displaying the link.

Karl suggests extending the `display` annotation at table level with another field like `row_name` that uses a template to form a row name from row values.  The `name` field is already used for the display name of the table.  The `display` annotation at column level can rename the foreign key column using the `name` field, and at column level this new `row_name` field should be ignored as irrelevant.

This should be done using the Reference API.

**Comment by robes** [comment]
I updated the _display_ annotation with a new `row_name` field.

https://github.com/informatics-isi-edu/ermrest/blob/annotation-update/user-doc/annotation.md#2015-display

**Comment by hongsudt** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #159](https://github.com/informatics-isi-edu/ermrestjs/issues/159) via [**ZenHub**](https://www.zenhub.com/)
