### ISSUE TITLE
Option (or default) to show column comments on data-entry form

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#380]
I think having the column comment displayed for all input fields would be much better than having them hidden as a tool-tip.  I think this would be fine as a default or only behavior, but will accept an annotation to control it if others disagree with always showing comments.

I imagine a layout something like this for short fields:

```
-----------------------------------------------------------------
Column Name   [    entry field/control    ]
Column comment text.
-----------------------------------------------------------------
...
```

Where the comment text would be in a smaller/lighter style than the column names.

If we ever support very long text-entry boxes, I suspect the comment text should be lifted above the entry field instead, so it remains clear which column name is being described by the comment:

```
-----------------------------------------------------------------
Column Name   Column comment text.
[   

 entry field/control    


]
-----------------------------------------------------------------
...
```

**Comment by robes** [comment]
Personally, I do not see what is wrong with the tool tips that we already have implemented.

**Comment by karlcz** [comment]
What's wrong is that I put it in front of users and they struggled to understand what to put where, even though they understand the model abstractly.

It is much more idiomatic to have field descriptions in data-entry forms for casual users, unless the forms and fields are extremely simple and common. The users need more concrete guidance and this should not be in the form of a treasure-hunt to expose the hidden instructions everywhere on the page.

**Comment by karlcz** [comment]
I think this should be made configurable (and eventually user-toggled if we ever do user display preferences).  But if it's just going to be ignored here, we should probably close it as wontfix.

**Comment by jrchudy** [comment]
Closing and moving this issue to wishlist.
