### ISSUE TITLE
Record edit

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#384]
Extend the data entry form to edit an existing record. The mode "new entry" vs "edit" can be inferred by the URL. If the fragment has a key filter then the data entry app should edit the identified record, if not, then it should be a new entry. The URL format should be the same as that used by the record app.

```
.../data-entry/#id/schema:table[/attribute=value[&attribute=value]*]
```

We should also look into making the URL parsing a reusable function of chaise or maybe even ermrestjs.

**Comment by howdyjessie** [comment]
Please see PR #397 for review.

**Comment by robes** [comment]
Worked for me
