### ISSUE TITLE
Markdown text entry and display

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#385]
We need to explore options for markup text entry and display. The text entry will apply to any data editing forms such as the `data-entry` app while the display will apply to just about any app. We need to evaluate markup formats, parsers, and finally editors, preferably WYSIWYG, and/or editors with preview. We also need to enumeration the requirements for formatting. I suggest that anyone, @hongsudt maybe in particular, add to this issue with required formatting.

**Comment by robes** [comment]
For one use case we need enough formatting to support display of Gene names. These require at least:
- superscript
- subscript
- italics

**Comment by hongsudt** [comment]
We have markdown rendering but we will delay the editor.
