### ISSUE TITLE
Record page login broken on globus_auth server

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#388]
Very recently (probably with https://github.com/informatics-isi-edu/chaise/commit/460935e449c7af1fc0e497619aaf62ebca28f7a0) login has stopped working on the record app.  It still works on search app.

It seems to be misdetecting the login mode as form based when there is really a redirect_url in the preauth response.

**Comment by karlcz** [comment]
Assigning to @shinyichen since I know she's looking at refactoring login stuff.  But also pinging @svoinea since I think his commit yesterday is probably what broke it...

**Comment by svoinea** [comment]
The /chaise/record/assets/javascripts/app.js should call a function equivalent to the current "function login(referrer)" from /chaise/scripts/ermrest.js.

The login form (../login?referrer=...) should be rendered only if the GET '/ermrest/authn/preauth' request returns an output having the 'login_form' field.
