### ISSUE TITLE
Inconsistent "display" column annotation behavior between Search and Record pages.

### ISSUE THREAD

**Issue by mikedarcy** [informatics-isi-edu/chaise#391]
The search page honors one type of "display" column annotation and the record page another.  

The search page uses the older style `description` tag with a JSON value of `{"display": "The display value"}`.

The record page uses the newer style `tag:misd.isi.edu,2015:display` tag with a JSON value of `{"name": "The display value"}`.

This requires the annotator to duplicate every column display annotation to cover both formats.  For table with many columns this is obviously an inconvenience and also negatively impacts performance, particularly on the client-side.

The documentation (https://github.com/informatics-isi-edu/chaise/blob/master/doc/annotation.md) on this is not clear and looks pretty out of date.

**Comment by robes** [comment]
you really won't like this... but i'd like to stop supporting both of these model renaming annotations. Neither have been implemented in the recordset app, and I'd like to keep it that way. I know this may not be agreeable wth you but I think this whole idea of renaming model elements was a bad idea from the start (might have been my idea). I would argue that all models should be updated in a way that is presentable, including case and white space. I would include the FaceBase model in this argument, changing tables like "mouse_gene" to "Mouse Gene" and so on. If you really need to have some model elements in an unpresentable scheme, the workaround would be to use the new ability to create views. You could create those with the names you want to have and use those in presentation. But I wouldn't advocate doing this, just put it out there as a way of getting around.

I feel pretty strongly about this...

**Comment by mikedarcy** [comment]
No, I don't like it. It makes it pretty onerous to support data models that have been defined elsewhere without altering them at the most fundamental level thereby ensuring that all subsequent data ingest will have to be ETL'ed.  I think it imposes a somewhat artificial limitation on what can be done with ERMrest and basically kicks a whole set of use cases to the curb.

I don't think the draconian "one-size-fits-all" approach is appropriate here.  I cannot think of another similar system that does not allow overriding column display labels, even if it does support nice heuristically determined defaults.

Creating views just to accomplish this just for the sake of display is absolutely overkill, especially if it is the only reason that one would have for creating the view.

The logic for doing this already exists in the code.  Its not complicated, it just needs to be cleaned up and unified.

**Comment by robes** [comment]
The search app should be updated to support the [newer form of the annotation](https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2015-display) to resolve this inconsistency.

For the latest applications, i.e., recordset, data-entry, they should use the new `displayname` attribute that has been added to the ermrestjs api via https://github.com/informatics-isi-edu/ermrestjs/issues/36. The `displayname` is determined also by using the newer form of the annotation, so they will be consistent.

**Comment by hongsudt** [comment]
@mikedarcy @robes I think we decided now to make any changes to the search app and roll this in to recordset. So maybe we can close this issue?

**Comment by mikedarcy** [comment]
Please do not close this yet. I would like to have one more (hopefully last) discussion about this before moving on.

**Comment by karlcz** [comment]
I think this should be closed wont-fix as we are planning to support the `2015:display`.`name` annotation going forward on new apps and there is no intention to change the legacy behavior of the search app. It will be replaced by an app that follows the new style.

**Comment by hongsudt** [comment]
I am closing this issue and put this on the chaise wiki.
