### ISSUE TITLE
Need fail-safe navigation link from table rows to record pages

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#396]
I feel that there needs to be a navigation link/handle for the row as a whole to always allow navigation to the related entity even if its key material is not displayed.

The key material may be hidden or replaced due to annotations, e.g. hiding serial keys or replacing a key with a download URL.  Or, if the row has a composite key formed from several columns that are also foreign keys to domain tables, I think each component of the key will be a different link to one such domain term. There won't be a link for the composite key!

It can be confusing if all available links are to other entities (via navigable foreign key material) rather than to the entity representing the row itself.

In the long run, this should appear and behave similarly on both related entity tables in the record app and on rows in the recordset app.

**Comment by karlcz** [comment]
I think this should be converted into a record2 and recordset requirement.  Any time we present a tabular result, the tables should offer a way to navigate to each row's record app no matter how the presentation has been tweaked or elided by annotations.

**Comment by hongsudt** [comment]
tag with wishlist and track in the wiki pages.
