### ISSUE TITLE
Search app stays on previous facet when changing to a new table

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#398]
This bug is mostly observed on GPCR that has several tables. 
To reproduce:

1) go to Targets search page
2) facet on an attribute, e.g. Class=B
3) Go to the top left and change to the construct table
4) facets stays on Class attribute that has no meaning in Constructs table

**Comment by svoinea** [comment]
Fixed through commit e13ac14b99b047648186c69cb498379c7d0a927c
Ready for review.

**Comment by bugacov** [comment]
this seems to be ok on prod. closing the issue
