### ISSUE TITLE
The "switch layout" buttons should be visible always rather than in dropdown control

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#4]
Right now, switch layout buttons appear in a drop down. We want these to be visible in a row and change state by toggling. See this for example:

http://store.apple.com/us/accessories/all-accessories/airport-wireless

Also, the label text should be turned into "tool tips". We do not want to have the labels in the buttons. Just little square buttons with icons.

**Comment by howdyjessie** [comment]
<img width="295" alt="screen shot 2015-08-21 at 4 09 55 pm" src="https://cloud.githubusercontent.com/assets/4585431/9420831/2a15f158-481f-11e5-9769-87a5bb9dee22.png">

@robes This is what I have. (see image) I don't see this toggle control in that Apple page you linked so I'm not 100% sure if this is what you wanted visually.

**Comment by robes** [comment]
right, that's exactly what we had in mind
