### ISSUE TITLE
Data-entry input consistent width styling

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#400]
Apply a consistent width styling to all input controls so they are the same column width.
- [x] Foreign-key drop down controls should not change widths when operated
- [x] Long text should only allow dragging of height and follow same width as other controls
- [x] If/when we have multiple record entry, behavior of columns and sizing should be sane

**Comment by howdyjessie** [comment]
The first 2 points have been addressed, but I'll save the third one after we implement multi-record entry.

**Comment by howdyjessie** [comment]
The third bullet point has been addressed in #415. A demo can be found [here](https://dev.isrd.isi.edu/chaise/data-entry/#1/public:form_test) to review this issue.
