### ISSUE TITLE
Data-edit show system-generated IDs

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#401]
For the fields that are replaced with "System generated value" in data-entry, show the actual existing value when in record editing mode. Keep it as an immutable field.

In the future, we need to invent a more subtle control for different contexts:

1. System generated may include things other than `serial` types due to triggers.  Need annotation to guide in general case?
2. Immutability may include things other than system-generated. A column might be "write-once" i.e. can be set during row insert but not modified later.
3. A field completely hidden during data-entry might need to be visible during data-edit or vice versa. Add sub-contexts `entry-new` and `entry-edit` to `ignore` annotation?

**Comment by howdyjessie** [comment]
This feature is now in my [user dir](https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/public:form_test/id=1). Since this was a relatively minor fix, the code has been pushed to `master` via commit ed977d54534b2d1e1d73507dfb9c519c72984b34.

**Comment by howdyjessie** [comment]
@karlcz Is it possible to add sub-contexts to sub-contexts? For points 2 and 3, I wonder if the annotations could be sub-contextualized via the HTTP verbs to avoid ambiguity and/or provide UI devs with a familiar system of sub-annotations. For example, column has the `ignore` annotation, which has the `entry` context, which can be further contextualized with `GET`, `POST`,  `PUT`, and `DELETE`. A "write-once" column could have a `POST` context of `true` but a `PUT` context of `false`.

**Comment by robes** [comment]
This is my counter proposal here. I would suggest we create two new Column annotations:

- `tag:...system-generated`: indicates that a column is system generate. The interpretation of this field would be to not allow user input during new record entry.
- `tag:...immutable`: indicates that a column is immutable (cannot be altered once defined). The interpretation of this field would be to not allow user input during existing record edit.

If used in combination, the interpretation would therefore be that you cannot enter or edit a value, which would be the case for a typical serial id.

Note that, the above annotations do not imply `hidden` for which we already have an annotation.

**Comment by robes** [comment]
Okay, now I'm actually reviewing the issue. I think there is a problem. The "Id" column is shown and it has a disabled text entry box, however, the text entry box is blank. I would expect it to have `1` in it and also to be disabled.

**Comment by howdyjessie** [comment]
@robes Hmmm I'm unable to reproduce that behavior. I went to this url: https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/public:form_test/id=23, and saw `23` in the Id column. Where did you see the blank text entry box?

**Comment by robes** [comment]
Now, that worked for me too. Seems okay then.
