### ISSUE TITLE
Add edit link from record pages

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#402]
Add a sensible edit button/link from record page to the new record-editing mode of the data-entry app.

**Comment by howdyjessie** [comment]
I made PR #439 for review and assigned @karlcz, @hongsudt, @robes for review.

**Comment by howdyjessie** [comment]
Updated PR #439 again. Please have a look when you can.

**Comment by hongsudt** [comment]
@karlcz can you please review this?

**Comment by karlcz** [comment]
@hongsudt I commented on the PR itself and think I am waiting for further revisions to review and test.

**Comment by howdyjessie** [comment]
@karlcz @robes @hongsudt PR #439 is ready for review again.

**Comment by hongsudt** [comment]
@howdyjessie PR #439 reported a conflict...

**Comment by karlcz** [comment]
@howdyjessie I commented on the PR again.

**Comment by karlcz** [comment]
I confirmed this is working in master and am closing this issue.
