### ISSUE TITLE
search app: allow different main entities to co-existing in the same schema

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#406]
On rbk-dev, there are 2 sets of tables---Protocol and Cell_Line. 
I set Protocol as a default. However, when I try to explicitly go to the search app with Cell_Line (or its related tables) as an argument, the app keeps spinning. The search seems to support only one main entity per schema. This needs to be changed.

**Comment by hongsudt** [comment]
@svoinea what's the status on this? What do I need to do to make them co-exist?

**Comment by svoinea** [comment]
On `rbk-dev`, I have:
 
  - "moved" the content of the `Resource2` schema under the `Resource` schema
  - dropped the `Resource2` schema
  - updated `schema_name='Resource' where schema_name='Resource2'` in the `_ermrest.model_table_annotation` and `_ermrest.model_column_annotation` tables

Seems to work w/o doing any code modifications.

**Comment by hongsudt** [comment]
I am closing this issue as it is no longer relevant.
