### ISSUE TITLE
search app: faceting based on a boolean column

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#407]
Cell_Line has a few boolean columns. When I click on those columns in order to specify the faceting criteria, nothing shows up under them.

**Comment by svoinea** [comment]
This should have been fixed now through the commit 8b590dd454614f82add813b8b4f0e6a22adc8949

**Comment by hongsudt** [comment]
@chiragsanghvi please help me review this fix on rbk-dev.
