### ISSUE TITLE
Record App: Second Related table header is distorted. 

### ISSUE THREAD

**Issue by chiragsanghvi** [informatics-isi-edu/chaise#410]
Visit any of the record page which has related tables. If you open the first related link with a row count of greater than 0, a table appears with data populated in it. Now if you open the second related link with the same row count criteria, the header of the table is distorted.

![rbk](https://cloud.githubusercontent.com/assets/1658152/15694209/99de1dba-2750-11e6-9004-4c109c822094.png)

Maybe this is a problem with the [jQuery.floatThead](http://mkoryak.github.io/floatThead/) plugin or we might have consumed it in wrong way.

Here's a [link](http://mkoryak.github.io/floatThead/examples/bootstrap3/) for using it with BootStrap3

**Comment by karlcz** [comment]
I think this is a duplicate of #149 right?
