### ISSUE TITLE
DISPLAY_ERROR is null on 500 error during login

### ISSUE THREAD

**Issue by mikedarcy** [informatics-isi-edu/chaise#414]
Using session-based basic auth, if a 500 is returned during the login sequence (e.g., due to a webauthn misconfiguration or db issue), somehow the JS execution scope gets altered in such a way that the DISPLAY_ERROR (and perhaps other) variable initialization done in initApplication of ermrest.js is invalidated.

This results in no error message being displayed and an null dereference error dumped to the console.

**Comment by svoinea** [comment]
This should have been fixed now through the commit a9dfee54aff68b23486d3cf34216909547acd98d

**Comment by mikedarcy** [comment]
Confirmed fixed.
