### ISSUE TITLE
Poor error handling and reporting

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#417]
The data entry app does not have very good error handling and has poor error message/reporting. I suggest also making a list of all the errors that need to be handled that you can brainstorm and make sure they are handled and they are reported clearly to the user.

**Comment by jrchudy** [comment]
Some work has been done on this. Check the latest commits to the `de-error-handling` branch.

**Comment by robes** [comment]
This looks like a good start. I think the error handling will have some complexity to it, so we should discuss next week.

**Comment by jrchudy** [comment]
Pull request #438 has the changes associated with this issue.

**Comment by robes** [comment]
If this is in a done state can you point me to a place where it is deployed and give suggestions for how to test it. Maybe an enumeration of test cases that should be handled by it.

**Comment by jrchudy** [comment]
If you go to my [synapse dev machine](https://synapse-dev.isrd.isi.edu/~jchudy/chaise/data-entry/#2/Zebrafish:Subject) you can test some of the functionality by inputting a catalog/schema/table that don't exist. Those should return not found exceptions and alert the user. 

Another note is the annotation not found error function. If you open developer tools, and then the console, you will see NotFoundErrors littering the console for annotations not being found. This is the case when we look to see if the vocab annotation or display annotation exist. Should we leave it this way or remove the logging for annotation not found?

**Comment by robes** [comment]
We don't need to log the annotation related not found errors. Those are expected.

**Comment by robes** [comment]
I tested with this URL using Firefox:

https://synapse-dev.isrd.isi.edu/~jchudy/chaise/data-entry/#2/Zebrafish:Fubar

It first did a modal dialog that was blank (see attached screenshot) then after I dismissed the blank dialog it proceeded to what I expected.
![badtable](https://cloud.githubusercontent.com/assets/4202842/15914557/bc435c34-2d96-11e6-8258-c553d36f125a.jpg)

**Comment by jrchudy** [comment]
I caught that and have since fixed it and pushed it to the branch, but I think I forgot to remove it from my dev machine. i.e. update the code

**Comment by jrchudy** [comment]
Additional issues were pointed out in PR #438. That pull request was merged, closing this issue.
