### ISSUE TITLE
Use common login/logout and navbar in data entry app

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#418]

**Comment by howdyjessie** [comment]
Please see PR #422 for review.

**Comment by robes** [comment]
The login works on the `data-entry` app but not the `recordset` app. On the latter, it takes you to the `chaise/login` page instead of to globus.

On both `data-entry` and `recordset` there is a little broken icon link on the top, to the left of the "Chaise" text.

**Comment by howdyjessie** [comment]
I've made a second PR. Please see #427 for review.
