### ISSUE TITLE
User Interface Style Guide: refine outline - flesh out sections

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#421]
Comment from Rob on previous issue #226 

> maybe we should approach the style guide a little more tactical. for instance, we have decided to use bootstrap so that encodes much of these style decision. what we need to know now is, which bootstrap container should we use -- i.e., use container vs container-fluid. should tables use the default (bootstrap) table style or should they use table-striped or table-bordered etc? and for fonts etc, i think that bootstrap mostly determines the basic font, we might just need some decisions about special cases where we deviate from the default font and which one to use.
> 
> secondly, i would say we should define our style guide in terms of the css classes to use and for those that need to extend bootstrap, our style guide should basically be a reference to the classes in our own custom chaise.css (or whatever).
> 
> and thirdly, then we need to pick a set of non-bootstrap 3rd party ui components, such as which dropdown control to use (e.g., angular-ui-selector or whatever its called).

There's more info on this wiki page - basically I'll narrow the scope and drill down to the actual elements we'll likely use: https://github.com/informatics-isi-edu/chaise/wiki/Towards-a-style-guide

**Comment by robes** [comment]
Right. The gist of my comment is that rather than invent a style guide, let’s just set a practice of adopting a set of styles and UI controls. And for example, in bootstrap a lot of the colors are determined for you (like the color of an warning etc). Let’s just use those and not fiddle with any of them. That’s my opinion at least…

**Comment by hongsudt** [comment]
It seems @crisaless has already generated one. @jrchudy Did you have a chance to move this to a wiki page?  Can you please put a link to this issue then close the issue?

**Comment by jrchudy** [comment]
The style guide has been copied over to this [link](https://github.com/informatics-isi-edu/chaise/wiki/Towards-a-style-guide).
