### ISSUE TITLE
Common login service

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#429]
Develop a common login service for Chaise. The login service should be a proper angular service. From what I understand it should support login, logout, and session interfaces. While you are at it, also please remove the `login`, `logout`, `session` interfaces from **ermrestjs**. The chaise login service should use the angular `$http` service for network operations. It will also need to get the server base url from the context or rootScope, however, we want to start doing this.

**Comment by robes** [comment]
While this is primarily focused on the data-entry app, try to retrofit recordset too if possible.

**Comment by robes** [comment]
Actually, the server base url may be in the chaise config object I suppose.

**Comment by shinyichen** [comment]
Just realized that this module will need to handle errors from server, like NotFoundError for session not found. We don't have those defined in Chaise (anymore).

**Comment by robes** [comment]
I think its okay to redefine those here. Like `LoginService.NotFound`. I would not reuse the ERMrest module errors in this context. My $0.02…
