### ISSUE TITLE
Provide more complete search results on search function

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#43]
Currently, we only can see matching attributes and have to drill down to see matching values.  Investigate if we can show both attribute and values on slideout during search

**Comment by carlkesselman** [comment]
We should spec out the behavior here.  In particular, search should be made consistent with the display heuristics in that if the table is normally included in the display, we should probably search it.

I'm also thinking we want to add a tier for the entity as well.  This would mean we get back a list of entityies, perhaps of different types, in which the substring matches.  I understand this gives us a multi-entity set, which we don't handle right now. However, if we had this addition, I think we end up with the equivalent of a google type search.  Type in a keyword, and you get back the entity/attrbitue/value in which there is a match.  Perhaps we should user test this and pull out as a seperate issue?

**Comment by robes** [comment]
Essentially resolved long time ago.
