### ISSUE TITLE
Basic documentation for data entry app

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#430]
We need to document:
- the features of this app and nuances about it. for example it the FK support is limited to single column FKs; we need that documented
- what annotations does it currently support; and any nuances about that
- what if any chaise-config parameters does it support
- what data types are support. for example in the columns.
- whatever else I may have missed?

**Comment by jrchudy** [comment]
@robes do you want this to be a readme.md document that is meant to be used as documentation for developers or a User Guide that is going to be used to understand the work flow of the application?

**Comment by robes** [comment]
Probably in between those, like administrators. People who are going to set up the app and need to know what annotations can be used with it.

**Comment by jrchudy** [comment]
So more of a dev ops setup sort of document. I understand. 

Where should this document live? Do we want a readme.md in the base folder of `data-entry` or should this be a wiki page?

**Comment by robes** [comment]
Should be a .md file either readme.md in data-entry (which should be renamed `recordedit` soon) or `recordedit.md` in the doc folder. Either way would make sense to me as long as all of the Chaise apps do it the same way.

On 6/16/16, 6:22 PM, "Josh Chudy" <notifications@github.com<mailto:notifications@github.com>> wrote:

readme.md in the base folder of data-entry

**Comment by jrchudy** [comment]
I added a `readme.md` doc to the `/recordedit` folder. Could @howdyjessie, @hongsudt, and @robes look at the file to see if I missed anything that is worth documenting? File can be seen [here](https://github.com/informatics-isi-edu/chaise/tree/master/recordedit) below the grid.

**Comment by howdyjessie** [comment]
I made a minor update to the document regarding ignore annotation contexts.
