### ISSUE TITLE
Support immutable and generated annotations

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#432]
Let's use these with the more explicit semantics in the recordedit app.
1. @robes should update ermrestjs to expose these as attributes on the column definition
2. then @howdyjessie should update the recordedit app

**Comment by hongsudt** [comment]
@robes @karlcz Do we need this for synapse?

**Comment by karlcz** [comment]
I don't need this in the short term as long as the ignore annotation w/ contexts works properly.

**Comment by karlcz** [comment]
How are these meant to interact with the newer Visible Columns annotation?  Do they override it?

**Comment by hongsudt** [comment]
From our discussion today, there should be a `.inputDisabled` attribute associated with a column in the Reference. This could be set to:
* `true` : do not allow user input 
* `false` : allow user input 
* `{message:"the message to show in place of the column value"}` : do not allow user input and the `message` should be shown in-place of the column value.  

Ermrestjs should handle those 2 annotations during contextualization: 
* When the context is `create`
  - if the column is `generated`, then `inputDisabled={message:"automatically generated by the server"}
* when the context is `update`
  - if the column is `generated`, then `inputDisabled=true`
  - if the column is `immutable`, then `inputDisabled=true`

**Comment by howdyjessie** [comment]
PR #679 has been merged
