### ISSUE TITLE
Check validity when duplicating last record

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#433]
When working in multi-row entry, the user can click "Add Record" to duplicate the most recently added row. If that row has an invalid value, however, that value is not copied into the duplicated row.

**Comment by hongsudt** [comment]
@karlcz @robes what do you think about complete duplication even when the cell values are invalid?  To me, this will make it easier for the users to understand the app behavior.

**Comment by robes** [comment]
I do not understand the description.

**Comment by howdyjessie** [comment]
@robes I made [a short video](http://recordit.co/BLipUTbPgN) to demonstrate. The duplicated row doesn't have the value from `C_smallint` while it does have the value from `C_int`.

**Comment by howdyjessie** [comment]
From today's standup: Only allow user to duplicate a form column if that form column has no invalid values. If that form column has 1+ invalid value, disable the "Add Record" button and/or display an alert.

**Comment by hongsudt** [comment]
I would prefer to get an error box telling me what to do than having the button disabled.

**Comment by howdyjessie** [comment]
There are now 2 buttons for adding a record to the form.
1. "Add Record" just adds a blank row/column.
2. "Duplicate Last Record" copies the last row/column if the last row/column has no invalid values. Otherwise, the app will display an error instead.

These two buttons should disambiguate what a singular "Add Record" would do.

You can see the feature live [here](https://dev.isrd.isi.edu/~jessie/chaise/data-entry/#1/public:form_test). This has already been push into `master`. [This commit](https://github.com/informatics-isi-edu/chaise/commit/06294b50946290e12e9ffd7a3e34effae8148f18) is the relevant diff to look at for code review.

**Comment by karlcz** [comment]
I don't understand why we would go from 1 to 2 buttons.  Where did this requirement come from?

**Comment by howdyjessie** [comment]
@karlcz I added the 2nd button of my own accord. This is not a strict requirement and is certainly up for debate.

**Comment by karlcz** [comment]
I don't like the extra buttons.  I think it makes it cluttered and confusing for a naive user.  Perhaps, if these could be reduced to idiomatic icons w/ a tooltip and better button placement, it might be OK.

Right now, the buttons compete for attention with the `Submit Data` button.  If they were instead down next to the form it might make sense:
- A `Copy` button (usually some kind of binary figure with arrow and small plus sign?) closely aligned with the record that will be copied and on the right, i.e. to the right corner while the `Remove` button is centered over the record.
- A `New` button (usually a plus sign?) as the right-most control just beyond the final column.
- Make sure there is some blank vertical space between the per-record controls and the overall page submit button.

**Comment by howdyjessie** [comment]
@karlcz How does this look? Does this reflect your description? The only caveat I'm seeing with the Remove button centered over the record is when the user starts working with multiple records and then the Remove and Copy buttons start melting together (see bottom-most screenshot). The buttons begin overlapping so icons are much more suitable here.

I'd like to use icons for the Remove and Copy buttons but I can't figure out why Bootstrap's copy icon won't show up, so I'm using text-only buttons for now. I feel I should move on to other issues first and return to this icon problem. At any rate, Bootstrap's "copy" icon looks like this: 
<img width="39" alt="screen shot 2016-06-14 at 3 51 16 pm" src="https://cloud.githubusercontent.com/assets/4585431/16062444/0197fdf2-3248-11e6-8c9d-ee6268b5a06e.png">
It doesn't scream "COPY" to me like similar icons do, but it should be serviceable when paired with an on-hover tooltip.

<img width="1440" alt="screen shot 2016-06-14 at 3 47 03 pm" src="https://cloud.githubusercontent.com/assets/4585431/16062336/4fccdc96-3247-11e6-88ae-2a81b12cfef1.png">
<img width="1440" alt="screen shot 2016-06-14 at 3 47 07 pm" src="https://cloud.githubusercontent.com/assets/4585431/16062342/58610d6e-3247-11e6-8651-5035e92a44aa.png">
<img width="1440" alt="screen shot 2016-06-14 at 3 46 33 pm" src="https://cloud.githubusercontent.com/assets/4585431/16062345/5de2d8d0-3247-11e6-9c13-fa1df688c91f.png">

**Comment by karlcz** [comment]
Oh, I wasn't even expecting to see a copy choice on every column but only on the last!  But this seems kind of interesting...

To address the crowding, another option would be to have a single "tools" sort of icon on each record that expands to have delete and clone options only when you click?

**Comment by howdyjessie** [comment]
@karlcz Oooohh well.. I'm sure eventually someone would've asked for a per-record Copy button. :) I like the "tools" icon idea a lot. A "settings" gear or a wrench icon should suffice?

**Comment by howdyjessie** [comment]
@karlcz @hongsudt It turns out the trash icon is blue in RBK viewer, sigh. I really believe it should be red. Anyway, how does this look?

<img width="1440" alt="screen shot 2016-06-14 at 6 41 01 pm" src="https://cloud.githubusercontent.com/assets/4585431/16065591/12356000-3261-11e6-9451-f63295c254d5.png">

**Comment by hongsudt** [comment]
This looks good to me..  One minor adjustment, can we move the submit data
button to be right aligned? So it is underneath the login?

**Comment by howdyjessie** [comment]
@hongsudt Sorry for the late reply; how's this? 
<img width="1430" alt="screen shot 2016-06-16 at 12 02 36 pm" src="https://cloud.githubusercontent.com/assets/4585431/16129623/4c62f22e-33ba-11e6-876b-5cadb1411256.png">

**Comment by howdyjessie** [comment]
I'm currently working on the related issue of making delete operations more modular by wrapping the confirmation modal tool in a directive, but I'd like to open a separate issue for it.

**Comment by hongsudt** [comment]
@howdyjessie this looks good to me.

**Comment by howdyjessie** [comment]
It seems like the review phase is done. Closing this issue now. Feel free to reopen this issue if anyone wants to add more comments.
