### ISSUE TITLE
data entry: update end-to-end test cases on the spreadsheet

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#434]
We should update the expected behavior of the data entry app in the excel sheet. 

https://docs.google.com/spreadsheets/d/1XdV4_MXEeycKKG8rhX_M5Bi4HSLKgtKzi3N7q7BUnTM/edit#gid=0

**Comment by jrchudy** [comment]
The spreadsheet has been updated with another sheet called `recordedit`. @robes, @howdyjessie, @hongsudt I added all three of you for review to see if I missed anything important.

**Comment by howdyjessie** [comment]
I added some more cases to the spreadsheet. This looks complete to me.

**Comment by jrchudy** [comment]
Thank you @howdyjessie, @hongsudt can you think of any other cases that need to be added? If not, I think we can close this issue.

**Comment by hongsudt** [comment]
yeah.. Let's close the issues..

Also, as you guys fix bugs or add features, please try to update the test
cases..  The spreadsheet is currently our documentation that describes our
system behavior.
