### ISSUE TITLE
Order the columns of the search result table based also on the facetOrder annotation

### ISSUE THREAD

**Issue by svoinea** [informatics-isi-edu/chaise#436]
Currently, the order of the columns displayed in the search result  table are based on the `top` annotation and the `score` computed from the number of the distinct values of the column.

The `facetOrder` annotation should have precedence relative to the two criteria mentioned above.

**Comment by svoinea** [comment]
The issue was fixed through the commit 7aace232d18e7e53dae7643158cf0b885eb067c7

**Comment by svoinea** [comment]
Assigning to @bugacov for review.

**Comment by karlcz** [comment]
Where is this requirement coming from?  This sounds wrong to me.

Why wouldn't we just show the results table in the natural table structure from the backend, like we do in other apps? I think that this should be the default unless another behavior is requested explicitly by annotation.

Also, I think it is a mistake to link facet-order in the filter sidebar with column order in the results presentation.  In general, I think dynamic reordering of results columns would be a bad UX even if we are using a dynamic strategy for the facet sidebar.  Each should have its own control, and at most there might be a fallback/syntactic sugar to allow one ordering list to be shared by both annotations.  (But, this fallback should not enable column reordering implicitly w/o any annotation.)

**Comment by svoinea** [comment]
The requirement came from @bugacov

**Comment by carlkesselman** [comment]
This sounds right to me.

I think in the GPCR case in fact, we have some very specific ordering we want on the columns, and these probably should be independent of the ordering on the facets.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Jun 8, 2016, at 10:31 AM, Karl Czajkowski <notifications@github.com<mailto:notifications@github.com>> wrote:

Where is this requirement coming from? This sounds wrong to me.

Why wouldn't we just show the results table in the natural table structure from the backend, like we do in other apps? I think that this should be the default unless another behavior is requested explicitly by annotation.

Also, I think it is a mistake to link facet-order in the filter sidebar with column order in the results presentation. In general, I think dynamic reordering of results columns would be a bad UX even if we are using a dynamic strategy for the facet sidebar. Each should have its own control, and at most there might be a fallback/syntactic sugar to allow one ordering list to be shared by both annotations. (But, this fallback should not enable column reordering implicitly w/o any annotation.)

**Comment by svoinea** [comment]
The changes were reverted and now there is the table annotation `top_columns` that contains an array with the columns to be present in the search result table. In this way, the order of the columns in the search result table is independent of the order of the columns in the filter sidebar.
