### ISSUE TITLE
Odd related entity column widths

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#440]
If you visit https://synapse-dev.isrd.isi.edu/chaise/record/#2/Synapse:Protocol/ID=PrcDsy20160101A (at least on Firefox) you'll see the related entity table for Protocol Step has a very wide column for `ID` and a very crowded and narrow column for `Description`.  I think this needs to do a better job of auto-sizing based on content and suspect that there is something wrong with the CSS...

**Comment by karlcz** [comment]
@robes @hongsudt I'm not sure whether to close this as wontfix or turn it into a record2 requirement that table layout be more sensible and responsive to its content...?

**Comment by hongsudt** [comment]
Mark this as wishlist and put it in the record 2 wiki page.
