### ISSUE TITLE
Chaise can get confused when ermrest redirects it to a login form

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#441]
When I do this:

1. Set up my system to use the webauthn database provider.
2. Configure my main ermrest catalog to require authentication.
3. Go to /chaise/search when I'm **not** logged in.

Then I get this:

![chaise search - google chrome_002](https://cloud.githubusercontent.com/assets/8785501/15913621/fd7e63d0-2d8f-11e6-8e13-8e5f019fdb2a.png)

I think what's happening is that Chaise is doing a GET /ermrest/catalog/1/schema HTTP/1.1, expecting a JSON object in return, and becoming confused when (after ermrest redirects it) it gets an HTML form instead.

This only happens when redirected by ermrest; if I click the Login button, I can log in, and subsequent requests work correctly.

**Comment by robes** [comment]
I don't think ermrest redirects the client to a login form. The js app itself should be getting back a 401 error and then redirecting. Maybe @svoinea can comment?

**Comment by ljpearlman** [comment]
Ummm, never mind. This was a product of my own weird setup.
