### ISSUE TITLE
data entry: ACL support

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#443]
Check whether users are allowed to edit or create an entry.  If not, we should throw an error message and direct them to the default page. Also, the edit button should not be shown on the record page. 

 @karlcz @robes  is there a way to check whether a user can create/edit an entry?

**Comment by robes** [comment]
`catalog/N/meta/content_write_user` returns the list of roles allow to write to a catalog. There is a `_read_` ACL as well. These indicate the catalog-wide read/write ACLs.

Beyond that, you need to reason over the postgres row level access control which … you can’t do that.

**Comment by hongsudt** [comment]
Since we need some time to design the ACL, I will defer this issue until we have a good solution. As a stop gap, we will use chaise config parameters to indicate to the apps whether to allow creation/edition/deletion. 
```
EnableRecordEdit = true
```
I don't think we need different params for create and delete. If editing is present, it should allow the rest. 
If the config param doesn't exist, treat it as false.

**Comment by howdyjessie** [comment]
@hongsudt The (temporary) fix for this issue has been included in PR #439.

**Comment by karlcz** [comment]
@hongsudt maybe this should move to back-log or be closed and a different issue opened for future work?
