### ISSUE TITLE
review annotation spec

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#446]
We will be working on a new version of record and search (i.e. recordset) apps. These apps will implement annotations as listed in the annotation doc:  https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md
Please review the document and identify missing features. A few of them have been identified including: 
* table order 
* column order and row order of the result set and facets 
* a mechanism to navigate from each row in the result set to a different table
* association tables to be used for faceting/filtering and/or search result 
* result list includes columns from related/associated tables

chaise
* fine-grain chaise config
  * on-demand result 
  * customized angular css/view (e.g. html "class" assignments) to change the table view. 
* unique keys/composite keys constraints

Others
* format string instead of {{name}} templates
* sql comment override? Chaise or Ermrest? 
* Table display annotation in addition to general display? 

![Uploading annotation.jpg…]()

**Comment by carlkesselman** [comment]
I would find this document a bit easier to read if we had a brief description of the purpose of each annotation in each section.

**Comment by hongsudt** [comment]
2016: visible columns and 2016: foreign keys have been added to the annotation document. Please review those two annotation spec. We will go with this unless anyone objects by wed.

**Comment by hongsudt** [comment]
I am closing this issue and put the content on the wiki instead.
