### ISSUE TITLE
Provide some kind of grouping mechanism in the additional facet selection popout

### ISSUE THREAD

**Issue by mikedarcy** [informatics-isi-edu/chaise#45]
When dealing with a large set of facets (e.g., hundreds) there are some usability issues in the facet selection pop-out.  Lack of a "grouping" mechanism is a big one.  Having an optional, collapsible header around facets at the entity level would be a big help here. This header could default to the currently annotated display value for the parent entity.

This would also help with the presentation of "duplicate" facet values in the selection pop-out, which can happen when more than one table entity has a column with the same name.  Simply annotating these duplicate column names differently (e.g., by prepending the table name) is less preferable than having a grouping mechanism that properly reflects the source entity.

This is also a very common UI feature in filter selection components of large-scale ecommerce sites.

**Comment by robes** [comment]
@hongsudt i suggest we see about scheduling this for the next sprint or moving this item to wishlist.

**Comment by mikedarcy** [comment]
This enhancement is badly needed for BDDS. Putting it off for a while longer is probably fine but closing it and sending it off to languish in the wishlist is not. We need to either implement it or come up with a reasonable alternative.

**Comment by robes** [comment]
@hongsudt okay, so let's see if it can be schedule for the next milestone then. it sounds generaly useful.

**Comment by hongsudt** [comment]
this should eventually be included in the recordset app.

**Comment by hongsudt** [comment]
track this on the recordset app feature.
