### ISSUE TITLE
Facet slide-out should be horizontally resizable

### ISSUE THREAD

**Issue by mikedarcy** [informatics-isi-edu/chaise#46]
It is possible to have column display name annotations that are much longer than the current fixed-width of the facet slide-out.  Instead of trying to wrap these strings to fit the width, it may be easier just to provide a horizontal resize function for the slide-out.  It should at initially at least persist the setting for the session, but ultimately persist across sessions.

**Comment by robes** [comment]
@hongsudt we should see if we can schedule for next sprint of move to wishlist

**Comment by hongsudt** [comment]
Maybe we can address this in recordset app.

**Comment by hongsudt** [comment]
closing this issue since we will be doing faceting differently in the recordset.
