### ISSUE TITLE
RecordEdit should show inserted records after submit

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#461]
The ERMrest entity POST operation responds with the actual records that were created, including server-generated keys when the client is using the `defaults` query parameter.

After submit, the data-entry app should go to a recordset page filtered by the new row keys.  Currently, it seems to go to an unfiltered page which is confusing, particularly once the new rows won't show on the first page of results.

**Comment by karlcz** [comment]
@hongsudt I think this improvement should be done soon as it affects usability for pilot projects.  I.e. I think it is a higher priority than the other new apps in the pipeline.

**Comment by hongsudt** [comment]
@jrchudy @howdyjessie one of you should take a look at this.

**Comment by karlcz** [comment]
BTW this feature will depend on the recordset feature to accept filters in the URL.  It exists but is a little buggy as described in #464

**Comment by howdyjessie** [comment]
>After submit, the data-entry app should go to a recordset page filtered by the new row keys. Currently, it seems to go to an unfiltered page which is confusing, particularly once the new rows won't show on the first page of results.

@robes, @jrchudy, and I have discussed this bit before but we landed on simply redirecting to the table, unfiltered, because recordset doesn't support `::leq::` and `::geq::` yet. (Are `::leq::` and `::geq::` even the right operators to use in this situation?)

**Comment by karlcz** [comment]
No, exact equality is the right operator.  It should be a disjunction of several keys, not a range.  (You cannot assume that server-generated keys are in contiguous and non-overlapping orders for multi-row insert...)

**Comment by howdyjessie** [comment]
It turns out recordset doesn't support disjunctive filters yet, so this issue depends on #465.

**Comment by hongsudt** [comment]
@shinyichen is this ready to be reviewed?

**Comment by hongsudt** [comment]
@karlcz I think this has been fixed, so I assigned you to review.

**Comment by karlcz** [comment]
I did a test on synapse-dev and doing a multi-insert still sends me to recordset without any filters so this is *not* done.

**Comment by howdyjessie** [comment]
Reassigned to @shinyichen.

**Comment by howdyjessie** [comment]
@karlcz I just tested and merged @shinyichen's PR #521, which should redirect properly now. Can you test on synapse-dev?

**Comment by karlcz** [comment]
works for me...
