### ISSUE TITLE
record2: show a tooltip if a table or column of the main entry has comment resource

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#463]
This tooltip should appear when moused over. The tooltip behavior/styling should be in the common module. Tooltips in all apps should have the same styling and bahavior. 

This is related to ermrestjs feature https://github.com/informatics-isi-edu/ermrestjs/issues/54

**Comment by jrchudy** [comment]
The tooltip properly shows if there is a comment on the column. This code is in PR #497. Assigning to @howdyjessie for review of code and functionality in the PR.

**Comment by howdyjessie** [comment]
PR #497 has been merged, closing this issue now.
