### ISSUE TITLE
Recordset handling of filters inconsistent in URL, permalink

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#464]
If I go to the URL https://synapse-dev.isrd.isi.edu/chaise/recordset/#2/Zebrafish:Subject/Issuer=Cza the filter predicate seems to be ignored.  The page shows unfiltered results and the Permalink lacks the predicate: https://synapse-dev.isrd.isi.edu/chaise/recordset/#2/Zebrafish:Subject

If I go to the URL https://synapse-dev.isrd.isi.edu/chaise/recordset/#2/Zebrafish:Subject/Issuer::eq::Cza the predicate seems to work partially. The page shows filtered results and the Permalink has a rewritten predicate: https://synapse-dev.isrd.isi.edu/chaise/recordset/#2/Zebrafish:Subject/Issuer=Cza

Of course, this rewritten URL is identical to the first one that doesn't actually work.  I think the URL parsing needs to be fixed to support the `=` operator.  I'm not sure if we should keep supporting `::eq::` as well...?

**Comment by hongsudt** [comment]
@shinyichen Do we still have this problem?

**Comment by karlcz** [comment]
I think this is fixed in master. It now supports `=` consistently in URL parsing and permalink, and no longer accepts `::eq::` at all.
