### ISSUE TITLE
Support disjunctive filters

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#465]
Currently the recordset app supports conjunctions but not disjunctions. The recordedit/data-entry app needs the disjunctive filters in order to display a recently submitted set of records. #461 has more related info.

**Comment by howdyjessie** [comment]
@hongsudt This issue needs to be completed before #461, which in turns should be completed soon [according to](https://github.com/informatics-isi-edu/chaise/issues/461#issuecomment-227520749) @karlcz.

**Comment by karlcz** [comment]
The ermrest disjunctive operator is `;` so I suggest we use the same syntax here to avoid confusion, i.e. `.../recordset/Schema:Table/Col=val1;Col=val2` with the same decoding logic as elsewhere:

1. Split the filter path on `/` to get a list of expressions which are to be conjoined
2. Split each expression on `;` to get a list of predicates which are to be disjoined
3. Split each predicate by looking for the `=` operator (or the `::` _opname_ `::` pattern for other supported operators)
4. URL decode the left-hand side column name and the right-hand side value

Of course encoding the permalink follows these steps in reverse, URL encoding each column name or value before gluing predicates and expressions back together.

**Comment by hongsudt** [comment]
@howdyjessie can you take on this task or does it have to be @shinyichen ?

**Comment by howdyjessie** [comment]
@hongsudt No I can do it too. :)

**Comment by hongsudt** [comment]
We decided at the meeting today that @howdyjessie will work on this.
