### ISSUE TITLE
Common library function for parsing URL fragments

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#466]
One of the things that should be refactored in Chaise and we can start on this with the record2 app, is to factor out the URL (fragment) parsing into the common library.

I also have a proposal on the table to write a parser in ermrestjs, something I’ve considered doing for a long time, so that we have one parser for URL fragments. See this and comments are welcomed.

https://github.com/informatics-isi-edu/ermrestjs/issues/55

As for Chaise, I still think it should have a common function for parsing URL fragments, even if its just a wrapper around this (to be developed) ermrestjs data path parser. For instance, there will be chaise specific options to be parsed. We should also keep in mind that each app may have some app specific options of its own, so a common library function need to accommodate that.

**Comment by robes** [comment]
This should also help to address issue #465.

**Comment by RFSH** [comment]
I noticed that we are using `window.location.origin` in the code that is used for URL parsing. 

Since [it is not supported by IE11- and has some issues with IE11](https://developer.mozilla.org/en-US/docs/Web/API/Window/location#Browser_compatibility), we should make sure that it is defined:

```javascript
//source: http://tosbourn.com/a-fix-for-window-location-origin-in-internet-explorer/
if (!window.location.origin) {
  window.location.origin = window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port: '');
}
```
