### ISSUE TITLE
Support for basic data entry

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#47]
Enhance the `chaise/record` app with ability to edit individual attributes in place. Should be able to pick or enter values from a data type appropriate entry control (e.g., a date picker for date fields).

**Comment by robes** [comment]
@carlkesselman @karlcz : I think we have a clear idea of what we want in the first 2 bullets of this task. However, we haven't defined clearly what we want for the last 2 bullets. I'm thinking for the mid-october milestone, we probably can only aim for the first 2 items anyway. We should think about what we want here.

**Comment by carlkesselman** [comment]
Perhaps we should break this into two issues to deal with the simpler edit case first.  I think this will depend on the versioning spec too...

**Comment by robes** [comment]
Yes. I should split this into at about 4 tasks based on the high level bullets.

**Comment by carlkesselman** [comment]
Is this still a valid issue?

**Comment by robes** [comment]
no, let's revise this in a new issue. context here was something different.
