### ISSUE TITLE
record 2: display record columns in the right order

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#471]
- [x] order : This is related to https://github.com/informatics-isi-edu/ermrestjs/issues/51
- [x] display name : https://github.com/informatics-isi-edu/ermrestjs/issues/60
- [ ] ~~whether to display a column with null value : https://github.com/informatics-isi-edu/ermrestjs/issues/53~~ See #474

**Comment by hongsudt** [comment]
Record2 should display the columns in the order stored in the Reference._columns.

**Comment by howdyjessie** [comment]
This issue is under review at PR #534.

**Comment by howdyjessie** [comment]
Since the PR has been merged, I'm closing this issue.
