### ISSUE TITLE
recordset, round 1: basic annotation

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#473]
**Resultset**
- [x] Display row name (a.k.a, title):
  * Annotation: `tag:isrd.isi.edu,2016:table-display` `row_name` 
  * Implementation: ermrestjs`Tuple.displayname`
- [x] Display record table name:
  * Annotation: `tag:misd.isi.edu,2015:display` `name`
  * Implementation: ermrestjs `Table.displayname`
- [x] Show the correct column name 
  * Annotation: `tag:misd.isi.edu,2015:display` `name`
  * Implementation: ermrestjs `Column.displayname`
- [x] Display record columns in the right order and correctly
  * This doesn't need to be specifically handled because the column order from schema is maintained. 
- [x] Show the right presentation depending on the column type (common code or ermrestjs)
  * Annotation: `tag:isrd.isi.edu,2016:table-display` `row_markdown_pattern`
  * Implementation: ermrestjs `Reference.display` and `Page.content`
- [x] Show a tooltip if a table or column of the main entity has a ~~tooltip annotation~~ comment resource. The tooltip should appear when moused over.

**Comment by shinyichen** [comment]
Besides the tooltip, is the rest already covered by contextualization?
