### ISSUE TITLE
record 2: handle whether to display null value 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#474]
If the null annotation/configuration exist, do not display null value columns on the page.

**Comment by karlcz** [comment]
This will actually be something like a "sparse" annotation to say we want to prune out nulls.

**Comment by karlcz** [comment]
This is drafted in the ermrest/master  user-doc/annotation.md as the `show_nulls` field in 2015:display

**Comment by hongsudt** [comment]
This issue is dependent on informatics-isi-edu/ermrestjs#152.

**Comment by hongsudt** [comment]
This will be handled in #519. So I am closing this issue now.
