### ISSUE TITLE
a common service to support permanent link

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#476]
We should factor out the permalink as a common library service. Probably also as a directive that we use in our apps. As we move toward a more modular design of our applications, we may have multiple components that need to influence what goes into the permalink. For instance, let's say we have a record app with nested tables in it. Let's say the nested tables have the option to transpose (this is just a hypothetical because we may not implement this again). If we want to capture the state of the nested table, whether it is transposed or not, in the permalink, then potentially each one of those nested table components will need to influence what goes into the permalink. However, they do not directly control the permalink nor should they override the permalink nor should they have to understand anything about the other components that may be on the same page with them. What I have in mind is an interface (could be a function on a service provider, or could be an event in a pub/sub approach) that lets components contribute to the permalink and a common permalink service that accepts these inputs and can compose a permalink from them.

**Comment by karlcz** [comment]
I think we should try to separate the back-end concepts from front-end concepts here.  E.g. there is no concept of "transpose" in ERMrest nor ermrestjs.

1. Have a core fragment ID structure that maps to ermrestjs/ERMrest concepts
  - Catalog ID
  - Entity path which can have links and filters in general case
  - Optional sort modifier
  - Optional paging modifier and limit parameter for page size
2. Add presentation-only state as additional "query parameters" on fragment ID
  - Status of sidebar/toggles

URL parts:
- App: `/chaise/foo/`
- Core fragment: `#1/datapath@sort(...)@after(...)?limit=N`
- App params: `&sidebar=1&...`

The idea would be that ermrestjs can parse the core fragment ID and the "syntax tree" is comprised of ermrestjs objects representing catalog and data access interfaces.  They should be able to reserialize their configuration back to a new core fragment ID.  We might have to refine the ermrestjs API if there aren't objects/states to represent everything we need to capture here.

There should be nothing here that cannot map down to an actual ERMrest resource that can be fetched and/or introspected. Some apps may raise an error if the returned "syntax tree" is too complicated for them to understand, i.e. record-edit can only operate on a base table w/ or w/o a key constraint.  It cannot handle partial constraints nor linked data paths.

The query parameters can include extra stuff that only the app knows how to interpret.

**Comment by robes** [comment]
Thinking about my original proposal, I realized that this is not just about the permalink but also about the window location itself. We might identify multiple aspects as:

1. presentation of the permalink (a _permalink directive_ and or _service_)
2. interface to the `window.location` (a new and improved _location service_)
3. coordinating updates to the location (a _location coordinator service_?)
4. and of course the fragment parsing that @karlcz goes into detail about above, and we also have discussion of this in #466 and an ermrestjs issue

A loose sketch of how these come together:
- Application state (or component state) changes
- If the state change is relevant to the location, it should be able to make this known (I'm being intentionally non-prescriptive about mechanism and implementation)
- In fact, it may not be up to the application or the component to make the decision about whether its state change is _relevant to the location_, perhaps that decision logic should be encapsulated elsewhere
- This is where a _location coordinator_ (for lack of a more creative term) can come in, this coordinator decides how to combine the various inputs (states) of the app and its components
- When it decides what the location should be, it updates the _location service_. This new and improved _location service_ will not mangle the URL like the angular `$location` service does.
- The _location service_ updates the actual `window.location` (which may be the `apply` or `replace` modes, the actual mode will be decided by the _location coordinator_)
- The _permalink directive_ will watch the (unmangled) _location_ and reflect it in the presentation.

As for the _location service_, we may want to take a look at the _$location_ service that angular provides. The interface of $location might be fine, since the only problem we really have with it, is that it mangles URLs by encoding and decoding them badly. We might want to copy its interface and essentially develop (and register) a replacement $location of our own implementation. This replacement $location could then also be used by other angular components that depend on $location. That would be a side benefit of that approach. Finally, we could possibly reuse some of the angular $location service using the composition pattern of inheritance (https://en.wikipedia.org/wiki/Composition_over_inheritance).

**Comment by hongsudt** [comment]
The information to create app-specific permalinks can be retrieved by the location object in Reference. So I am closing this issue.
