### ISSUE TITLE
viewer: change the tag glyph to a different symbol 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#482]
If the tag is scaled down as an image is zoomed out, maybe we don't need to do anything with this.  Otherwise, Jill just needs a different glyph that maybe less opaque.

**Comment by howdyjessie** [comment]
Mei has put in a fix that makes the tag smaller and more transparent so we're putting this issue in backlog for now.

**Comment by hongsudt** [comment]
duplicate with #457. 

Will close this issue for now and reopen if Jill insists after seeing the new release.
