### ISSUE TITLE
record app requires authentication even when ermrest is configured for anonymous access

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#484]
In the facebase case, access is anonymous but when trying to access a record from the records set, it asks for authentication, when it shouldn't require authentication since ermrest is configured for anonymous access.

For example, try to access the first item from this results set
https://dev.isrd.isi.edu/chaise/search/#1/legacy:dataset?facets=(dataset_organism:organism::eq::Mouse)&layout=list&page=1

**Comment by shinyichen** [comment]
Fix is in pull request #486
