### ISSUE TITLE
Make our AJAX app crawlable

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#49]
For background on this issue see:
https://developers.google.com/webmasters/ajax-crawling/docs/learn-more

This may be a challenge, but if our app is not crawlable then our sites will be hidden from much of the web. The suggestions in the google link do not provide much comfort. We need to evaluate the issue and propose some solutions first.

Not sure who wants to take this on: @svoinea @howdyjessie @crisaless

**Comment by robes** [comment]
@karlcz adding karl to the discussion because we may need to think broadly about this issue (i.e., it may not just be a client-side chaise issue).

**Comment by howdyjessie** [comment]
This might not be an issue according to [this link](http://searchengineland.com/google-may-discontinue-ajax-crawlable-guidelines-216119), which says that Googlebot should be able to render the full page.

**Comment by robes** [comment]
That could be good news. We should look into Google’s Webmaster Tools to understand how Google renders our app.

http://googlewebmastercentral.blogspot.no/2014/05/understanding-web-pages-better.html

**Comment by karlcz** [comment]
If I search google with stuff found on the default data browser page
of results, it serves it as the first result:

  facebase investigator steve potter

However, I don't think we're following linked-data practices very well
so the crawler has nowhere to go after that page of 25 results. I
don't think a crawler will press arbitrary buttons in a UI.  I think
that the page needs links that can be followed to reach related
search result views, page through results, etc.


karl

**Comment by karlcz** [comment]
This is related to #1 since we need to have individual document URLs that show meaningful pages of stuff that the search engine can index.

We also need to think about how to present many such URLs so they are discoverable by the crawler, e.g. in a site-map and/or as related content links embedded in each data browser screen.

**Comment by robes** [comment]
@hongsudt this is important for driving traffic to facebase, but it might have to move to wishlist.

**Comment by robes** [comment]
We can have a student do this, I think. Assuming this information is still current (and we could find out at google's instructions for web masters):

http://blog.woorank.com/2014/05/how-to-create-a-robots-txt-file-with-sitemap-location/

Essentially we just need a student to create a sitemap app that dynamically generates a sitemap when a crawler hits it. I suppose this might be more efficient if ERMrest did it so that it was served up only when it changes.

**Comment by robes** [comment]
Based on our most recent conversation, we have decided that having a dynamically updated sitemap is not necessary and maybe not possible anyway. What we need is to generate a static site map from a script that can be rerun on some schedule and/or manually. This will probably be a 10 line bash script. It should take the following parameters:

* `URL`: the URL of the ermrest catalog, e.g., `https://www.facebase.org/ermrest/catalog/1`
* `schemaName`: the name of the schema to target, e.g., `legacy`
* `tableName`: the name of the table to target, e.g., `dataset`
* `keyColumn`: the name of the column to retrieve data from, e.g., `id`

We suggest using the EMRrest _ATTRIBUTE_ interface and request the CSV content type for just the key column of the table. We also think we can start by assuming the table has a single key column (not a composite key made of multiple columns).

**Comment by jrchudy** [comment]
The script for generating a sitemap has been added to the chaise application inside the sitemap/ folder at the root of the project. There is a readme in there explaining the nuances of the script and how to apply that to other applications in the future.

The next step would be to take the script and add it to our recipe for the chaise application and generating the robots.txt file in that recipe.

**Comment by robes** [comment]
Let's take the defaults out. Actually that forces this script to only generate a sitemap for facebase. So this line:

https://github.com/informatics-isi-edu/chaise/blob/master/sitemap/generate-sitemap.sh#L19

should be replaced with:

```
record_urls ${1} ${2} ${3} ${4} ${5} ${6}
```

leave the `> sitemap.txt` off and let the caller simply redirect.

For the readme, similarly remove the note on defaults and replace with and example of using the script in a code block.

**Comment by jrchudy** [comment]
I modified the script to take in 6 arguments per @robes's suggestion. When running the script, the user needs to specify the file to output stdout to. The readme has been updated to reflect this as well.

**Comment by robes** [comment]
i made one minor fix, to include the trailing `/` here `...record/#...`
