### ISSUE TITLE
Usability problem in recordedit column ignore behavior?

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#491]
When a column is marked to `ignore` only in edit context, it is completely hidden on the record-edit page. For my use case, the non-editable fields are often identifying information that cannot be changed for the record. Having this information hidden makes the whole edit UX confusing/risky as there is no obvious display showing what record is being edited!

I would have assumed that this app would consider both the `detailed` context and `edit` context, and cover three cases:
1. No applicable ignore context: show current value and make it editable
2. Only `entry` / `edit` ignore context: show current value but no edit controls for this field
3. Both `entry` / `edit` and `detailed` context: completely hide column

The `detailed` context applies to the mode where a current record is being edited. For the mode where new records are created, I think the current behavior is correct in only considering the `entry` / `create` contexts.

**Comment by hongsudt** [comment]
This is no longer applicable.
