### ISSUE TITLE
Editing record shows alert "Column 0 not found in table"

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#494]
I tried to go to the record editing page for an existing record:

https://dev.isrd.isi.edu/chaise/recordedit/#1/legacy:dataset/id=263

And see a fatal error with alert: "Column 0 not found in table".

**Comment by jrchudy** [comment]
It was an issue associated with the parse function and not changes a piece of code in the viewer app to use that structure. This can be tested [here](https://dev.isrd.isi.edu/~jchudy/chaise/recordedit/#1/legacy:dataset/id=263). Changes are in [this commit](https://github.com/informatics-isi-edu/chaise/commit/48299b8252561073452c394bfe1e41617860ac72).

Assigning back to @karlcz to make sure it is fixed.

**Comment by karlcz** [comment]
Heh, I see that this now works and stops on the next alert about record editing being disabled. What a bunch of party-poopers.
