### ISSUE TITLE
Recordedit shows existing null date as epoch zero (1969-12-31) instead of blank

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#498]
When using recordedit to edit records that have optional date columns, an existing null date field is displayed as  "0 seconds from unix epoch" date value, e.g. `1969-12-31` instead of showing a blank value.

If the user doesn't notice this and submits a revision, the null will get replaced with that bogus value instead of remaining null as before.

- Description updated 2016-08-02 after re-testing chaise/master

**Comment by karlcz** [comment]
I'm not sure if I made a mistake observing this, or if a fix was done already.  I now see that I can delete the date field and hit submit and end up with a NULL value in ERMrest as desired.

However, on reopening the record with recordedit, it again *displays* the "0 seconds from unix epoch" date value `1969-12-31` instead of showing a blank/null value.  This will then submit bad data the next time if I don't manually clear it again.

Should I open a separate issue for this or just revise this issue description?

**Comment by howdyjessie** [comment]
@karlcz I'm not aware intentional efforts to fix this bug, but seeing as there's no commit activity associated with this issue, a revision of the description should suffice.

**Comment by hongsudt** [comment]
@chiragsanghvi can you take a look at this?

**Comment by karlcz** [comment]
I confirmed that the null date is now preserved in the entry field when opening an existing record to edit it.
