### ISSUE TITLE
Internet Explorer broken image bug + other tweaks

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#499]
IE shows a broken image for the empty image tag in the header. A couple of other issues showed up in the debugger which doesn't seem to break anything but are easy fixes.
- [ ] Image tag in header is empty unless the config adds a logo file - most browsers ignore it but IE shows an empty image which looks ugly
- [ ] IE shows border around empty image tag
- [ ] Fix non-closing <span> tag for the "Clear All Filters" chiclet

**Comment by hongsudt** [comment]
I am assuming that this is the old search. Since we plan to roll out the new search app, I am closing this issue.
