### ISSUE TITLE
Include attributes, from related entities, in the search results views

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#5]
Currently, the search results views only display data coming from the target table type (e.g., the one selected "search within" XYZ table). The search results views should include additional attributes from related entities. I.e., searching on table A, it should be able to display attributes that are also in table B, if table B and A are related by a foreign key reference.

More specifically:
* use annotations to determine what, if any, attributes should be included in the results view by default;
* and allow the user to add/remove attributes from the views.

**Comment by karlcz** [comment]
Is this idea obsoleted by using views instead?  I.e. we really want a way to link a view definition to a table so that chaise can present the modified ermrest view instead of the raw storage table?

**Comment by robes** [comment]
yes, i think so
