### ISSUE TITLE
When adding a row/column to the form for boolean fields, the most recently added row/column should be duplicated and appended to the form. 

### ISSUE THREAD

**Issue by chiragsanghvi** [informatics-isi-edu/chaise#502]
@howdyjessie @jrchudy 

This doesn't works for boolean field if you select an empty value in the first column and then duplicate it.

For example, if you select an **empty** value for the boolean field `is luxurious` for a record and then duplicate it, you will find **false** set for the `is luxurious` field for the second row.

![data entry app](https://cloud.githubusercontent.com/assets/1658152/16819972/a942a468-4903-11e6-81a7-1e57637024d6.png)

**Comment by karlcz** [comment]
I confirmed that the new row copies the previous record's boolean state properly now.
