### ISSUE TITLE
Recordedit sets Boolean fields as "" instead of null.

### ISSUE THREAD

**Issue by chiragsanghvi** [informatics-isi-edu/chaise#503]
@jrchudy @robes @howdyjessie 

**Scenario**: 

1. Open  this [RecordAdd](https://dev.isrd.isi.edu/chaise/recordedit/#1337/product:accommodation) page.
2. Open browser console and run following script to enable edit
```javascript
$('.modal').remove(), $('.modal-backdrop').remove(), $('body').removeClass('modal-open');
```
2. Open the boolean dropdown which is not mandatory
3. Select the empty("") option
4. Fill all other required fields
5. Press Submit Data.

When you select the empty value for a boolean field explicitly from the dropdown, you end up getting Ermrest API error. If you don't select anything from the dropdown it works fine.

The JSON request is
```javascript
[
  {
    "title": "some title",
    "website": "https://www.google.com",
    "category": "Hotel",
    "rating": 2.5,
    "summary": "Some summary",
    "description": "Some description",
    "no_of_rooms": 119,
    "opened_on": "2016-07-13T07:00:00.000Z",
    "luxurious": ""    // this is not valid as it should send null 
  }
]
```

You get following error for above request
```
400 Bad Request
The request is malformed. Bad JSON array input. ERROR:  invalid input syntax for type boolean: ""
```

**Comment by karlcz** [comment]
See also #498 as I think there is a more general problem with nulls getting turned into some other empty/zero value

**Comment by hongsudt** [comment]
@chiragsanghvi can you look into this as well?

**Comment by chiragsanghvi** [comment]
Yes sure

**Comment by karlcz** [comment]
I confirmed that the boolean case works as expected now, sending a null to ermrest when the blank boolean value is chosen.
