### ISSUE TITLE
User override to order the facets

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#51]
In the facet selector, the listing is somewhat random or based on some internal implementation state. Users would like that ability to have a specific attribute type (e.g., organism) appear as the 1st facet in the list, followed by some other attribute (e.g., data type) appears as the 2nd facet in the list and so on.

We should have an annotation that lets the user say exactly what order an attribute appears in the facet control. When the order is not specified the UI can pick the order based on other heuristics.

**Comment by svoinea** [comment]
Defined the column annotation "facetOrder".
Example of setting "organism" as 1st facet and "data type" as 2nd facet:

insert into model_column_annotation values('legacy', 'dataset_organism', 'organism', 'facetOrder', to_json(1));
insert into model_column_annotation values('legacy', 'dataset_data_type', 'data_type', 'facetOrder', to_json(2));

**Comment by carlkesselman** [comment]
Have we added this to the documentation?

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl

From: svoinea
Reply-To: informatics-isi-edu/chaise
Date: Wednesday, September 9, 2015 at 6:28 PM
To: informatics-isi-edu/chaise
Subject: Re: [chaise] User override to order the facets (#51)


Defined the column annotation "facetOrder".
Example of setting "organism" as 1st facet and "data type" as 2nd facet:

insert into model_column_annotation values('legacy', 'dataset_organism', 'organism', 'facetOrder', to_json(1));
insert into model_column_annotation values('legacy', 'dataset_data_type', 'data_type', 'facetOrder', to_json(2));

**Comment by robes** [comment]
And you might also give an example of how to set this annotation using the rest interface rather than the underlying SQL statements.

**Comment by carlkesselman** [comment]
Yes.

**Comment by carlkesselman** [comment]
Actually, I don't see any examples in the documentation.
