### ISSUE TITLE
dev.isrd static home page that contains links to chaise apps

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#511]
@jrchudy can you fill in the url for the rest of the app 
- [ ] search: https://dev.isrd.isi.edu/chaise/search
- [ ] record: https://dev.isrd.isi.edu/chaise/record/#1/legacy:dataset/id=269
- [ ] record2: https://dev.isrd.isi.edu/chaise/record-two/#1/legacy:dataset/id=269
- [ ] recordedit: https://synapse-dev.isrd.isi.edu/chaise/recordedit/#2/Zebrafish:Subject
- [ ] recordset: https://dev.isrd.isi.edu/~jchudy/chaise/recordset/#1/legacy:dataset/id::gt::100&id::lt::13000@sort(summary)
- [ ] viewer: https://dev.rebuildingakidney.org/chaise/viewer/#1/rbk:image/id=46

**Comment by jrchudy** [comment]
Some caveats:
**Viewer**
If you navigate to https://dev.rebuildingakidney.org/chaise/search, you can pick any of the records that appear in search and they should redirect to `viewer`. If you are feeling curious, https://dev.rebuildingakidney.org/chaise/viewer/#1/rbk:image/id=1, has a large amount of annotations from testing and will probably have the best set of data for the latest search features and showing/hiding annotations.

**Recordedit**
https://dev.isrd.isi.edu/chaise/recordedit/#1/public:form_test should work and I am certain that is the most up to date code for `recordedit`. But the chaise config parameter `editRecord` must be set to false for that deployment, so you only get a popup notification that returns the user to the landing page for that project. 

@karlcz, is `synapse-dev` running hourly updates? If so then the link provided above should be sufficient.

**Record & Record-two**
The link to search above can be used to navigate to any `record` page. If you want to see that same record in `record-two`, you just need to change the url to include record-two instead. Currently nothing links directly to `record-two`.

**Comment by crisaless** [comment]
Initial landing page is up: https://dev.isrd.isi.edu/

FYI, this design is based on the design for the public ISRD site that will someday go live - the sidebar is for navigation - it could be empty for this page, but I added a few common ISRD dev links (GitHub, Slack, etc). Open to suggestions for what could go there or just leave it empty.

**Comment by jrchudy** [comment]
Sorry @crisaless, one of the links was to my private dev folder. The one for recordset. Use this one instead:
https://dev.isrd.isi.edu/chaise/recordset/#1/legacy:dataset/id::gt::100&id::lt::13000@sort(summary)

It's just omitting the `/~jchudy` part. 

I think a note for the viewer should be mentioned on that page. When you go to viewer, nothing shows up because your session isn't automatically grabbed for you. So for viewer, you would need to navigate to https://dev.rebuildingakidney.org/chaise/search and log in first.

**Comment by crisaless** [comment]
The latest version is up - I added various notes from this issue. I also added indicators when the link takes you to another project's site but it may not be clear enough, just let me know.

**Comment by hongsudt** [comment]
The static page looks good. I am closing the issue.
