### ISSUE TITLE
Recordset shows no results

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#515]
Recordset on our CI servers is showing a blank page when it should be showing results.

E.g.  https://dev.isrd.isi.edu/chaise/recordset/#1/legacy:dataset

**Comment by jrchudy** [comment]
When I navigate to the following address: https://dev.isrd.isi.edu/chaise/recordset/#1/legacy:dataset/id::gt::100&id::lt::13000@sort(summary)
data does appear for me properly. This must be linked to there be no filters defined.

**Comment by chiragsanghvi** [comment]
@hongsudt @karlcz  You can test the fix [here](https://dev.isrd.isi.edu/~chirag/chaise/recordset/#1/legacy:dataset)

**Comment by jrchudy** [comment]
Closing this issue.
