### ISSUE TITLE
by default, display related entity in a tabular format

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#517]
- [x] use styling similar to record table at top of page
- [x] row count next to related table displayname
- [x] accordion click for tables

**Comment by karlcz** [comment]
Why does this say "by default"?  I thought tabular display is the *only* way we're going to do it?

**Comment by jrchudy** [comment]
It was discussed that these displays are going to be tabular displays but can be changed to other sorts of charts or graphs.

**Comment by jrchudy** [comment]
PR #527 addresses this issue.
