### ISSUE TITLE
search: support markdown column type

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#522]
I have added a customed column type "markdown" to dev.isrd and rbk-dev. Upon going to the search page "Protocol" which uses a markdown column type, the search throws an error for "type not found".

**Comment by svoinea** [comment]
Fixed through commit e6461880ce43289aaa819339de66bcc7fcbfd5ec

**Comment by hongsudt** [comment]
@svoinea any unknown type should be treated as text instead of throw an error.. Is this the case now?

**Comment by hongsudt** [comment]
This is now working on rbk-dev. Will close.
