### ISSUE TITLE
Recordedit doesn't validate foreign key fields for not-null prior to submission

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#525]
On columns with nullok=false, an actual ERMrest 409 Conflict error is shown when submitting a form that has a foreign-key based dropdown field left unset.  Other columns like date fields seem to be caught earlier by pre-validation and do not include an ERMrest error message.

Since the ERMrest error is pretty ugly, I think we should consistently pre-validate and give a simpler error for all nullok=false columns.

**Comment by hongsudt** [comment]
This problem still exists.

**Comment by karlcz** [comment]
Is this a duplicate of #500 or is that different?

**Comment by jrchudy** [comment]
This issue has been fixed. The changes were pushed to the `recordedit2-master` branch. Closing this issue.
