### ISSUE TITLE
end-to-end test skeleton for record 2

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#536]
Some old multi-fcs files referred to construct id or biomass id that do not exist in our database. For these, we should just mark them as won't fix instead of keep trying.

**Comment by chiragsanghvi** [comment]
@hongsudt isn't this a duplicate of #533  ?

**Comment by hongsudt** [comment]
That's wierd. I didn't see that task under in-progrss that's why I generated it.. Ok. Will close this now.
