### ISSUE TITLE
common module for dealing with default catalog and table

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#537]
We should have a Chaise common module, defined as an Angular service, that converts the _Chaise URL_ into the appropriate _ERMrest URL_.

It should determine whether to use a default catalog/table or throw an error. Here are possible urls: 
* `chaise/app-name` (e.g. no catalog is specified) : throws an error if 
  * default catalog is not specified in the chaise config
  * default table is not specified in the chaise config
* `chaise/app-name/#<catalog#>` (e.g., no `[schema:]table` is specified: throws an error if 
  * default table is not specified in the chaise config

All apps should handle these errors the same way. However, if it is a valid url (no error thrown), the behavior will be dependent on the app e.g. for record 2, it should pop up a message and direct the app to the recordset or search page.  

Note that `ERMrest.resolve(url)` will do the parsing, validation, and error checking for the ERMrest URL. We should keep these two functions separate and let the application call one after the other. Let's assume this hypothetical function is called `c2eURL(chaiseURL)`.

```javascript
// ...maybe in the run block of an application
try {
    var ermrestURL = c2eURL(window.location);
    ERMrest.resolve(ermrestURL).then( ...
    );
}
catch (e) {
    // ...check error, could be error thrown from the c2eURL function
}
```

**Comment by jrchudy** [comment]
PR #548 merged. Closing this issue.
