### ISSUE TITLE
add simple support for dropdown menus on navbar

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#543]
This should be done for the following apps: 
- [x] search 
- [x] common navbar
- [x] record

We could start with 2 drop-down list:
* search 
* create

Within each drop-down list will be deployment specific configuration that links to specific tables.

**Comment by hongsudt** [comment]
From the lunch discussion, we decided to use a json object to config the navbar menu options: 
```
navbar-menu = [ 
  { "menu1" = [ 
      {"caption" = "Experiment", "url" = "chaise/search/#1/experiments:Experiment"},
      {"caption" = "Sample", "url" = "chaise/search/#1/experiments:Sample"},
      {"sub-menu" = [         ] }  
    ]
  },
 ...  
]
```

**Comment by robes** [comment]
Shouldn't the navbar be configured per catalog rather than "deployment specific"?

**Comment by hongsudt** [comment]
From a user' s perspective, I don't think I would care where the data is from, as long as it is navigable. Also I expect navbar/menu to be fixed. I think changing the menu options based on the catalog will cause confusion as the catalog concept is hidden to the users.

**Comment by svoinea** [comment]
Added support for the dropdown menus on the navbar in the search page through the commit 1a85945d7212b2557e8d76d76deb168c6e75e16c.
The menus are specified in the `navbar_menu.json` file.
It follows the above structure.
The `navbar_menu.json` file should be placed in the same directory as the `chaise-config.js` file.
The applications that want those menus should include the `navbar_menu.json` file under the `www/chaise` directory in the `division` repository.
The provision rule for the `navbar_menu.json` is similar to the `chaise-config.js` one.

**Comment by hongsudt** [comment]
@svoinea This should not be in a separate file. It should be in the chaise_config.json file.

**Comment by hongsudt** [comment]
We decided to add navbar_menu as another json object in chaise_config.js file for ease of deployment. In terms of the styling, @howdyjessie and I decided to start with what @crisaless has designed for facebase, brighter blue on black background, etc.

**Comment by svoinea** [comment]
Removed the `navbar_menu.json` file.
Its content will be appended in the chaise-config.js file under the definition of the JavaScript variable `navbar_menu`.
These changes were performed under the commit 658ea7124863ad9be614d52927c134e7866a940d

**Comment by hongsudt** [comment]
navbar_menu = [
{ "name": "Search", 
  "children": [ 
     { "name": "Experiment", "url": "chaise/search/#1/experiments:Experiment" },
     { "name": "Sample", "url": "chaise/search/#1/experiments:Sample" },
     { "name": "Target", "url": "chaise/search/#1//chaise/search/#1/gpcr_browser:target_gui"}
  ]
},
{ "name": "Create",
  "children": [ 
     { "name": "Experiment", "url": "..." },
     { "name": "Sample", "url": "..." }
  ]
},
 ...  
]

**Comment by hongsudt** [comment]
This is now being used on rbk and gpcr. I am closing the issue.
