### ISSUE TITLE
Rename local variable `catalogID` to `catalogId`

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#544]
We use camel case throughout the application and I keep seeing this gem show up in different places in chaise. This affects viewer, recordedit, recordset, and the common folder.

**Comment by hongsudt** [comment]
Is this the time for you to do this for record2?

**Comment by jrchudy** [comment]
This relies on changing the parser in the common module which each app uses. To fix this, we would need it to be done for all apps at once instead of on a per app basis.

**Comment by hongsudt** [comment]
I am closing this issue with `wishlist`. We can reopen this later if needed.
