### ISSUE TITLE
Need entity delete button

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#552]
Users need to be able to delete rows.

This could be some combination of:
1. Record app delete button alongside edit button
2. Recordedit app delete record button alongside submit
~~~3. Recordset app delete button or context menu on each row?~~~ I want to delay this feature on recordset.

**Comment by hongsudt** [comment]
Let's only add the button on recordedit for now.

**Comment by karlcz** [comment]
@hongsudt this work was done right..?

**Comment by hongsudt** [comment]
Only for bullet one and two and right now it is configured based on a
chaise config whether to show the delete button or not.

**Comment by jrchudy** [comment]
Correct. This feature was completed when recordedit refactor was merged into master. And what @hongsudt said is correct. There is a delete button on `record` and `recordedit` now that shows based on a chaise config property.

**Comment by karlcz** [comment]
Can someone help me debug synapse-dev which doesn't seem to show delete buttons even though I have `showDeleteButton: true` and `confirmDelete: true` in my chaise-config.js?

**Comment by hongsudt** [comment]
@shinyichen can you help @karlcz with this?

**Comment by karlcz** [comment]
@jrchudy already helped... we finally figured out I was missing a `t` in `showDeleteButton` in my test config... can now confirm it works for me too.
