### ISSUE TITLE
Support 2016 App Links annotation

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#557]
This annotation is needed to go from search/recordset to different apps e.g. viewers vs. record2. 

@robes my thought is to have this set as an attribute in the reference and let the app uses it as appropriate. Make sense?

**Comment by robes** [comment]
I'm not convinced about this annotation. At some level its probably good to have but the details of it really need review.

**Comment by hongsudt** [comment]
I agree on simplifying the syntax. Here is what I am suggesting. 

* renaming record link to "2016 Link"  with tag `tag:isrd.isi.edu,2016:link`
* Json payload : `{ context : app_name, ... }` where app_name is one of the following
  - `tag:isrd.isi.edu,2016:chaise:record`,
  - `tag:isrd.isi.edu,2016:chaise:record-two`,
  - `tag:isrd.isi.edu,2016:chaise:viewer`,
  - `tag:isrd.isi.edu,2016:chaise:search`,
  - `tag:isrd.isi.edu,2016:chaise:recordset`

**Comment by hongsudt** [comment]
Please also look at #381 for heuristics.

**Comment by hongsudt** [comment]
Issue moved to [informatics-isi-edu/ermrestjs #202](https://github.com/informatics-isi-edu/ermrestjs/issues/202) via [**ZenHub**](https://www.zenhub.com/)
