### ISSUE TITLE
search: support the recordedit url syntax for showing multi-row insertion result

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#563]
Right now, recordedit directs users to recordset if multiple rows of records were submitted. I want this link to be configuration. We have defined a new annotation for this  (2016 Link), but for now this can just be a simple chaise config. 

Note: For a deployment that uses Search, it doesn't make sense to direct users to recordset.

**Comment by karlcz** [comment]
Sending it to the search app will be a bit of pain since it has a very different URL structure for the query constraints needed to show just specific newly created entities...

**Comment by hongsudt** [comment]
instead of doing this on recordedit, due to resource limitation, I am going to move the functionality to the search app. Recordedit will call the search app with its syntax and let's the search app deals with the parsing.

**Comment by hongsudt** [comment]
Assuming that the input url will be `#N/S:T/column=a;column=b;column=c` which can be converted to `#N/S:T?facets=column::eq::a,b,c`

This assumption will not support composite unique keys.

**Comment by svoinea** [comment]
Fixed through the commit e595020810f949bbe23fcdc95b09ed796a9d57f3

**Comment by karlcz** [comment]
This doesn't seem to work on dev.isrd.  The following URLs should show the same two records but the search page just leaves a spinner running and shows no data:

- https://dev.isrd.isi.edu/chaise/recordset/#1/legacy:dataset/id=263;id=269
- https://dev.isrd.isi.edu/chaise/search/#1/legacy:dataset/id=263;id=269

**Comment by svoinea** [comment]
The `id` column has the annotation `hidden`. 
In other words, a bookmark can not be created with it.
That explains the error that leaves the spinner running.
Some work needs to be done in order to make the search page to work with bookmarks containing `hidden` columns.

**Comment by hongsudt** [comment]
How much effort does it take to get the search app to deal with hidden columns?

**Comment by svoinea** [comment]
Even if we unhidden the `id` column, it will not work.
The column `id` has the `integer` type, for which the current search provides a `slider` representation.
In other words, the `OR` operator is not supported for `integer` values.

**Comment by hongsudt** [comment]
This doesn't seem to be a simple task, will delete it and push for recordedit.
