### ISSUE TITLE
Be able to test chaise with different chaise configs

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#566]
Currently, `chaise-config-sample.js` is being used for the protractor e2e tests in chaise. We need to consider a way to support defining a chaise config that can be used per spec so that different sets of configurations can be tested.

**Comment by hongsudt** [comment]
@chiragsanghvi it seems like there is a problem with the approach you mentioned to @howdyjessie. Can you report on the status?

**Comment by chiragsanghvi** [comment]
The approach works but not on @howdyjessie machine. Just to make it simple the **CHAISE_BASE_URL** is **dev.isrd.isi.edu/~jessie/chaise**. So the HTML and Javascript that is being used is sourced from the CHAISE_BASE_URL,  and not localhost while running the test-cases. 

When she runs the test-cases on her local machine pointing to **dev.isrd**, even if she sets the `chaiseConfigFilePath` its going to change the config file locally on her machine and not on the **dev.isrd** user-dir directory.
  
So you will see the chaise-config that is on `dev.isrd` and not the one at `chaiseConfigFilePath`

**Comment by chiragsanghvi** [comment]
For it to work locally on our machine's, we will need to enable Cross Origin Resource Sharing for ermrest or run ermrest locally on your machine.

**Comment by hongsudt** [comment]
No. CORS is not an option. Is there any other way to achieve this?
If she changes the base_url to point to localhost, will that work?

**Comment by chiragsanghvi** [comment]
Yes, but then ermrest will not work for localhost. She will need to run ermrest locally.

**Comment by howdyjessie** [comment]
@chiragsanghvi With your work on PR #593, would I still need to have ermrest installed locally?

**Comment by chiragsanghvi** [comment]
@howdyjessie No you don't need ermrest to be deployed locally for this.

**Comment by jrchudy** [comment]
PR #593 merged. Closing this issue.
