### ISSUE TITLE
set up end-to-end testing with authorization

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#567]

**Comment by karlcz** [comment]
Can someone remind me why I am assigned on this issue?  Am I supposed to be designing or documenting something?

**Comment by jrchudy** [comment]
We have introduced ACLs into the test environment pending documentation to be written (#594). These schema ACLs can be used in conjunction with a mocked session instead of integrating globus into our tests.

**Comment by hongsudt** [comment]
ok. I am closing this issue then.
