### ISSUE TITLE
Record2: the related entities section should be contextualized appropriately

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#570]
It should also check the Reference.display.type to deal with different way of presenting the related entity. The context to use is `compact/brief`.

**Comment by jrchudy** [comment]
This is blocked until [this issue](https://github.com/informatics-isi-edu/ermrestjs/issues/184) is resolved.

**Comment by jrchudy** [comment]
Changes for the issue with not contextualizing properly were fixed.

PR #579 merged, closing this issue.
