### ISSUE TITLE
Explore loading and rendering in tests

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#574]
When our e2e tests run, there seems to be a race condition where sometimes the chaise-config is not available before some elements are rendered. We should explore a solution that keeps our tests from running if the assets haven't fully loaded yet. 

@chiragsanghvi mentioned the use of `$document.ready()`. This was often used in conjunction with jQuery to prevent trying to modify or manipulate the DOM before it has all loaded.

**Comment by chiragsanghvi** [comment]
Yes either we do it using Jquery's `$(document).ready` or we can use the `viewContentLoaded` event of Angular.

**Comment by chiragsanghvi** [comment]
Yes.

**Comment by hongsudt** [comment]
@jrchudy @chiragsanghvi Since the code has been merged, should I close this?

**Comment by chiragsanghvi** [comment]
Yes we can close this issue.
