### ISSUE TITLE
search: remove the grey box surrounded by "User the sidebar to the right to select search attributes."

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#575]
@svoinea what do we do to get rid of that grey box?  It should only be shown if there is no search result on the page to provide new users with instructions..

**Comment by svoinea** [comment]
@hongsudt As long as no filter was selected, it appears to guide the user what to do.
The search results might appear also if no filter was selected and chaise-config has the option `showUnfilteredResults: true`. I think that is the case you are referring.

**Comment by hongsudt** [comment]
ok. I am closing the issue.

**Comment by mikedarcy** [comment]
I changed this to not show the box  (the "jumbotron") by default if `showUnfilteredResults: true`.
