### ISSUE TITLE
Hard code default list of sidebar facets

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#58]
On load, the default enabled facets and facet order should be: 
- Organism
- Data Type
- Image
- Mouse Age Stage
- Somite Count
- Mouse Phenotype
- Mouse Genotype
- Zebrafish Genotype
- Human Enhancer

**Comment by robes** [comment]
This is specific to the Facebase deployment. I believe we can consider this partially covered by #51 and then this belongs in the Facebase issue tracker for how we implement those. Added a new issue in that repo facebase-org/site#13.

**Comment by howdyjessie** [comment]
D'oh I totally forgot about that. My brain needs to stop conflating chaise with Facebase!
