### ISSUE TITLE
Support iframe in record2

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#580]
Record2 needs to support showing iframes as content in the related section. This should include a link after the content of that related reference to search or recordset as defined by the 2016 app_links annotation. If nothing is defined, navigate to recordset by default.

**Comment by jrchudy** [comment]
@hongsudt: When I get back data that is supposed to be rendered in an iframe, should I expect each value in Tuple.values to be an object with properties `isHtml` and `value` or is the `isHtml` property on the `Tuple` object?

Is rendering these iframes supposed to be a repeatable action across apps? Is there a case where recordset will render a set of iframes instead of a table?

**Comment by chiragsanghvi** [comment]
@jrchudy You need to refer to the `reference.display.type` property. If it says **markdown** then simply access the `page.content` property and put in in the related section placeholder adding the link at the end to recordset/search additionally. Make sure that you render the content as HTML using `ng-bind-html`.

You can refer the syntax here. https://github.com/informatics-isi-edu/ermrestjs/pull/175

**Comment by jrchudy** [comment]
PR #579 was merged, closing this issue.
