### ISSUE TITLE
Nothing happens when updating URL in address bar 

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/chaise#581]
In some of the apps, observed in Recordset and Record-Two, if user updates the address bar by changing anything after app's base url (after `.../recordset/` or after `.../record-two/`) and hit enter, nothing happens. Then if manually refresh the page, the new page is loaded.

In recordset I had `$window.onhashchange` to detect manual address bar changes and force the page to reload. However, this code was removed because it causes problem with e2e testing.

Further investigation needed on this issue.

**Comment by jrchudy** [comment]
I noticed the same thing. Another `work-around` is the following:

If the user updates the address bar and hits enter, nothing happens. If the user then clicks in the address bar again and hits enter, it will navigate to the new url. Essentially it's the same as a page refresh.
