### ISSUE TITLE
Display search results and chiclet for search term

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#59]
Opened this issue to see if this is possible. Users found it helpful in tests.

Basically, when a user searches for a keyword (e.g. “msx”) but hasn’t selected a facet yet, the main panel should display initial results and a chiclet for that search term.

And then when the user selects a facet after searching for a keyword, change the keyword filter chiclet to a facet filter chiclet.

@svoinea @robes

**Comment by howdyjessie** [comment]
Is this doable and/or advisable? :confused:

**Comment by karlcz** [comment]
I don't understand what was mocked and tested.

The whole point of the current keyword UX is to force the user to disambiguate what they really want to search in the structured data model.The whole point of the current keyword UX is to force the user to disambiguate what they really want to search in the structured data model.

There isn't any search mechanism that uses keywords without a facet, so there isn't any search result set nor query constaint to represent to the user before the facet and value constraints are chosen.

**Comment by robes** [comment]
And keep in mind that we have a regular expression (regex), effectively a substring search predicate, which could be used in a scenario like:

1- user first searches by a keyword, which brings up the set of matching facets
2- user drills down to the facet of interest

At this point, “select all” is equivalent to applying a regex predicate based on the keyword that was used in #1.

**Comment by karlcz** [comment]
There are actually two cases:

1. Facet name matched keyword
2. Facet value(s) matched keyword

In the first case, we don't also apply the pattern match to values, do we? At best, I think it is unknown what kind of constraint the user intended if they searched by facet name.  Could be not-null, could be a boolean test on boolean facets, could be weirder than we ever imagined...

**Comment by howdyjessie** [comment]
Okay sounds like this issue is NOT doable/advisable :)

This thread is good resolution to earlier discussions about Google-like "free searching" (which users like) vs faceted search (which we want users to use instead).
