### ISSUE TITLE
Documentation for e2e tests

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#594]
We have recently added more features to the e2e test suite including:
- defining user ACLs
- defining a chaise config for tests
- new environment variable for ssh-agent

These need to be documented in the e2e test wiki.

**Comment by chiragsanghvi** [comment]
I will document it once **PR** #593 is merged.

**Comment by chiragsanghvi** [comment]
This is documented in the wiki, over [here](https://github.com/informatics-isi-edu/chaise/wiki/E2E-tests-guide).
