### ISSUE TITLE
record2: markdown bullets do not show up on the page

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#595]
Take a look at the url here... 
https://dev.rebuildingakidney.org/chaise/record-two/#2/Protocol:Protocol/Title=Generation%20of%20kidney%20organoids%20from%20human%20pluripotent%20stem%20cells&Version=1.0

@RFSH what did you do to fix this issue in record?

**Comment by RFSH** [comment]
In record I used the column type to attach the `markdown-container` class to the container. In here, I think we can also use `isHTML` flag.

**Comment by jrchudy** [comment]
This issue is fixed. This required adding the `markdown-pattern` class to record.html.
