### ISSUE TITLE
Move navbar_menu to chaise_config

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#598]
The current method of declaring navbar_menu as a global variable causes the navbar to crash if the deployment config doesn't have narbar_menu declared in their chaise_config file.  The easiest way to solve this problem is to move the navbar_menu into the chaise_config variable. 

The following project-specific config will need to be modified: 
* rbk: dev, staging
* gpcr: dev, staging

**Comment by howdyjessie** [comment]
This issue has been addressed in PR #614.
