### ISSUE TITLE
Add tiered search in sidebar search

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#60]
Instead of having users drill down facet name > facet value, users should be able to search a term and see both the matching facet names and matching facet values. Something like this:

![screen shot 2015-09-21 at 12 16 43 pm](https://cloud.githubusercontent.com/assets/4585431/10002228/d63b4908-605a-11e5-93cd-bc2fe450f22c.png)

**Comment by karlcz** [comment]
The screenshot seems a bit redundant... shouldn't there just be two sections "FACETS" and "VALUES" if we're going to show "under Facetname" along with each value?

**Comment by howdyjessie** [comment]
Yeah it is redundant (it's an old mockup), so I'd remove the "under [facet name]" as well. The red badges are also redundant too. I'll put up a new image when I'm done with it.

**Comment by robes** [comment]
seems like this duplicates #43 ?

**Comment by howdyjessie** [comment]
Oops yeah this does.
