### ISSUE TITLE
Have a common page info object

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#606]
We should have a common page info object for our chaise defaults. This object shouldn't be repeated in apps so we can have consistency. We should take the page info object that is currently in `recordset` and use it for our defaults and remove the one in `record-two`.

This object should be a part of the table directive seeing as it is used only for the tables that are displayed.

**Comment by hongsudt** [comment]
@jrchudy is this still an issue?

**Comment by jrchudy** [comment]
This is still a valid issue.

**Comment by hongsudt** [comment]
I am marking this as a wishlist and close this for now.
