### ISSUE TITLE
support thumbnail and original image

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#607]
@chiragsanghvi mentioned that we could the following markdown to associate the thumbnail with original image `[caption](thumbnail_url){original_image_url}` but chaise will need to do something to make sure that the thumbnail is clickable. 

@chiragsanghvi please provide more information on this.

**Comment by karlcz** [comment]
I thought markdown supports this directly by putting the thumbnail
image inside the link text:

    [![alt text](thumbnail-URL)](destination-URL)

i.e. it is just this inline image:

    ![alt text](thumbnail-URL)

nested inside this normal link syntax:

    [...](destination-URL)

**Comment by chiragsanghvi** [comment]
Oh yes markdown supports that too. Just in case if we need to change the width and height or the final target window, that can also be achieved

```
[![Image](http://assets.barcroftmedia.com.s3-website-eu-west-1.amazonaws.com/assets/images/recent-images-11.jpg){width=500 height=400}](http://assets.barcroftmedia.com.s3-website-eu-west-1.amazonaws.com/assets/images/recent-images-11.jpg){target=_blank}
```

**Comment by chiragsanghvi** [comment]
I have added this to the documentation [here](https://github.com/informatics-isi-edu/ermrestjs/wiki/Template-and-Markdown-Guide)
