### ISSUE TITLE
Automated Testing FAQ wiki

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#608]
Please document the scenarios that cause test to fail (i.e. the one that you guys struggle to get it to pass) and their corresponding solutions. This should be our knowledge base for testing e.g. when a test fail, check this page. 

@chiragsanghvi please start the page that people have been asking you. 
@shinyichen @howdyjessie @jrchudy @RFSH  Please also add your cases to the page as well.

**Comment by chiragsanghvi** [comment]
I have made a wiki page [here](https://github.com/informatics-isi-edu/chaise/wiki/Automated-Testing-FAQ's). You can add more things to it as you remember.
