### ISSUE TITLE
Figure out and begin writing tests

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#61]
We don't have any tests in Chaise right now

**Comment by howdyjessie** [comment]
- Added Protractor tests in `tests/e2e` (e1bfd2d0b8a1b99f82929713040b2939172e57de)
- Configured Protractor tests to run through Sauce Labs locally and via Travis CI (06bbf435586d467a8fdfa9fda0824233d826aa2c)
- Configured Protractor tests to run with `make test` (68a84832d3fdc64a7a9d1221696e41dd0bfa2455)

**Comment by robes** [comment]
The `test` target in the makefile needs to list `deps` (dependencies) as a requirement so that it gets your node and protractor setup.

Secondly, and this may just be an issue with my local configuration (not sure), when I run `make test` I get a popup that say "To use 'java' command-line tool you need to install a JDK" and yet I did install the JDK. And then the tests end here in an error.

```
$ make test
for file in test/e2e/search/protractor.conf.js test/e2e/record/protractor.conf.js test/e2e/login/protractor.conf.js; do \
		node_modules/.bin/protractor $file; \
	done
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
/Users/schuler/devel/chaise/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
  goog.global.setTimeout(function() { throw exception; }, 0);
                                            ^
Error: Server terminated early with status 1
    at Error (native)
    at /Users/schuler/devel/chaise/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:204:25
    at promise.ControlFlow.runInFrame_ (/Users/schuler/devel/chaise/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
...
```

**Comment by howdyjessie** [comment]
That's weird; it shouldn't ask you to install a JDK because the tests should be going through Sauce Labs.

One thing I didn't mention that might be related to this: Protractor is set up to use Sauce Labs credentials from the environment. Have you set `export`ed a set of credentials yet?

**Comment by robes** [comment]
No, I haven't set anything in the environment. Did I miss some instructions?

**Comment by karlcz** [comment]
Look for the two SAUCE_* environment variable lookups in the test
configuration file. Those both need to be set in the environment
before running the test, so it can authenticate with saucelabs.  For
developer testing, each develop who runs tests will need to get a
(free for opensource) account.

For eventual Travis testing, we can just use one developer's account
at saucelabs, e.g. Jessie's, similar to how only one Travis user
has to enable Travis for a particular GitHub repo...

**Comment by robes** [comment]
@howdyjessie Can you add a "How to Test" section to the README?

**Comment by howdyjessie** [comment]
@robes sure thing
