### ISSUE TITLE
remove extra space character from gene_sequence annotation 

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#610]
Example 

https://dev.gpcrconsortium.org/chaise/record-two/#1/gpcr_browser:construct_gui/title=IMPT-4779

Also, is the red color configurable?

**Comment by howdyjessie** [comment]
@bugacov The red color isn't configurable but @hongsudt said we should just make it black text.

**Comment by howdyjessie** [comment]
Ok I've pushed the fix to master so dev.gpcr should have the fix in the next hourly update. The gene sequences should be black font and aligned now.

![screen shot 2016-09-20 at 4 23 50 pm](https://cloud.githubusercontent.com/assets/4585431/18692414/c0d306fa-7f4e-11e6-9687-36ac8b24d59e.png)

@hongsudt has approved this so I'm closing the issue.
