### ISSUE TITLE
Recordset error module._mustache is undefined

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#612]
Viewing recordset app when I have a markdown_pattern causes the error `Error module._mustache is undefined` to be displayed.

Example:
https://synapse-dev.isrd.isi.edu/chaise/recordset#1/Zebrafish:Cropped%20Image@sort(Extract%20Date::desc::)

**Comment by hongsudt** [comment]
@chiragsanghvi can you look into this quickly?

**Comment by chiragsanghvi** [comment]
@hongsudt I don't have access to `synapse-dev`. Can you give me access ?

**Comment by karlcz** [comment]
I can confirm that this happens sporadically if I visit the link over and over.  So that supports the idea of a race-condition...

**Comment by hongsudt** [comment]
@karlcz here is the group name and url
isrd-tester https://www.globus.org/app/groups/9d596ac6-22b9-11e6-b519-22000aef184d

**Comment by chiragsanghvi** [comment]
This has been fixed.
