### ISSUE TITLE
Record2 not showing Edit link to recordedit app

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#613]
Example:

https://synapse-dev.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/ID=ZfCza20160815A

The chaise-config.js file has `editRecord: true` which worked for previous record app...  see example:

https://synapse.isrd.isi.edu/chaise/record/#1/Zebrafish:Subject/ID=ZfCza20160815A

**Comment by jrchudy** [comment]
That's odd. When I go to the first link (the new record page) I see an `Edit Record` button. As I look through the `meta` information from the server, I can verify that the `isrd-staff` globus group is in the `content-write-user` list and that I have that permission (`isrd-staff`) as part of my session attributes.

**Comment by hongsudt** [comment]
@karlcz if this is no longer the issue, please close it.

**Comment by karlcz** [comment]
Strangely this resolved itself.  Not sure if recent commits fixed something or what... :-(
