### ISSUE TITLE
record-two co-exist with record and detailed. Is this expected?

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#616]
The path using /record-two/ and /record/ point to the same content. I would assume that /record-two/ url should no longer exist.

**Comment by jrchudy** [comment]
I noticed this was the case with my local directory running on dev.isrd. After cleaning up the directory and removing the `/record-two` folder, that path no longer exists. 

Each deployment will have to remove that folder from the server (or maybe we need to look at why the recipes don't clean up old files).

**Comment by karlcz** [comment]
The recipe runs make install on top of whatever was there.  The install doesn't delete old stuff.

**Comment by howdyjessie** [comment]
I can confirm that record-two no longer exists once I reinstalled Chaise in my user dir.

So is this still an issue or should we change this issue to reflect that deployments need to remove the `record-two` folder?

(Do they even need to remove the folder? As long as nothing links to the folder, it should be fine.)

**Comment by hongsudt** [comment]
This is because the stale directory under /var/www/html/chaise/. Remove the directory manually on live servers.
