### ISSUE TITLE
Need timestamp data-entry widget for timestamp column types

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#619]
I have timestamp column types in synapse-dev model and the recordedit page shows a date picker but no control for time of day.  We really need to be able to insert full times including a convenient button for "now" to get wall clock time.

What happens now, I think, is that Chaise only collects a date and sends it to ermrest where postgres then promotes it to a timestamp at midnight on that date, i.e. adds zeros for hours/minutes/seconds.

**Comment by hongsudt** [comment]
I assume this can be done in parallel to the refactoring that @jrchudy is working, correct?

**Comment by howdyjessie** [comment]
PR #661 has been merged; closing now.
