### ISSUE TITLE
Update the chaise/record app URL fragment id format and its history behavior

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#62]
We have specified a new URL fragment id format to use in chaise/record. See:

https://github.com/informatics-isi-edu/chaise/blob/master/doc/urls.md#chaiserecord-resource-names

Then we also want the app to support proper browser history behavior. I.e., forward/back buttons should work, should be possible to copy a link into the browser location and get to the same app state (given various caveats of how browser location bars are seriously broken).

**Comment by karlcz** [comment]
We should put a an <a href="...">bookmark</a> link at the top of the
page like we do in the facet search UI.  That way we can always tell
users to use their browser's copy-link-location function to get it in
case they are having trouble with the location bar.

**Comment by robes** [comment]
We still have some issues with forward/backward navigtion (native browser navigation that is).

**Comment by robes** [comment]
appears to be working AFAICT
