### ISSUE TITLE
plotly figure of FCS data doesn't display correctly inside new record2 iframe annotation 

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#623]
See for example FCS PLOTS section of 

https://dev.gpcrconsortium.org/chaise/record/#1/gpcr_browser:biomassprodbatch_gui/title=IMPT-10017

Initially the figure doesn't display properly, then if you press the red "Reset" button it shows the 
figure correctly.

**Comment by hongsudt** [comment]
@chiragsanghvi please take a look at this. The position of the iframe content seems to be off upon the first display.

**Comment by chiragsanghvi** [comment]
Fixed.
