### ISSUE TITLE
"name" 2015display annotation doesn't seem to be working on columns w/ tooltips (COMMENT)

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#624]
See the columns "Surface Elc" and "Surface Eac" in 

https://dev.gpcrconsortium.org/chaise/record/#1/gpcr_browser:biomassprodbatch_gui/title=IMPT-10017

Those cols have 2015 display annotations to show "Surface ELC" but somehow it shows "Surface Elc". Same thing happens in the "Surface Eac" column which also has a COMMENT to show as tooltip so that maybe the problem?

**Comment by hongsudt** [comment]
@RFSH please take a look at this asap. It should be a simple fix.

**Comment by RFSH** [comment]
@hongsudt @bugacov 

Based on [annotation document](https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2015-display), `title_case` display annotation converts element names to "title case" meaning the first character of each word is capitalized and **the rest are lower cased regardless of model element name casing**. Word separators include white-space, hyphen, and underline characters.

The gpcr_browser schema has set the `title_case` to true. So all of its tables and columns will have this settings; unless you explicitly define it in Tables or Columns. If you just want to change the `_` with space, you can set the `title_case` to false for these columns.

**Comment by bugacov** [comment]
Right. I have the title_case to true but I thought that the display
annotation would overwrite that and display the annotated value
regardless of other annotations.

Shouldn't that be the correct behavior?

**Comment by bugacov** [comment]
This was a problem on my end due to annotation not getting entered correctly. The problem is solved now. I'm closing the issue.
