### ISSUE TITLE
redirect to URL pointing to a record doesn't display in record2 markdown annotation 

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#625]
See the "VIEW TARGET IMPT-CCR1" link in 

https://dev.gpcrconsortium.org/chaise/record/#1/gpcr_browser:construct_gui/title=IMPT-1003

The url is correct but need to do an extra page reload in order to display the page. 

Redirects to results set, like the one above for "VIEW BIOMASSES..." work ok

**Comment by hongsudt** [comment]
This might be relevant to issue #581. @chiragsanghvi @robes do you have any suggestions?

**Comment by robes** [comment]
@hongsudt yep, i believe its exactly like that issue.

**Comment by chiragsanghvi** [comment]
Fixed in **PR** https://github.com/informatics-isi-edu/chaise/pull/629
