### ISSUE TITLE
Improve apps' performances on CSS side

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#627]
- Concatenate CSS files into fewer files
  - Only source files? Include vendor files too?
- Minify source CSS
- Use minified versions of vendor CSS
  - Remove unused, un-minified stylesheets from repo
- Load external CSS (i.e. `chaiseConfig.customCSS`) before external JS*
  - \* Might be more effort than it's worth for this one file. I imagine we'd need to read `chaiseConfig.customCSS` and then add the file inside Makefile so that apps will load the custom CSS at runtime, not later.

**Comment by hongsudt** [comment]
part of #1361. WIll close this issue.
