### ISSUE TITLE
gray box around iframe objects seems to have a fix size and not adjusting to define size of the iframe

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#628]
See for example 

https://dev.gpcrconsortium.org/chaise/record/#1/gpcr_browser:target_gui/title=IMPT-5HT2A

**Comment by hongsudt** [comment]
@chiragsanghvi maybe this is a minor adjustment?

**Comment by chiragsanghvi** [comment]
This issue is fixed in this commit https://github.com/informatics-isi-edu/chaise/commit/9e8a7e5ef44a527d886740e501483ae05c5d40de.
