### ISSUE TITLE
Update chaise/search per the faceting heuristics and recommended ERMrest annotations

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#63]
We have recently specified a new set of recommended ERMrest annotations and heuristics specific to Chaise presentation behaviors.

Generally see:

https://github.com/informatics-isi-edu/chaise/blob/master/doc/heuristics.md

Specific to the faceting heuristics see this section:

https://github.com/informatics-isi-edu/chaise/blob/master/doc/heuristics.md#facet-presentation

**Comment by carlkesselman** [comment]
Decision is to use a tree control to enable expansion/exploration of attributes.  For the time being, we will still use the slide out for value selection.

Also, the plan is to remove the calculation of attribute counts as part of this reworking.

**Comment by robes** [comment]
I think this has been put on the back burner until we can take a step back and make a roadmap for the ui development.

**Comment by robes** [comment]
move to wishlist; we should update chaise/search per the updated annotations though
