### ISSUE TITLE
search app: wrong table get displayed in the case of duplicate table name in different schemas

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#631]
I have the following 2 tables: `Cell_Line:Cell_Line` and `Cell_Line2:Cell_Line`. When I specified `chaise/search/#2/Cell_Line:Cell_Line`, it displays the content of `Cell_Line2:Cell_Line`.

**Comment by svoinea** [comment]
Should have been fixed through the commit 0b2a5bcb003af9095ae3bc005bb5b7d7f06a3b2e
