### ISSUE TITLE
Recordset Module 'recordset' is not available

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#639]
The recordset app on master is completely broken.

It shows raw angular template content, a stuck spinner, and a web console error like `[$injector:nomod] Module 'recordset' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument`

**Comment by karlcz** [comment]
@hongsudt can we prioritize this?

**Comment by jrchudy** [comment]
I found the issue with this, there was a `,` missing in the definition of the `run` block causing it to fail. This was committed directly to master.

**Comment by chiragsanghvi** [comment]
My mistake. I missed adding the `,` while adding `uiUtils`.

**Comment by jrchudy** [comment]
@karlcz: This issue should be resolved. Can you confirm and close this?

**Comment by karlcz** [comment]
yeah I tested and it worked for me
