### ISSUE TITLE
Record2 create and edit buttons disappear on forward/back navigation

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#641]
1. Start on a record page showing `Create Record` and `Edit Record` buttons
2. Click one of the buttons to navigate
3. Click browser Back button
4. Back on record page but `Create Record` and `Edit Record` buttons are gone!
5. Hitting browser Reload button will restore those buttons again

This also happens for other cross-page navigations, like going back to a recordset page, then forward to the same record page again.

Hitting reload will render the buttons.

**Comment by chiragsanghvi** [comment]
This issue can be fixed the same way we fixed it for issue #703 for recordedit in this PR https://github.com/informatics-isi-edu/chaise/pull/713.

**Comment by jrchudy** [comment]
PR #757 was merged. Closing this issue.
