### ISSUE TITLE
prototype related entities layout to look like it is part of the main table

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#643]
- [ ] if the inbound fk is in the visible column, display this pseudo-column like any other regular column. The table display name should be used as the column name (this should be provided by ermrestjs already). The column value should be a table or what's specified in the table annotation.
- [ ] Add edit and view all capability. We will need to experiment with the UI.
- [ ] change the default display to be a list of row name instead of a tabular format. We will need to have an annotation to show a tabular format.

**Comment by amitjha21** [comment]
This has been merged to master. Assigning @hongsudt to verify and close it.
