### ISSUE TITLE
Support 2016 App Links annotation

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#644]
@hongsudt commented on [Fri Sep 16 2016](https://github.com/informatics-isi-edu/ermrestjs/issues/202)

@hongsudt commented on [Wed Aug 24 2016](https://github.com/informatics-isi-edu/chaise/issues/557)

This annotation is needed to go from search/recordset to different apps e.g. viewers vs. record2. 

@robes my thought is to have this set as an attribute in the reference and let the app uses it as appropriate. Make sense? 

---

@robes commented on [Wed Aug 24 2016](https://github.com/informatics-isi-edu/chaise/issues/557#issuecomment-242235501)

I'm not convinced about this annotation. At some level its probably good to have but the details of it really need review.

---

@hongsudt commented on [Wed Aug 31 2016](https://github.com/informatics-isi-edu/chaise/issues/557#issuecomment-242247472)

I agree on simplifying the syntax. Here is what I am suggesting. 

* renaming record link to "2016 App Links"  with tag `tag:isrd.isi.edu,2016:app-links`
* Json payload : `{ context : app_name, ... }` where app_name is one of the following
  - `tag:isrd.isi.edu,2016:chaise:record`,
  - `tag:isrd.isi.edu,2016:chaise:record-two`,
  - `tag:isrd.isi.edu,2016:chaise:viewer`,
  - `tag:isrd.isi.edu,2016:chaise:search`,
  - `tag:isrd.isi.edu,2016:chaise:recordset`

---

@hongsudt commented on [Tue Sep 13 2016](https://github.com/informatics-isi-edu/chaise/issues/557#issuecomment-246880021)

Please also look at #381 for heuristics. 

---

@hongsudt commented on [Fri Sep 16 2016](https://github.com/informatics-isi-edu/ermrestjs/issues/202#issuecomment-247736221)

As a starting point, we will make an `app_link` object available for apps to use. 

@robes has a suggestion for a longer term plan, which we can implement later. 

---

@robes commented on [Fri Sep 16 2016](https://github.com/informatics-isi-edu/ermrestjs/issues/202#issuecomment-247739331)

This makes sense. But let's go with `tag:...record` as the _new_ record app (i.e., the app formerly known as "record-two"). And I don't think we should even include the `tag:...detail` (or `tag:...record-old`) as an option. This only applies to deployments that are using the new code. Unless we are going to support this annotation in the search app?

---

@hongsudt commented on [Thu Sep 29 2016](https://github.com/informatics-isi-edu/ermrestjs/issues/202#issuecomment-250634561)

According to our discussion today, this should be implemented as a common module in chaise that takes a reference and the app_link tag and turns that into a proper url.

**Comment by shinyichen** [comment]
should recordedit be one of the apps too? @hongsudt
