### ISSUE TITLE
Add "profile card" to navbar

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#651]
Add a dropdown to the profile name that's displayed on the navbar. 

Upon clicking the profile name, a "card" or dropdown appears with all the other information found in webauthn's `client` object.

Also change the profile name to only show whatever's in the `display_name` field.

**Comment by nitishksahu** [comment]
The idea is to implement:
- When the user is not logged in, only `Login` link is shown at the rightmost of the navbar.
- Once the user is logged in, the `display_name` is shown along with a caret sign just beside it, clicking on the caret sign would open a submenu, with a `log out` link and all the group names like (`isrd_testers`, `gpcr_academia_readers`) the user is part of.

**Comment by nitishksahu** [comment]
The changes have been merged to master, assigning this to @hongsudt to verify and close.
