### ISSUE TITLE
Button to link to and launch modal popup for selecting values

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#655]
The record edit page will display `PseudoColumn`s in a similar manner as regular `Column`s however for the `PseudoColumn` the app will need to:
- [x] display the value as normal text rather than in an editable control (unless you feel it looks better in a non-editable text entry control)
- [x] display a button that indicates to the user that they click there to select a new value for that field
- [x] when clicking that button, the app should display the modal dialog with the recordset directive in it.

**Comment by robes** [comment]
I discussed with @RFSH how he should generate the underlying `PseudoColumn.reference`. And I discussed with @shinyichen that when a `reference` is contextualized for the entry/create context it should strip off the filters because you really want a reference to the whole set in that case so that you can pick a new value.

Therefore the app, when the above button is clicked will do something like this (but don't take this too literally):
```
if (col.isPseudo == true) {
  var ref = col.reference;
  var applink = ref.contextualize.entry.applink;
  ...applink is a uri, and can be used in the button or link to select new values...
```

**Comment by jrchudy** [comment]
This is implemented in the `recordedit2-master` branch.
