### ISSUE TITLE
recordedit: Add link to 'create new' entry for out-bound foreign key 

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#658]
Extends #656 with a 'create new' entry button or link to the recordset directive. When using this link for the recordedit modal this link should open a new window or tab. However, from the recordset app, we might want this to replace the current window.

**Comment by jrchudy** [comment]
[Here's](https://github.com/informatics-isi-edu/chaise/blob/foreignkey-modal/recordedit/index.html.in#L106-L111) the lines I added to recordedit's html page.

**Comment by jrchudy** [comment]
I would suggest taking the `recordedit2-master` branch and creating a new branch based off of that one. When you finish the implementation, we can merge it back into the `recordedit2-master` branch.

**Comment by hongsudt** [comment]
To limit the scope, we will first add a link next to the peudo-column to allow users to create a new entry to be added in the domain table. This will just open recordedit in a new tab.
