### ISSUE TITLE
OnClick handler for recordset directive to return value to recordedit app

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#659]
The recordedit will need to define the onclick handler of the recordset directive described in #656. The handler function will need to:
- [x] dismiss the modal
- [x] return an array (of 1 element for now) of the selected tuple for the row that was clicked in the recordset directive
- [x] update the recordedit's tuple's value based on the tuple returned by the directive
- [x] update the recordedit's displayed value for the pseudocolumn

**Comment by jrchudy** [comment]
This is implemented in the `recordedit2-master` branch.
