### ISSUE TITLE
Setting the values for pseudocolumn should update the underlying foreign key columns

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#662]
Unlike a normal `Column` value a `PseudoColumn` value actually represents a `tuple` of the foreign key columns. The recordset directive and its onclick handler #659 will "return" (using that term loosely) a tuple representing the clicked element from the recordset directive.

Ideally, I would suggest that the `Tuple` class from ermrestjs should be extended with a way to assign values like this:

```
  // where 'i' is the index of a column or pseudocolumn
  // and 'val' is a new value, in this case a tuple
  tuple.setValue(i, val);
```

Note that **if** javascript had let us override its basic types, like arrays, then the above code might have been like this:

```
   tuple.values[i] = val;
```

We need to review the above with @jrchudy because he has already had to do something to set values for the record edit and we should continue that pattern (or adjust it now, if needed).

The internal logic of `setValue()` will need to:
- understand when it is assigning a value for a regular `Column` or a `PseudoColumn` attribute
- when it is a regular `Column` we just assign the value directly to that attribute (*)
- but for `PseudoColumn` we need to enumerate the "key" columns for the target table of the FKR
  - assign the value from the target "key" column
  - to the value of the tuple's corresponding "foreign key" column

(*) One caveat here is whether we want to reverse-format a value. If given a `'1,000'` string to turn it into a `1000` integer if the column is an integer type. For now, I think we decided not to do that.

This is really an _ermrestjs_ issue but its easier to manager in this epic if we keep all the related tasks together.

**Comment by jrchudy** [comment]
@robes, the implementation for this deviated from what you suggested. Should we leave this issue open for you to review the changes?

**Comment by robes** [comment]
@jrchudy No, you don't need to keep it open.

But I would like to learn what approach was taken. Maybe someone can review with me.
