### ISSUE TITLE
recordset: encoding is incorrect if the column names have spaces in them

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#663]
https://dev.rebuildingakidney.org/chaise/recordset/#2/Common:RBK_Resources
Here is the table content. 

```
        Table        |   Data Type    | Number Of Entries |         Last Updated          
---------------------+----------------+-------------------+-------------------------------
 Protocol:Protocol   | Protocol       |                 8 | 2016-10-07 16:37:36.706347-07
 Cell_Line:Cell_Line | Cell Line      |                 4 | 2016-10-05 19:06:45.666385-07
 RNASeq:Sample       | RNASeq Samples |                 1 | 2016-10-05 21:03:27.143068-07
```

This is the link that gets generated. 
https://dev.rebuildingakidney.org/ermrest/catalog/2/entity/Common:RBK_Resources@sort(Number%20Of%20Entries,Table,Data%2520Type,Last%2520Updated)

**Comment by hongsudt** [comment]
Please also remove the words `Records for ` from the recordset title and only leave the table name there.

**Comment by shinyichen** [comment]
I am not seeing the problem with sorting now. The ermrest links look correct now as well. It's possible recent updates with URI encoding/decoding in ermrestjs fixed the problem. Can you confirm it is working now @hongsudt

**Comment by shinyichen** [comment]
"Records for" has been removed from another PR.
