### ISSUE TITLE
Markdown column type: Provide a link to markdown syntax or other online markdown editor

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#664]
@hongsudt commented on [Sat Oct 08 2016](https://github.com/informatics-isi-edu/ermrestjs/issues/233)

We decided that instead of extending the comments to contain markdown, a tooltip to the markdown syntax or online editor can be shown by record-edit.

**Comment by howdyjessie** [comment]
PR #681 has been merged, closing now.
