### ISSUE TITLE
Move Ermrest Data Utils Repo

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#665]
I discussed this with @hongsudt today, and we both think the [Ermrest Data Utils Repository](https://github.com/chiragsanghvi/ErmrestDataUtils) should be moved into a repo under `github.com/informatics-isi-edu`. 

@chiragsanghvi we can discuss this when you are in the office. This issue is created as a reminder to discuss this in scrum Thursday.

**Comment by hongsudt** [comment]
@chiragsanghvi can we work on moving this repo to informatics-isi-edu? If you give me an admin access on that repo, and let me know what I need to do, I can then move it.

**Comment by chiragsanghvi** [comment]
I have added you as a collaborator and now you can transfer the repo **ErmrestDataUtils** to **informatics-isi-edu**. Just to be sure we will also need an NPM account for our organisation. 

As the code is pulled from npm whenever we build systems and run test-cases.

**Comment by hongsudt** [comment]
We decided in the meeting to change the process so there is no dependency on the NPM account.
