### ISSUE TITLE
recordedit: support pre-filled value

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#669]
We decided to support this through cookie. These cookies should have a UUID associated with each tab. 
- cookie _name_ will be the UUID
- the url for the recordedit app should have a parameter that references the uuid like:
  `http://.../#1/...?prefill=UUID`
- ermrestjs will need to parse these extra options if it does not already
- recordedit then needs to check the the query options and see that it has the `prefill` option (you can change that option name if you like)
- the contents of the cookie will probably be a json serialization something like:
  `{column_name: value, column_name_2: value, ...}`
- record edit then needs to prefill the values based on contents of the cookie
- prefilled columns should be disabled (I think they should be visible just not editable)
- we should clean up our cookies. the simplest way might be to have an expiration (24 hours?) so that the cookie gets cleaned up by the browser. (I assume this is possible)

**Comment by howdyjessie** [comment]
PR #699 has been merged, closing now.
