### ISSUE TITLE
support multiple conjuntive search strings

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#672]
Right now the recordset only assume one search string is provided. Is there a way to allow a conjunctive of search strings? Should we use `" "` to indicate the boundary of search terms? 

@karlcz @robes any ideas?

**Comment by karlcz** [comment]
I suppose splitting on whitespace and treating each word as a separate
constraints is an OK approach to start with.  I assume we'd eventually
have to add "quotes for phrases" to allow whitespace in a particular
constraint?

**Comment by robes** [comment]
I think this is one of the topics that I discussed with @shinyichen the other day. We have a few options:
- treat the entire string as a search string
- tokenize on white spaces and
  - do a conjunction
  - or a disjunction

Technically all the above are feasible. This is really a UX question. My guess is that the most intuitive would be that it should be a _conjunction_ by default.

We could add to the requirements to add a little radio button to select between 'all' or 'any' terms which we would translate into conjunction or disjunction respectively.

**Comment by karlcz** [comment]
And this is stuff the client app would need to do.  The protocol layer already
supports conjunctive filters and this would just turn into something like:

   table/*::regexp::word1/*::regexp::word2

Where the client also needs to do some escaping of the words (or limit
their character ranges in some way) to avoid passing through
regular-expression meta-syntax.  The protocol accepts regular
expressions for this operator, obviously, but we don't think we want
to ask users to write them.

**Comment by robes** [comment]
+1 for karl's suggestion to "quote phrases". Though I'd agree that could come in the next round of requirements. 

Not to mention that my suggestion for the all/any selection could also come in the next round.

**Comment by robes** [comment]
Let's keep the escaping to a minimum... in my opinion.
