### ISSUE TITLE
results tally items not collapsing gracefully

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#673]
On my laptop, with a browser width of 1280px or less, the "Download" set (text plus dropdown plus button) ends up on the line below. It's not collapsing gracefully because elements aren't separated into columns, they're all within one col-xs-12 class. 

I _think_ it would be better instead of using one column of "12", to break down into col-md-7, col-md-3 and col-md-2 respectively. Also could move the 'pull-left' class to the first span or p of each column.

To hack for now, could just take out "Download" label text. Don't think it's really needed with the download icon there...

[chaise-search-collapse.pdf](https://github.com/informatics-isi-edu/chaise/files/528479/chaise-search-collapse.pdf)

**Comment by hongsudt** [comment]
We are deprecating search..So I am closing this issue.. If there are UX improvement on recordset or other chaise apps, we can generate new issues.
