### ISSUE TITLE
Add checksums to common files

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#676]
The Makefile doesn't append checksums to `common/` files  so when we request those common files from the server, the server think they're the same as older versions. Since we're currently adding and modifying the files in `common/` quite often, we should version these files as well so we don't have to hard reload all the time.

**Comment by hongsudt** [comment]
@chiragsanghvi is this something you can help with?

**Comment by chiragsanghvi** [comment]
@hongsudt Yes I can.

**Comment by howdyjessie** [comment]
PR #751 has been merged so I'm closing this issue.
