### ISSUE TITLE
Faceting: round 1

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#678]
Take a look at [this wiki page](https://github.com/informatics-isi-edu/chaise/wiki/Faceting) for more implementation-oriented description of this feature.

This round will focus on: 
- skeleton 
  - listing the main entity column names
  - as the column name is clicked, display a list of faceting options. This is going to be criteria per data type. For the skeleton, we can use the number type and ask a user to specify the range.
  - when a value or a range is specified, summarize the faceting criteria on the top (like the search app). 
  - generate an ermrest call to get the result set
- Faceting option for each data type
  - number/float: 
    - 2 number entries for min and max 
    - retrieve the min and max from ermrest and display that as the default values
  - date/datetime
    - 2 entries for min and max 
    - retrieve the min and max from ermrest and display that as the default values
  - text/default: 
    - a search box to filter the column
    - a page of existing column values with prev and next   

An initial draft on the UI
![img_20170203_143048 =300x200](https://cloud.githubusercontent.com/assets/414732/22611237/54978cdc-ea1e-11e6-810c-b9e207d7fc55.jpg)
![img_20170203_143217](https://cloud.githubusercontent.com/assets/414732/22611242/5bf1bb4c-ea1e-11e6-9963-e11694bf71a1.jpg)
![img_20170203_143233](https://cloud.githubusercontent.com/assets/414732/22611280/89fca5e2-ea1e-11e6-9508-ded258a7bdaa.jpg)

@robes @karlcz is this a good starting point?

**Comment by robes** [comment]
The faceting option for each data type should be loosely coupled per karl and my comments earlier. This can be worked out in the software design.

I'm curious what people will think about the 'chiclets' moved into each attribute's facet control. Currently, we have those 'chiclets' at the top. We wanted to move them within the context of each attribute facet control. There might be other options for doing this, but I kinda like @hongsudt 's proposal here.

Also, others that are reviewing this, we were thinking that the results won't be updated until the user hits the "Apply" button.

I'm not sure I'd put the overall Search control within the context of the faceting side bar. I'd still like to see that as a separate loosely coupled control. The faceting, I think of as a "refine within results".

**Comment by robes** [comment]
This is an iteration on Hongsuda's drawings, just to continue the conversation. Maybe we can meet and discuss early next week.

![faceting](https://cloud.githubusercontent.com/assets/4202842/22851333/5477dd6e-efd3-11e6-8a9a-f2c29e071a2d.jpg)

Labels:

A. The general search box at the top.

B. Count of records and the type (by table name) of the records. I realize we may not be able to give the total count but it is something that comes up.

C. Example of a value picker.

D. User types in this box to find values of interest which then updates the visible checkboxes below.

E. Selected items are shows at the top of the list as selected checkboxes.

F. Clicking on "Show more" opens the recordset modal from which the user can have more real estate in which to search, page, etc.

G. Example of a range selector. (Can be applied to any column data type but the example shows a date range.)
- First row shows the user's last input with a (X) on the right to remove that selection.
- Second row shows a new entry with a (+) to add it to the set of filters.

H. Example of a free form search control for searching on specific attributes (e.g., description fields, comment fields, anything that can be searched).

I. All of the examples have "Apply" and "Clear" on the top right (same as Hongsuda's drawings)
- Filters aren't activated until user hits Apply, or the whole facet can be cleared.

J. Searches that have been added are shown below with (X) to the right to remove.

K. The table display of results of the resultset directive.

**Comment by carlkesselman** [comment]
FYI, this is starting to look a bit like the interface in OpenRefine (formally Google Refine)

![image](https://cloud.githubusercontent.com/assets/3597150/22855529/7b133690-f036-11e6-98eb-bd8d56de5f99.png)

**Comment by robes** [comment]
Yes. I would say that Open Refine looks like a conventional faceting interface. And in this round, we also are trying to stick to a more conventional faceting design.

**Comment by hongsudt** [comment]
Here is the mock-up..   https://dev.isrd.isi.edu/~ashafaei/chaise2/recordset/#1/isa:dataset

**Comment by carlkesselman** [comment]
Do you want comments on this?

Carl


----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl

**Comment by hongsudt** [comment]
Sure..

**Comment by carlkesselman** [comment]
The first thing that strikes me as that an indication/control of the open close state of a panel would be helpful.  As it stands, I have nothing that visually indicates that if I click on the bar something opens, and then the state changes so that if I click again it closes.  I think a simple V,> indicator would be helpful here.

Carl


----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl
