### ISSUE TITLE
Make a howto video on Chaise....

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#68]
Bennett has made a nice new video for the details page.  We should do something similar to this for using the facet/search on Facebase.

https://youtu.be/j9qzCi-XzsI

**Comment by karlcz** [comment]
Hmm, do we need another issue to develop a theme song for chaise then...?  Should it be lounge-friendly jazz? :-)

**Comment by carlkesselman** [comment]
I think so….

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl

From: karlcz
Reply-To: informatics-isi-edu/chaise
Date: Sunday, September 27, 2015 at 4:13 PM
To: informatics-isi-edu/chaise
Cc: Carl Kesselman
Subject: Re: [chaise] Make a howto video on Chase.... (#68)

Hmm, do we need another issue to develop a theme song for chaise then...? Should it be lounge-friendly jazz? :-)

**Comment by crisaless** [comment]
One question - do we really need two videos? One for vanilla chaise and one that's specifically for FB?

**Comment by carlkesselman** [comment]
No, probably not.  We do need to have some actual data for the video, and it can be facebase…..

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Oct 8, 2015, at 10:18 AM, Cris Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


One question - do we really need two videos? One for vanilla chaise and one that's specifically for FB?

**Comment by robes** [comment]
@crisaless you are actively doing this I think, but its not assigned to this milestone.

**Comment by crisaless** [comment]
I'm working on one for FaceBase - but if that would work as a chaise how-to, then yes this should be assigned to the current milestone. What do you think?

**Comment by hongsudt** [comment]
@crisaless is this done? Can we close this?

**Comment by crisaless** [comment]
We now have a video for FaceBase that has a strong focus on Chaise - although it is not referred to as such. @carlkesselman  - does this suffice for now or do you really want a chaise branded video?

**Comment by crisaless** [comment]
Here's the latest version of the facebase video - there will be one more iteration and then it will go public (it's set to unlisted for now)

https://www.youtube.com/watch?v=5NUQyV3FSfM

**Comment by hongsudt** [comment]
@crisaless is this video done? Can we close the issue?

**Comment by crisaless** [comment]
the facebase one is done.
