### ISSUE TITLE
Record needs to call read with a proper limit

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#685]
Currently Record calls `Reference.read` with a value of 1 that is hardcoded, this needs to be handled differently.

**Comment by karlcz** [comment]
Just to clarify, this is for the main record?  If so, I guess a better limit would be `2` and then throw an error if we actually get 2 results, meaning that the filter predicates are not unique...?

Another approach is to analyze the filter and make sure it applies a single `=` constraint to a key. It is not a valid record page URL if it does not encode a unique key constraint, in my opinion.

**Comment by robes** [comment]
I think we can close this issue. I believe #1098 is the right way to do this, in conjunction with the associated ermrestjs issue.

**Comment by hongsudt** [comment]
duplicated with #1098.
