### ISSUE TITLE
Viewer: Vocab table values aren't loading in dropdowns when editing metadata

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#689]
@svoinea found that when editing the metadata for an image on the Viewer app, the dropdowns aren't loading the domain values from the vocab tables.

This might be because the first dropdown is unable to find table `image_grade_code`, which no longer exists in the `rbk` schema (why?). The app throws an error, causing the rest of the code that populates the other dropdowns in to not run in `viewer.app.js`.

**Comment by hongsudt** [comment]
If this is a quick fix, let's get this out of the way.

**Comment by howdyjessie** [comment]
@hongsudt So the issue is indeed because the table `image_grade_code` no longer exists. I suspect `image_grade_code` has been dropped in favor of this other table called `image_status`. Is this correct?

This bug only affects `dev.rebuildingakidney.org`. Staging and production servers still use the `image_grade_code` table. All 3 servers should have _either_ `image_grade_code` or `image_status` for consistency.

**Comment by howdyjessie** [comment]
From a face-to-face conversation I had with @hongsudt, we've decided to use `image_grade_code` across all servers.

**Comment by howdyjessie** [comment]
In addition to renaming `image_status` in catalog 1 of dev rbk to `image_grade_code`, the table's `term` column was changed to `code`.

This bug has been fixed and I've confirmed it with Serban. No changes to Chaise code were made.
