### ISSUE TITLE
Bootstrap tooltips do not render correctly

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#69]
Quoting @crisaless: 

"Img1 - tooltip shows all the way to the left and unstyled

Img2 - plus you can scroll down below the footer and see the other tooltips living there. Shows up in this kind of code:

`<div role="log" aria-live="assertive" aria-relevant="additions" class="ui-helper-hidden-accessible"><div style="display: none;">This link stores your search results as a URL. Right click and save.</div><div style="display: none;">This link stores your search results as a URL. Right click and save.</div><div style="display: none;">This link stores your search results as a URL. Right click and save.</div><div style="display: none;">This link stores your search results as a URL. Right click and save.</div><div style="display: none;">This link stores your search results as a URL. Right click and save.</div><div>This link stores your search results as a URL. Right click and save.</div></div>`"

I cannot reproduce this bug on my own installation. Does anyone else see this in theirs? @svoinea @robes

![image](https://cloud.githubusercontent.com/assets/4585431/10142515/0b5aea68-65c8-11e5-9b94-d343f97dd499.png)
![image](https://cloud.githubusercontent.com/assets/4585431/10142518/1094c224-65c8-11e5-847e-a28eef504c65.png)

**Comment by karlcz** [comment]
Also buried in that HTML blob is: `This link stores your search results as a URL.` which is the wrong description for the bookmark.

It saves the search *criteria* and not *results*. This distinction may become signficiant once we start seeing data updates happening more often, since those updates may change what results appear in a bookmarked query.

**Comment by howdyjessie** [comment]
Very true. Fixed wording in [this commit](a108be7b42e3f3bb1d5c35db58bae2d391532c88).

**Comment by crisaless** [comment]
I see that jquery-ui-tooltip.js is also being pulled into chaise so it may be a jquery angular conflict...

**Comment by crisaless** [comment]
Another thing I noticed is that the chiclets for a chosen attribute is using a tooltip function that looks like the ones we don't like - the formatting works well in this case (when you hover over the chiclet's value, the full list of values appears underneath lined up with the left side of the screen). Here is the output for the corresponding <span> tag:

<span ng-attr-title="{{facetResults.displayTitle(facet)}}" class="filter-item-value ng-scope" ng-if="facetResults.if_type(facet, 'enum')" title="8q24, ABCA4, Alk5, BMP4, COL1A2, CTGF, Erk2, FGF10, IRF6, MSX1, NOG, Smad4, SOX4, SOX5, Tgfbr2, VAX1, ZFP503">

It's looking like this is what might be interfering with the other tooltips...

**Comment by crisaless** [comment]
My code paste didn't work. Here's a screenshot of what I'm talking about.
<img width="1280" alt="chiclet-tooltip" src="https://cloud.githubusercontent.com/assets/8965132/10233703/0300973a-6845-11e5-9a3e-5d7ed7b28178.png">

**Comment by howdyjessie** [comment]
These chiclet tooltips are also not appearing on my local installation :confounded: 

An update: I'm working on implementing a directive per your email but the bootstrap tooltips still aren't working for me..

**Comment by howdyjessie** [comment]
@crisaless I don't see these weird tooltip alignments (showing up on the left side and bottom of the screen) on @svoinea's installation either. (They just appear as plain, regular title descriptions when you hover over them). Perhaps these weird tooltips are the result of interference from your stylesheets?

**Comment by crisaless** [comment]
Ok, I'll investigate that on my end.

**Comment by crisaless** [comment]
Fixed it on the facebase side - standardized the calls to the css and js files with how they're linked in the chaise version and that seems to have fixed the issue. Next step is adding the bootstrap data attributes and see how they render now.

**Comment by crisaless** [comment]
The bootstrap tooltips still render strangely - it's the arrow of the tooltip that is misplaced on some of the ones using data-placement="bottom". Looks like a newer version of bootstrap fixes it but I have to do some more testing.

**Comment by crisaless** [comment]
the original bug was fixed. there's still an issue with bootstrap tooltips arrows rendering strangely when you hover over the views. as I noted above upgrading the version of bootstrap we're using should fix that. I'll open a new issue for that and close this one.
