### ISSUE TITLE
Parse out modifiers systematically

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#693]
The `UriUtils` factory should parse out the modifiers in a url more systematically by storing any params encountered in the URL inside a dictionary/object. In `parseURLFragment()`, we currently look for specific modifiers that we know are supported in ermrestjs (e.g. `@sort`, `?limit`). 

Instead of scanning the same string repeatedly to find specific modifiers, it would be more flexible to scan the string once and store all params inside an object. Then, when specifying logic for specific modifiers, we can simply check if the modifier exists inside the object.

**Comment by hongsudt** [comment]
@howdyjessie Can you check whether we have done this? I think @shinyichen has provided a function for this.

**Comment by howdyjessie** [comment]
@hongsudt Yep I see there's a `queryParams` object inside `context`, which has all the query parameters (`?copy`, `?limit`). And then paging modifiers (`@after`, `@before`) go inside `context.paging`; sort modifiers (`@sort`) are in `context.sort`.

I'll close this issue now.
