### ISSUE TITLE
409 Conflict error when searching on a path with a join

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#696]
Not sure if that title makes sense or not.

_This bug only seems to be reproducible on the facebase `legacy:dataset` table after getting to that table by joining from another entity set._

To recreate:

- view a person record in the _record_ app
- then click on the "View All Record" link for the nested table of Datasets
- that will take you to the _recordset_ app for the Datasets linked to that person
- enter something into the search box (e.g., "mouse") and click the search icon

Here is an example:

https://dev.isrd.isi.edu/chaise/recordset/#1/legacy:person/username=David%20E.%20Clouthier/(username)=(legacy:dataset:owner)/*::ciregexp::mouse@sort(id)?limit=15

**Comment by karlcz** [comment]
The actual request causing the 409 is:

    https://dev.isrd.isi.edu/ermrest/catalog/1/attributegroup/M:=legacy:person/username=David%20E.%20Clouthier/(username)=(legacy:dataset:owner)/*::ciregexp::mouse/F3:=left(owner)=(legacy:person:username)/$M/F2:=left(project)=(legacy:project:id)/$M/F1:=left(thumbnail)=(legacy:file:id)/$M/id;M:=array(M:*),F3:=array(F3:*),F2:=array(F2:*),F1:=array(F1:*)@sort(id)?limit=16&cid=recordset

if I understand what it was trying to do, it has bound the table alias `M` to the wrong element of the path. It should instead be:

    https://dev.isrd.isi.edu/ermrest/catalog/1/attributegroup/legacy:person/username=David%20E.%20Clouthier/M:=(username)=(legacy:dataset:owner)/*::ciregexp::mouse/F3:=left(owner)=(legacy:person:username)/$M/F2:=left(project)=(legacy:project:id)/$M/F1:=left(thumbnail)=(legacy:file:id)/$M/id;M:=array(M:*),F3:=array(F3:*),F2:=array(F2:*),F1:=array(F1:*)@sort(id)?limit=16&cid=recordset

**Comment by RFSH** [comment]
@shinyichen fixed this issue and the url is now working.

**Comment by hongsudt** [comment]
OK. I am moving this to review. @robes please review and close.
