### ISSUE TITLE
Column tooltips in recordedit are hidden

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#698]
The tooltips that appear when the user hovers over the column name on the left are hidden by the input fields when the form is shrunk down, as seen below.

![image](https://cloud.githubusercontent.com/assets/2932600/19874565/7b9b0e8e-9f83-11e6-9df3-73ca4ab7f9e8.png)

**Comment by howdyjessie** [comment]
PR #721 has been merged into `recordedit2-master`, closing now.
