### ISSUE TITLE
Add a progress indicator when updating the results

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#7]
We should have one of those spinning progress indicator icons displayed whenever the search results are being updated. Especially for clients on a bad wifi or wireless data connection, the latency can be fairly high and the site does not give an indication that anything is happening.

**Comment by mikedarcy** [comment]
This should be active on initial page load as well, perhaps with a message like "Please wait while the application is initialized..."

Databases with big schemas take longer to process initially while the code is parsing the schema metadata. This is mostly client side latency from what I have observed. 

Also, the initial set of queries posed to the backend can take a while with a larger database. This, combined with the initial schema processing can cause the browser to freeze on first load and in extreme cases cause the dreaded "long running script" dialog box to appear.

**Comment by karlcz** [comment]
These sound like separate issues... could you file them?

How big a schema causes noticeable client-side delay?  Sounds like an
algorithmic problem.

Any subsequent queries to the server that may take variable amounts of
time should really be handled asynchronously rather than blocking the
client script, e.g. scripted event finishes and server responses get
handled later to update UI state.

**Comment by robes** [comment]
How is this progress indicator task going? There's an angular slider server btw that bennett is using in the details (chaise/record) page that I'd think could work here also.

**Comment by robes** [comment]
How is this progress indicator task going? There's an angular slider server btw that bennett is using in the details (chaise/record) page that I'd think could work here also.

**Comment by svoinea** [comment]
The spinner is currently implemented on loading the search page.

**Comment by robes** [comment]
This seems done to me. Unless we need to have the spinner any time the users adds a filter to the current search?
