### ISSUE TITLE
bogus 401 unauthorized pop-up during init of recordedit2

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#703]
On synapse-dev I get a bogus pop-up about not being authorized to update entities, but if I dismiss it I can still use the app.

If this is consulting ermrest ACLs, I suspect it isn't understanding that ownership implies write access?

**Comment by jrchudy** [comment]
This issue is resolved by the commit that @robes made. This was merged into the `recordedit2-master` branch when PR #713 was merged.
