### ISSUE TITLE
FK modal isn't limited to window height

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#705]
When showing a longer domain, the modal makes the page longer and introduces a whole-page scrollbar which pushes the bottom modal buttons off-screen.  I think the modal should be limited and introduce a scrollbar only for its results pane.

**Comment by hongsudt** [comment]
I agree with Karl.. This is make it quite difficult to navigate. 
Is it possible to make the modal expandable e.g. widen the screen width? If not, can we make it wider?

**Comment by jrchudy** [comment]
This issue has been resolved in PR #712. This was merged last night. Closing this issue.
