### ISSUE TITLE
A visible column (not psuedo) when part of FK shows broken input controls

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#706]
In this case, it uses the pseudo column displayed, but the entry is editable. The buttons do nothing. 
@karlcz please provide a link for an example.

**Comment by karlcz** [comment]
The synapse-dev system can show an example (until I update its annotations) in the Subject table. Along with the text-entry boxes, there are broken buttons that don't do anything. 

Later, if we get appropriate hueristics, I think this non-composite and non-overlapping FK scenario should just automatically substitute the corresponding pseudo-column. That would be a change in ermrestjs.

I think the change in Chaise needs to be that if we don't have a psuedo column with all the related features, we should show a simple data input just like other non-FK columns.

**Comment by jrchudy** [comment]
There is an example of this occurring [here](https://synapse-dev.isrd.isi.edu/chaise/recordedit/#1/Zebrafish:Subject). 

The case here is that the foreign key is being interpreted as one but it isn't being replaced by it's pseudo-column. This causes chaise to break when trying to call `column.reference`.

As @karlcz mentioned, Chaise needs to handle this properly. If the pseudo-column doesn't have all of it's related features, Chaise should show a simple data-input.

**Comment by RFSH** [comment]
I think [this](https://github.com/informatics-isi-edu/chaise/blob/recordedit2-master/recordedit/form.controller.js#L391,L393) function is causing the bug. We should just check for `isPseudo` and not the actual foreign keys of the column. This flag ensures us that the column is replaced with pseudo-column.
