### ISSUE TITLE
adjusting mainContent width for wide screens

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#71]
Things are spacing out well for screens ~1250 pixels or less - but for wider screens/higher resolution windows, I want to adjust the column classes for greater widths. Basically, on wider screens, the main content won't be as wide as it ideally should be.

image 'col-lg-8' shows the default size for the main content using bootstrap class "col-lg-8" on a wide screen - the browser window width is 2330px

image 'col-lg-12' shows what it would look like in the same window if using the class "col-lg-12".

There are also a couple of other breakpoints in between.

Should be able to do this with some jquery

**Comment by crisaless** [comment]
re-adding the images referred to above.

'col-lg-8' example
![col-lg-8](https://cloud.githubusercontent.com/assets/8965132/11071075/2ac70314-879c-11e5-9f20-0e1d186f4e70.png)

'col-lg-12' example
![col-lg-12](https://cloud.githubusercontent.com/assets/8965132/11071094/45941a92-879c-11e5-84fc-d2aab75f7df5.png)

**Comment by crisaless** [comment]
Note that we've fixed this in FaceBase (in the jekyll /data/search/index.html.in file) with additional bootstrap xl-col class and javascript and it's looking good. Should test a vanilla chaise deployment and see if these changes would be useful there.

**Comment by robes** [comment]
@crisaless can we move this fix into the general chaise repo? has it already?

**Comment by crisaless** [comment]
just fixed this - I'll assign to you to review. Just test a non-facebase chaise deployment on a widescreen monitor (ie, 27" with 2560 x 1440 resolution). If you don't have one at the ready I know Carl should have that.

**Comment by robes** [comment]
okay, i could confirm on `dev.isrd.isi.edu/chaise/search/` that the pages are not expanding similar to facebase. Ironically, the record page on isrd-dev expands more than the facebase deployment.

@crisaless is that what you expect?
