### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#722]
When a user visits a recordedit page without authentication, a 404 is currently being returned. The 404 is returned  by the server (webauthn service) because there is no session resource for the current user, when they are not logged in.

The new logic that @jrchudy and @robes recently added to fix the race condition #703 added a conditional to handle getting the current session. But the promise chaining needs to be fixed so that we can allow anonymous access to the page _if_ the catalog allows anonymous writes. If not, it should automatically direct user to a login page.

See this block:
https://github.com/informatics-isi-edu/chaise/blob/fa9fa8cfee0eaa60255d52f6d4c927c0c8071333/recordedit/recordEdit.app.js#L56-L182

If it isn't obvious how to fix this, @robes can explain roughly what should be done.

**Comment by ljpearlman** [comment]
Is this the bug to watch for record returning 401 if the user isn't logged in, even if the system is set up not to require authentication?

**Comment by jrchudy** [comment]
You are correct @ljpearlman. That bug was related to this bug as well. I created that bug the other morning and have since fixed it for the record app. I'm almost done fixing this issue as well so recordedit should get proper error responses again.. (soon).
