### ISSUE TITLE
trying to edit an association table associated with an experiment throws an error on timestamp

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#727]
Error 400 Bad Request The request is malformed. Bad JSON array input. ERROR: invalid input syntax for type timestamp with time zone: "{"date":"2016-11-01","time":"12:21:07","meridiem":"PM"}" 

Here is the url.
https://dev.gpcrconsortium.org/chaise/recordedit/#1/experiments:experiment_link_sds_page/id=161@sort(last_modified_timestamp::desc::,id)

I can create but not update.. Note: this problem was in the previous record-edit as well.. and @howdyjessie has fixed this for the master branch. But last night, I was able to edit a record..

**Comment by jrchudy** [comment]
This issue is resolved in a recent commit to the `recordedit2-master` branch. Closing this issue.
