### ISSUE TITLE
table-display row_order unreliable in related entities?

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#731]
I added the row_order annotation on several tables to sort by ID in descending order, e.g. https://synapse-dev.isrd.isi.edu/ermrest/catalog/1/schema/Zebrafish/table/Subject/annotation

When I go to a page with many related entity sections, some do not seem to follow the sort.  Once again, I tried to double-check my annotations but it is possible I am missing some typo...

https://synapse-dev.isrd.isi.edu/chaise/record/#1/Synapse:Person/Full%20Name=William%20Dempsey

**Comment by shinyichen** [comment]
I see that Zebrafish:Subject annotation is sort by ID descending. And it is showing by ID descending. Is is another table that doesn't follow the sort?
