### ISSUE TITLE
Validation on foreign key fields

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#736]
@jrchudy commented on [Wed Nov 02 2016](https://github.com/informatics-isi-edu/ermrestjs/issues/272)

Foreign key fields that are marked as not-null need to be validated in the UI before the data is submitted to ermrest.

**Comment by karlcz** [comment]
Is this a duplicate of #525 and/or #500?

**Comment by jrchudy** [comment]
Correct, this is a duplicate of #500 and #525. Issue #500 was closed. I'm closing this issue so we can track all the development in #525.
