### ISSUE TITLE
Search / record linking broken

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#742]
I have a table that has both a primary key and a multi-column unique constraint. The search results link the primary key column to a record URL that uses the other unique constraint instead of the primary key to create the ermrest URL. If any of the columns referenced in the unique constraint is null, the result will be this error:

> Cannot read property 'displayname' of undefined 
> 
> Please check the URL or click OK to return to the home page.

You can see this at https://staging.rebuildingakidney.org/chaise/search/#2/Antibody:Antibody_Tests (if you want to see the null-column behavior, choose "McMahon's Lab" from the Laboratory attribute and then click on any row from the results).

This is happening on dev/staging/production for rbk. Dev is using the latest stuff. Staging is using versions tagged rbk-20161024 for all components. Production is using rbk-20161027, but that's basically the same as the staging version.

**Comment by ljpearlman** [comment]
Actually, I've removed the unique constraint on production to force it to use the primary  key (which is working). But you can still see the behavior on staging.

**Comment by jrchudy** [comment]
Thank you @ljpearlman. 

A note for who works on this going forward, this might be an issue with the app-link function. This could be a problem in the chaise code or in the ermrestJS code.

**Comment by hongsudt** [comment]
If this is the search app, it has nothing to do with ermrestjs. 

@ljpearlman If you set the comment annotation of the primary key column to title, the search app will use that explicitly for linking.

**Comment by ljpearlman** [comment]
@hongsudt the broken table already has this annotation:

```
   table_name   | schema_name | column_name | annotation_uri | annotation_value 
----------------+-------------+-------------+----------------+------------------
 Antibody_Tests | Antibody    | ID          | comment        | ["title"]
```

The link appears on that column, but what the link points to is a query build up from the other unique key. So it looks like the title annotation controls where the link goes, but not what the link points to.

**Comment by svoinea** [comment]
The link points to an unique key, selected randomly (more exactly the first one returned by the introspection). If you desire a specific unique key to be used for the `record` page, then I need to define an annotation in that respect and to do an update to the code.

**Comment by hongsudt** [comment]
Why can't you use what's defined under title?

**Comment by ljpearlman** [comment]
Can the search app distinguish between a primary key and another unique key? If so, I think using the primary key would make the most sense.

Also, it appears that the record link is failing because we're searching for null values. Is that an expected limitation, or a bug somewhere in record / ermestjs / ermrest?

**Comment by karlcz** [comment]
A "primary key" is just exposed as unique and also having not-null
constraints on the column(s).

In the newer apps, we use the following criteria to sort keys into
tiers, prefering the best match:

1. Prefer keys with not-null on all columns
2. Prefer keys with fewer columns
3. Prefer integer over text keys

We only use later criteria to sort among candidates which are tied in
the previous criteria.

**Comment by ljpearlman** [comment]
@karlcz are queries for null values supported? I'm just wondering whether this is one problem (not using the best possible key) or two (not using the best possible key and the query failing).

**Comment by karlcz** [comment]
You can query for null in ermrest with a different operator
(col::null:: which means "col IS NULL" in SQL).

But, null cannot be a key... in SQL, uniqueness constraints are not
enforced for nulls (or any partially null composite) so you could have
many rows which would match the same query, leading to very confusing
results or app misbehavior if you mistakenly tried to reference
exactly one row with a null key.

**Comment by svoinea** [comment]
The PK with the `title` annotation should have been fixed through the a650bac93d9053cc21dfcfe8969a7f0097f32af3 commit in the `chaise` repository.
Currently, you can test it using the https://dev.rebuildingakidney.org/~serban/chaise/search/#2/Antibody:Antibody_Tests link.

**Comment by ljpearlman** [comment]
That fixed the original problem, but now when I try to search the Person table (https://dev.rebuildingakidney.org/chaise/search/#2/Common:Person), I get 

```
ERROR: 400
ResponseText: 400 Bad Request
The request is malformed. Output column name "Email" appears more than once.
TextStatus: error
ErrorThrown: Bad Request
URL: https://dev.rebuildingakidney.org/ermrest/catalog/2/attribute/A:=Common:Person/$A/Full_Name,Email,ID,Email@sort(Full_Name,Email,ID,Email)?limit=1
```

I suspect this is because I this table has unique indexes with columns that overlap:

```
Indexes:
    "Person_pkey" PRIMARY KEY, btree ("ID")
    "Person_Email_key" UNIQUE CONSTRAINT, btree ("Email")
    "Person_Full_Name_Email_key" UNIQUE CONSTRAINT, btree ("Full_Name", "Email")
    "Person_Full_Name_key" UNIQUE CONSTRAINT, btree ("Full_Name")
```

(the name/email constraint is there to support a foreign key; postgres requires an explicit unique index for multi-column foreign keys even if each column in the key is unique and non-null).

**Comment by hongsudt** [comment]
The search app cannot handle composite keys.

**Comment by ljpearlman** [comment]
@hongsudt - This was working until today. One of the affected tables was the rbk Antibodies table (although it turns out the constraints that triggered the bug in that table were no longer necessary, so I removed them).

**Comment by svoinea** [comment]
This should work now based on the commit ff3d686da5c71e4ad197d893e0e730545717390d which avoids collecting "duplicate" PK.
I have tested it on https://dev.rebuildingakidney.org/~serban/chaise/search/#2/Common:Person

**Comment by ljpearlman** [comment]
Works for me, too. Thanks!
