### ISSUE TITLE
Attribute list on samples/all attributes seems messed up.

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#744]
@carlkesselman commented on [Thu Oct 06 2016](https://github.com/informatics-isi-edu/gpcr-project/issues/261)

See https://dev.gpcrconsortium.org/chaise/search/#1/experiments:sample select all attributes:

![image](https://cloud.githubusercontent.com/assets/3597150/19143471/803889dc-8ba4-11e6-8b94-72ddc4733922.png)

---

@hongsudt commented on [Fri Nov 04 2016](https://github.com/informatics-isi-edu/gpcr-project/issues/261#issuecomment-258513461)

@svoinea please fix this styling issue.. We see the same problem on multi-cellline entries.

**Comment by hongsudt** [comment]
@svoinea what's the status on this? Please work with @howdyjessie to fix the styling problem.

**Comment by svoinea** [comment]
![experiments_sample](https://cloud.githubusercontent.com/assets/1609577/20401595/4ea7c402-acae-11e6-9c8f-d0447a51b099.png)
This is an old issue that seems to have been fixed.
I have attached the screenshot on how it looks today on my Firefox browser.
