### ISSUE TITLE
Tests that rely on delete button

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#747]
The e2e tests that rely on the delete button being visible and clicking that button to make sure the user can delete the current record/entity, were marked as pending.

These tests are in `02-recordedit.delete.spec.js` and `record/helpers.js` (test names: "should show the action buttons properly" and "should redirect to data browser" under the `testDeleteButton` function).

**Comment by howdyjessie** [comment]
These tests have been written and merged into `recordedit2-master` via ee4f330. The tests are failing on Travis (but passing locally) due to PR #757 not being in `recordedit2-master` yet, but it will be later (today?).
