### ISSUE TITLE
Tests for pre-fill data

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#748]
The tests for pre-filling data in the `recordedit` form were marked pending. We changed the form input from an `input` to a `div` so this might be what caused this test to start failing.

The test in `record/helpers.js` under the `relatedTableLinks` function is "should have a Add link for a related table that redirects to that related table in recordedit with a prefill query parameter". The other test, "should pre-fill fields from the prefill cookie", is in `00-recordedit.add.spec.js`.

**Comment by howdyjessie** [comment]
The tests have been fixed via ed222bb and merged into `recordedit2-master`.
