### ISSUE TITLE
Summary text cuts off in card view

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#75]
![screen shot 2015-09-28 at 3 43 09 pm](https://cloud.githubusercontent.com/assets/4585431/10151001/0b534224-65f8-11e5-9310-8fb9e9ec34b0.png)

**Comment by carlkesselman** [comment]
I think it would be better to have the cards be a fixed length, and to indicate large text fields with a '...'  The purpose of the card is to provide just enough info to decide if you want a detailed view right?
