### ISSUE TITLE
Viewer using wrong value for accession id

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#750]
The viewer is using the `description` field instead of the `accession_number` field for the accession id displayed in the metadata view. I think it's probably just a typo:

```
<span ng-if="metadata.image.entity.accession_number">{{metadata.image.entity.description}}</span>
```

**Comment by howdyjessie** [comment]
I pushed the typo fix straight to master branch. This bug should be resolved now.
