### ISSUE TITLE
Cosmetic tweaks to record page for nested entities display

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#752]
We've had outside feedback that mirrors our internal review of the record app w.r.t. display of nested entities.

- [ ] use the same font for the (nested) table name as we use for the attribute names (i.e., light gray and smaller)
- [ ] use different icons for the expand/collapse indicators because the - / + are very weak affordances.
- [ ] move the separator line to the bottom of each nested entity set so that it serves as the separator between nested tables similar to how the separator line is used as a separator between attributes (for the entity attributes that the page starts with)
- [ ] make the "View All Records" link be horizontally aligned with the (nested) table name

**Comment by hongsudt** [comment]
@robes Do we have a specific deadline for this change?

**Comment by robes** [comment]
end of november release for facebase, if possible

**Comment by hongsudt** [comment]
I disagree with the first bullet regarding the font size since the behavior of the nested table is different from columns in the main table. It has to be clear that the items are clickable.

**Comment by chiragsanghvi** [comment]
This has been done and merged in Master
