### ISSUE TITLE
Loading/refreshing page flashes Details page template

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#76]
When you load or refresh a page, you can see a brief glimpse of the details page. 

For users with slower connections, the details page appears for a longer period of time, but if their browser is loading a cached version then the details page only shows up as a glimpse.

![screen shot 2015-09-28 at 4 10 03 pm](https://cloud.githubusercontent.com/assets/4585431/10151326/68b3fb86-65fb-11e5-9ced-f0ebd590095d.png)

**Comment by carlkesselman** [comment]
I am still seeing this too when I follow a bookmark.  Fixing the history function does not seem to have solved this.

**Comment by robes** [comment]
hmm. this is the old details page. we can probably resolve this by pruning this vestigial page.

**Comment by svoinea** [comment]
Removed the detail template from the list of templates in the Makefile.

**Comment by svoinea** [comment]
Fixed in commit b1d6ea9057e871bc040a8b693e464cf3025fdbac.
