### ISSUE TITLE
Pseudocolumns wrap badly

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#760]
Contents of pseudocolumns runover the fake form field div.

For example,
![recordedit-bad-wrap](https://cloud.githubusercontent.com/assets/4202842/20158695/de073b6a-a690-11e6-8cae-d2b6537b2294.jpg)

**Comment by hongsudt** [comment]
@chiragsanghvi can you fix the div..

**Comment by hongsudt** [comment]
@chiragsanghvi please update the issues to the right status as you work on them.

**Comment by chiragsanghvi** [comment]
This is how it looks now. 

<img width="600" alt="screen_shot_2016-11-09_at_4 03 12_pm" src="https://cloud.githubusercontent.com/assets/1658152/20321272/c288fa7a-ab29-11e6-8a66-17c9c2390f89.png">
