### ISSUE TITLE
Set up pilot genome browser to see if that is sufficent for BAM and VCF files

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#764]
jbrowse.org

**Comment by hongsudt** [comment]
This task shouldn't go under the chaise repo.. I assume you want this to go
under rbk?

**Comment by carlkesselman** [comment]
Yes, sorry.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Nov 10, 2016, at 8:36 AM, Hongsuda <notifications@github.com<mailto:notifications@github.com>> wrote:

This task shouldn't go under the chaise repo.. I assume you want this to go
under rbk?

**Comment by carlkesselman** [comment]
Issue moved to [informatics-isi-edu/rbk-project #259](https://github.com/informatics-isi-edu/rbk-project/issues/259) via [**ZenHub**](https://www.zenhub.com/)
