### ISSUE TITLE
Chaise config not copied for Travis tests

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#765]
Chaise config is copied properly per test when you run the tests locally against the dev.isrd server. 

When you run the tests in travis the chaise config isn't copied per test. I noticed it was only using the sample chaise config.

**Comment by chiragsanghvi** [comment]
This was failing because the chaise-config was getting copied to some other place.

```sh
cp /home/travis/build/informatics-isi-edu/chaise/test/e2e/specs/navbar/data-dependent/chaise-config.js /home/travis/build/informatics-isi-edu/chaise/chaise-config.js
```

The path should have been
```sh
cp /var/www/html/chaise/test/e2e/specs/navbar/data-dependent/chaise-config.js /var/www/html/informatics-isi-edu/chaise/chaise-config.js
```
