### ISSUE TITLE
Some e2e tests are non-deterministic

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#766]
Some e2e tests rely on a value being set, but if that value isn't set it runs a different set of expectations. These e2e tests need to be split into multiple tests in separate specs. Having them in separate specs will allow us to test functionality one way in one spec and a different way in the other spec.

**Comment by hongsudt** [comment]
@howdyjessie @shinyichen @jrchudy @chiragsanghvi @RFSH can you guys review your test cases and generate issues if they need to be fixed...

**Comment by jrchudy** [comment]
We addressed this issue before christmas and completed the changes when the `recordedit` PR was merged early in January coming back from the break.
