### ISSUE TITLE
"Add Record" links to wrong table on association table linkages

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#768]
When you have a model that has associated entities, the "Add Record" will take you to the recordedit page to add another of the target entities rather than to add a new association.

Based on this figure:
`[Table 1] <-- [Association Table] --> [Table 2]`

If you were on the record page for an entity from `Table 1` and you see the nested tables section for `Table 2` entities, when you click on the "Add Record" link it takes you to the recordedit page to create a new entity for `Table 2`. This is a bug. What it should do is take you to the recordedit page to create a new entity for `Association Table` instead.

**Comment by robes** [comment]
@hongsudt if we could get this fixed we could have a workaround to let us move forward on the CIRM update.

**Comment by hongsudt** [comment]
@RFSH Can you look into this?

**Comment by hongsudt** [comment]
@robes Do you have the latest code?  Chaise/ermrestjs seems to handle the association table correctly in the gpcr use case.

**Comment by robes** [comment]
We are using the chaise master branch and it should be up to date.

I showed this to @jrchudy and he confirmed it was a bug. I can show to others.

For example, go to this record:

https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Specimen/ID=20160920-mKDCrlf1IRES21d-GA-0

Under the "Specimen Gene" section click "Add a Record". It takes you to record edit for the `gene` entity. It should go to the `specimen_gene` table to add an entity to the association table.

**Comment by RFSH** [comment]
The problem is that in ermrestjs, the context that is returning the association table is edit ([`ref.contextualize.entryEdit`](https://github.com/informatics-isi-edu/ermrestjs/blob/master/js/reference.js#L1213)) while in chaise we're using create context ([`ref.contextualize.entryCreate`](https://github.com/informatics-isi-edu/chaise/blob/master/record/record.controller.js#L98)). 

I expanded the logic in ermerstjs to include all the entry contexts (entry, entry/create, and entry/edit).

**Comment by hongsudt** [comment]
@howdyjessie please review this issue and make sure that the contexts are in sync.  I think what we have is now correct.. Ermrestjs should handle all editing contexts and that link in chaise should be create.

**Comment by howdyjessie** [comment]
It does look like Aref's fixed it in informatics-isi-edu/ermrestjs#283. I tested on schema `legacy` on dev.isrd for the association table link among `[dataset] <-- [dataset_organism] --> [organism]`, and the Add link showed me a RecordEdit page for `dataset_organism`.
