### ISSUE TITLE
Bad encoding of row name (used as title of the entity) on record page

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#769]
We have an attribute value, our identifier column `ID`, that has a value with an `'&'` character in it. We also use that column as the row name of the entity. However, on the _title_ of the record app the `&` gets (double?) encoded as `"&amp;"`. @svoinea has tried a few approaches which are discussed here:

https://github.com/informatics-isi-edu/cirm-project/issues/55

Example of this can be seen here:

https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Experiment/ID=20160914-H%26ENone-JAM-0

And the annotations for that table can be seen here:

https://cirm-dev.isrd.isi.edu/ermrest/catalog/1/schema/Microscopy/table/Experiment/annotation

If its not a bug in the `record` app, then we really need some guidance in the documentation. We've both read this wiki page and not figured it out.

https://github.com/informatics-isi-edu/ermrestjs/wiki/Template-and-Markdown-Guide#encoding-variables-for-url-manipulation

**Comment by chiragsanghvi** [comment]
@robes The problem is the `&` is getting escaped. If you don't want the value of the attribute to be escaped simply use syntax as mentioned [here](https://github.com/informatics-isi-edu/ermrestjs/wiki/Template-and-Markdown-Guide#disable-escaping) i.e.
```js
{{&ID}}

//or

{{{ID}}
```

**Comment by svoinea** [comment]
@chiragsanghvi The current annotation is:

```"row_name" :{"row_markdown_pattern":"{{{ID}}}"}```

The value of the ```ID``` is ```20160915-H&ENone-GA-0```. 
In the title it gets rendered as ```20160915-H&amp;ENone-GA-0```.
Otherwise, it is rendered properly in the ```detailed``` or ```compact``` contexts.

I tried also:

```"row_name" :{"row_markdown_pattern":"{{&ID}}"}```

or:

```"row_name" :{"row_markdown_pattern":"{{ID}}"}```

or:

```"row_name" :{"row_markdown_pattern":"{{#escape}}{{{ID}}}{{/escape}}"}```

The result was the same.

**Comment by hongsudt** [comment]
Yeah.. This is probably a bug since we don't have the logic that render column header in html. 

@robes should we have another property `row_name_is_html` to indicate whether the row name should be rendered as html? We will need the same thing for column.displayName since the column displayname can be annotated with a markdown pattern. Should we refactor the code to return a row_name as an object which contains a display name and whether it is an html?

**Comment by robes** [comment]
@hongsudt Maybe we can discuss at our next stand up. I'm not sure I fully understand the issue.

**Comment by shinyichen** [comment]
Can we discuss this together? I am not sure if @robes and @hongsudt are talking about the same thing. And the example link is giving me 403 error.

**Comment by robes** [comment]
@shinyichen right, hongsuda and I were talking about different things. she was talking about the column headers and I was talking about the row name/title that appears at top of the record page.

**Comment by chiragsanghvi** [comment]
@robes I just tried the same column value with unescaped syntax. And it works [here](https://runkit.com/chiragsanghvi/57b4b5f94c7bbd13004b43f6).

I am unable to access the above url's due to permissions.

**Comment by robes** [comment]
@chiragsanghvi The problem might be if the record page is not recognizing that the value should be treated as html?

**Comment by chiragsanghvi** [comment]
@shinyichen @robes Yes, it is not rendering it as HTML. https://github.com/informatics-isi-edu/chaise/blob/master/record/index.html.in#L36. We need to add `ng-bind-html` here for recordDisplayname

**Comment by robes** [comment]
@chiragsanghvi @shinyichen The only question is whether we need a flag to indicate whether it should be treated as html. In this case, (afaik) the `tuple.displayname` can only be defined via the `row_markdown` annotation (correct me if I'm mistaken), then it should be safe always to assume that the row name can include html.

But note that this is _not_ a valid assumption for model element displayname's such as the line right below: https://github.com/informatics-isi-edu/chaise/blob/master/record/index.html.in#L36.

**Comment by shinyichen** [comment]
I see that tuple.displayname comes from a utility function which return a string of raw text or HTML. Other places that use this utility function assumes the result is HTML. Easiest fix is to always display it as html. Or I can add a flag.

**Comment by hongsudt** [comment]
We have decided that to always treat the row name as an html at the chaise level.. However, at the ermrestjs level, if the row-name is not derived through a markdown annotation, it should be html-escaped.
