### ISSUE TITLE
Default Active Facets

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#77]
Currently, we have an annotation for providing a prefered ordering of facets that should be displayed.  This should be extended so that the default ordering is dependent on current facet set.  Perhaps what we want is a simple filtering precondition the selects a ordering based on what filters are currently applied.  The example presented from facebase is if you are looking for genes, then you shouldn't include somite count.

It could be argued that this might be better fixed by a proper model.....

**Comment by robes** [comment]
moved to wishlist
