### ISSUE TITLE
Add analytics to approriate Chaise applications

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#771]
FaseBase has a requirement that we track downloads of assets.  I would propose that we use accomplish this be instrumenting Chaise applications to publish asset download stats to Google Analytics.

We should also think about instrumenting Chaise code so we know what users are doing with respect to interactions with the UI.  Just tracking ERMRest queries is not going to provide the information we need and this should probably be integrated into ERMRestJS

**Comment by hongsudt** [comment]
I am closing this since #1389 is more concrete and will address this issue.
