### ISSUE TITLE
count of entities for nested tables is misleading

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#776]
The count of entities maxes out at the limit for display in the nested entity table. For instance, you might have 100s of related entities but you configure the limit to 25. On the record page it will show you "Nested Table Name Here (25)".

This leaves the user not knowing:
- does this mean I am seeing all 25 related entities, or
- am I seeing 25 out of `some unknown number` of entities?

We know it is the latter but users would not. We may need to lazily get the count so the user has an indication that there are more records available.

**Comment by bugacov** [comment]
And also when going into the "View all records" table doesn't seem to be an
idea of count in that view

**Comment by hongsudt** [comment]
What about using 25+? To indicate that there are more and we don't have to try to go through all the rows to get an aggregate..

**Comment by howdyjessie** [comment]
PR #797 has been merged into master, closing this issue now.
