### ISSUE TITLE
icon missing when toggling the show/hide related entities

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#779]
Go here:

https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Scan/id=35

1. Click 'Show all related records'
2. Click 'Hide empty related records'

Now the icon for the 'Show all related entities' is missing.

**Comment by hongsudt** [comment]
@howdyjessie Please move this to review if this feature is done.

**Comment by howdyjessie** [comment]
@robes I've pushed for the fix for this to `master` (it was a small typo).
