### ISSUE TITLE
create "add" button into the search directive

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#784]
When the add button is clicked, a new tab is opened with recordedit. After the addition is complete, the newly added value need to be populated in the search directive. 

@robes @chiragsanghvi We discussed that a search directive can monitor some event in the submission. Please provide some detail in this issue.

**Comment by shinyichen** [comment]
Update this to use cookie to monitor event.

**Comment by hongsudt** [comment]
@shinyichen There should be a tooltip associated with the add button. After the add button is done, we should delete the add button from the recordedit page.

**Comment by shinyichen** [comment]
I think your second suggestion about removing the button is kind of strange. Even though it's not likely user will add another record, but it's strange to prevent user from adding another record.

**Comment by hongsudt** [comment]
Sorry.. That's not what I meant. I meant to remove the add button that we currently have on the recordedit page itself, so they won't be adding a new item without going to the search directive.
