### ISSUE TITLE
Blank tables appear before data is loaded

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#787]
For example:

https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:User/Initials=JJG

The nested table for experiments will be displayed with all empty cells, and then after a second or two the data will be populated in the table in one flash.

**Comment by robes** [comment]
Actually this appears to be a problem in the recordset directive because this behavior is also on the recordset app too.

For example:

https://cirm-dev.isrd.isi.edu/chaise/recordset/#1/Microscopy:tissue/id=3/(term)=(Microscopy:Specimen:Tissue)@sort(ID)

**Comment by shinyichen** [comment]
I got table "User" and table "tissue" not found errors.

**Comment by shinyichen** [comment]
We made each table cell a directive to handle ellipses. I think it's blank while running the ellipses code. Adding @chiragsanghvi into the discussion.

**Comment by shinyichen** [comment]
I played around with it and it seems to be simply the HTML is loaded while data is still being fetch. I will check how to fix it.
