### ISSUE TITLE
Sort annotation

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#788]
Seems like we need an annotation to set the default sort order for a recordset. Here's an example use case. In CIRM we have a record page for each User. It has all the nested tables for that user's data including Experiments, Specimens, Slides, Scans. Ideally, when they view their page, they will want to see their Scans sorted from most recent to least recent.

This might even be an annotation on the _constraint_ rather than the table, because given the example above that might make sense to sort Scans by descending order on the timestamp _within the nesting context_ of the User table. But it might not be the desired sorting in other contexts.

**Comment by karlcz** [comment]
we already have 2016 Table Display row_order field for this purpose
and it is in use in multiple projects.
