### ISSUE TITLE
Edit / Preview for markdown data entry

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#794]
I think we can safely predict that our users will need to be able to 'preview' their markdown text (if possible) during data entry. Otherwise they have to hit Submit, then look at the record display, and then hit edit, to fix every typo in formatting.

The github interface itself might be a good UI to copy. It has tables for "Write" and "Preview". Or... maybe there's a markdown editor widget we can use. In fact, does Github make this editor widget available in open source?

**Comment by jrchudy** [comment]
[Here's](https://github.com/toopay/bootstrap-markdown) a repo that has a markdown editor that has the look and feel of bootstrap.

**Comment by amitjha21** [comment]
Public function `ERMrest.renderMarkdown().`  is now in use to render markdown in Live Preview. It takes care of superscript/subscript.
