### ISSUE TITLE
Buttons vs links in Chaise apps

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#798]
This continues from [issue #782](https://github.com/informatics-isi-edu/chaise/issues/782#issuecomment-262390637), where @robes said:

>One other thing. I believe that karl and hongsuda felt that everything except "Permalink" should use a style that looks more like a button than simply a link. They felt that simply looking like a link didn't give the user the right indication of its affordances.

In the front-end standup today, we discussed whether we should be using buttons or links in our Chaise apps. In Record, we use links (e.g. Add, Edit, Delete, Show All...) while in RecordEdit we use buttons (e.g. Submit Data, Delete) to indicate the similar actions a user can take. 

For the sake of consistency, we need to decide on a unified UX to expose these actions to Chaise users. At the end of the meeting, we decided to punt until next week when everybody will be back in office and can weigh in on this; this issue can track that discussion.

**Comment by hongsudt** [comment]
I am marking this as a wishlist. We all are kind of aware of the consistency issues, and hopefully, we can eventually merge on consistent style.. I don't see us spending a lot of time refactoring all apsp on this.
