### ISSUE TITLE
navigation not working on record view page

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#80]
For instance from a details page displaying facebase dataset details.

The link for an age stage (e.g., E10.5) seems to have the correct link:

http://vm-dev-030.misd.isi.edu/chaise/record/#1/legacy:mouse_age_stage/term=E13.5

However, when you click the link the page shows the "loading" spinner but doesn't navigate to that page.

And then again from that page in the nested table you have a link to based on the ID of the row (entity) with a link like this:

http://vm-dev-030.misd.isi.edu/chaise/record/#1/legacy:dataset/id=1566

The link looks correct but if you click it the page again just shows the "loading" spinner but doesn't actually change its contents.

**Comment by bennettl** [comment]
Should be fixed with the latest push
