### ISSUE TITLE
Font Awesome scripts

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#800]
We decided to move away from font awesome and use bootstraps glyphicons. I noticed that font awesome is still loading css rules that are overriding bootstrap css rules.

![image](https://cloud.githubusercontent.com/assets/2932600/20692346/19f5bf34-b58c-11e6-8b26-06662e42b2bd.png)

**Comment by chiragsanghvi** [comment]
I think this is  fixed by @howdyjessie but hasn't been merged due to the font-file issue.

I have fixed the issue and pushed it to her branch. Changes can be seen here
https://dev.isrd.isi.edu/~chirag/chaise/recordset/#1/legacy:dataset@sort(accession,id)?limit=15

**Comment by howdyjessie** [comment]
Yep @chiragsanghvi is correct. The branch in question is `update-icons`, and this issue is tracked by #789. Now that @chiragsanghvi fixed the font file warnings I had a problem with earlier, I've opened PR #804 for review, and I'll close this issue for now to avoid duplicating #789.
