### ISSUE TITLE
create reusable directive for a number input

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#806]
This directive can be used in the recordedit and faceting. 
- integer
- float

**Comment by jrchudy** [comment]
While writing this directive, I realized that float and integer can't be handled in the same directive. Float will require a separate directive for showing properly.

**Comment by jrchudy** [comment]
Moving this issue to round 2.

**Comment by RFSH** [comment]
An [input-switch](https://github.com/informatics-isi-edu/chaise/blob/master/common/inputs.js#L360) has been recently implemented that will create an input for any type of columns. This includes numbers too.
