### ISSUE TITLE
add isrd-tester group to the catalog on the dev.isrd

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#810]
@robes can you add the group to the catalog? If not, would @svoinea know how to do this?

**Comment by robes** [comment]
@hongsudt add isrd-tester for? read or write or both?

**Comment by robes** [comment]
@hongsudt and... add the group to _which_ catalog?

**Comment by hongsudt** [comment]
@robes we should allow isrd-testers to read/write to all catalogs on the isrd test server.

**Comment by robes** [comment]
documented here: https://github.com/informatics-isi-edu/ermrest/blob/master/api-doc/rest-catalog.md

we need to know what is the URI for the isrd-testers group.

**Comment by robes** [comment]
A script like this will do it locally:

```
#!/bin/sh
# 1 - database
# 2 - acl
# 3 - rolename (like a globus uri)
psql -c "insert into _ermrest.meta (key, value) values ('${2}', '${3}');" ${1}
```

It can be run like:

```
isrd-dev::ermrestddl[~] ./update_acl.sh facebase-legacy "content_write_user" "https://auth.globus.org/9d596ac6-22b9-11e6-b519-22000aef184d"
```

If the acl already exists, it will fail like this:

```
ERROR:  duplicate key value violates unique constraint "meta_key_value_key"
DETAIL:  Key (key, value)=(content_write_user, https://auth.globus.org/9d596ac6-22b9-11e6-b519-22000aef184d) already exists.
```

I put that script under the `ermrestddl` user on 'dev.isrd.isi.edu'.

I ran the test on all the original catalogs like `facebase-legacy`, `facebase-isa`, `rbk`, `gpcr` and they already had those permissions set. I ran on one of the newer `_ermrest...` catalogs and the first one did not have the perms -- does now.

Anyone can do this for any catalog they create.

**Comment by hongsudt** [comment]
@svoinea has helped us set this up.. I also put the howto to the chaise wiki page. https://github.com/informatics-isi-edu/chaise/wiki/Ermrest-Howto-(set-ACL,-cookies)

I am closing this issue since you guys can now set it up yourselves. Here is the isrd-testers GUID https://auth.globus.org/9d596ac6-22b9-11e6-b519-22000aef184d
