### ISSUE TITLE
Convert current tooltips to Bootstrap tooltips

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#816]
Each tooltip needs to be replaced with the Bootstrap implementation for tooltips. This is a more robust implementation and handles the oddities we are seeing with our current ones.

This requires adding `tooltip-placement`, `tooltip-append-to-body`, and `uib-tooltip` to the elements that should have tooltips and removing the existing tooltip elements.

**Comment by howdyjessie** [comment]
PR #897 has been merged, so closing this issue now.
