### ISSUE TITLE
More/less ellipses non-deterministic on page load

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#819]
See https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Behavior@sort(Image%20Date::desc::)

1. On a fresh page load w/ empty browser cache, I see no more/less ellipses on the rows with thumbnail images.
2. On a reload, I see thumbnails truncated with a "...more" control below them.

One time, I even saw a mixed rendering where some rows had a truncation control and some rows were showing full thumbnails without any "...less" control (like in case 1).

So, I think there is an async initialization bug in this feature that depends on resource load times.  I see this on firefox.

**Comment by jrchudy** [comment]
I cannot reproduce this issue in Chrome. 

What I think could be happening is that the renderer for firefox is rendering the angular template for the ellipsis directive before the images finish loading. So they load and show at their full size. 

But when you go to this page with the images cached everything appears properly, which leads me to believe that the images load before the ellipsis directive when the data is cached.

**Comment by chiragsanghvi** [comment]
@karlcz This issue has been fixed and is in Master.
