### ISSUE TITLE
More/less ellipses needs fine-tuning

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#820]
On https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Behavior@sort(Image%20Date::desc::)

The "...less" control for an expanded thumbnail adds significantly more vertical height to the row. It has even more padding than the "...more" control. At minimum, it should be tightened up like the "...more" control.  Ideally, both controls should be even more compact so they don't add to the very problem they are trying to solve...

Also, I think the thresholds need to be a little smarter so that if a truncated value + "...more" control is nearly as tall as the original content (I'd say within 80-90%), the control is omitted and the full content shown instead. Having something truncated and replaced with this control when it basically fits is very frustrating to a user...

**Comment by hongsudt** [comment]
Please review.

**Comment by karlcz** [comment]
Master still has most of the bad behaviors I described originally.

1. The "less" and "more" divs are identical height but there is an extra vertical padding before the "less" which makes an expanded cell even more spread out.
2. The threshold doesn't seem to take into account the added height of the control to realize that showing the entire content would use less vertical space than a slightly truncated content plus "...more". Test with content that is just a few pixels taller than the threshold.

**Comment by hongsudt** [comment]
@chiragsanghvi this issue still exists. Please fix.

**Comment by chiragsanghvi** [comment]
@karlcz The threshold approach is not required. You can simply set the height to the threshold height you're looking for. 

Currently the more button height is not considered when we consider the height. The calculation considers the actual element height.

You see the more button, because the height is actually greater than the allowed height.

I tested the behavior on the above link, and the image itself has a height of 170px and the threshold is 160px. Thats the reason you see a more link. If you want it to be rendered completely then set the max-height as 170.

**Comment by karlcz** [comment]
I think you're missing my point.

The version of the row with the "...more" button should *never* be taller than the original content.

So whatever the threshold, once activated this mode should truncate the content to be the threhold height *minus* the extra space needed for the "...more" control.

**Comment by chiragsanghvi** [comment]
@karlcz Oh,  I got it wrong. I have made the changes to consider the more button too and added the support to disable more-less behavior as requested by @mikedarcy and @robes .

You just need to set the property `maxRecordsetRowHeight` property to the threshold height in the chaiseConfig. If this property is not set then more-less behavior will not be enabled.

Changes can be viewed here - https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Behavior@sort(Image%20Date::desc::,ID)?limit=25. I have set the `maxRecordsetRowHeight` to `160` in the chaiseConfig.

**Comment by hongsudt** [comment]
By default, the more or less should be enabled with reasonable default, not
disabled.  But the config can be used to turn off or change the height.
Please change accordingly.

There is another issue that will allow annotation to be applied at the
schema or table level, but that task is to be scheduled later.

**Comment by chiragsanghvi** [comment]
Merged in Master
