### ISSUE TITLE
markdown adds more vertical space to columns

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#827]
I happened to encounter a recordset result where some rows had only plain text and others had a markdown-rendered anchor tag (i.e. from using a guarded markdown pattern).

The table cell has a structure like this according to element inspector:

    td
      div ng-switch="val.isHTML"
        div class="showContent"
          span class="markdown-container..."
            p
              a href="my link"

it seems like the span element (markdown container) above has extra padding below the anchor and its enclosing paragraph.  This makes all rows taller than they need to be when they contain markdown.

Edit: I am seeing this on firefox.

**Comment by chiragsanghvi** [comment]
@karlcz  This is fixed for recordset. Do you want me to handle the markdown content in record app too ?

**Comment by hongsudt** [comment]
@karlcz  please review and close the issue.

**Comment by karlcz** [comment]
This looks more consistent in master now.
