### ISSUE TITLE
use heuristics or annotations to hide primary key columns in record page

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#83]
see the chaise/doc guides. if we haven't addressed these we should.

**Comment by bennettl** [comment]
The schema ermrest returns doesn't seem to indicate a column is a primary key or not

**Comment by karlcz** [comment]
That's right, there is no distinction between "primary" or any other
unique key in ermrest. The original issue is really misstated and
should say to hide "internal" keys which requires a hueristic like
detecting that they are of serial type, which I think ermrest does
expose.

**Comment by robes** [comment]
Discussed with Karl. I'm going to add an annotation definition to flag uniques (i.e., keys) as "surrogate". Then the heuristic in Chaise should be to hide surrogate keys.

**Comment by bennettl** [comment]
The primary key column has the annotation ```hidden```, which is now used when hiding columns for the main entity on the record page.

**Comment by robes** [comment]
confirmed on dev
