### ISSUE TITLE
recordset (directive?) flashes on page refocus

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#831]
It seems like the recordset directive flashes a reload on ever refocus. I thought this would only do a reload _if_ it checked a cookie to see if it needed to do a refresh. Its very easy to recreate. Just open any recordset, switch to a different application window, then return to your browser.

**Comment by robes** [comment]
@hongsudt can we prioritize this for @shinyichen next on her list? its kind of jarring on the UX. i would imagine its a little thing to fix too.

**Comment by hongsudt** [comment]
@robes I am moving this to review. Please review after @shinyichen PR is merged.
