### ISSUE TITLE
Consistent use of Tooltips throughout all Chaise applications

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#832]
This should probably become an epic for every page. We have inconsistent application of Tooltips throughout the UI. I would suggest that every control or link in the UI (proper) should probably have tooltips on them.

_Note_ this is distinct from the issue of what Bootstrap or native HTML5 style to use. This issue refers to the presence or absence of tooltips is inconsistent across the apps.

**Comment by hongsudt** [comment]
This issue is too broad. We need to list the page and icons/links that need tooltips. Going forward, every single icons needs to have a tooltip.
