### ISSUE TITLE
create a pseudo-column that contains a list of actions that users can do

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#838]
@hongsudt commented on [Thu Dec 01 2016](https://github.com/informatics-isi-edu/ermrestjs/issues/298)

- This column should be the first column (left most). 
- The column name should be "Actions". The value should be linkable icons (with tooptips) for `view`, `unlink` or `delete`, and `edit`.
- In the compact/brief context, if the related table is derived based on pure and binary association table, `unlink` should be provided, otherwise, `delete` should be provided. `Unlink` deletes an entry in the association table. `Delete` deletes the actual row in the table. 

@robes @karlcz I am making an assumption that we can determine whether the user can delete or create at the row level, which I am not sure whether it has to eventually be an asynchronous call or not. 
   

---

@robes commented on [Fri Dec 02 2016](https://github.com/informatics-isi-edu/ermrestjs/issues/298#issuecomment-264587093)

@hongsudt I think the reference api covers row-level security but of course that is not and cannot be implemented given the current mechanism that ermrest uses based on postgres row level security.

---

@hongsudt commented on [Tue Dec 06 2016](https://github.com/informatics-isi-edu/ermrestjs/issues/298#issuecomment-265342677)

@shinyichen we decided to implement this in chaise. I am moving this issue to chaise repo.

**Comment by shinyichen** [comment]
1) Is the action column always shown? For example, it may not be useful when in the popup selection modal. What should the visibility be based on? App decides?
2) Hide or disable edit/delete icons when not logged in?

**Comment by hongsudt** [comment]
For Glyphicons, what about: in the compact or compact/brief context,
* use glyphicon-list for view. 
* use trashcan for delete. For a related table that is generated based on pure and binary association,  user a remove icon (an x) for unlink instead of trash. This will delete the entry in the association table. The table should be refreshed upon deletion.
* use pencil for editing. Similar to pre-filled add, the related table should be refresh after the editing is done. 
 
In the search modal, use an ok font (check) for select. The rest can be the same as the compact context..

**Comment by hongsudt** [comment]
Instead of using cookies or local storage, we should try Karl's suggestion on DOM manipulation through windows.opener with the suggested flow below. With this, we don't have to deal with garbage collection. 

The general recordedit flow to avoid using cookies for signalling between parent and child:

1. parent defines entry points which consult local hashmaps etc.
   -- window.getPrefill(url) function
   -- window.childChanged(url, ...) function
2. parent sets up hashmap contents using child url as key
3. parent launches child (and captures window object to variable)
4. child starts to run
5. child does conditional prefill startup
   -- have window.opener, or skip prefill
   -- have window.opener.getPrefill, or skip prefill
   -- prefill = window.opener.getPrefill(child_location)
   -- prefill != null, or skip prefill
6. child does remaining app logic
7. child does submit/data change
8. child does conditional signalling after server update success
   -- have window.opener, or skip signal
   -- have window.opener.childChanged, or skip signal
   -- window.opener.childChanged(child_location, ...)
9. parent can poll (or listen?) for child window close status
   if needed

The parent sets up any per-child state before opening the child
window, so it is safe for the child to invoke the entry-point
functions any time after that w/o further synchronization.

The extra args to the childChanged() function could be etag or even
more details about the new/changed data?

The child can tolerate other launch modes where the parent is missing,
or does not have the task-specific entry-point function(s), or does
not have a hashmap entry for the child_location url.

The entry-point functions can potentially store info that the parent
can poll later, or even invoke further callback logic to perform
parent app state updates?
