### ISSUE TITLE
Precondition Failed (412) Error When Deleting Record

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/chaise#846]
Steps to reproduce this problem:
1) Open RecordEdit and submit a new record --> redirects to record page (keep this page open)
2) Open another RecordEdit and create another record. 
3) Go back to the first (Record) page and delete this record gives 412 Precondition Failed error.

The reason:
A new etag is generated when second create request was submitted. Now the first record has an out of date etag and forces it to fail.

Proposed solutions:
1) Better display of the error/information for the user at UI level. (This still seems inconvenient for the user)
2) emrestJS handle a failure case.
3) Karl's comment : it requires UX intervention in general case. ETag mismatch is a conservative signal that something *might* be out of sync. if you reload and find that the data you based your decisions on is still the same, you can just repeat with the newer ETag you found.  if you find a difference, you would want to prompt the user as in, "<displayname> has changed. Please review the latest content and resubmit your request." then present a refreshed page where the user can either delete again or make edits again without silently clobbering changes made in parallel.

**Comment by howdyjessie** [comment]
A sketch from @karlcz on how to deal with 412 errors:
![img_2144](https://cloud.githubusercontent.com/assets/4585431/23228069/19f54304-f8f0-11e6-9ce2-cf69a68afba8.JPG)

**Comment by howdyjessie** [comment]
In Chaise:
On 412 in UPDATE case in recordedit, 
- Show a modal that explains that some data has changed and user must review the data.
- Highlight the inputs where the current data in the DB isn't the same as what the user entered in the input. Show current data in blue text beneath input fields (like validation messages).

**Comment by howdyjessie** [comment]
PR #1006 has been merged, closing now.
