### ISSUE TITLE
e2e tests should use browser.wait instead of sleep

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#853]
In our e2e tests we are using `browser.sleep` in some cases and `browser.wait` in others. `Sleep` will stop execution for the amount of time specified whereas `wait` will stop execution until the condition is satisfied. `Wait` is more ideal because it can break out of the timer if the condition is satisfied.

**Comment by hongsudt** [comment]
The test owners should change their test to use wait instead of sleep.

**Comment by hongsudt** [comment]
From our standup meeting today, it seems like we are all done with this task.. So I am closing the issue.
