### ISSUE TITLE
Performance problems with Record app

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#857]
On FF, the CPU goes into 100% spin on this record.

https://dev.facebase.org/data/record/#2/vocabulary:species/id=2

The main distinguishing characteristic is that it has a lot of 'related' tables. Whether that is the cause is to be determined.

**Comment by howdyjessie** [comment]
Preliminary investigation: The page spends a lot of time (~40%) on running Angular digests. It would be a good idea to comb through Record (and RecordSet) to reduce the number of active watches (e.g. switch to more one-time bindings, tweak ng-repeats to add filters and limits).

**Comment by karlcz** [comment]
browser "performance" tracer shows it running a storm of setTimeout calls that look like they pulse once per
second in big bursts...

**Comment by jrchudy** [comment]
This issue is linked to PR #974.
