### ISSUE TITLE
align with heuristics or annotations for determining preview, thumbnail, files in record pages

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#86]
We display these - preview, thumbnail and files - data using the old annotations. we need to align with the new heuristics or annotations, which might not exist yet, so need to check on that first and see if some are missing from our guidelines.

**Comment by robes** [comment]
need to rethink this

**Comment by robes** [comment]
@hongsudt we should schedule this for next sprint

**Comment by hongsudt** [comment]
Won't fix in the current record. Move the functionality to record 2.

**Comment by hongsudt** [comment]
I am closing this as the topic is covered by other issues.
