### ISSUE TITLE
Image in column markdown overflows into adjacent column

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#861]
I have a column markdown pattern like:

   [![Behavior Plot]({{{Plot URL}}}){height=150}]({{{Plot URL}}})

and when the image retrieved from the Plot URL is wider than column, it overflows and looks like "background" material in the next column over to the right, i.e. text column content seems to overlay on top of the image.

This is on production using the tag synapse-20161205.1 on Firefox.

The element inspector shows some pretty strange element rectangle sizes for the nested elements of this table cell (from outside to innermost):

1. `td`: 500x187
2. `div ng-switch=val.isHTML`: 483x160
3. `div class=showContent`: 483x191
4. `span class=markdown-container`: 483x191
5. `p`: 483x150
6. `a href=Plot URL`: 661x20
7. `img src=Plot URL height=150`: 656x150

It is a 1204x275 raw image size before scaling due to the height=150 property.

**Comment by chiragsanghvi** [comment]
This has been merged in Master.
