### ISSUE TITLE
Horizontal scrollbar can be far off-screen

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#862]
On a smaller browser window, the tabular content is truncated ~~without any~~ with the horizontal scrollbar off-screen and requiring vertical scrolling to find it.

Also, the table content is actually truncated before the edge fo the window, i.e. the right margin is still visible which makes look less like a scrolling scenario.

This is on Firefox and I see it both on production and dev (hourly update) systems.

Edit: updated to reflect that scrolling is possible but the controls are off-screen and counter-intuitive.

**Comment by hongsudt** [comment]
@karlcz please check this again.

**Comment by karlcz** [comment]
I apparently just missed the horizontal scrollbar as it is way off-screen at the bottom of the table, so you have to scroll vertically before finding the control to scroll across.  I'll update the issue description.

I think this is a UX problem we should revisit at some point... I think other sites tend to avoid having an off-screen scroll, as this isn't a scenario frequently experience.  I am not sure if there are any simple fixes though... perhaps most sites just divide the window into panes so the long scrolling region has scroll bars at the edge of the pane (and always on screen)?
