### ISSUE TITLE
Remove hardcoded reference to vm-dev-030

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#87]
Can find them in a variety of places by searching:

https://github.com/informatics-isi-edu/chaise/search?utf8=%E2%9C%93&q=vm-dev-030&type=Code

For example:

https://github.com/informatics-isi-edu/chaise/blob/4405533360e37f4237778a36360cec050fa7b4d3/record/index.html#L29

and:

https://github.com/informatics-isi-edu/chaise/blob/4405533360e37f4237778a36360cec050fa7b4d3/record/assets/javascripts/app.js#L39

**Comment by bennettl** [comment]
Was just checking this now, seems like someone resolved it already.

**Comment by carlkesselman** [comment]
I think rob just replaced one hard coded solution with another. The correct solution need to be to set this at deployment time.

Carl

Sent from my iPhone

Dr. Carl Kesselman
Dean's Professor, Epstein Dept. Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Phone: +1 (310) 448-9338
Email: carl@isi.edu<mailto:carl@isi.edu>

On Oct 2, 2015, at 7:09 PM, Bennett Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


Was just checking this now, seems like someone resolved it already.

-

**Comment by robes** [comment]
actually serban went back in and fixed it with the window.location. but I think we may still want to get rid of that global variable.
