### ISSUE TITLE
Search should prefer primary aka not-null keys for paging

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#874]
When search chooses a key for paging, it should prefer a key that has not-null constraints on its columns over any key that lacks such a constraint.

Only a not-null key can reliably distinguish all rows to act as page boundaries.

@hongsudt @svoinea

**Comment by svoinea** [comment]
Defined a function to get a preferred unique key.
The key has the NOT NULL constraint and is not a composite key.

**Comment by svoinea** [comment]
@hongsudt The issue is ready for review. Please assign a reviewer.
