### ISSUE TITLE
Search produces invalid paging filters with null keys

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#875]
When search chooses a key that can contain nulls, it produces invalid paging filters such as `Columnname::ge::null` when it encounters nulls.  A null can never be used in a comparison (it will always return non-truth).

I suspect the code was trying to get rows *including or after* a null value when it produced this `::ge::` constraint, considering the NULLs last sort order we always perform in ERMrest.  The correct filter would use `Columnname::null::` in this case to get the same ordering effect.

@hongsudt @svoinea

**Comment by svoinea** [comment]
The problem was fixed by setting the adequate `::null::` operator for `NULL` values.

**Comment by svoinea** [comment]
@hongsudt  The issue is ready for review. Please assign a reviewer.
