### ISSUE TITLE
Edit converts boolean false value to null

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#876]
In edit mode, it seems like an existing false value or a newly chosen false value gets mangled into a null when I submit the data, so the record afterwards has a null for that column.  This doesn't happen for true, so I think either the app or the ermrestjs layer is failing to distinguish false from null.

**Comment by hongsudt** [comment]
After this issue is fixed, a test case should be added to cover this case.

**Comment by howdyjessie** [comment]
The fix for this has been merged into master via PR #920.
