### ISSUE TITLE
add total number of records found in the recordset

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#878]
On the resultset page, there should be a total number of records that match the specified criteria. This should be implemented asynchronously, so that the initial page load doesn't have to wait for it. 

To support this, we probably need an ermrestjs api to make an aggregate call to ermrest.

**Comment by robes** [comment]
We probably also need to consider making this optional either by config or by annotation

On large tables this is going to add a lot of overhead.

**Comment by karlcz** [comment]
We already have the async API to do it via promises.  We just need the app to launch this extra query and add the count to the page when it is ready rather than delaying page rendering until the count returns.

**Comment by karlcz** [comment]
yes, particularly a large table with row-level security can be 10-20x slower than one without...

**Comment by hongsudt** [comment]
By default, this feature should be on though since most of the tables do not have performance issue..

**Comment by hongsudt** [comment]
This is pending on informatic-isi-edu/ermrestjs#304.

**Comment by jrchudy** [comment]
Before total count comes back:
Displaying X records
After:
Displaying X from Y records

**Comment by jrchudy** [comment]
the corresponding PR has been merged. Closing this issue.
