### ISSUE TITLE
Record view (aka Details page) claims catalog does not exist, though it does

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#88]
Not sure why but on Safari the details / record page doesn't load the data while testing on Firefox it does. I'll attach a screen shot showing the url, the page display, and the error console.

Not sure if this could be related to #87 .

![chaise-record-404](https://cloud.githubusercontent.com/assets/4202842/10251427/7927b6c8-68e5-11e5-9c3c-ac767aa0ba79.jpg)

**Comment by bennettl** [comment]
Works for me now in Safari
![screen shot 2015-10-02 at 10 56 28 pm](https://cloud.githubusercontent.com/assets/1672224/10261688/de5d70be-6958-11e5-9923-cd0a70964ee4.png)
