### ISSUE TITLE
Sidebar: check and x

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#89]
We seem to have replaced the back button with two small icons with selected attributes.  These are pretty hard to figure out and are formatting incorrectly.  We need to use words here, not icons.  

1. Is it possible/desirable to have the search result reflect the current selection as soon as its made.
2. Will all this become moot as soon as we have the new search box with the details of the search (attribute/value) available. 

As it stands, I find it very hard to figure out what is supposed to happen or what I'm supposed to do.

**Comment by robes** [comment]
I felt it was a small intermediate step in the right direction, however there are a couple significant bugs:

- the check button should apply the selection and go back

- the X button should cancel the current selection and go back


However:

- the check button is closing the slide out and not applying the selection (its acting more like reset almost)

- the X button is applying the selection and going back (it's doing what check button should do)


I agree we should get labels on these.


What you are asking for, to have the selection immediately. I agree. I'd like to see that happen too. Not sure whether its feasible by Wed AM.


________________________________

**Comment by carlkesselman** [comment]
Can whoever in required to be involved in 1) fixing the check box or 2) making the selections apply immediately please comment on the complexity?

Thanks,

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Oct 3, 2015, at 3:07 PM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:

I felt it was a small intermediate step in the right direction, however there are a couple significant bugs:

- the check button should apply the selection and go back

- the X button should cancel the current selection and go back


However:

- the check button is closing the slide out and not applying the selection (its acting more like reset almost)

- the X button is applying the selection and going back (it's doing what check button should do)


I agree we should get labels on these.


What you are asking for, to have the selection immediately. I agree. I'd like to see that happen too. Not sure whether its feasible by Wed AM.


________________________________

**Comment by howdyjessie** [comment]
I have to consult with @svoinea before commenting on the complexity. 



I agree the check and X buttons need labels. Adding those labels to the top will produce another problem, though, which is that there's too much going on there (too cramped). 


In the interest of keeping the interface less cluttered and reducing undesired "momentum behavior," we should remove (1) the Reset Search button and (2) the ability to hide/show the sidebar (the sidebar will be open all the time, except in Record view).

**Comment by howdyjessie** [comment]
Forgot to add: I didn't necessarily mean remove permanently but remove until we do a more complete rethink of the search workflow at a future date.

**Comment by carlkesselman** [comment]
Please check with Serbian then.  I’m thinking that we need to drop the modal interaction here completely, and get rid of the two buttons.  Right now its pretty confusing and the behavior is inconsistant.

Carl

On Oct 5, 2015, at 10:13 AM, Jessie Wong <notifications@github.com<mailto:notifications@github.com>> wrote:

Forgot to add: I didn't necessarily mean remove permanently but remove until we do a more complete rethink of the search workflow at a future date.
