### ISSUE TITLE
viewer doesn't hide the channel filter completely after being fully expanded in an iframe

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#893]
If the viewer is embedded in an iframe, the channel filter has a couple issues:

1. The "x" on the upper right hand corner doesn't dismiss it.
2. If the channel filter has been expanded all the way (to show contrast, brightness, etc. sliders), then trying to dismiss it by clicking the "channels" control results in it being partly hidden but still obscuring part of the image.

This all works if the viewer is in its own window rather than an iframe. Also, dismissing "annotations" works fine in an iframe.

There's an example image at https://dev.rebuildingakidney.org/chaise/record/#2/Gene_Expression:Slide/ID=1

**Comment by meihuisu** [comment]
Laura, your setup is picking up wrong stylesheet.


----- Original Message -----

**Comment by ljpearlman** [comment]
I'm using the current master versions of all components. Where is the "right" stylesheet?

**Comment by hongsudt** [comment]
@ljpearlman is this still an issue?

**Comment by hongsudt** [comment]
@ljpearlman I am moving this to blocked at the moment.. At some point, we should close the issue or mark it as not-fixed.

**Comment by ljpearlman** [comment]
This has actually been fixed for some time.
