### ISSUE TITLE
eTag checking

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/chaise#895]
Apps should constantly check eTag and make necessary updates to the page. Details still to be defined.

**Comment by hongsudt** [comment]
@karlcz I think this issue is no longer relevant.. Correct?

**Comment by karlcz** [comment]
It's only relevant if we want to proactively check for changes made concurrently to show updates rather than leaving a page indefinitely with stale data in it... this might matter more once we have more users doing data curation.

**Comment by hongsudt** [comment]
We decided not to do this for delete/edit. So I am closing this issue for now..
