### ISSUE TITLE
Tooltip on Record Select is obscured...

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#898]
![image](https://cloud.githubusercontent.com/assets/3597150/21401699/1ff48dee-c76a-11e6-97c4-0efda35b9566.png)

Also, I wonder if the order of things should be changed.  Its a bit weird to have this big "?" button in the middle of the action buttons.  Perhaps it would be better to move this someplace else, as you really only use this once. One suggestion would be to get rid of this and make it a tool tip on the search button

**Comment by howdyjessie** [comment]
The issue of the obscured tooltip should be addressed as soon as PR #897 is merged into master.

**Comment by hongsudt** [comment]
@howdyjessie please review and close this issue after the code is merged.

**Comment by howdyjessie** [comment]
<img width="1426" alt="screen shot 2016-12-23 at 10 55 56 am" src="https://cloud.githubusercontent.com/assets/4585431/21460572/bfe031ba-c8fe-11e6-8caa-346780c12fe2.png">

The tooltip issue has been fixed, so I'm closing this issue for now.
