### ISSUE TITLE
More/Less (Ellipses) incorrect after table reload

### ISSUE THREAD

**Issue by shinyichen** [informatics-isi-edu/chaise#899]
This happens when the record table's data has been updated, we get rows with more/less link when it's not necessary. It's because the table's ellipses is not being re-calculated.  This could happen when clicking on previous/next page, or after table refreshes with a new record. 

The example in the screenshot. Before adding record 103, row 3 in table was record 263 where some of its content were wrapped with more link. After adding a new record 103, row 3 is now replaced with new content, but the ellipses did not get updated.

<img width="1356" alt="screen shot 2016-12-21 at 2 06 48 pm" src="https://cloud.githubusercontent.com/assets/636361/21407943/ef126d0a-c786-11e6-80e0-c92dcd334909.png">

**Comment by chiragsanghvi** [comment]
@shinyichen I am unable to reproduce it. It is on your branch or Master ?
