### ISSUE TITLE
Info button on recordset page

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#907]
The "?" button on the recordset page seems unnecessary to me and inconsistent in behavior.  It looks like a button, but it doesn't do anything if you push it, and it has information about the search box.  I would put the contents of the tooltip for this button on the magnifying glass (which has no tool tip) and eliminate this button.

**Comment by hongsudt** [comment]
@karlcz @robes @jrchudy @howdyjessie @RFSH @chiragsanghvi any objection?

**Comment by jrchudy** [comment]
Seems reasonable to me and should be simple to change.

**Comment by howdyjessie** [comment]
No objection here.

**Comment by robes** [comment]
No objection.
