### ISSUE TITLE
Search needs an edit button

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/chaise#919]
With the addition of multi-edit to the recordedit app, we need to have a way to trigger this functionality from the `search` app.

There should be a button that links to recordedit that will allow the user to edit the # of visible entities they see in `search`. The number of entities should be limited by what is shown on the search page.

**Comment by svoinea** [comment]
Added the `Edit` button next to the `Download` button.
On clicking it, it opens the `recordedit` page with an equivalent filter used by the `search` page.
In a test, I can see the records on the `recordedit` page. 
However, there is a mismatch between the number of the displayed records and the number displayed in page title.
In my test there are 9 records (which is OK), but the title displays `Edit 37 Records`.

**Comment by svoinea** [comment]
Ready for review.

**Comment by jrchudy** [comment]
I verified this functionality.
