### ISSUE TITLE
Submit and display timestamp and timestamptz values as local time

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#922]
A *timestamptz* value is stored as a single point in time in Postgres. When the value is retrieved, the value is in whatever time zone the database is in.

A *timestamp* value is stored as a string with the date and time; time zone info will be dropped in Postgres.

When submitting values for timestamp and timestamptz columns, the app should just submit the values as browser's local time. (The app currently converts to UTC before submitting, which is unnecessary.)

When displaying *timestamp* value, display whatever is in the db (the date and time, no need to convert to local time because there's no time zone info attached anyway)

When displaying *timestamptz* value, convert that value to browser's local time.

**Comment by howdyjessie** [comment]
Note to self: Test this in `09-recordedit.types.spec.js`

**Comment by howdyjessie** [comment]
This has been addressed in PRs #934 (implementation) and #942 (tests).
