### ISSUE TITLE
chaise/search table view broken when thumbnail not found

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#924]
I'm not sure whether this is a more general issue but it can be demonstrated here.

https://dev.facebase.org/data/search/#1/legacy:dataset?facets=(dataset_organism:organism::eq::Mouse)&layout=table&page=1

**Comment by svoinea** [comment]
I don't understand the issue. 
I have attached the screenshot for the above mentioned link.

![screenshot-1](https://cloud.githubusercontent.com/assets/1609577/22162826/1df314d6-df05-11e6-9f8b-a5a287becf0c.png)

**Comment by robes** [comment]
Ah the URL is wrong -- it should have included the 'sort' condition. Go to that same URL and sort by 'Accession' and descending order.

**Comment by robes** [comment]
![chaise-search-table-broken](https://cloud.githubusercontent.com/assets/4202842/22170485/cba0b0b6-df32-11e6-9c4b-a63bb623459c.jpg)

**Comment by robes** [comment]
See how the thumbnail column has disappeared from the header and the first row, but rows 2+ behave as if that row should have been there.

**Comment by svoinea** [comment]
The database contains a number of `32` entries that have a `null` value for the thumbnail:
```
_ermrest_7AuB3fESSu-tVd_942G29Q=# select count(*) from dataset where thumbnail is null;
 count 
-------
    32
(1 row)
```
That explains the de-synchronization.
The code expects all the thumbnails to be `not null`.
I think we should update the database to set for the `null` thumbnails the default value `17416` that corresponds to the  `generic` thumbnail.

**Comment by hongsudt** [comment]
@robes please respond.. This issue seems to be blocking/pending.

**Comment by robes** [comment]
Okay, thanks I didn't see serban's reply. We can do that in the facebase database. I gather we will leave this bug unfixed in the search app since we are trying not to invest more effort in it. I'll close this and mark it wont fix.
