### ISSUE TITLE
adding angular date function to auto update year in footer

### ISSUE THREAD

**Issue by crisaless** [informatics-isi-edu/chaise#925]
it's silly to have to manually update the copyright year in the chaise footer. but regular js breaks chaise - so we need someone to add a function to do this in angular and add it to the ermfooter.html view. I've manually update the footer for 2017 so we have about a year to do this but shouldn't take long at all.

**Comment by karlcz** [comment]
Shouldn't a copyright statement be present as literal text in the content we serve up?  I don't think it sounds right to dynamically generate this on the client side...
