### ISSUE TITLE
Sidebar: we have lost the "SELECTED ATTRIBUTES view all" column header.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#93]
This needs to be there.

**Comment by robes** [comment]
the bottom row is "View all attributes (42) >>"


Is that what you wanted or something else?


(Btw, that count should always read "42" in my opinion)


________________________________

**Comment by carlkesselman** [comment]
Ahh, there it is…visually, I completely lost this.

However, now we have a can’t get there from here problem.  If you go into the view all, there is no way to get back to the subset view.

Carl

----------------------------------------------------------
Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute
Viterbi School of Engineering

Professor, Preventive Medicine
Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
Email:  carl@isi.edu<mailto:carl@isi.edu>
Web: http://www.isi.edu/~carl








On Oct 3, 2015, at 3:13 PM, robes <notifications@github.com<mailto:notifications@github.com>> wrote:

the bottom row is "View all attributes (42) >>"


Is that what you wanted or something else?


(Btw, that count should always read "42" in my opinion)


________________________________

**Comment by robes** [comment]
it's not too obvious. but you can click the (X) icon and get back to the previous page.


________________________________
