### ISSUE TITLE
modify ermrest config in travis yaml to enable features for test

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#931]
* enable timestamp type

**Comment by karlcz** [comment]
This is done in 3e718fb29f37da6f777764f1d83f84f4f1cf84e1.

The new test/ermrest_config.json is a customized copy of the default one from ermrest, and it replaces the default copy during the test VM setup in .travis.yml.

**Comment by hongsudt** [comment]
@howdyjessie can you verify?

**Comment by howdyjessie** [comment]
I encountered the following error when running my tests on Travis:

```
cp: cannot stat ‘test/ermrest_config.json’: No such file or directory

The command "cp test/ermrest_config.json /home/ermrest/" failed and exited with 1 during .
```

**Comment by howdyjessie** [comment]
I ran into an error on Travis:
`cp: cannot stat ‘test/ermrest_config.json’: No such file or directory`.

It seems like Travis can't find `ermrest_config.json` in the `ermrest` repo. See [build log](https://travis-ci.org/informatics-isi-edu/chaise/builds/193850695) for more info.

**Comment by howdyjessie** [comment]
This has been fixed; Travis builds are creating timestamp fields just fine now.
