### ISSUE TITLE
When you click "done" button on sidebar, sidebar closes....

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#94]
Sidebar should probably only close when the user explicitly closes it.

**Comment by carlkesselman** [comment]
So the behavior of done should be to just update the search pane, nothing else.  To be honest, I'm not sure what cancel should do.  I suppose it should revert the changes that were made since the last time done was pressed?

**Comment by karlcz** [comment]
@carlkesselman can you close this issue if it is really done, or put it in a meaningful pipeline stage if not...?
