### ISSUE TITLE
search: edit button visbility configuration 

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#941]
Only show the edit button on the search app if 
* editRecord config is true, and
* table annotation is not generated or immutable (note: a table is generated/immutable if either itself is generated/immutable or its schema is generated/immutable), and 
* if the user is in the groups that are allowed to write to the catalog

All these logic can be found in Reference.canEdit method..

**Comment by svoinea** [comment]
Done through the commit d678fdcc24618f33bfecb4ffc57615b4ceac3790

**Comment by svoinea** [comment]
Ready for review.

**Comment by hongsudt** [comment]
@mikedarcy can you please review this issue..

**Comment by robes** [comment]
@hongsudt it seems to work for me on facebase.

@svoinea on cirm-dev, from what I can tell, we do not have `editRecord` set in the chaise-config.js and therefore it correctly does not display the edit button. if that's the correct assumption than i can confirm it seems to work on cirm as well.

**Comment by svoinea** [comment]
It should be visible if all of the below conditions are met:

- the `chaise-config.js` file has `"editRecord": true`
- the schema has **not** the `tag:isrd.isi.edu,2016:generated` or `tag:isrd.isi.edu,2016:immutable` annotation
- the table has **not** the `tag:isrd.isi.edu,2016:generated` or `tag:isrd.isi.edu,2016:immutable` annotation
- the logged in user has write permission

**Comment by mikedarcy** [comment]
Works for me.
