### ISSUE TITLE
Don't show 'edit' icon in Actions if the user does not have edit permission

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#947]
Rather than _disable_ the edit icon in the Actions column, why not just not show it? In a largely read only usage scenario like FaceBase, GUDMAP, and (I presume) RBK, these icons aren't useful to most people visiting the site.

**Comment by carlkesselman** [comment]
And potentially confusing.

Carl

**Comment by hongsudt** [comment]
I think @howdyjessie has a similar issue generated based on the standup meeting. I will let her close the duplicate issue..

**Comment by howdyjessie** [comment]
PR #978 addresses this issue and has been merged into master.
