### ISSUE TITLE
Use of fonts is inconsistant across Chase

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#95]
We have what looks like inconsistent  use of fonts between elements within the search pane as well as between the details page and the search pane.  We need to go back to a consistent use of font, emphasis, font size, and icon set that we are using.

Is there a good reason not to use the initial font and icon set that we currently have in the facebase site (i.e. what we started with) and just use that everywhere?  We should be following a style guide for these things.

**Comment by crisaless** [comment]
FYI, some changes in font size (bigger) and emphasis (bold) were made because of comments about difficulty reading the text. So I think some of these changes should stay if it makes it easier to read.

**Comment by karlcz** [comment]
Wouldn't readability concerns apply to all text including the homepage and navbar?

Can we make sure that browser zoom/magnification works consistently and perhaps educate users that they can adjust this for their browser?

**Comment by carlkesselman** [comment]
Problem is we are inconsistent.  Values selection is bold, facet selection isn’t, I think fonts in the detail page are gray, fonts in search page are black.  Making something bold is supposed to highlight something, not be the baseline font.

Carl

On Oct 5, 2015, at 10:44 AM, Cris Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


FYI, some changes in font size (bigger) and emphasis (bold) were made because of comments about difficulty reading the text. So I think some of these changes should stay if it makes it easier to read.

**Comment by carlkesselman** [comment]
So we seem to be making the attribute names regular, and the values bold.  If we were to highlight something, this seems a bit backward to me.  However, the question is to we want to typographically distinguish attributes from values?

Carl

On Oct 5, 2015, at 10:53 AM, Carl Kesselman <carl@isi.edu<mailto:carl@isi.edu>> wrote:

Problem is we are inconsistent.  Values selection is bold, facet selection isn’t, I think fonts in the detail page are gray, fonts in search page are black.  Making something bold is supposed to highlight something, not be the baseline font.

Carl

On Oct 5, 2015, at 10:44 AM, Cris Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


FYI, some changes in font size (bigger) and emphasis (bold) were made because of comments about difficulty reading the text. So I think some of these changes should stay if it makes it easier to read.

**Comment by crisaless** [comment]
I've committed a lot of style fixes. May need to do some more tweaking.

**Comment by robes** [comment]
The site looks good to me. From what I can tell the font typeface is consistent across search and record pages. We do have several different font sizes. Going to punt this over to Carl to review.

**Comment by robes** [comment]
Could you please give your take on it?
