### ISSUE TITLE
"Add" on a nested table of _associated_ entities should add the association not the target entity

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#951]
This was the regression bug we discussed.

**Comment by robes** [comment]
You can recreate this bug on this site and page by clicking the "Add" link for the "Specimen Gene" nested entity set.

https://cirm-dev.isrd.isi.edu/chaise/record/#1/Microscopy:Specimen/ID=20160920-mKDCrlf1IRES21d-GA-0

**Comment by robes** [comment]
@svoinea This bug must be resolved and then tested on CIRM in order to resolve 2 of the items on the pre-release checklist.

@jrchudy when you are done you can assign this to @svoinea for review.

**Comment by jrchudy** [comment]
The corresponding PR has been merged. Assigning this to @svoinea for verification.

**Comment by hongsudt** [comment]
@robes please confirm and close the issue..

**Comment by robes** [comment]
appears to be working.
