### ISSUE TITLE
record-edit performance issue

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#959]
We should do a profile on record-edit and improve performance where applicable. 

A gpcr user has notified that when she created 16 records, the app was very slow, especially when she had to choose a foreign key from a construct or biomass table which could take more than 1 minute to render. She ended up deleting 8 out of 16. 

Will update the issue with browser type and version when I hear more from the user.

**Comment by jrchudy** [comment]
This issue is linked to PR #974.
