### ISSUE TITLE
Help and feedback buttons missing.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#96]
We need to recover these buttons.  In addition, the three small glyphs (help/feedback/bookmark) should be moved to the top right of the left pane, not be in the search box.

**Comment by howdyjessie** [comment]
If the links to help and feedback already exist in the top nav bar (where the Log In and Sign Up is), would the help and feedback buttons in the sidebar be too redundant?

**Comment by carlkesselman** [comment]
I think it still might make sense to have help on the left pane.  We can make it more context sensitive too.

Also, I would change the text on the bookmark bar to say something like:

"Bookmark your current search results.”

Carl



On Oct 5, 2015, at 10:42 AM, Jessie Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


If the links to help and feedback already exist in the top nav bar (where the Log In and Sign Up is), would the help and feedback buttons in the sidebar be too redundant?

**Comment by howdyjessie** [comment]
What do you mean by context sensitive?

How about "Save Search | Help | Send Feedback" with a glyph before each of these?

"Save Search" because as @karlcz pointed out in another issue, we're actually saving the search criteria and not the results themselves. Also, it's more concise.

**Comment by carlkesselman** [comment]
Lets just move the bookmark button and keep just the one.

**Comment by robes** [comment]
Let's not call it "Save Search" that seems misleading. Let's simply call it Bookmark or Permalink.

**Comment by howdyjessie** [comment]
I'd go with Permalink since 'Bookmark' could be ambiguous (e.g. bookmark what? will this bookmark be saved somewhere in my account?). Permalink is more established as a term that you know will give you a URL.

**Comment by robes** [comment]
agreed


________________________________

**Comment by karlcz** [comment]
@robes can you close this if it is really done?

**Comment by robes** [comment]
@crisaless I don't think we ever recovered these.

**Comment by howdyjessie** [comment]
I interpreted @carlkesselman's last comment in this thread to mean that that the help and feedback buttons are no longer needed. If this is right, then we can move this to Closed.

**Comment by robes** [comment]
This has entered the realm of "we don't remember what this bug report means and therefore what should be done to resolve it." :-)

Thus we close it in and open a new issue as needed.
