### ISSUE TITLE
recordedit sometimes doesn't show long column names properly

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/chaise#962]
For a column name that is longer than 2 rows, the recordedit sometimes did not automatically add more rows/space so that all the name was displayed correctly (no matter how many times I refreshed the app). But for some other times, the names seem to be displayed properly.

 See column `Protein Concentration(mg/mL)` in the example here: 
https://dev.gpcrconsortium.org/chaise/recordedit/#1/experiments:sample
 
@chiragsanghvi any clue?

**Comment by chiragsanghvi** [comment]
@hongsudt Closing this issue as unable to regenerate the issue. This might be fixed because of the [display](https://github.com/informatics-isi-edu/ermrest/blob/master/user-doc/annotation.md#2015-display) html annotation that we implemented.
