### ISSUE TITLE
400 Error when trying to sort a column with "/" in the column name

### ISSUE THREAD

**Issue by bugacov** [informatics-isi-edu/chaise#968]
Trying to sort on the "Num Constructs Total/Prev Month" column f=of 

https://dev.gpcrconsortium.org/chaise/recordset/#1/common:targets_dashboard

produces a bad request 
  
https://dev.gpcrconsortium.org/ermrest/catalog/1/attributegroup/M:=common:targets_dashboard/F2:=left(target_id)=(gpcr_browser:target_gui:title)/$M/F1:=left(site)=(iobox_data:site:name)/$M/target_id,Num%20Expressions%20Total/Prev%20Month;M:=array(M:*),F2:=array(F2:*),F1:=array(F1:*)@sort(Num%20Expressions%20Total%2FPrev%20Month,target_id)?limit=26&cid=recordset

The first time the "/" appears is not proerly encoded w/ %2F 

s%20Total/Prev%20

**Comment by hongsudt** [comment]
@RFSH please fix..

**Comment by RFSH** [comment]
@bugacov It should be fixed now. Can you please verify?
