### ISSUE TITLE
View action button (eye-ball) is broken with paging

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#975]
I've experienced this bug several times today and questioned my own mouse click accuracy.  But I've finally repeated it and can confidently say the app is malfunctioning.

1. Go to a recordset page like https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Subject%20Summary@sort(Issue%20Date::desc::,ID)?limit=10
2. Page through a few times, e.g. I hit next 4 times to get a page w/ lots of stuff in the Pointclouds column
3. Scroll around and then click the eye-ball icon in the Action column, e.g. I picked the one for `ZfZdu20160825A` in the middle of the page.

Usually, the browser sends me to a record page for a completely unrelated entity.  If I reload the recordset app first, it usually works right.  I think the action column probably gets out of sync when the next page function is used.

**Comment by hongsudt** [comment]
@karlcz please review after the PR is merged.

**Comment by karlcz** [comment]
Yes, the view link seems to track the next page contents now.
