### ISSUE TITLE
Broken table width determination w/ images and iframes

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#976]
I think this is a recent regression...

1. Go to https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Subject
2. Hit next page 4 times to get to a page w/ plot imagery in the right-most 2 columns
3. Scroll down to the bottom
4. Change window widths and notice that a horizontal scrollbar appears for many widths even though the table content can re-flow to adapt to the new width.

It seems like we must be miscalculating the width somewhere and forcing this scrolling layout?

**Comment by hongsudt** [comment]
@chiragsanghvi @karlcz has mentioned this bug in the standup meeting.. Please take a look..

**Comment by hongsudt** [comment]
@chiragsanghvi Please look at this.

**Comment by chiragsanghvi** [comment]
@karlcz Unable to regenerate the issue

**Comment by hongsudt** [comment]
@karlcz please check whether you still have this problem?

**Comment by karlcz** [comment]
I still see it but it is less pronounced than it was before.  It's certainly usable now, so these are just minor graphical layout quirks.

The scrollbar appears with a cell padding's worth of wiggle room and the right-most column is truncated at the padding.

If I make the window much wider, the scroll bar finally collapses and disappears as the cell padding reappears, even though some text in the left column is still flowed over multiple lines...

**Comment by hongsudt** [comment]
@chiragsanghvi can you look into this, so we can close the issue?

**Comment by karlcz** [comment]
In case it helps, when I repeat this test as described the current behavior is that the iframes are extending past the shaded table border region by a cell padding width.  It looks like the column width is being calculated as the iframe width rather than the iframe plus two horizontal padding widths.

**Comment by hongsudt** [comment]
@jrchudy do you know whether @chiragsanghvi has submitted PR for this issue?

**Comment by jrchudy** [comment]
No he did not.

**Comment by chiragsanghvi** [comment]
@karlcz Is this still an issue ?

**Comment by karlcz** [comment]
The original test scenario is now invalid since that Subject table has a table-alternative and no longer presents inline images.

I tried to reproduce it on a different table like https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Image%20Pair%20Study and I don't see the same layout issue.

I guess we can assume this went away with the styling changes for the new facet UX.  I'll file a new bug if I encounter any new problems.
