### ISSUE TITLE
"Chiclet" space

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/chaise#98]
The following changes should be made to the search terms part of the display
[ ] We need to have a title above the chicklets so the user knows what they are looking at.  I suggest something like "Current Attribute Filter Terms" or something like that.  The font of this should be consistent with other header fonts on the page.

[ ] The "Reset Search" button should be moved to be by the chiclets and taken out of the sidebar

**Comment by howdyjessie** [comment]
I currently have the title as "Selected Attributes" and wrapped with a `<h3>`. Not sure if this considered consistent with other header fonts, but I made it an `h3` in the hopes that the larger size will grab users' attentions more quickly and differentiate it from the surrounding text. @crisaless can weigh in?

**Comment by crisaless** [comment]
I don't think it needs to be that attention-getting. A <4> tag might be sufficient.  I also think it should be called "Selected by:"

**Comment by howdyjessie** [comment]
Okay here's "Selected by" in h4

![screen shot 2015-10-05 at 3 09 35 pm](https://cloud.githubusercontent.com/assets/4585431/10295113/200a20b8-6b73-11e5-9276-2855ea9a4029.png)

**Comment by carlkesselman** [comment]
I think this looks good.

I like the “Save Search” button.

Carl

On Oct 5, 2015, at 3:10 PM, Jessie Wong <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay here's "Selected by" in h4

[screen shot 2015-10-05 at 3 09 35 pm]<https://cloud.githubusercontent.com/assets/4585431/10295113/200a20b8-6b73-11e5-9276-2855ea9a4029.png>

**Comment by crisaless** [comment]
It still looks too big. I think it should look like 'Search within' - but at this point, let me fool around with it. I might need to add a style.

**Comment by carlkesselman** [comment]
Good point.  That would be better.

Are we happy with the way the clear attributes button looks and placement?

Carl

On Oct 5, 2015, at 3:14 PM, Cris Williams <notifications@github.com<mailto:notifications@github.com>> wrote:


It still looks too big. I think it should look like 'Search within' - but at this point, let me fool around with it. I might need to add a style.

**Comment by crisaless** [comment]
Jessie, try using this p tag for Selected by:
<p class="filter-item-field"></p>

Carl, In my head I was thinking the Clear All could have a background color the same as the close icon (#fc868d) and white font - but it's a long button to use such an imperative color. Maybe if you shorten the text to just say "Clear All"

Another way to go is to make the "Clear..." text italicized...

**Comment by crisaless** [comment]
github scrubbed the markup. I was going to suggest using a p tag with the class "filter-item-field" for the "Selected by:" heading.

**Comment by howdyjessie** [comment]
@crisaless Here's "Selected by" with `.filter-item-field`. Doesn't it look a little too subtle?

![screen shot 2015-10-05 at 4 44 21 pm](https://cloud.githubusercontent.com/assets/4585431/10296765/b1ce87f2-6b80-11e5-93a0-46de9823fb6e.png)

Here it is surrounded by `<strong>` tags:
![screen shot 2015-10-05 at 4 46 47 pm](https://cloud.githubusercontent.com/assets/4585431/10296772/c21d88ba-6b80-11e5-95b2-4b30258ed386.png)

**Comment by howdyjessie** [comment]
@crisaless Also, to make GitHub not scrub out your code, you can try surrounding your code with a pair of ` (that accent mark thing)
