### ISSUE TITLE
Confusing search results caused by caching of trigger-generated values

### ISSUE THREAD

**Issue by ljpearlman** [informatics-isi-edu/chaise#981]
In RBK, we have a table called Protocol that has several columns that are generated via triggers that fire when a related table is updated (for example, whenever a row is added to or deleted from the Protocol_Subject table, the associated row in the Protocol table is updated with a list of associated subject terms). We do this so people can see the lists of subjects, etc., in `search` results.

@todd noticed that when he added subject terms to a protocol, `search` results for the Protocol table within that same session didn't reflect that change (`search` results from another browser or after logging out/in again did reflect it). I'm pretty sure that this is because ermrest doesn't know about the database trigger, so as far as it knows, only the Protocol table has changed.

One approach to dealing with this would be to add an annotation to tell ermrest to consider table X updated whenever table Y is. Another would be to add an annotation to refer to aggregated values (lists and counts would be particularly useful) from a related table.

This probably affects multiple components, not just chaise.

To reproduce:

1. Go to https://staging.rebuildingakidney.org/chaise/search/#2/Protocol:Protocol
2. Log in.
3. Select a protocol ("Laura's fake protocol" is always a good choice).
4. Add a Subject term.
5. Add a different Subject term
6. Load the Protocol search page again. The first subject term you added may or may not be displayed, but the second one won't be.

**Comment by karlcz** [comment]
The way to fix this is to modify your trigger definition to report
the data change event:

  EXECUTE _ermrest.data_change_event('schema name', 'table name')

or similar.

**Comment by hongsudt** [comment]
@ljpearlman should we move this task back to rbk_project since we have to add that to the trigger method?

**Comment by hongsudt** [comment]
This problem has been fixed in the v05_05_protocol_trigger by explicitly calling the ermrest data change event. The fix has been applied to dev.
