### ISSUE TITLE
Empty results page is too empty

### ISSUE THREAD

**Issue by karlcz** [informatics-isi-edu/chaise#985]
I think the empty results page needs to say something like `No matching results.` rather than just being a completely blank div.  I think this is definitely true for recordset, and perhaps also possibly for any other
compact display context.

[recordset example](https://synapse-dev.isrd.isi.edu/chaise/recordset/#1/Zebrafish:Subject%20Summary/*::ciregexp::Tol25@sort(Issue%20Date::desc::,ID)?limit=10)

**Comment by hongsudt** [comment]
This is now done. So I am closing this issue.
