### ISSUE TITLE
Not checksumming ermrestjs script

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#986]
The Makefile is looking in the wrong location for the ermrestjs script during its checksumming step. The deployment dir and build dir are at different locations. The generated script tag leaves the checksum part blank and so we are more likely for the browser to use a cached ermrestjs script when a new one was available on the server.

**Comment by jrchudy** [comment]
It looks like none of the deployments are broken and no one has complained that `Chaise` isn't working on a dev server, so I'm going to close this issue.
