### ISSUE TITLE
Revise layout of sidebar

### ISSUE THREAD

**Issue by robes** [informatics-isi-edu/chaise#99]
For the initial facet selection sidebar layout:

1. Search (on top)
2. "Selected Attributes"
3. List of Facets/Attributes
4. "View all attributes (#)"

For the value selection sidebar:

1. Search (on top)
2. "back" icon followed by Facet Name (e.g., "Mouse Genotype")
3. Attribute type specific value picker

**Comment by crisaless** [comment]
What about instead of "Selected Attributes", we say "Select Attributes"? That would turn it into a call-to-action.

**Comment by howdyjessie** [comment]
Yeah and to avoid the ambiguity in Select Attributes (select as an adjective), maybe Choose Attributes?

**Comment by crisaless** [comment]
Yes, even better. And a colon at the end

Choose Attributes:

**Comment by howdyjessie** [comment]
@crisaless I need your help with styling on this. I'm having difficulty with:
1. Getting the back arrow and title to vertically align
2. Removing the black underline where it is unnecessary (i.e. in the sidebars that already have a gray top line above the first value. But the All Attributes sidebar doesn't have this line?).
![screen shot 2015-10-05 at 4 18 25 pm](https://cloud.githubusercontent.com/assets/4585431/10296523/1efa430a-6b7e-11e5-8422-15687b475c95.png)
![screen shot 2015-10-05 at 4 18 35 pm](https://cloud.githubusercontent.com/assets/4585431/10296522/1ef8f202-6b7e-11e5-8b23-abe630b1c845.png)

**Comment by crisaless** [comment]
I'm on it.

**Comment by howdyjessie** [comment]
:raised_hands: :raised_hands: :raised_hands: thank you

**Comment by crisaless** [comment]
I've committed a fix. One thing I'm still having trouble is the link target for the Back button. The bootstrap column is rendering to the left even though the elements within (the a tag and arrow icon) are visually showing up where expected. That makes the clickable area off and consequently a smaller target to click than it should be. I think it's another consequence of using the position:fixed sidebar.

**Comment by crisaless** [comment]
Well it _was_ fixed but it's looking janky again. Grrrr. Working on it some more...

**Comment by crisaless** [comment]
Think I got it now - we'll see after 1pm's deployment

**Comment by crisaless** [comment]
looks like it's fixed now.
