### ISSUE TITLE
Active element ("focusser") error in e2e tests

### ISSUE THREAD

**Issue by howdyjessie** [informatics-isi-edu/chaise#995]
There's an error in the RecordEdit tests on [this line](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L370) or [this line](https://github.com/informatics-isi-edu/chaise/blob/master/test/e2e/specs/recordedit/helpers.js#L402), if you add a `browser.pause` (according to @RFSH). 

Both lines are expecting the browser's current active element to be the search input's ID but instead the active element is something from the boolean dropdown tool we're using. 

A screenshot of error stack from @RFSH:
![screen shot 2017-02-23 at 12 55 28 pm](https://cloud.githubusercontent.com/assets/4585431/23278832/afdf3f78-f9c7-11e6-9b6b-c214409418b3.png)

**Comment by howdyjessie** [comment]
@RFSH The fix for this has been reviewed and merged into master, but could you check on your tests to see if the failures have gone away?

**Comment by RFSH** [comment]
@howdyjessie Yes, I can confirm that the test is not failing for me anymore.
